const SERVICE="sanctuary-management";
const API_VERSION="1.7";
const DATABASE_CONTRACT="445";
const SESSION_TOKEN=/^kws_[A-Za-z0-9_-]{40,80}$/;
const REQUEST_KEY=/^[A-Za-z0-9][A-Za-z0-9._:-]{7,119}$/;
const PROD_ORIGINS=new Set(["https://kinojo.info","https://www.kinojo.info"]);
const ACTIONS=new Set(["bootstrap","month","conflicts","notification-summary","archive-preview","command","lease","character-search","character-register","transition-report","transition-approve"]);
const PILOT_WRITE_ACTIONS=new Set(["archive-preview","command","lease","character-search","character-register","transition-approve"]);
type JsonObject=Record<string,unknown>;

function text(value:unknown,max=500){return String(value??"").trim().slice(0,max);}
function object(value:unknown):JsonObject|null{return value&&typeof value==="object"&&!Array.isArray(value)?value as JsonObject:null;}
function positiveInteger(value:unknown){const number=Number(value);return Number.isSafeInteger(number)&&number>0?number:null;}
function normalized(value:unknown){return text(value,160).replace(/<[^>]+>/g,"").normalize("NFKC").toLocaleLowerCase("ko-KR").replace(/\s+/g,"");}
function originAllowed(request:Request){const origin=text(request.headers.get("origin"),300);if(!origin||PROD_ORIGINS.has(origin))return true;try{const url=new URL(origin);return(url.hostname==="127.0.0.1"||url.hostname==="localhost")&&["http:","https:"].includes(url.protocol);}catch{return false;}}
function headers(request:Request):HeadersInit{const origin=text(request.headers.get("origin"),300);const result:Record<string,string>={"access-control-allow-methods":"GET, POST, OPTIONS","access-control-allow-headers":"authorization, apikey, content-type, x-client-info, idempotency-key","access-control-expose-headers":"X-Kinojo-Request-Id, X-Kinojo-Sanctuary-Contract","access-control-max-age":"600","cache-control":"private, no-store","content-type":"application/json; charset=utf-8",vary:"Origin","x-content-type-options":"nosniff","x-kinojo-sanctuary-contract":DATABASE_CONTRACT,"x-kinojo-request-id":crypto.randomUUID()};if(origin&&originAllowed(request))result["access-control-allow-origin"]=origin;return result;}
// EDGE_CONTRACT_AUTHORITY: DB RPC payloads can retain legacy apiVersion/schemaVersion values.
// Always spread body first and write Edge-owned service/API/database/schema fields last; reversing this order caused the 2026-08-28 production contract mismatch.
function response(request:Request,body:JsonObject,status=200){return new Response(JSON.stringify({...body,service:SERVICE,apiVersion:API_VERSION,databaseContract:DATABASE_CONTRACT,schemaVersion:Number(DATABASE_CONTRACT)}),{status,headers:headers(request)});}
function failure(request:Request,code:string,message:string,status=400,detail?:unknown){return response(request,{ok:false,code,message,...(detail===undefined?{}:{detail})},status);}
function context(){const url=text(Deno.env.get("SUPABASE_URL"),500).replace(/\/$/,"");let key=text(Deno.env.get("SUPABASE_SERVICE_ROLE_KEY"),2200);if(!key){try{key=text(JSON.parse(Deno.env.get("SUPABASE_SECRET_KEYS")||"{}")?.default,2200);}catch{key="";}}if(!url||!key)throw new Error("SERVER_NOT_CONFIGURED");return{url,key};}
async function rpc(name:string,payload:JsonObject){const{url,key}=context();const result=await fetch(`${url}/rest/v1/rpc/${name}`,{method:"POST",headers:{apikey:key,authorization:`Bearer ${key}`,"content-type":"application/json","x-client-info":`${SERVICE}/${API_VERSION}`},body:JSON.stringify(payload)});const raw=await result.text();let data:unknown={};try{data=raw?JSON.parse(raw):{};}catch{data={};}if(!result.ok){const detail=object(data);const error=new Error(text(detail?.message,500)||"성역 관리 요청을 처리하지 못했습니다.");error.name=result.status===409?"CONFLICT":"RPC_FAILED";throw error;}return object(data)||{};}
async function assertPilotWrite(credential:string,action:string){const access=await rpc("kinojo_sanctuary_management_write_access_v445",{p_credential:credential,p_action:action});if(access.effectiveWriteEnabled===true)return access;const error=new Error(text(access.message,500)||"승인된 시험 사용자만 신규 성역 관리 쓰기를 사용할 수 있습니다.");error.name="PILOT_REQUIRED";throw error;}
function sessionFrom(request:Request,body:JsonObject){const bearer=text(request.headers.get("authorization"),2200).replace(/^Bearer\s+/i,"");const token=text(body.sessionToken||bearer,2200);return SESSION_TOKEN.test(token)?token:"";}
function rows(value:unknown,depth=0):unknown[]{if(depth>6||value==null)return[];if(Array.isArray(value))return value;const item=object(value)||{};for(const key of["list","content","items","characters"]){if(Array.isArray(item[key]))return item[key] as unknown[];}for(const child of Object.values(item)){const found=rows(child,depth+1);if(found.length)return found;}return[];}
function getCharKey(value:unknown){const source=text(value,3000);const match=source.match(/[?&]charKey=(\d{10,})/i)||source.match(/\b(\d{10,})\b/);return match?match[1]:"";}
function decodedCharacterId(value:unknown){const source=text(value,800);if(!source)return"";try{return decodeURIComponent(source);}catch{return source;}}
function exactCandidate(payload:unknown,characterName:string,serverId:number){const wanted=normalized(characterName);for(const source of rows(payload)){const item=object(source)||{};const name=text(item.name||item.characterName||item.character_name,160).replace(/<[^>]+>/g,"");const candidateServerId=positiveInteger(item.serverId||item.server_id);if(normalized(name)!==wanted||candidateServerId!==serverId)continue;const characterId=decodedCharacterId(item.characterId||item.character_id||item.encryptedCharacterId);if(!characterId)continue;const profileImageUrl=text(item.profileImageUrl||item.profile_image_url,1600);return{characterName:name,serverName:text(item.serverName||item.server_name,120),characterId,profileImageUrl,charKey:getCharKey(profileImageUrl),className:text(item.className||item.class_name,80),legionName:text(item.legionName||item.legion_name||item.guildName,80)};}return null;}
function parseCharacterQuery(value:unknown){const raw=text(value,48);if(!raw)return{ok:false,message:"캐릭터 이름을 입력해 주세요."};const bracket=raw.match(/^([^\[\]]{1,16})\[([^\[\]]{1,20})\]$/u);if(bracket)return{ok:true,characterName:bracket[1].trim(),serverName:bracket[2].trim()};if(raw.includes("[")||raw.includes("]"))return{ok:false,message:"다른 서버는 이름[서버] 형식으로 입력해 주세요."};if(Array.from(raw).length>16)return{ok:false,message:"캐릭터 이름은 16자까지 입력할 수 있습니다."};return{ok:true,characterName:raw,serverName:"지켈"};}
function retryAfterSeconds(value:unknown){const raw=text(value,160),number=Number(raw);if(Number.isFinite(number)&&number>0)return Math.min(600,Math.max(1,Math.ceil(number)));const date=Date.parse(raw);return Number.isFinite(date)?Math.min(600,Math.max(1,Math.ceil((date-Date.now())/1000))):30;}
async function fetchOfficial(url:string){const controller=new AbortController();const timer=setTimeout(()=>controller.abort(),15000);try{const result=await fetch(url,{method:"GET",headers:{accept:"application/json,text/plain,*/*","accept-language":"ko-KR,ko;q=0.9","user-agent":"KINOJO-Sanctuary-Management/439"},redirect:"follow",signal:controller.signal});const raw=await result.text();let data:unknown={};try{data=raw?JSON.parse(raw):{};}catch{data={};}return{ok:result.ok,status:result.status,retryAfter:result.headers.get("retry-after"),data,bodySample:raw.slice(0,1000)};}catch(error){return{ok:false,status:error instanceof DOMException&&error.name==="AbortError"?504:502,retryAfter:null,data:{},bodySample:text(error,500)};}finally{clearTimeout(timer);}}
async function officialRequest(credential:string,teamId:number,serverId:number,characterName:string,url:string){const prepared=await rpc("kinojo_sanctuary_management_official_prepare_v432",{p_credential:credential,p_team_id:teamId,p_server_id:serverId,p_character_name:characterName});if(prepared.allowed===false)return{failure:{status:429,code:"PLAYNC_RATE_PAUSED",message:"PLAYNC 요청 제한 대기 중입니다.",retryAfterSeconds:positiveInteger(prepared.retryAfterSeconds)||30}};const waitMs=Math.max(0,Number(prepared.waitMs||0));if(waitMs>5000)return{failure:{status:429,code:"PLAYNC_RATE_WAIT",message:"공식 조회 요청 간격을 조정 중입니다.",retryAfterSeconds:Math.max(1,Math.ceil(waitMs/1000))}};if(waitMs>0)await new Promise(resolve=>setTimeout(resolve,waitMs));const result=await fetchOfficial(url);await rpc("kinojo_sanctuary_management_official_gate_v432",{p_credential:credential,p_team_id:teamId,p_http_status:result.status,p_retry_after_seconds:result.status===429?retryAfterSeconds(result.retryAfter):null,p_error:result.ok?null:result.bodySample}).catch(()=>null);if(result.ok)return{data:result.data};if(result.status===404)return{failure:{status:404,code:"CHARACTER_NOT_FOUND",message:"해당 서버에서 캐릭터를 찾지 못했습니다."}};if(result.status===429)return{failure:{status:429,code:"PLAYNC_HTTP_429",message:"PLAYNC 요청 제한이 적용되었습니다.",retryAfterSeconds:retryAfterSeconds(result.retryAfter)}};if(result.status===504)return{failure:{status:504,code:"PLAYNC_TIMEOUT",message:"PLAYNC 공식 조회 응답 시간이 초과되었습니다."}};return{failure:{status:result.status>=500?502:400,code:`PLAYNC_HTTP_${result.status}`,message:"PLAYNC 공식 조회를 완료하지 못했습니다."}};}
async function characterSearch(request:Request,body:JsonObject,credential:string){const teamId=positiveInteger(body.teamId);const parsed=parseCharacterQuery(body.query);if(!teamId)return failure(request,"CHARACTER_SEARCH_TEAM_REQUIRED","캐릭터를 추가할 팀을 다시 선택해 주세요.");if(!parsed.ok)return failure(request,"CHARACTER_SEARCH_QUERY_INVALID",parsed.message||"캐릭터 검색어를 확인해 주세요.");const searched=await rpc("kinojo_sanctuary_management_character_search_v432",{p_credential:credential,p_team_id:teamId,p_character_name:parsed.characterName,p_server_name:parsed.serverName});if(searched.officialLookupRequired!==true)return response(request,searched);
  const target=object(searched.request)||{};const serverId=positiveInteger(target.serverId),raceId=positiveInteger(target.raceId),characterName=text(target.characterName,16);if(!serverId||!raceId||!characterName)return failure(request,"OFFICIAL_TARGET_INVALID","Server의 공식 조회 대상을 확인할 수 없습니다.",502);
  const searchUrl=new URL("https://aion2.plaync.com/ko-kr/api/search/aion2/search/v2/character");searchUrl.searchParams.set("keyword",characterName);searchUrl.searchParams.set("serverId",String(serverId));searchUrl.searchParams.set("page","1");searchUrl.searchParams.set("size","20");const searchResult=await officialRequest(credential,teamId,serverId,characterName,searchUrl.toString());if(searchResult.failure){const f=searchResult.failure;return failure(request,f.code,f.message,f.status,f.retryAfterSeconds?{retryAfterSeconds:f.retryAfterSeconds}:undefined);}const candidate=exactCandidate(searchResult.data,characterName,serverId);if(!candidate)return failure(request,"CHARACTER_NOT_FOUND","해당 서버에서 정확히 일치하는 캐릭터를 찾지 못했습니다.",404);
  const infoUrl=new URL("https://aion2.plaync.com/api/character/info");infoUrl.searchParams.set("lang","ko");infoUrl.searchParams.set("serverId",String(serverId));infoUrl.searchParams.set("characterId",candidate.characterId);const infoResult=await officialRequest(credential,teamId,serverId,characterName,infoUrl.toString());if(infoResult.failure){const f=infoResult.failure;return failure(request,f.code,f.message,f.status,f.retryAfterSeconds?{retryAfterSeconds:f.retryAfterSeconds}:undefined);}const payload=object(infoResult.data)||{},profile=object(payload.profile)||{};const officialName=text(profile.characterName||payload.characterName,16),serverName=text(profile.serverName||candidate.serverName,120),className=text(profile.className||candidate.className,80),officialRaceId=positiveInteger(profile.raceId||payload.raceId),profileImageUrl=text(profile.profileImage||profile.profileImageUrl||candidate.profileImageUrl,1600),charKey=getCharKey(profileImageUrl)||candidate.charKey,legionName=text(profile.legionName||profile.legion_name||profile.regionName||profile.guildName||payload.legionName||candidate.legionName,80);if(normalized(officialName)!==normalized(characterName))return failure(request,"OFFICIAL_NAME_MISMATCH","공식 조회 결과의 캐릭터명이 입력값과 다릅니다.",409);if(officialRaceId!==raceId)return failure(request,"OFFICIAL_RACE_MISMATCH","공식 조회 결과의 종족이 서버 정보와 다릅니다.",409);if(!serverName||!className||!charKey)return failure(request,"OFFICIAL_IDENTITY_INCOMPLETE","PLAYNC 공식 응답에서 서버·클래스·고유값을 모두 확인하지 못했습니다.",502);const encoded=encodeURIComponent(candidate.characterId).replace(/%3D/gi,"=");const official={characterName:officialName,serverId,serverName,raceId,className,legionName:legionName||null,charKey,characterId:candidate.characterId,profileImageUrl:profileImageUrl||null,detailUrl:`https://aion2.plaync.com/ko-kr/characters/${serverId}/${encoded}`,provider:"PLAYNC",fetchedAt:new Date().toISOString()};const recorded=await rpc("kinojo_sanctuary_management_official_record_v432",{p_credential:credential,p_team_id:teamId,p_requested_character_name:characterName,p_official_payload:official});return response(request,recorded);
}

Deno.serve(async(request:Request)=>{if(!originAllowed(request))return failure(request,"ORIGIN_NOT_ALLOWED","허용되지 않은 요청 출처입니다.",403);if(request.method==="OPTIONS")return new Response(null,{status:204,headers:headers(request)});if(request.method==="GET"){try{return response(request,{...(await rpc("kinojo_sanctuary_management_rollout_state_v445",{})),status:"ready",writeEnabled:false,actions:Array.from(ACTIONS)});}catch{return failure(request,"HEALTH_DEPENDENCY_FAILED","성역 관리 Server 상태를 확인하지 못했습니다.",503);}}if(request.method!=="POST")return failure(request,"METHOD_NOT_ALLOWED","허용되지 않은 요청 방식입니다.",405);if(!text(request.headers.get("content-type"),100).toLowerCase().includes("application/json"))return failure(request,"JSON_REQUIRED","JSON 요청만 허용됩니다.",415);if(Number(request.headers.get("content-length")||0)>65536)return failure(request,"REQUEST_TOO_LARGE","요청 데이터가 너무 큽니다.",413);let body:JsonObject;try{body=object(await request.json())||{};}catch{return failure(request,"JSON_INVALID","요청 내용을 확인해 주세요.");}const action=text(body.action,40).toLowerCase();if(!ACTIONS.has(action))return failure(request,"ACTION_INVALID","지원하지 않는 성역 관리 작업입니다.");const credential=sessionFrom(request,body);if(!credential)return failure(request,"SESSION_TOKEN_INVALID","로그인 세션을 다시 확인해 주세요.",401);
  try{
    if(PILOT_WRITE_ACTIONS.has(action))await assertPilotWrite(credential,action);
    if(action==="bootstrap")return response(request,await rpc("kinojo_sanctuary_management_bootstrap_v445",{p_credential:credential}));
    if(action==="month"){const month=text(body.month,10);if(!/^20\d{2}-(0[1-9]|1[0-2])$/.test(month))return failure(request,"MONTH_INVALID","조회할 월을 YYYY-MM 형식으로 선택해 주세요.");return response(request,await rpc("kinojo_sanctuary_management_month_v445",{p_credential:credential,p_month:`${month}-01`}));}
    if(action==="transition-report"){const month=text(body.month,10);if(!/^20\d{2}-(0[1-9]|1[0-2])$/.test(month))return failure(request,"MONTH_INVALID","비교할 월을 YYYY-MM 형식으로 선택해 주세요.");return response(request,await rpc("kinojo_sanctuary_management_transition_report_v445",{p_credential:credential,p_month:`${month}-01`}));}
    if(action==="transition-approve"){const month=text(body.month,10),scopeHash=text(body.scopeHash,64),scopePayload=object(body.scopePayload),confirmation=text(body.confirmation,40);if(!/^20\d{2}-(0[1-9]|1[0-2])$/.test(month)||!/^[0-9a-f]{64}$/.test(scopeHash)||!scopePayload||confirmation!=="전환 범위 승인")return failure(request,"TRANSITION_APPROVAL_INVALID","전환 범위와 확인 문구를 다시 확인해 주세요.");return response(request,await rpc("kinojo_sanctuary_management_transition_approve_v445",{p_credential:credential,p_month:`${month}-01`,p_scope_hash:scopeHash,p_scope_payload:scopePayload,p_confirmation:confirmation}));}
    if(action==="character-search")return await characterSearch(request,body,credential);
    if(action==="character-register"){const teamId=positiveInteger(body.teamId),candidateId=text(body.candidateId,80),relationType=text(body.relationType,16).toUpperCase(),mainCharacterId=body.mainCharacterId==null?null:positiveInteger(body.mainCharacterId),requestKey=text(request.headers.get("idempotency-key")||body.requestKey,120);if(!teamId||!candidateId||!["MAIN","ALT","GUEST"].includes(relationType)||!REQUEST_KEY.test(requestKey))return failure(request,"CHARACTER_REGISTER_INVALID","관계 확정 요청을 다시 확인해 주세요.");return response(request,await rpc("kinojo_sanctuary_management_official_materialize_v445",{p_credential:credential,p_team_id:teamId,p_candidate_id:candidateId,p_relation_type:relationType,p_main_character_id:mainCharacterId,p_request_key:requestKey}));}
    if(action==="notification-summary")return response(request,await rpc("kinojo_sanctuary_management_notification_summary_v445",{p_credential:credential}));
    if(action==="archive-preview"){const teamId=positiveInteger(body.teamId);if(!teamId)return failure(request,"ARCHIVE_TEAM_REQUIRED","해산할 팀을 다시 선택해 주세요.");return response(request,await rpc("kinojo_sanctuary_management_archive_preview_v445",{p_credential:credential,p_team_id:teamId}));}
    if(action==="conflicts"){const teamId=positiveInteger(body.teamId),characterId=positiveInteger(body.characterId);if(!teamId||!characterId)return failure(request,"CONFLICT_TARGET_INVALID","팀과 캐릭터를 다시 선택해 주세요.");return response(request,await rpc("kinojo_sanctuary_management_conflicts_v412",{p_credential:credential,p_team_id:teamId,p_character_id:characterId}));}
    if(action==="lease"){const teamId=positiveInteger(body.teamId),leaseAction=text(body.leaseAction,16).toUpperCase(),leaseToken=text(body.leaseToken,180);if(!teamId||!["ACQUIRE","RENEW","RELEASE"].includes(leaseAction)||leaseToken.length<32)return failure(request,"LEASE_REQUEST_INVALID","편집 잠금 요청을 다시 확인해 주세요.");return response(request,await rpc("kinojo_sanctuary_management_lease_v445",{p_credential:credential,p_team_id:teamId,p_action:leaseAction,p_lease_token:leaseToken}));}
    const requestKey=text(request.headers.get("idempotency-key")||body.requestKey,120),command=text(body.command,48).toUpperCase(),payload=object(body.payload)||{},expectedRevision=body.expectedRevision==null?null:positiveInteger(body.expectedRevision);if(!REQUEST_KEY.test(requestKey))return failure(request,"REQUEST_KEY_INVALID","중복 요청 방지 키를 다시 만들어 주세요.");if(!command)return failure(request,"COMMAND_INVALID","실행할 작업을 선택해 주세요.");return response(request,await rpc("kinojo_sanctuary_management_command_v445",{p_credential:credential,p_request_key:requestKey,p_action:command,p_payload:payload,p_expected_revision:expectedRevision}));
  }catch(error){const message=error instanceof Error?text(error.message,500):"성역 관리 요청을 처리하지 못했습니다.";const pilot=(error instanceof Error&&error.name==="PILOT_REQUIRED")||/승인된 시험 사용자|PILOT_NOT_APPROVED/i.test(message);const locked=/다른 사용자가|새로고침|conflict/i.test(message);return failure(request,pilot?"SANCTUARY_PILOT_REQUIRED":locked?"SANCTUARY_CONFLICT":"SANCTUARY_REQUEST_FAILED",message,pilot?403:locked?409:400);}
});
