'use strict';
const fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict');
const {PGlite}=require(process.env.PGLITE_MODULE||'@electric-sql/pglite');
const root=path.resolve(__dirname,'..');
const historical=fs.readFileSync(path.join(root,'supabase/migrations/20260824110551_banner_content_overlay_library_v396.sql'),'utf8').replace(/\r\n/g,'\n');
const start=historical.indexOf('create or replace function private.kinojo_banner_manifest_internal_v396(');
const original=historical.slice(start,historical.indexOf('$function$;',start)+11);
const migration=fs.readFileSync(path.join(root,'supabase/migrations/20260909091815_banner_plain_delivery_derivatives.sql'),'utf8');
(async()=>{const db=new PGlite();try{
 await db.exec(`create schema private;
 create table public.kinojo_banner_campaign_items(item_id bigint,content_overlays jsonb,composite_object_path text,composite_source_hash text);
 create function private.kinojo_banner_manifest_internal_v395(text,text,timestamptz) returns jsonb language sql as $$select '{"ok":true,"manifestVersion":"test","playlist":[{"itemId":1,"objectPath":"original.png"},{"itemId":1,"objectPath":"original.png"}]}'::jsonb$$;
 create function private.kinojo_banner_content_enabled_v396(jsonb) returns boolean language sql as $$select jsonb_array_length($1)>0$$;
 create function private.kinojo_banner_content_overlays_normalize_v396(jsonb) returns jsonb language sql as $$select coalesce($1,'[]'::jsonb)$$;
 create function private.kinojo_banner_text_overlay_normalize_v394(jsonb) returns jsonb language sql as $$select '{}'::jsonb$$;
 create function private.kinojo_banner_content_manifest_v396(jsonb) returns jsonb language sql as $$select $1$$;
 insert into public.kinojo_banner_campaign_items values(1,'[]','delivery.webp',md5('[]'));`);
 await db.exec(original);
 const read=async()=>JSON.parse(JSON.stringify((await db.query("select private.kinojo_banner_manifest_internal_v396('HOME','MAIN',now()) value")).rows[0].value));
 assert.equal((await read()).playlist[0].objectPath,'original.png','baseline must reproduce plain-image bypass');
 await db.exec(migration);
 let result=await read();assert.equal(result.playlist.length,2,'exposure count');assert.ok(result.playlist.every(x=>x.objectPath==='delivery.webp'&&x.composite===true));
 await db.exec("update public.kinojo_banner_campaign_items set composite_source_hash='stale'");assert.equal((await read()).playlist[0].objectPath,'original.png','stale hash rejected');
 await db.exec("update public.kinojo_banner_campaign_items set content_overlays='[{\"type\":\"TEXT\"}]',composite_source_hash=md5('[{\"type\": \"TEXT\"}]')");assert.equal((await read()).playlist[0].objectPath,'delivery.webp','overlay path preserved');
 await db.exec("update public.kinojo_banner_campaign_items set composite_object_path=null");assert.equal((await read()).playlist[0].objectPath,'original.png','legacy/no derivative preserved');
 await db.exec(fs.readFileSync(path.join(root,'supabase/rollbacks/20260909091815_banner_plain_delivery_derivatives_rollback.sql'),'utf8'));
 await db.exec("update public.kinojo_banner_campaign_items set content_overlays='[]',composite_object_path='delivery.webp',composite_source_hash=md5('[]')");assert.equal((await read()).playlist[0].objectPath,'original.png','rollback');
 console.log('Banner SQL487 baseline/plain/overlay/stale/missing/order/rollback: PASS');
}finally{await db.close();}})().catch(e=>{console.error(e);process.exitCode=1;});
