const fs=require('node:fs'),assert=require('node:assert/strict'),vm=require('node:vm');
const {stripTypeScriptTypes}=require('node:module');
const {PGlite}=require('../.codex-test-runtime/node_modules/@electric-sql/pglite');
(async()=>{
 const db=new PGlite();
 await db.exec(`create schema private;create role anon;create role authenticated;create role service_role;
 create table character_master(id bigint primary key,char_key text,server_id int,server_name text,character_name text,main_character_name text,is_main boolean,class_name text,
 profile_image_url text,detail_url text,legion_name text,latest_pve_combat_power int,latest_pve_item_level int,latest_pvp_combat_power int,latest_pvp_item_level int,
 latest_power_total int,latest_item_level_total int,last_synced_at timestamptz);
 create table lookup_session_targets(id bigint);
 create function kinojo_character_identity_key_v298(text) returns text language sql immutable as 'select lower(replace($1,'' '',''''))';
 create function kinojo_growth_status_from_delta(int,int) returns text language sql as $$select case when $1 is null then 'NEW' when $2>$1 then 'UP' else 'SAME' end$$;
 create function kinojo_growth_label(text) returns text language sql as 'select $1';
 create function kinojo_growth_review_text(text,text,int,int) returns text language sql as 'select $1||$2';
 `);
 await db.exec("create table character_history(id bigint generated by default as identity,history_date integer,character_name text,record_type text,gear_type text,pve_item_level integer,pve_combat_power integer,pvp_item_level integer,pvp_combat_power integer,pve_review_tag text,pvp_review_tag text,status text,mvp text,session_id text,role text,updated_at_sheet timestamp with time zone,memo text,server_id integer default 2002,server_name text,created_at timestamp with time zone default now(),growth_reviewed_at timestamp with time zone,growth_review_id bigint,growth_status text,growth_label text,power_delta integer, primary key(id));\ncreate table growth_reviews(id bigint generated by default as identity,session_id text,review_date integer,server_id integer default 2002,server_name text,character_name text,main_character_name text,is_main boolean default false,class_name text,current_history_id bigint,previous_history_id bigint,current_power_total integer,previous_power_total integer,power_delta integer,current_item_level_total integer,previous_item_level_total integer,item_level_delta integer,pve_power_delta integer,pvp_power_delta integer,pve_item_level_delta integer,pvp_item_level_delta integer,growth_status text default 'NODATA'::text,growth_label text default '데이터없음'::text,review_text text,review_source text default '033_GROWTH_REVIEW_ENGINE'::text,raw_current jsonb default '{}'::jsonb,raw_previous jsonb default '{}'::jsonb,created_at timestamp with time zone default now(),updated_at timestamp with time zone default now(), primary key(id));\ncreate table extension_character_payloads(id bigint generated by default as identity,session_id text,server_id integer default 2002,server_name text,character_name text,main_character_name text,class_name text,char_key text,profile_image_url text,detail_url text,pve_item_level integer,pve_combat_power integer,pvp_item_level integer,pvp_combat_power integer,raw_payload jsonb default '{}'::jsonb,received_at timestamp with time zone default now(),schema_version text,tool_name text,client_id text,snapshot_uid text,payload_hash text,lookup_order integer,intake_status text default 'received'::text,master_synced_at timestamp with time zone,master_sync_status text,master_sync_message text,growth_reviewed_at timestamp with time zone,growth_review_status text,growth_review_message text,gear_type text,gear_parse_status text,gear_evidence jsonb,source_snapshot_id bigint,parsed_item_level integer,parsed_combat_power integer, primary key(id));\ncreate table master_sync_events(id bigint generated by default as identity,session_id text,payload_id bigint,character_name text,main_character_name text,event_type text default 'sync'::text,status text default 'synced'::text,message text,before_data jsonb,after_data jsonb,raw_payload jsonb default '{}'::jsonb,created_at timestamp with time zone default now(), primary key(id));");
 await db.exec(`
 create unique index review_session_name on growth_reviews(session_id,server_id,character_name);
 create view v_kinojo_ranking_character_scope_v296 as select id as character_id,cm.*,
 legion_name as ranking_legion_name,id as ranking_owner_character_id,character_name as ranking_owner_character_name,true as is_default_ranking_legion from character_master cm;
 create view v_reaction_summary as select ''::text as character_name,0::int like_count,0::int dislike_count,0::int total_count,array[]::text[] comments where false;
 `);
 await db.exec(fs.readFileSync('supabase/migrations/20260908083301_character_history_stable_identity.sql','utf8'));
 // Integrated DB boundary: actual history backfill + review + ranking + rollup triggers.
 await db.exec(fs.readFileSync('tests/evidence/20260908-character-refresh-audit/rollup-existing-fixture.sql','utf8'));
 await db.exec('create trigger trg_character_history_growth_rollup_insert_v424 after insert on character_history for each row execute function private.kinojo_growth_rollup_history_insert_v424()');
 await db.exec(fs.readFileSync('supabase/migrations/20260908090023_character_rollup_identity_writer.sql','utf8'));
 await db.exec(fs.readFileSync('supabase/migrations/20260908091051_character_rollup_write_guard.sql','utf8'));
 await db.exec(`insert into character_master(id,char_key,server_id,character_name,main_character_name,is_main,class_name,latest_pve_combat_power,latest_pve_item_level)
 values(1,'111111111111111111',2003,'renamed','renamed',true,'궁성',150,20),
 (2,'222222222222222222',2002,'old','old',true,'궁성',999,20),
 (3,'333333333333333333',2002,'unknown','unknown',true,'궁성',70,20);
 insert into character_history(id,history_date,character_name,record_type,gear_type,status,session_id,server_id,pve_combat_power,pve_item_level,created_at)
 values(1,260901,'old','POWER','PVE','OK','s1',2002,100,10,'2026-09-01'),
 (2,260902,'old','POWER','PVE','OK','s2',2002,200,10,'2026-09-02'),
 (3,260903,'unknown','POWER','PVE','OK','s3',2002,50,10,'2026-09-03'),
 (4,260904,'collision','POWER','PVE','OK','s4',2002,50,10,'2026-09-04');
 `);
 const proof=async(payload,session,name,id,key)=>{
  await db.query("insert into extension_character_payloads(id,session_id,server_id,character_name,char_key,master_sync_status) values($1,$2,2002,$3,$4,'synced')",[payload,session,name,key]);
  await db.query("insert into master_sync_events(session_id,payload_id,status,after_data) values($1,$2,'synced',$3)",[session,payload,JSON.stringify({id,server_id:2002,character_name:name,char_key:key,latest_payload_id:payload})]);
 };
 await proof(1,'s1','old',1,'111111111111111111');await proof(2,'s2','old',2,'222222222222222222');
 await proof(4,'s4','collision',1,'111111111111111111');await proof(5,'s4','collision',2,'222222222222222222');
 const bf=async(apply)=>(await db.query('select kinojo_history_identity_backfill_v1(0,100,$1) as v',[apply])).rows[0].v;
 let r=await bf(false);assert.equal(r.linkable,2);assert.equal(r.linked,0);assert.equal(r.unresolved,2);
 r=await bf(true);assert.equal(r.linked,2);
 assert.deepEqual((await db.query('select id,character_master_id from character_history order by id')).rows.map(x=>x.character_master_id),[1,2,null,null]);
 r=await bf(true);assert.equal(r.linked,0); // idempotent, no rewriting verified links
 assert.equal((await db.query("select source_count from private.character_growth_rollups where character_master_id=1 and granularity='MONTH'")).rows[0].source_count,1);
 await assert.rejects(db.exec("update character_history set growth_identity_rolled_up=false where id=1"),/ROLLUP_RECEIPT_SERVER_OWNED/);
 await assert.rejects(db.exec("update character_history set growth_identity_rolled_up=true where id=3"),/ROLLUP_RECEIPT_SERVER_OWNED/);
 await assert.rejects(db.exec("update character_history set pve_combat_power=9999 where id=1"),/ROLLUP_SOURCE_CORRECTION_REQUIRED/);
 await assert.rejects(db.exec("update character_history set character_master_id=null where id=1"),/ROLLUP_SOURCE_CORRECTION_REQUIRED/);
 await assert.rejects(db.exec("insert into character_history(id,growth_identity_rolled_up) values(999,true)"),/ROLLUP_RECEIPT_SERVER_OWNED/);
 await db.exec('grant select,update on character_history to service_role; set role service_role');
 await assert.rejects(db.exec("update character_history set growth_identity_rolled_up=true where id=3"),/ROLLUP_RECEIPT_SERVER_OWNED/);
 await db.exec('reset role');
 assert.equal((await db.query('select character_name from character_history where id=1')).rows[0].character_name,'old');
 await db.exec(`insert into character_history(id,character_master_id,history_date,character_name,record_type,gear_type,status,session_id,server_id,pve_combat_power,pve_item_level,created_at)
 values(5,1,260908,'renamed','POWER','PVE','OK','now',2003,150,20,'2026-09-08'),
 (6,2,260908,'old','POWER','PVE','OK','now',2002,999,20,'2026-09-08');
 `);
 let g=(await db.query('select kinojo_growth_review_history(5) as v')).rows[0].v;
 assert.equal(g.previousHistoryId,1);assert.equal(g.powerDelta,50);
 g=(await db.query('select kinojo_growth_review_history(6) as v')).rows[0].v;
 assert.equal(g.previousHistoryId,2);assert.equal(g.powerDelta,799);
 g=(await db.query('select kinojo_growth_review_history(3) as v')).rows[0].v;assert.equal(g.code,'HISTORY_IDENTITY_UNVERIFIED');
 const rank=(await db.query('select private.kinojo_ranking_snapshot_scope_payload_v426(true,true) as v')).rows[0].v;
 const renamed=rank.pveItems.find(x=>x.character_id===1),namesake=rank.pveItems.find(x=>x.character_id===2);
 assert.equal(renamed.rank_power_delta,50);assert.equal(namesake.rank_power_delta,799);
 assert.equal(renamed.rank_baseline_date,260901);assert.equal(namesake.rank_baseline_date,260902);
 const month=(await db.query("select power_delta,source_count from private.character_growth_rollups where character_master_id=1 and granularity='MONTH'")).rows[0];
 assert.equal(month.power_delta,50);assert.equal(month.source_count,2);
 await db.exec(`insert into character_history(id,character_master_id,history_date,character_name,record_type,gear_type,status,server_id,pve_combat_power,pve_item_level,created_at)
 values(7,1,260908,'renamed','POWER','PVE','OK',2003,140,20,'2026-09-08 01:00'),
 (8,1,260909,'renamed','POWER','PVE','OK',2003,null,null,'2026-09-09');`);
 const repeated=(await db.query('select private.kinojo_ranking_snapshot_scope_payload_v426(true,true) as v')).rows[0].v.pveItems.find(x=>x.character_id===1);
 assert.equal(repeated.rank_baseline_date,260901);assert.equal(repeated.rank_power_delta,50);
 await db.exec('set enable_seqscan=off');
 const plan=await db.query("explain select history_date from character_history where character_master_id=1 and record_type='POWER' and status='OK' order by history_date desc,created_at desc,id desc limit 1");
 assert.match(JSON.stringify(plan.rows),/character_history_identity_day_idx/);
 await db.exec('reset enable_seqscan');
 // Execute the entire Master sync function, not a replacement INSERT.
 // Official HTTP and Snapshot intake transport are synthetic; actual Worker adapter and operating SQL Parser execute.
 await db.exec('begin');
 await db.exec(`create sequence master_fixture_ids start 10000;
 alter table character_master alter column id set default nextval('master_fixture_ids');
 alter table character_master add unique(server_id,character_name);
 alter table character_master add column status text,add column first_seen_at timestamptz,add column last_seen_at timestamptz,
 add column latest_session_id text,add column latest_payload_id bigint,add column latest_snapshot_uid text,add column latest_payload_hash text,add column sync_status text;
 alter table lookup_session_targets add column session_id text,add column lookup_order int,add column server_id int,
 add column server_name text,add column character_name text,add column list_original_name text;
 create table character_stat_sources(character_id bigint,gear_type text,item_level int,combat_power int,payload_id bigint,snapshot_id bigint,parser_version text,parse_status text,evidence jsonb,detected_at timestamptz,primary key(character_id,gear_type));
 create function kinojo_json_text(j jsonb,variadic keys text[]) returns text language sql as $$select j->>k from unnest(keys) k where j->>k is not null limit 1$$;
 create function kinojo_json_int(j jsonb,variadic keys text[]) returns int language sql as $$select kinojo_json_text(j,variadic keys)::int$$;
 create function kinojo_strip_server_suffix(text) returns text language sql as $$select $1$$;
 create function kinojo_server_name_by_id(int) returns text language sql as $$select 'fixture-server'::text$$;
 select setval(pg_get_serial_sequence('character_history','id'),100);
 select setval(pg_get_serial_sequence('master_sync_events','id'),100);
 insert into lookup_session_targets(id,session_id,server_id,character_name) values(50,'master-test',2003,'renamed');
 insert into extension_character_payloads(id,session_id,server_id,character_name,char_key,main_character_name,class_name,raw_payload)
 values(50,'master-test',2003,'renamed','111111111111111111','renamed','궁성',
 '{"targetId":50,"diagnosis":{"detectedGearType":"PVE","itemLevel":25,"combatPower":175}}');`);
 await db.exec(fs.readFileSync('tests/fixtures/character-refresh-parser.sql','utf8'));
 const worker=vm.createContext({TextEncoder,URL,Date,crypto:require('node:crypto').webcrypto,Deno:{serve(){},env:{get:()=>''}},console});
 vm.runInContext(stripTypeScriptTypes(fs.readFileSync('supabase/functions/character-refresh-worker/index.ts','utf8')).replace('export {};',''),worker);
 const snapshot=async(id,session,power,item)=>{
  const info={profile:{characterName:'renamed',serverId:2003,serverName:'fixture-server',className:'궁성',combatPower:power,itemLevel:item,profileImage:'https://synthetic.invalid/image?charKey=111111111111111111'}};
  const equipment={equipment:{equipmentList:Array.from({length:10},(_,i)=>({name:'합성 장비 '+i,icon:'https://synthetic.invalid/icon'}))}};
  const adapted=worker.parserSource(info,equipment);
  const collected=worker.officialSnapshot({sessionId:session,targetId:id,lookupOrder:1,context:{},target:{},candidate:{},resolved:{characterName:'renamed',expectedKey:'111111111111111111'},characterId:'synthetic-address',serverId:2003,adapted,infoPayload:info,equipmentPayload:equipment}).snapshot;
  await db.query('insert into lookup_snapshots(id,session_id,server_id,character_name,raw_payload,created_at) values($1,$2,2003,\'renamed\',$3,now())',[id,session,JSON.stringify(collected)]);
  await db.query('update extension_character_payloads set source_snapshot_id=$1 where id=$1',[id]);
 };
 await snapshot(50,'master-test',175,25);
 // Latest main DB477: explicitly edited family must survive old worker/main-name payloads.
 await db.exec("alter table character_master add main_character_id bigint;create table private.roster_family_overrides_v477(character_id bigint primary key,main_character_id bigint not null,updated_at timestamptz default now());insert into private.roster_family_overrides_v477(character_id,main_character_id) values(1,2)");
 const familySql=fs.readFileSync('supabase/migrations/20260908090316_legion_roster_family_editor_v477.sql','utf8');
 await db.exec(familySql.slice(familySql.indexOf('create function private.kinojo_roster_family_override_v477'),familySql.indexOf('create function private.kinojo_roster_family_state_v477')));
 let synced=(await db.query('select kinojo_master_sync_payload(50) v')).rows[0].v;
 assert.equal(synced.ok,true);assert.equal(synced.historyInserted,true);
 assert.equal((await db.query('select main_character_id from character_master where id=1')).rows[0].main_character_id,2);
 assert.equal((await db.query('select is_main from character_master where id=1')).rows[0].is_main,false);
 const linked=(await db.query("select * from character_history where session_id='master-test'")).rows[0];
 assert.equal(linked.character_master_id,1);assert.equal(linked.source_payload_id,50);assert.equal(linked.growth_identity_rolled_up,true);
 assert.equal((await db.query('select latest_pve_combat_power from character_master where id=1')).rows[0].latest_pve_combat_power,175);
 assert.equal((await db.query('select kinojo_growth_review_history($1) v',[linked.id])).rows[0].v.ok,true);
 synced=(await db.query('select kinojo_master_sync_payload(50) v')).rows[0].v;
 assert.equal(synced.skipped,true);
 assert.equal((await db.query("select count(*)::int n from character_history where session_id='master-test'")).rows[0].n,1);
 assert.equal((await db.query("select count(*)::int n from master_sync_events where payload_id=50")).rows[0].n,1);
 await db.exec(`insert into extension_character_payloads(id,session_id,server_id,character_name,char_key,raw_payload)
 values(51,'master-test',2002,'wrong','111111111111111111','{"targetId":50}');
 create function reject_master_event_fixture() returns trigger language plpgsql as $$begin if new.payload_id=52 then raise exception 'FORCED_MASTER_EVENT_FAILURE';end if;return new;end$$;
 create trigger reject_master_event after insert on master_sync_events for each row execute function reject_master_event_fixture();
 insert into lookup_session_targets(id,session_id,server_id,character_name) values(52,'atomic-test',2003,'renamed');
 insert into extension_character_payloads(id,session_id,server_id,character_name,char_key,raw_payload)
 values(52,'atomic-test',2003,'renamed','111111111111111111','{"targetId":52,"diagnosis":{"detectedGearType":"PVE","itemLevel":99,"combatPower":999}}');`);
 assert.equal((await db.query('select kinojo_master_sync_payload(51) v')).rows[0].v.code,'TARGET_IDENTITY_MISMATCH');
 await snapshot(52,'atomic-test',999,99);
 await db.exec('savepoint atomic_master');
 await assert.rejects(db.query('select kinojo_master_sync_payload(52)'),/FORCED_MASTER_EVENT_FAILURE/);
 await db.exec('rollback to savepoint atomic_master');
 assert.equal((await db.query('select latest_pve_combat_power from character_master where id=1')).rows[0].latest_pve_combat_power,175);
 assert.equal((await db.query("select count(*)::int n from character_history where session_id='atomic-test'")).rows[0].n,0);
 console.log('PASS: actual Worker adapter + operating SQL Parser + full Master/source/history/rollup/review/event link; DB477 family survives; retry dedup, target mismatch, downstream exception atomic rollback (HTTP and intake transport synthetic)');
 await db.exec('rollback');
 await db.exec('begin');
 const started=performance.now();
 await db.exec(`insert into character_history(id,character_master_id,history_date,character_name,record_type,gear_type,status,server_id,pve_combat_power,pve_item_level,created_at)
 select 100000+n,1000+(n%100),230101,'load-'||(n%100),'POWER','PVE','OK',2002,n,10,'2023-01-01'::timestamptz+n*interval '1 second' from generate_series(1,1000) n;`);
 const elapsed=performance.now()-started;
 assert.equal((await db.query('select count(*)::int n from character_history where id>100000 and growth_identity_rolled_up')).rows[0].n,1000);
 assert.equal((await db.query("select sum(source_count)::int n from private.character_growth_rollups where character_master_id>=1000 and granularity='MONTH'")).rows[0].n,1000);
 await db.exec(fs.readFileSync('tests/evidence/20260908-character-refresh-audit/rollup-existing-cleanup.sql','utf8'));
 const dry=(await db.query('select kinojo_character_growth_rollup_cleanup_v425(true,1000) v')).rows[0].v;
 assert.equal(dry.deleted.DAY,0);assert.equal(dry.deleted.WEEK,0);
 const cleaned=(await db.query('select kinojo_character_growth_rollup_cleanup_v425(false,1000) v')).rows[0].v;
 assert.ok(cleaned.deleted.DAY>=100);assert.ok(cleaned.deleted.WEEK>=100);
 assert.equal((await db.query("select count(*)::int n from private.character_growth_rollups where character_master_id>=1000 and granularity='MONTH'")).rows[0].n,100);
 assert.equal((await db.query('select count(*)::int n from character_history where id>100000')).rows[0].n,1000);
 console.log(JSON.stringify({test:'local PGlite history INSERT + guard + rollup',rows:1000,characters:100,elapsedMs:Math.round(elapsed),includesOfficialAPI:false,includesFullMasterSync:false,productionBenchmark:false}));
 await db.exec('rollback');
 await db.exec(fs.readFileSync('supabase/rollbacks/20260908091051_character_rollup_write_guard.sql','utf8'));
 await db.exec(fs.readFileSync('supabase/rollbacks/20260908090023_character_rollup_identity_writer.sql','utf8'));
 for(const role of ['anon','authenticated'])assert.equal((await db.query("select has_function_privilege($1,'kinojo_history_identity_backfill_v1(bigint,integer,boolean)','execute') as allowed",[role])).rows[0].allowed,false);
 await db.exec(`create table private.kinojo_ranking_history_state_v426(server_id int,character_name text,gear_type text,previous_history_date int,previous_power int,previous_item_level int);
 create table private.kinojo_ranking_review_state_v426(server_id int,character_name text,review_mode text,growth_label text,growth_status text,review_text text,source_updated_at timestamptz);`);
 await db.exec(fs.readFileSync('supabase/rollbacks/20260908083301_character_history_stable_identity.sql','utf8'));
 assert.equal((await db.query('select count(*)::int n from character_history')).rows[0].n,8);
 assert.equal((await db.query('select character_master_id from character_history where id=1')).rows[0].character_master_id,1);
 console.log('PASS: backfill dry-run/unique proof/ambiguity/missing proof/idempotence; transfer+rename versus namesake growth and ranking; ACL; rollback preserves raw identity links');
 await db.close();
})().catch(e=>{console.error(e.message);process.exit(1)});
