const fs=require('node:fs'),assert=require('node:assert/strict');
const {PGlite}=require('../.codex-test-runtime/node_modules/@electric-sql/pglite');
(async()=>{
 const db=new PGlite();
 await db.exec(`
 create schema private;
 create table private.character_snapshot_dispatch(singleton boolean,enabled boolean,candidate_id bigint,attempts int,retry_at timestamptz,last_result jsonb);
 insert into private.character_snapshot_dispatch values(true,true,null,0,null,null);
 create table private.character_snapshot_requests(completed_at timestamptz,due_at timestamptz);
 create table private.kinojo_ranking_snapshots_v390(snapshot_id bigint,status text,next_scope int);
 create table private.kinojo_ranking_snapshot_pointer_v390(singleton boolean,snapshot_id bigint,published_at timestamptz);
 insert into private.kinojo_ranking_snapshot_pointer_v390 values(true,75,now());
 create table public.updater_sessions(status text);create table public.character_detail_refresh_jobs(status text);
 create function public.kinojo_get_updater_actor(text) returns table(member_id int,level int) language sql as $$select 28,case when $1='local-admin' then 5 else 0 end$$;
 create function private.kinojo_admin_server_queue_status_cached_v422(int,int,text) returns jsonb language sql as $$select '{"ok":true,"active":false}'::jsonb$$;
 `);
 await db.exec(fs.readFileSync('supabase/migrations/20260908141651_character_refresh_completion_status.sql','utf8'));
 const read=async(key='local-admin')=>(await db.query('select public.kinojo_admin_server_queue_status_v289($1,null) r',[key])).rows[0].r;
 assert.equal((await read('invalid')).code,'LOOKUP_ADMIN_ACCESS_DENIED');
 assert.equal((await read('invalid')).publicSnapshot,undefined);
 assert.equal((await read()).publicSnapshot.state,'IDLE');
 await db.exec("insert into private.character_snapshot_requests values(null,now()+interval '30 minutes')");
 assert.equal((await read()).publicSnapshot.state,'WAIT_30_MINUTES');
 await db.exec("insert into updater_sessions values('running')");
 assert.equal((await read()).publicSnapshot.state,'WAIT_REFRESH');
 await db.exec("delete from updater_sessions; update private.character_snapshot_requests set due_at=now()-interval '1 minute'");
 assert.equal((await read()).publicSnapshot.state,'QUEUED');
 await db.exec("insert into private.kinojo_ranking_snapshots_v390 values(76,'BUILDING',2);update private.character_snapshot_dispatch set candidate_id=76");
 assert.equal((await read()).publicSnapshot.state,'BUILDING');
 await db.exec("update private.kinojo_ranking_snapshots_v390 set next_scope=4");
 assert.equal((await read()).publicSnapshot.state,'VERIFY');
 await db.exec("update private.kinojo_ranking_snapshots_v390 set status='READY'");
 assert.equal((await read()).publicSnapshot.state,'READY');
 await db.exec("update private.character_snapshot_dispatch set retry_at=now()+interval '5 minutes',attempts=1,last_result='{\"ok\":false,\"code\":\"TEST\"}'");
 assert.equal((await read()).publicSnapshot.state,'RETRY_WAIT');
 assert.equal((await read()).publicSnapshot.lastErrorCode,'TEST');
 await db.exec("update private.character_snapshot_dispatch set enabled=false");
 assert.equal((await read()).publicSnapshot.state,'DISABLED');
 assert.equal((await read()).publicSnapshot.publishedSnapshotId,75);
 await db.exec(fs.readFileSync('supabase/rollbacks/20260908141651_character_refresh_completion_status_rollback.sql','utf8'));
 assert.equal((await read()).publicSnapshot,undefined);
 await db.close();console.log('PASS: authorized read-only snapshot states and rollback');
})().catch(e=>{console.error(e);process.exitCode=1});
