const fs=require('node:fs');
const path=require('node:path');
const assert=require('node:assert/strict');
const {PGlite}=require('../.codex-test-runtime/node_modules/@electric-sql/pglite');
async function run(){
 const db=new PGlite();
 await db.exec(`create schema private; create role anon; create role authenticated; create role service_role bypassrls;
 create table public.character_master(id bigint primary key,char_key text,server_id int,class_name text);
 create table public.server_master(server_id int primary key,server_name text,server_short_name text,race_id int,is_active boolean);
 create table public.member_codes(id bigint,level int);
 create table public.lookup_session_targets(id bigint);
 create table public.updater_sessions(session_id text);
 create table public.character_identity_review_queue(review_id bigint,character_id bigint,review_status text);
 create table public.official_lookup_rate_state(provider text primary key,paused_until timestamptz,next_request_at timestamptz,consecutive_429 int,last_http_status int,last_source text,updated_at timestamptz);
 insert into public.character_master values(1,'123456789012345678',2002,'궁성');
 insert into public.server_master values(2002,'old','o',2,true),(2003,'new','n',2,true),(1001,'other','x',1,true);`);
 await db.exec(fs.readFileSync(path.join(__dirname,'../supabase/migrations/20260908053907_character_refresh_identity_and_list_guards.sql'),'utf8'));
 const servers=[{serverId:2002,serverName:'old',serverShortName:'o',raceId:2},{serverId:2003,serverName:'new',serverShortName:'n',raceId:2}];
 const checkpoint=async(completed=null,matches=null,k='123456789012345678',catalog=servers)=>(await db.query('select public.kinojo_identity_scan_checkpoint_v1($1,$2,$3,$4,$5) as value',[1,k,JSON.stringify(catalog),completed===null?null:JSON.stringify(completed),matches===null?null:JSON.stringify(matches)])).rows[0].value;
 let value=await checkpoint();assert.equal(value.ok,true);assert.deepEqual(value.completed,[]);
 value=await checkpoint([2002],[]);assert.deepEqual(value.completed,[2002]);
 value=await checkpoint([2003],[{serverId:2003,charKey:'123456789012345678'}]);assert.equal(value.completed.length,2);
 value=await checkpoint([1001],[]);assert.equal(value.code,'INVALID_SCAN_CHECKPOINT');
 value=await checkpoint(null,null,'123456789012345679');assert.equal(value.code,'STALE_IDENTITY');
 value=await checkpoint(null,null,'123456789012345678',servers.slice(0,1));assert.equal(value.code,'STALE_SERVER_CATALOG');
 await db.exec("update private.character_identity_scan_checkpoints set expires_at=now()-interval '1 second'");
 value=await checkpoint([2002],[]);assert.equal(value.code,'SCAN_EXPIRED_RESTART_REQUIRED');
 value=await checkpoint();assert.deepEqual(value.completed,[]);
 let gate=(await db.query('select public.kinojo_identity_rate_gate_v1() as value')).rows[0].value;assert.equal(gate.allowed,true);
 await db.exec("update official_lookup_rate_state set next_request_at=now()+interval '10 seconds'");
 const before=(await db.query('select next_request_at from official_lookup_rate_state')).rows[0].next_request_at;
 gate=(await db.query('select public.kinojo_identity_rate_gate_v1() as value')).rows[0].value;assert.equal(gate.allowed,false);
 assert.deepEqual((await db.query('select next_request_at from official_lookup_rate_state')).rows[0].next_request_at,before);
 gate=(await db.query('select public.kinojo_identity_rate_gate_v1(429,90) as value')).rows[0].value;assert.equal(gate.allowed,false);
 const acl=await db.query("select has_function_privilege('anon','public.kinojo_identity_scan_checkpoint_v1(bigint,text,jsonb,jsonb,jsonb)','execute') as allowed");assert.equal(acl.rows[0].allowed,false);
 await db.exec(fs.readFileSync(path.join(__dirname,'../supabase/rollbacks/20260908053907_character_refresh_identity_and_list_guards.sql'),'utf8'));
 assert.equal((await db.query("select has_function_privilege('service_role','public.kinojo_identity_scan_checkpoint_v1(bigint,text,jsonb,jsonb,jsonb)','execute') as allowed")).rows[0].allowed,false);
 assert.equal((await db.query('select count(*)::int as n from private.character_identity_scan_checkpoints')).rows[0].n,1);
 console.log('PASS: PostgreSQL migration syntax, resume/expiry, catalog/key guards, shared rate gate, service-only ACL');
 await db.close();
}
run().catch(e=>{console.error(e.message);process.exitCode=1});
