const fs=require('node:fs'),assert=require('node:assert/strict');
const {PGlite}=require('../.codex-test-runtime/node_modules/@electric-sql/pglite');
const read=p=>fs.readFileSync(p,'utf8');
async function run(){
 const db=new PGlite();
 try{
 await db.exec(read('tests/fixtures/character-refresh-policy-schema.sql'));
 await db.exec(read('tests/fixtures/character-refresh-relation-schema.sql'));
 // Isolated auth fixture: no real session creation or production writes.
 await db.exec(`create function public.kinojo_admin_member_from_credential_v325(text) returns setof public.member_codes language sql as $$ select * from member_codes where id=case when $1='test-manager' then 1 else -1 end $$;
 create function public.kinojo_prepare_lookup_queue_from_list(text,text,jsonb,jsonb default '{}'::jsonb) returns jsonb language sql as $$ select '{}'::jsonb $$;
 create function public.kinojo_prepare_lookup_queue_from_list(text,text,jsonb) returns jsonb language sql as $$ select '{}'::jsonb $$;
 create function public.kinojo_character_identity_key_v298(text) returns text language sql immutable as $$ select lower(regexp_replace($1,'\\s','','g')) $$;
 insert into member_codes(id,level) values(1,3);`);
 const schedule=read('supabase/migrations/20260828104017_sanctuary_management_stage5_complete_v437.sql');
 const start=schedule.indexOf('create or replace function private.kinojo_sm_rule_occurrences_v437');
 await db.exec(schedule.slice(start,schedule.indexOf('$$;',schedule.indexOf('as $$',start))+3));
 await db.exec(read('supabase/migrations/20260908062618_character_refresh_eligibility_and_restore.sql'));
 const q=async(sql,args=[])=> (await db.query(sql,args)).rows;
 const policy=async id=>(await q('select private.kinojo_character_lookup_policy($1) p',[id]))[0].p;
 await db.exec(`insert into character_master(id,character_name,server_id,legion_name,main_character_id,last_lookup_success_at) values
 (1,'root',2002,'깡',null,now()),(2,'externalalt',2003,'other',1,now()),(3,'guest',2003,'other',null,now()),
 (4,'archived_D',2002,'깡',null,now()),(5,'samelegionother',2003,'깡',null,now()),(6,'due',2003,null,null,now()-interval '8 days');`);
 assert.equal((await policy(1)).reason,'MANAGED_LEGION');
 assert.equal((await policy(2)).eligible,false);assert.equal((await policy(5)).eligible,false);
 assert.equal((await policy(4)).reason,'DELETION_CANDIDATE');assert.equal((await policy(6)).reason,'ACTIVITY_REVIEW_DUE');
 await db.exec(`insert into private.sanctuary_management_teams_v412(team_id,status) values(1,'ACTIVE');
 insert into private.sanctuary_management_slots_v412(team_id,character_id) values(1,3);
 insert into private.sanctuary_management_schedule_rules_v412(schedule_id,team_id,status) values(1,1,'ACTIVE');
 insert into private.sanctuary_management_schedule_versions_v437(schedule_id,team_id,effective_from,schedule_kind,starts_on,weekdays,starts_at,duration_minutes,timezone_name,status)
 values(1,1,current_date-10,'WEEKLY',current_date-10,array[1,2,3,4,5,6,7]::smallint[],'10:00',30,'Asia/Seoul','ACTIVE');`);
 assert.equal((await policy(3)).reason,'CURRENT_SANCTUARY');
 await db.exec("update private.sanctuary_management_schedule_versions_v437 set starts_on=current_date+365");assert.equal((await policy(3)).eligible,false);
 await db.exec("update private.sanctuary_management_schedule_versions_v437 set starts_on=current_date-10");
 await db.exec("update character_master set lookup_excluded=true where id=3");assert.equal((await policy(3)).reason,'ADMIN_EXCLUDED');
 const update=async(id,mode,scope,revision='',credential='test-manager')=>(await q('select kinojo_admin_character_lookup_policy_update($1,$2,$3,$4,$5,$6) p',[credential,id,mode,scope,'synthetic test',scope==='GROUP'&&revision===''?(await policy(id)).groupRevision:revision]))[0].p;
 assert.equal((await update(1,'EXCLUDE','GROUP')).ok,true);assert.equal((await policy(2)).reason,'ADMIN_EXCLUDED');
 assert.equal((await update(2,'INCLUDE','CHARACTER')).ok,true);assert.equal((await policy(2)).reason,'ADMIN_INCLUDED');
 assert.equal((await update(2,'EXCLUDE','CHARACTER')).code,'STALE_LOOKUP_POLICY');
 assert.equal((await update(4,'INCLUDE','CHARACTER')).code,'IDENTITY_RESTORE_REQUIRED');
 assert.equal((await update(6,'INCLUDE','CHARACTER','','bad')).code,'ADMIN_ACCESS_DENIED');
 assert.equal((await policy(3)).reason,'ADMIN_EXCLUDED');
 assert.equal((await q("select has_function_privilege('anon','kinojo_prepare_lookup_queue_from_list(text,text,jsonb)','execute') allowed"))[0].allowed,false);
 await db.exec(`create function kinojo_meter_int_50010(text) returns integer language sql immutable as $$ select $1::integer $$;
 create function kinojo_normalize_aion_class_name(text) returns text language sql immutable as $$ select nullif(trim($1),'') $$;
 create function kinojo_normalize_character_name(text) returns text language sql immutable as $$ select lower(trim($1)) $$;
 update member_codes set level=4,main_character_name='root' where id=1;
 update character_master set char_key='123456789012345678',class_name='궁성',is_main=true where id=1;
 update character_master set main_character_name='root' where id=2;
 insert into server_master(server_id,server_name,server_short_name,race_id,is_active) values(2002,'지켈','지켈',2,true),(2003,'브리트라','브리',2,true),(1001,'다른종족','타',1,true);
 insert into private.legion_tree_assignments(legion_name,character_id) values('깡',1);
 insert into private.legion_tree_configs(legion_name,revision) values('깡',1);`);
 const candidate={charKey:'123456789012345678',serverId:2003,characterName:'changed',className:'궁성',detailUrl:'https://example.test/characters/2003/verified',sourceServerId:2002,sourceCharacterName:'root'};
 const apply=async candidate=>(await q('select kinojo_admin_character_identity_apply_v1($1,1,$2) p',['test-manager',JSON.stringify(candidate)]))[0].p;
 assert.equal((await apply({...candidate,className:'치유성'})).code,'CLASS_MISMATCH');
 assert.equal((await apply({...candidate,charKey:'123456789012345679'})).code,'CHAR_KEY_MISMATCH');
 assert.equal((await apply({...candidate,sourceCharacterName:'stale'})).code,'STALE_IDENTITY_SOURCE');
 assert.equal((await apply({...candidate,serverId:1001})).code,'SERVER_RACE_MISMATCH');
 assert.equal((await q('select count(*)::int n from character_identity_change_history'))[0].n,0);
 await db.exec(`create function private.reject_identity_test() returns trigger language plpgsql as $$ begin raise exception 'synthetic failure'; end $$;
 create trigger reject_identity_test before update on character_master for each row when (new.character_name='changed') execute function private.reject_identity_test();`);
 await assert.rejects(()=>apply(candidate),/synthetic failure/);
 assert.equal((await q('select character_name from character_master where id=1'))[0].character_name,'root');
 assert.equal((await q('select count(*)::int n from private.legion_tree_assignments'))[0].n,1);
 assert.equal((await q('select revision from private.legion_tree_configs'))[0].revision,1);
 assert.equal((await q('select count(*)::int n from character_identity_change_history'))[0].n,0);
 assert.equal((await q('select main_character_name from character_master where id=2'))[0].main_character_name,'root');
 await db.exec('drop trigger reject_identity_test on character_master');
 assert.equal((await apply(candidate)).ok,true);
 assert.equal((await q('select legion_name from character_master where id=1'))[0].legion_name,null);
 assert.equal((await q('select count(*)::int n from private.legion_tree_assignments'))[0].n,0);
 assert.equal((await q('select main_character_name from character_master where id=2'))[0].main_character_name,'changed');
 assert.equal((await apply(candidate)).ok,true);
 assert.equal((await q('select count(*)::int n from character_identity_change_history'))[0].n,1);
 console.log('PASS: admin identity exact key/class/race/stale guards, atomic relation rollback and commit, retry history dedup');
 await db.exec(`create function kinojo_validate_updater_session(text,text) returns jsonb language sql as $$ select jsonb_build_object('ok',$2='test-session') $$;
 insert into lookup_batches(session_id,status,list_sync_status,stage,worker_id) values('complete','completed','done','COMPLETE','old');
 insert into updater_sessions(session_id,session_token,status,stage) values('complete','test-session','completed','COMPLETE');`);
 let result=(await q("select kinojo_lookup_record_sheet_export_result('complete','test-session',false) p"))[0].p;
 assert.equal(result.alreadyCompleted,true);
 result=(await q("select kinojo_server_queue_list_sync_fail_v289('complete','test-session','old','LATE','late error') p"))[0].p;
 assert.equal(result.alreadyCompleted,true);assert.equal(result.failed,false);
 assert.equal((await q("select status from updater_sessions where session_id='complete'"))[0].status,'completed');
 await db.exec("insert into lookup_batches(session_id,status) values('pending','running')");
 result=(await q("select kinojo_lookup_record_sheet_export_result('pending','test-session',true,5,5,0) p"))[0].p;
 assert.equal(result.code,'LIST_COMPLETION_COUNT_MISMATCH');
 console.log('PASS: completed session survives late export/failure, actual Queue count required');
 await db.exec(`create table private.character_identity_scan_checkpoints(character_id bigint,char_key text,servers jsonb,class_name text,completed jsonb,matches jsonb,expires_at timestamptz,generation bigint);
 alter table google_list_sheet_sync_queue add unique(session_id,character_name,server_id);
 alter table google_list_sheet_sync_queue alter updated_at set default now();
 create sequence synthetic_queue_id;alter table google_list_sheet_sync_queue alter id set default nextval('synthetic_queue_id');
 create function kinojo_list_display_name_v287(text,integer) returns text language sql immutable as $$ select $1||'['||$2||']' $$;
 insert into character_master(id,character_name,server_id,class_name,char_key,list_row) values(10,'old-owner',2003,'궁성','222222222222222222',10),(11,'incoming',2003,'치유성','333333333333333333',11);
 insert into private.character_identity_scan_checkpoints select 10,'222222222222222222',jsonb_agg(jsonb_build_object('serverId',server_id,'serverName',server_name,'serverShortName',server_short_name,'raceId',race_id) order by server_id),'궁성','[2002,2003]','[]',now()+interval '5 minutes',1 from server_master where race_id=2;`);
 await db.exec(read('tests/fixtures/character-refresh-list-payload.sql'));
 await db.exec("update character_master set is_main=true where id=11;insert into character_master(id,character_name,server_id,class_name,main_character_id,main_character_name,list_row) values(12,'linked-alt',2003,'궁성',11,'incoming',12)");
 const chain=[{characterId:10,action:'DELETE_CANDIDATE',generation:'1'},{characterId:11,action:'APPLY',candidate:{charKey:'333333333333333333',className:'치유성',serverId:2003,characterName:'old-owner',sourceServerId:2003,sourceCharacterName:'incoming'}}];
 const collision=async changes=>(await q("select kinojo_admin_identity_collision_apply('test-manager',$1) p",[JSON.stringify(changes)]))[0].p;
 assert.equal((await collision([{...chain[0],generation:'stale'},chain[1]])).ok,false);
 assert.equal((await q('select character_name from character_master where id=10'))[0].character_name,'old-owner');
 assert.equal((await collision([chain[0],{...chain[1],candidate:{...chain[1].candidate,charKey:'wrong'}}])).ok,false);
 assert.equal((await q('select character_name from character_master where id=10'))[0].character_name,'old-owner');
 assert.equal((await collision(chain)).ok,true);
 assert.equal((await q('select character_name from character_master where id=10'))[0].character_name,'old-owner_D');
 assert.equal((await policy(10)).reason,'DELETION_CANDIDATE');
 assert.equal((await q('select character_name from character_master where id=11'))[0].character_name,'old-owner');
 const pending=(await q("select kinojo_admin_identity_list_pending('test-manager',11) p"))[0].p;
 assert.equal(pending.items.length,3);assert.equal(pending.items[0].listStatus,'삭제후보');
 assert.equal(pending.items.find(x=>Number(x.id)===12).mainCharacterName,'old-owner[2003]');
 assert.equal((await q("select kinojo_admin_identity_list_pending('test-manager',11,$1,'stale') p",[pending.items[0].queueId]))[0].p.ok,false);
 assert.equal((await q("select kinojo_admin_identity_list_pending('test-manager',11,$1,$2) p",[pending.items[0].queueId,pending.items[0].queueRevision]))[0].p.ok,true);
 console.log('PASS: collision both-side transaction, stale/invalid proof rollback, _D archive and durable existing list Queue');
 await db.exec(`create function private.kinojo_legion_tree_finalize_relation_v373(text) returns jsonb language sql as $$ select '{"ok":true}'::jsonb $$;
 create function kinojo_server_name_by_id(integer) returns text language sql as $$ select server_name from server_master where server_id=$1 $$;
 insert into updater_sessions(session_id,session_token) values('restore','test-session');
 insert into character_master(id,character_name,server_id,legion_name,class_name,latest_payload_id,last_lookup_success_at,legion_source_snapshot_id,legion_updated_at)
 values(20,'db-only',2002,'깡','궁성',20,now(),20,now());
 insert into extension_character_payloads(id,session_id,master_sync_status,gear_type) values(20,'restore','synced','PVE');
 insert into lookup_session_targets(id,session_id,character_name,server_id,target_source,target_status,payload_id,snapshot_id,queued_at,lookup_order)
 values(20,'restore','db-only',2002,'server:db_only_restore_v1','lookup_done',20,20,now()-interval '1 minute',1);`);
 const restoreAllowed=async()=>(await q('select private.kinojo_db_only_list_restore_allowed(20) allowed'))[0].allowed;
 assert.equal(await restoreAllowed(),false);
 await db.exec("update character_master set char_key='555555555555555555' where id=20;update extension_character_payloads set char_key='555555555555555555',server_id=2002,character_name='db-only' where id=20");
 assert.equal(await restoreAllowed(),true);
 await db.exec("update lookup_session_targets set target_source='server_queue:server:db_only_restore_v1' where id=20");
 assert.equal(await restoreAllowed(),false,'regression: worker prefix was rejected');
 await db.exec(read('supabase/migrations/20260908145200_character_db_only_restore_source.sql'));
 assert.equal(await restoreAllowed(),true,'worker-prefixed DB-only target must restore');
 await db.exec("update lookup_session_targets set target_source='untrusted:server:db_only_restore_v1' where id=20");
 assert.equal(await restoreAllowed(),false,'do not broadly accept arbitrary suffixes');
 await db.exec("update lookup_session_targets set target_source='server_queue:server:db_only_restore_v1' where id=20");
 await db.exec("update character_master set legion_name='other' where id=20");assert.equal(await restoreAllowed(),false);
 await db.exec("update character_master set legion_name='깡',lookup_excluded=true where id=20");assert.equal(await restoreAllowed(),false);
 await db.exec("update character_master set lookup_excluded=false where id=20");
 await db.exec('update character_master set legion_source_snapshot_id=19 where id=20');assert.equal(await restoreAllowed(),false);
 await db.exec("update character_master set legion_source_snapshot_id=20,legion_updated_at=now()-interval '1 hour' where id=20");assert.equal(await restoreAllowed(),false);
 await db.exec('update character_master set legion_updated_at=now() where id=20');
 const makeQueue=async()=>(await q("select kinojo_queue_list_sheet_sync_session('restore','test-session') p"))[0].p;
 result=await makeQueue();assert.equal(result.ok,true,JSON.stringify(result));assert.equal(result.appendCount,1);
 assert.equal((await q("select list_row from google_list_sheet_sync_queue where session_id='restore'"))[0].list_row,null,'append must never use stale Master row');
 assert.equal((await makeQueue()).reusedExistingQueue,true);
 const queue=(await q("select * from google_list_sheet_sync_queue where session_id='restore'"))[0];
 await db.exec("update google_list_sheet_sync_queue set character_name='wrong' where session_id='restore'");
 assert.equal((await makeQueue()).code,'LIST_QUEUE_MEMBERSHIP_MISMATCH');
 await db.exec("update google_list_sheet_sync_queue set character_name='db-only' where session_id='restore'");
 const finalize=async maps=>(await q("select kinojo_legion_tree_list_readback_finalize_v373('restore','test-session',$1) p",[JSON.stringify(maps)]))[0].p;
 result=await finalize([{id:queue.id,row:25},{id:999999,row:26}]);assert.equal(result.ok,false);
 assert.equal((await q('select list_row from character_master where id=20'))[0].list_row,null);
 result=await finalize([{id:queue.id,row:25}]);assert.equal(result.ok,true,JSON.stringify(result));
 assert.equal((await q('select list_row from character_master where id=20'))[0].list_row,25);
 assert.equal((await finalize([{id:queue.id,row:25}])).ok,true);
 console.log('PASS: DB-only current official evidence, Queue exact membership/reuse, atomic mapping rollback/commit/retry');
 await db.exec(`insert into character_master(id,character_name,server_id,legion_name,class_name,char_key) values(30,'auto-old',2002,'깡','궁성','444444444444444444');
 insert into lookup_session_targets(id,session_id,character_name,server_id,list_row) values(30,'auto','auto-old',2002,30);
 insert into private.legion_tree_assignments(legion_name,character_id) values('깡',30);`);
 const autoCandidate={charKey:'444444444444444444',className:'궁성',serverId:2003,characterName:'auto-new',sourceServerId:2002,sourceCharacterName:'auto-old'};
 const auto=async c=>(await q("select kinojo_character_identity_recovery_apply_v1('auto','test-session',30,$1) p",[JSON.stringify(c)]))[0].p;
 assert.equal((await auto({...autoCandidate,className:'치유성'})).code,'CLASS_MISMATCH');
 await db.exec("create trigger reject_identity_test before update on character_master for each row when (new.character_name='auto-new') execute function private.reject_identity_test()");
 await assert.rejects(()=>auto(autoCandidate),/synthetic failure/);
 assert.equal((await q('select count(*)::int n from private.legion_tree_assignments where character_id=30'))[0].n,1);
 assert.equal((await q("select count(*)::int n from google_list_sheet_sync_queue where session_id='auto'"))[0].n,0);
 await db.exec('drop trigger reject_identity_test on character_master');
 result=await auto(autoCandidate);assert.equal(result.ok,true,JSON.stringify(result));
 assert.equal((await auto(autoCandidate)).ok,true);
 assert.equal((await q('select legion_name from character_master where id=30'))[0].legion_name,null);
 assert.equal((await q('select count(*)::int n from private.legion_tree_assignments where character_id=30'))[0].n,0);
 assert.equal((await q('select count(*)::int n from character_identity_change_history where character_id=30'))[0].n,1);
 assert.equal((await q("select count(*)::int n from google_list_sheet_sync_queue where session_id='auto'"))[0].n,1);
 console.log('PASS: automatic transfer relation transaction rollback/commit, history and Queue retry idempotence');
 await db.exec(`insert into updater_sessions(session_id,session_token) values('auto','test-session');
 insert into extension_character_payloads(id,session_id,master_sync_status,gear_type) values(30,'auto','synced','PVE'),(31,'auto','synced','PVE');
 update character_master set latest_payload_id=30,latest_pve_combat_power=12345 where id=30;
 update lookup_session_targets set target_status='lookup_done',payload_id=30 where id=30;
 insert into character_master(id,character_name,server_id,class_name,latest_payload_id) values(31,'normal-list',2002,'궁성',31);
 insert into lookup_session_targets(id,session_id,character_name,server_id,list_row,target_status,payload_id) values(31,'auto','normal-list',2002,31,'lookup_done',31);`);
 result=(await q("select kinojo_queue_list_sheet_sync_session('auto','test-session') p"))[0].p;assert.equal(result.ok,true,JSON.stringify(result));assert.equal(result.queuedCount,2);
 const autoQueue=(await q("select * from google_list_sheet_sync_queue where session_id='auto' and character_id=30"))[0];assert.equal(Number(autoQueue.pve_combat_power),12345);assert.equal(autoQueue.identity_changed,true);
 console.log('PASS: early identity Queue expanded without loss and exports freshly committed stats');
 await db.exec(`create function kinojo_lookup_step_upsert(text,text,integer,text,integer,integer,text,jsonb) returns jsonb language sql as $$ select '{"ok":true}'::jsonb $$;
 create function kinojo_runtime_progress(text,text,text,text,text,integer,integer,jsonb) returns jsonb language sql as $$ select '{"ok":true}'::jsonb $$;
 create function kinojo_strip_server_suffix(text) returns text language sql immutable as $$ select $1 $$;
 create function kinojo_character_identity_strict_258(text,integer) returns jsonb language sql as $$ select jsonb_build_object('matchable',true,'status','OK','characterName',$1,'serverId',$2) $$;
 create function kinojo_lookup_admin_exclusion_reason(integer,text) returns text language sql as $$ select exclusion_reason from character_master where server_id=$1 and character_name=$2 and lookup_excluded is true limit 1 $$;
 alter table lookup_session_targets add unique(session_id,server_id,character_name);
 create sequence synthetic_target_id start 1000;alter table lookup_session_targets alter id set default nextval('synthetic_target_id');
 alter table character_master add unique(server_id,character_name);
 insert into character_master(id,character_name,server_id,class_name,legion_name) values(40,'h-only',2002,'궁성','깡'),(41,'suffix_D',2002,'궁성','깡'),(42,'normal-prepare',2002,'궁성','깡');`);
 const prepare=async(list,complete=true)=>(await q("select kinojo_prepare_lookup_queue_from_list_v296('prepare','test-session',$1,$2) p",[JSON.stringify(list),JSON.stringify({serverReadComplete:complete})]))[0].p;
 const input=[{row:40,name:'h-only',status:'삭제후보',serverId:2002},{row:41,name:'suffix_D',serverId:2002},{row:42,name:'normal-prepare',className:'치유성',serverId:2002}];
 assert.equal((await prepare(input,false)).code,'COMPLETE_LIST_READ_REQUIRED');
 result=await prepare(input);assert.equal(result.ok,true,JSON.stringify(result));
 assert.equal((await policy(40)).reason,'DELETION_CANDIDATE');assert.equal((await policy(41)).reason,'DELETION_CANDIDATE');
 assert.equal((await q("select count(*)::int n from lookup_session_targets where session_id='prepare' and character_name in ('h-only','suffix_D')"))[0].n,0);
 assert.equal((await q('select class_name from character_master where id=42'))[0].class_name,'궁성');
 const targets=(await q("select count(*)::int n from lookup_session_targets where session_id='prepare'"))[0].n;
 assert.equal((await prepare([])).code,'SESSION_ALREADY_PREPARED');assert.equal((await q("select count(*)::int n from lookup_session_targets where session_id='prepare'"))[0].n,targets);
 console.log('PASS: H-only/suffix prepare exclusion, incomplete read blocks, verified class preserved, repeated prepare preserves targets');
 console.log('PASS: policy SQL, manual precedence, group exceptions, current schedule/future guard, 7-day review, stale/admin ACL');
 const rowsBefore=(await q('select count(*)::int n from character_master'))[0].n;
 await db.exec(read('tests/fixtures/character-refresh-list-preference-schema.sql'));
 await db.exec(read('supabase/migrations/20260908073247_character_refresh_list_write_preference.sql'));
 await db.exec(`insert into updater_sessions(session_id,session_token,raw_payload) values('off-identity','test-session','{"serverQueue":true,"listSheetSyncEnabled":false}');
 insert into character_master(id,character_name,server_id,legion_name,class_name,char_key) values(50,'off-old',2002,'깡','궁성','555555555555555555');
 insert into lookup_session_targets(id,session_id,character_name,server_id,list_row) values(50,'off-identity','off-old',2002,50);
 insert into private.legion_tree_assignments(legion_name,character_id) values('깡',50);`);
 const offCandidate={...autoCandidate,charKey:'555555555555555555',characterName:'off-new',sourceCharacterName:'off-old'};
 const offApply=(await q("select kinojo_character_identity_recovery_apply_v1('off-identity','test-session',50,$1) p",[JSON.stringify(offCandidate)]))[0].p;
 assert.equal(offApply.ok,true);assert.equal(offApply.listSyncQueued,false);
 assert.equal((await q('select legion_name from character_master where id=50'))[0].legion_name,null);
 assert.equal((await q("select count(*)::int n from google_list_sheet_sync_queue where session_id='off-identity'"))[0].n,0);
 assert.equal((await q("select kinojo_queue_list_sheet_sync_session('off-identity','test-session') p"))[0].p.queuedCount,0);
 console.log('PASS: combined policy + OFF automatic identity transaction clears former legion but creates zero initial/final list Queue');
 // Run the actual prepare facade and v296 consumer with the new lifecycle policy.
 await db.exec('alter table character_master add primary key(id)');
 await db.exec(read('supabase/migrations/20260909060134_character_family_lookup_eligibility.sql'));
 await db.exec(read('supabase/migrations/20260909082438_character_activity_lifecycle.sql'));
 await db.exec(`create function public.kinojo_is_full_list_lookup_v297(jsonb) returns boolean language sql as $$select true$$;
 insert into character_master(id,character_name,server_id,legion_name,main_character_id,last_lookup_success_at,legion_updated_at,legion_source_snapshot_id)
 values(60,'auto-external',2003,'external',60,now(),now(),60),(61,'protected-alt',2003,'external',60,now(),now(),61);
 insert into lookup_snapshots(id,server_id,character_name,status,raw_payload)
 select id,server_id,character_name,'OK',jsonb_build_object('officialRaw',jsonb_build_object('info',jsonb_build_object('profile',
 jsonb_build_object('serverId',server_id,'characterName',character_name,'regionName',legion_name))))
 from character_master where id in(60,61);`);
 const activityPrepare=async(session,list=[],complete=true)=>(await q(
 "select kinojo_prepare_lookup_queue_from_list($1,'test-session',$2,$3) p",
 [session,JSON.stringify(list),JSON.stringify({serverReadComplete:complete})]))[0].p;
 assert.equal((await activityPrepare('activity-fail',[],false)).ok,false);
 assert.equal((await q('select count(*)::int n from private.character_activity_lifecycle'))[0].n,0);
 result=await activityPrepare('activity-exclude');
 assert.equal(result.ok,true,JSON.stringify(result));
 assert.equal((await q("select count(*)::int n from lookup_session_targets where session_id='activity-exclude' and character_name in ('auto-external','protected-alt')"))[0].n,0);
 assert.equal((await q("select count(*)::int n from private.character_activity_lifecycle where character_id in(60,61) and state='EXCLUDED'"))[0].n,2,'DB-only excluded records receive lifecycle dates');
 const activityEvents=await q('select * from private.character_activity_events order by id');
 assert.equal((await activityPrepare('activity-exclude')).code,'SESSION_ALREADY_PREPARED');
 assert.deepEqual(await q('select * from private.character_activity_events order by id'),activityEvents);
 await db.exec("update character_master set server_id=2002,legion_name='깡' where id=61");
 result=await activityPrepare('activity-restore');
 assert.equal(result.ok,true,JSON.stringify(result));
 assert.equal((await q("select count(*)::int n from lookup_session_targets where session_id='activity-restore' and character_name in ('auto-external','protected-alt')"))[0].n,2);
 assert.equal((await q("select count(*)::int n from private.character_activity_lifecycle where character_id in(60,61) and state='RESTORED' and cleanup_candidate_at is null"))[0].n,2);
 const reconcileDefinition=(await q("select pg_get_functiondef('private.kinojo_character_activity_reconcile(bigint,timestamptz)'::regprocedure) definition"))[0].definition;
 await db.exec("create or replace function private.kinojo_character_activity_reconcile(p_character_id bigint,p_at timestamptz default now()) returns jsonb language sql as $$select '{\"ok\":false}'::jsonb$$");
 await assert.rejects(activityPrepare('activity-error'),/ACTIVITY_RECONCILIATION_FAILED/);
 assert.equal((await q("select count(*)::int n from lookup_session_targets where session_id='activity-error'"))[0].n,0,'failed lifecycle write rolls back queue preparation');
 await db.exec(reconcileDefinition);
 for(const role of ['anon','authenticated'])assert.equal((await q(
   "select has_function_privilege($1,'public.kinojo_prepare_lookup_queue_from_list(text,text,jsonb,jsonb)','EXECUTE') ok",[role]))[0].ok,false);
 await db.exec(read('supabase/rollbacks/20260909082438_character_activity_lifecycle_rollback.sql'));
 const restoredEvents=await q('select * from private.character_activity_events order by id');
 assert.equal((await activityPrepare('activity-rollback')).ok,true);
 assert.deepEqual(await q('select * from private.character_activity_events order by id'),restoredEvents,'rollback disables preparation writes');
 console.log('PASS: actual prepare facade/queue, DB-only exclusion, family restoration, failed/repeated requests and caller rollback');
 await db.exec(read('supabase/rollbacks/20260908073247_character_refresh_list_write_preference.sql'));
 await db.exec(read('supabase/rollbacks/20260908062618_character_refresh_eligibility_and_restore.sql'));
 assert.equal((await q('select count(*)::int n from character_master'))[0].n,rowsBefore+3);
 assert.equal((await q("select character_name from character_master where id=10"))[0].character_name,'old-owner_D');
 console.log('PASS: staged rollback compiles, preserves records/policies/identity audit and Queue');
 }finally{await db.close();}
}
run().catch(e=>{console.error(e);process.exitCode=1});
