const fs=require('node:fs'),assert=require('node:assert/strict');
const {PGlite}=require(process.env.PGLITE_MODULE||'../.codex-test-runtime/node_modules/@electric-sql/pglite');
const read=p=>fs.readFileSync(p,'utf8');
const base='tests/fixtures/legion-add-baseline/';
async function main(){
 const db=new PGlite();
 try{
 await db.exec(read('tests/fixtures/character-refresh-policy-schema.sql'));
 await db.exec(read(base+'queue-schema.sql'));
 await db.exec(`create schema extensions;
 create function kinojo_character_identity_key_v298(text) returns text language sql immutable as $$select lower(replace($1,' ',''))$$;
 create function kinojo_web_session_validate_v320(text,boolean default false) returns jsonb language sql as $$select case when $1='fixture-manager' then '{"ok":true,"profile":{"id":1,"level":3,"role":"ADMIN","mainCharacterName":"fixture"}}'::jsonb else '{"ok":false,"code":"SESSION_INVALID"}'::jsonb end$$;
 create function kinojo_validate_updater_session(text,text) returns jsonb language sql as $$select jsonb_build_object('ok',exists(select 1 from updater_sessions where session_id=$1 and session_token=$2))$$;
 create function kinojo_lookup_admin_exclusion_reason(integer,text) returns text language sql stable as $$select case when $2='excluded' then 'MANUAL' else null end$$;
 create function kinojo_expire_updater_lock() returns void language sql as $$select null::void$$;
 create function kinojo_lookup_step_upsert(text,text,integer,text,integer,integer,text,jsonb) returns void language sql as $$select null::void$$;
 create sequence fixture_master;alter table character_master alter id set default nextval('fixture_master');
 create sequence fixture_target;alter table lookup_session_targets alter id set default nextval('fixture_target');
 alter table character_master add unique(server_id,character_name);
 insert into server_master(server_id,server_name,is_active) values(2002,'지켈',true),(2003,'다른서버',true);
 insert into updater_lock_state(id,is_locked) values('global',false);
 insert into character_master(server_id,character_name,is_active,status,list_row,main_character_id) values(2002,'unrelated',true,'OK',7,777),(2003,'unrelated',true,'OK',8,888);`);
 await db.exec(read(base+'private.kinojo_legion_tree_character_dedupe_v366.sql'));
 await db.exec(read(base+'public.kinojo_prepare_lookup_queue_from_list_v296.sql'));
 await db.exec(read(base+'private.kinojo_legion_tree_character_queue_prepare_v368.sql'));
 const q=async(sql,args=[]) => (await db.query(sql,args)).rows;
 const add=async(name='new-main',mode='MAIN',mainName=name,server=2002,mainServer=server,token='fixture-manager')=>(await q('select private.kinojo_legion_tree_character_queue_prepare_v455($1,$2,$3,$4,$5,$6) result',[token,server,name,mainServer,mainName,mode]))[0].result;
 const wrapper=read('supabase/migrations/20260831064411_legion_tree_listless_character_add_v455.sql');
 const start=wrapper.indexOf('create or replace function private.kinojo_legion_tree_character_queue_prepare_v455');
 await db.exec(wrapper.slice(start,wrapper.indexOf('$function$;',wrapper.indexOf('as $function$',start))+11));
 await assert.rejects(add(),/LEGION_TREE_QUEUE_PREPARE_FAILED:COMPLETE_LIST_READ_REQUIRED/);
 assert.equal((await q('select count(*)::int n from updater_sessions'))[0].n,0);
 assert.equal((await q('select count(*)::int n from lookup_session_targets'))[0].n,0);
 console.log('PASS: production caller reproduces COMPLETE_LIST_READ_REQUIRED and rolls back');
 const unaffected=JSON.stringify(await q('select * from character_master order by id'));
 const fullListBefore=(await q("select pg_get_functiondef('public.kinojo_prepare_lookup_queue_from_list_v296(text,text,jsonb,jsonb)'::regprocedure) d"))[0].d;
 await db.exec(read('supabase/migrations/20260916201305_legion_character_add_single_target.sql'));
 assert.equal((await add('new-main','MAIN','new-main',2002,2002,'invalid')).code,'SESSION_INVALID');
 assert.equal((await add('excluded')).code,'CHARACTER_EXCLUDED');
 const r=await add();assert.equal(r.code,'QUEUE_READY');assert.equal(r.queueCount,1);
 const target=(await q('select * from lookup_session_targets'))[0];assert.equal(target.character_name,'new-main');assert.equal(target.server_id,2002);assert.equal(target.list_row,null);assert.equal(target.target_source,'server:legion_tree_character_add_v455');
 assert.equal(JSON.stringify(await q("select * from character_master where character_name='unrelated' order by id")),unaffected);
 assert.equal((await add()).code,'QUEUE_ALREADY_RUNNING');
 assert.equal((await add('other-new')).code,'QUEUE_BUSY');
 assert.equal((await q('select count(*)::int n from lookup_session_targets'))[0].n,1);
 const fullListAfter=(await q("select pg_get_functiondef('public.kinojo_prepare_lookup_queue_from_list_v296(text,text,jsonb,jsonb)'::regprocedure) d"))[0].d;
 assert.equal(fullListAfter,fullListBefore);
 assert.equal((await q("select kinojo_prepare_lookup_queue_from_list_v296($1,$2,'[]','{}') r",[r.sessionId,r.sessionToken]))[0].r.code,'COMPLETE_LIST_READ_REQUIRED');
 console.log('PASS: one target, unrelated rows untouched, resume/busy, auth/exclusion, full-list guard preserved');
 await db.exec("update updater_lock_state set is_locked=false;insert into character_master(server_id,character_name,is_active,status,is_main,main_character_id) values(2002,'parent',true,'OK',true,100)");
 const alt=await add('cross-alt','ALT','parent',2003,2002);assert.equal(alt.code,'QUEUE_READY');assert.equal(alt.mainServerId,2002);assert.ok(alt.mainCharacterId);
 assert.equal((await q('select main_character_name from lookup_session_targets where session_id=$1',[alt.sessionId]))[0].main_character_name,'parent');
 await db.exec('update updater_lock_state set is_locked=false');
 const same=await add('parent','ALT','parent',2003,2002);assert.equal(same.code,'QUEUE_READY');
 assert.equal((await q('select main_character_name from lookup_session_targets where session_id=$1',[same.sessionId]))[0].main_character_name,'parent');
 console.log('PASS: cross-server ALT and same-name cross-server ALT retain v455 binding');
 await db.exec("update updater_lock_state set is_locked=false;insert into character_master(server_id,character_name,is_active,status,class_name) values(2002,'reuse',true,'OK','fixture-class')");
 const reused=await add('reuse');assert.equal(reused.code,'QUEUE_READY');
 assert.equal((await q("select count(*)::int n from character_master where character_name='reuse'"))[0].n,1);
 assert.equal((await q('select existed_in_master from lookup_session_targets where session_id=$1',[reused.sessionId]))[0].existed_in_master,true);
 const sig='private.kinojo_legion_tree_character_queue_prepare_v368(text,integer,text,text,text)';
 assert.equal((await q("select has_function_privilege('anon',$1,'execute') p",[sig]))[0].p,false);
 assert.equal((await q("select has_function_privilege('authenticated',$1,'execute') p",[sig]))[0].p,false);
 console.log('PASS: reuse does not duplicate Master, private caller ACL preserved');
 await db.exec("update updater_lock_state set is_locked=false;alter table lookup_session_targets add constraint fixture_reject check(character_name<>'reject-target')");
 const counts=await q('select (select count(*) from updater_sessions) sessions,(select count(*) from character_master) masters,(select count(*) from lookup_session_targets) targets');
 await assert.rejects(add('reject-target'),/fixture_reject/);
 assert.deepEqual(await q('select (select count(*) from updater_sessions) sessions,(select count(*) from character_master) masters,(select count(*) from lookup_session_targets) targets'),counts);
 assert.equal((await q("select is_locked from updater_lock_state where id='global'"))[0].is_locked,false);
 await db.exec(read('supabase/rollbacks/20260916201305_legion_character_add_single_target.sql'));
 await assert.rejects(add('rollback-target'),/COMPLETE_LIST_READ_REQUIRED/);
 console.log('PASS: downstream failure rolls back Master/Queue/lock; rollback restores baseline');
 }finally{await db.close();}
}
main().catch(e=>{console.error(e.message);process.exitCode=1;});
