const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path');
const {createBridgeMock}=require('./helpers/list-metadata-mock.cjs');
const source=fs.readFileSync(path.join(__dirname,'../apps-script/list-master/BRIDGE.gs'),'utf8');
const update={id:1,characterId:10,listRow:6,originalListName:'before',characterName:'after',listDisplayName:'after',identityChanged:true,className:'궁성',mainCharacterName:'main',pveCombatPower:300};
let m=createBridgeMock(source,{unavailable:true}),r=m.write([update]);
assert.equal(r.ok,false);assert.equal(m.writes.length,0);assert.equal(m.cells[5][0],'before');
m=createBridgeMock(source,{remove:true});r=m.write([update]);
assert.equal(r.ok,false);assert.equal(m.cells.find(x=>x[0]==='unrelated')[3],999);assert.equal(m.writes.length,0);
m=createBridgeMock(source);r=m.write([{...update,characterId:null}]);assert.equal(r.ok,false);assert.equal(m.writes.length,0);
m=createBridgeMock(source);r=m.write([update]);assert.equal(r.ok,true);
m.metadata.push({...m.metadata[0],id:999,row:m.cells[6]});
const n=m.writes.length;r=m.write([update]);assert.equal(r.ok,false);assert.equal(m.writes.length,n);
m=createBridgeMock(source);r=m.write([update]);assert.equal(r.ok,true);
r=m.write([{...update,id:2,characterId:20,originalListName:'after',characterName:'intruder',listDisplayName:'intruder'}]);
assert.equal(r.ok,false);assert.equal(m.cells[5][0],'after');
m=createBridgeMock(source);
const appended={...update,characterId:30,listRow:null,originalListName:'new',characterName:'new',listDisplayName:'new',appendIfMissing:true};
r=m.write([appended]);assert.equal(r.ok,true);assert.equal(r.results[0].appended,true);
const count=m.cells.length;r=m.write([appended]);assert.equal(r.ok,true);assert.equal(m.cells.length,count);assert.equal(m.cells.filter(x=>x[0]==='new').length,1);
assert.equal(m.cells[5][3],200);assert.equal(m.cells[6][3],999);
m=createBridgeMock(source);r=m.write([{...update,identityChanged:false,characterName:'before',listDisplayName:'before',mainCharacterName:'',pveCombatPower:null}]);
assert.equal(r.ok,true);assert.equal(m.cells[5][3],200);assert.equal(m.cells[5][6],'main');
r=m.write([{...update,identityChanged:false,characterName:'before',listDisplayName:'before',clearPveStats:true}]);
assert.equal(r.ok,true);assert.equal(m.cells[5][2],'');assert.equal(m.cells[5][3],'');
const edge=fs.readFileSync(path.join(__dirname,'../supabase/functions/lookup-list-sync/index.ts'),'utf8');
m=createBridgeMock(source);r=m.write([update,{...update,id:2,characterId:20}]);
assert.equal(r.ok,false);assert.equal(m.metadata.length,1);assert.equal(m.cells[5][0],'after');
const manyRows=Array.from({length:50},(_,i)=>['n'+i,'궁성',100,200,'','','main','']);
m=createBridgeMock(source,{rows:manyRows});
r=m.write(manyRows.map((row,i)=>({id:i+1,characterId:i+1,listRow:i+6,originalListName:row[0],characterName:row[0],className:'궁성',pveCombatPower:300})));
assert.equal(r.ok,true);assert.equal(r.processedCount,50);assert.equal(m.calls.length,5);
assert(!edge.includes('legacyAppendV311'));
assert(edge.includes('characterId:r.character_id'));
console.log('PASS: metadata API failure, row deletion, missing ID, duplicate binding, foreign binding, append retry, null preservation, explicit clear, no unsafe fallback');
