const fs=require('node:fs'),assert=require('node:assert/strict');
const {PGlite}=require('../.codex-test-runtime/node_modules/@electric-sql/pglite');
const migration='supabase/migrations/20260923045528_master_sync_event_compaction.sql';
(async()=>{const db=new PGlite();try{
 await db.exec("set time zone 'UTC';create schema private;create role anon;create role authenticated;create role service_role;grant usage on schema private to anon,authenticated,service_role");
 const columns=JSON.parse(fs.readFileSync('tests/fixtures/master-event-schema.json','utf8'));
 for(const table of new Set(columns.map(x=>x.table_name)))await db.exec('create table '+table+'('+columns.filter(c=>c.table_name===table).map(c=>'"'+c.name+'" '+c.type).join(',')+')');
 await db.exec("create sequence report_ids;alter table updater_run_reports alter id set default nextval('report_ids');alter table updater_run_reports add unique(session_id)");
 const rollback=fs.readFileSync(migration.replace('/migrations/','/rollbacks/'),'utf8');
 await db.exec(rollback.slice(rollback.indexOf('CREATE OR REPLACE FUNCTION public.'),rollback.indexOf('drop function private.')));
 await db.exec(fs.readFileSync(migration,'utf8'));
 await db.exec(`create function kinojo_json_text(j jsonb,variadic keys text[]) returns text language sql immutable as $$select j->>k from unnest(keys) k where j->>k is not null limit 1$$;
 create function kinojo_json_int(j jsonb,variadic keys text[]) returns int language sql immutable as $$select kinojo_json_text(j,variadic keys)::int$$;
 create function kinojo_normalize_character_name(text) returns text language sql immutable as $$select lower(replace($1,' ',''))$$;`);
 const weeklyFunctions=fs.readFileSync('tests/evidence/20260908-character-refresh-audit/weekly-existing-functions.sql','utf8');
 await db.exec(weeklyFunctions.slice(0,weeklyFunctions.indexOf('CREATE OR REPLACE FUNCTION public.kinojo_hof_weekly_deltas')));
 await db.exec(fs.readFileSync('supabase/migrations/20260908131116_character_weekly_identity_query_plan.sql','utf8'));
 await db.exec(fs.readFileSync('tests/fixtures/master-event-report.sql','utf8'));
 const compact='update master_sync_events set before_data=private.kinojo_master_event_state_v499(before_data),after_data=private.kinojo_master_event_state_v499(after_data),raw_payload=private.kinojo_master_event_raw_v499(raw_payload)';
 for(const value of [null,{},[],[1],1,'text',{unused:'large'},{id:1,char_key:'123',latest_pve_combat_power:0,latest_pvp_item_level:null,unused:'large'}]){
  const r=(await db.query('select private.kinojo_master_event_state_v499($1::jsonb) v',[JSON.stringify(value)])).rows[0].v;
  assert.equal(JSON.stringify(value)==='{}',JSON.stringify(r)==='{}');
  if(value&&typeof value==='object'&&!Array.isArray(value)&&Object.hasOwn(value,'unused'))assert.ok(!Object.hasOwn(r,'unused'));
  assert.deepEqual((await db.query('select private.kinojo_master_event_state_v499(private.kinojo_master_event_state_v499($1::jsonb)) v',[JSON.stringify(value)])).rows[0].v,r);
 }
 assert.equal((await db.query('select private.kinojo_master_event_state_v499(null) is null v')).rows[0].v,true);
 for(const role of ['anon','authenticated','service_role'])for(const fn of ['state','raw'])assert.equal((await db.query("select has_function_privilege($1,'private.kinojo_master_event_"+fn+"_v499(jsonb)','execute') v",[role])).rows[0].v,false);
 await db.exec("insert into character_master(id,char_key,server_id,character_name) values(1,'111111111111111111',2003,'renamed'),(2,'222222222222222222',2002,'old');insert into updater_runtime_jobs(session_id,job_id,status,started_at,finished_at,updated_at,created_at,raw_payload,summary) values('report','job','completed','2026-09-08 01:00Z','2026-09-08 02:00Z','2026-09-08 02:00Z','2026-09-08 01:00Z','{}','{}')");
 const event=async(id,master,name,server,gear,power,at,override={})=>{
  const key=master===1?'111111111111111111':'222222222222222222';
  await db.query("insert into extension_character_payloads(id,session_id,server_id,character_name,char_key,gear_type,master_sync_status) values($1,'report',$2,$3,$4,$5,'synced')",[id,server,name,key,gear]);
  const after={id:master,char_key:key,server_id:server,character_name:name,latest_payload_id:id,latest_pve_combat_power:power,latest_pve_item_level:10,latest_pvp_combat_power:35,latest_pvp_item_level:5,profile_image_url:'synthetic',duplicate:'x'.repeat(9000),...override};
  const before=id===1?{}:id===2?null:id===3?{unused:'original nonempty comparison'}:{...after,latest_pve_combat_power:power-10};
  await db.query("insert into master_sync_events(id,session_id,payload_id,character_name,status,event_type,before_data,after_data,raw_payload,created_at) values($1,'report',$1,$2,'synced',$3,$4,$5,$6,$7)",[id,name,id===1?'insert_master':'update_master',before,after,{gearDiagnosis:{detectedGearType:gear||'PVE',unused:'x'.repeat(9000)},officialRaw:{unused:'x'.repeat(9000)}},at]);
  await db.query("insert into lookup_session_targets(id,session_id,lookup_order,server_id,character_name,payload_id,target_status,existed_in_master) values($1::bigint,'report',$1::int,$2,$3,$1::bigint,'lookup_done',$4)",[id,server,name,id!==1]);
 };
 await event(1,1,'old',2002,'PVE',100,'2026-09-02T06:00:00+09:00');
 await event(2,1,'renamed',2003,'PVE',150,'2026-09-08T12:00:00+09:00');
 await event(3,2,'old',2002,'PVE',200,'2026-09-03T12:00:00+09:00');
 await event(4,2,'old',2002,'PVE',900,'2026-09-08T12:00:00+09:00');
 await event(5,1,'old',2002,'PVP',20,'2026-09-03T12:00:00+09:00');
 await event(6,1,'renamed',2003,'PVP',35,'2026-09-08T12:00:00+09:00');
 await event(7,1,'old',2002,'PVE',9999,'2026-09-02T05:59:59+09:00');
 await event(8,1,'renamed',2003,'PVE',9999,'2026-09-09T06:00:00+09:00');
 await event(9,1,'renamed',2003,'PVE',9999,'2026-09-08T13:00:00+09:00',{id:2});
 await event(10,1,'renamed',2003,'PVE',9999,'2026-09-08T13:00:00+09:00',{char_key:111});
 await event(11,1,'renamed',2003,'PVE',9999,'2026-09-08T13:00:00+09:00',{latest_payload_id:99});
 await event(12,1,'renamed',2003,'',160,'2026-09-08T13:00:00+09:00');
 const weekly=async()=>(await db.query("select * from kinojo_hof_weekly_gear_deltas('2026-09-08T14:00:00+09:00') order by server_id,character_name,gear_type")).rows;
 const report=async()=>(await db.query("select kinojo_updater_build_run_report('report') v")).rows[0].v;
 const beforeWeek=await weekly(),beforeReport=await report();assert.equal(beforeWeek.length,3);assert.equal(beforeWeek.find(r=>r.character_name==='renamed'&&r.gear_type==='PVE').sample_count,3);
 assert.equal(beforeReport.ok,true);assert.equal(beforeReport.counts.noComparison,1);assert.equal(beforeReport.counts.new,1);
 const beforeRows=(await db.query('select * from master_sync_events order by id')).rows;
 await db.exec(compact);
 assert.deepEqual(await weekly(),beforeWeek);assert.deepEqual(await report(),beforeReport);
 const once=(await db.query('select * from master_sync_events order by id')).rows;
 await db.exec(compact);assert.deepEqual((await db.query('select * from master_sync_events order by id')).rows,once);
 assert.ok(JSON.stringify(once).length<JSON.stringify(beforeRows).length/10);
 await db.exec('begin');await db.exec("update master_sync_events set after_data='{}' where id=1");await db.exec('rollback');assert.deepEqual(await weekly(),beforeWeek);
 await db.exec(rollback);assert.deepEqual((await db.query('select * from master_sync_events order by id')).rows,once);
 assert.deepEqual(await weekly(),beforeWeek);assert.deepEqual(await report(),beforeReport);
 console.log('PASS actual compact SQL: all value kinds, null/empty comparison semantics, ACL, Wednesday06/identity/gear fallback weekly parity, full report parity, idempotence, transaction rollback and code rollback');
}finally{await db.close();}})().catch(e=>{console.error(e);process.exitCode=1;});
