const fs=require('fs'),assert=require('assert/strict');const {PGlite}=require('../.codex-test-runtime/node_modules/@electric-sql/pglite');
const migration='supabase/migrations/20260924051556_ranking_replica_retention.sql';
(async()=>{const db=new PGlite();try{
 await db.exec("create schema private;create role anon;create role authenticated;create role service_role;set timezone='UTC'");
 await db.exec(fs.readFileSync('tests/fixtures/ranking-replica-schema.sql','utf8'));
 await db.exec(fs.readFileSync(migration,'utf8'));
 for(let id=1;id<=11;id++)await db.query("insert into private.kinojo_ranking_snapshots_v390(snapshot_id,status,created_at,updated_at) values($1,$2,now()-interval '1 day',now())",[id,id===1||id===11?'PUBLISHED':id===8?'BUILDING':id===9?'READY':id===10?'FAILED':'SUPERSEDED']);
 await db.exec("insert into private.kinojo_ranking_snapshot_pointer_v390(singleton,snapshot_id,previous_snapshot_id) values(true,1,2);insert into private.kinojo_ranking_snapshot_pipeline_control_v396(singleton,snapshot_retention_days,snapshot_orphan_after) values(true,90,interval '2 hours')");
 const children=['private.kinojo_ranking_snapshot_items_v390','private.kinojo_ranking_snapshot_owner_metrics_v390','private.kinojo_ranking_snapshot_scopes_v390'];
 for(const t of children)await db.exec('insert into '+t+'(snapshot_id) select snapshot_id from private.kinojo_ranking_snapshots_v390');
 const capture=async()=>({meta:(await db.query('select * from private.kinojo_ranking_snapshots_v390 order by snapshot_id')).rows,pointer:(await db.query('select * from private.kinojo_ranking_snapshot_pointer_v390')).rows});
 const before=await capture();
 const run=async(dry=false,limit=4)=>(await db.query('select private.kinojo_ranking_replica_cleanup_v507($1,$2) r',[dry,limit])).rows[0].r;
 assert.deepEqual((await run(true,100)).snapshotIds,[3,4,5,6]);
 const wrap=(await db.query('select private.kinojo_ranking_snapshot_cleanup_v401(true) r')).rows[0].r;assert.ok(wrap.replicaCleanup.dryRun);
 await db.exec('begin');assert.deepEqual((await run(false,100)).snapshotIds,[3,4,5,6]);await db.exec('rollback');
 assert.equal((await db.query('select count(*) n from '+children[0])).rows[0].n,11);
 const first=await run(false,100);assert.equal(first.itemsDeleted,4);assert.equal(first.ownersDeleted,4);assert.equal(first.scopesDeleted,4);
 assert.deepEqual((await run()).snapshotIds,[7]);assert.deepEqual((await run()).snapshotIds,[]);
 for(const t of children)assert.deepEqual((await db.query('select snapshot_id from '+t+' order by snapshot_id')).rows.map(r=>Number(r.snapshot_id)),[1,2,8,9,10,11]);
 assert.deepEqual(await capture(),before);
 await db.exec('update private.kinojo_ranking_snapshot_pointer_v390 set previous_snapshot_id=null');
 assert.equal((await run()).code,'VALID_CURRENT_AND_PREVIOUS_REQUIRED');
 for(const role of ['anon','authenticated','service_role'])assert.equal((await db.query("select has_function_privilege($1,'private.kinojo_ranking_replica_cleanup_v507(boolean,integer)','execute') v",[role])).rows[0].v,false);
 await db.exec(fs.readFileSync(migration.replace('/migrations/','/rollbacks/'),'utf8'));
 assert.equal((await db.query("select to_regprocedure('private.kinojo_ranking_replica_cleanup_v507(boolean,integer)') r")).rows[0].r,null);
 assert.equal((await db.query('select count(*) n from private.kinojo_ranking_snapshots_v390')).rows[0].n,11);
 console.log('PASS SQL507: bounded superseded replicas only; current/previous/building/ready/failed retained; missing pointer fail closed; dry run and transaction rollback; metadata parity; ACL and code rollback');
 }finally{await db.close();}})().catch(e=>{console.error(e.message);process.exitCode=1;});
