const assert=require('node:assert/strict'),fs=require('node:fs');
const {PGlite}=require(process.env.PGLITE_MODULE||'@electric-sql/pglite');
const read=p=>fs.readFileSync(p,'utf8');
(async()=>{const db=new PGlite();try{
 await db.exec(`create schema private;create role anon;create role authenticated;create role service_role;
 create table public.member_codes(id bigint primary key,main_character_name text,is_active boolean default true);
 insert into public.member_codes values(1,'Fixture account',true);
 create table public.character_master(id bigint primary key,server_id int,server_name text,character_name text,main_character_id bigint,main_character_name text,is_main boolean,is_active boolean default true,status text default 'OK',visibility_excluded boolean default false,legion_name text);
 create table private.sanctuary_character_owners_v412(character_id bigint primary key,owner_member_id bigint,root_character_id bigint,relation text,verification_source text,updated_at timestamptz,check((owner_member_id is null)=(relation='GUEST')));
 create table private.sanctuary_management_slots_v412(character_id bigint,force_id bigint,owner_root_character_id bigint,character_relation text,revision int default 0);
 create function public.kinojo_character_identity_key_v298(text) returns text language sql immutable as $$select lower(replace($1,' ',''))$$;
 create function public.kinojo_web_session_validate_v320(text,boolean) returns jsonb language sql as $$select '{"ok":false}'::jsonb$$;`);
 await db.exec(read('supabase/migrations/20260908090316_legion_roster_family_editor_v477.sql'));
 await db.exec(read('supabase/migrations/20260908094523_roster_family_guest_relation_v478.sql'));
 await db.exec(`insert into public.character_master(id,character_name,main_character_id,main_character_name,is_main,is_active,visibility_excluded) values(11,'Main',11,'Main',true,true,false),(12,'Alt',11,'Main',false,true,false),(13,'Archived',11,'Main',false,false,true),(14,'Other',14,'Other',true,true,false),(15,'Hidden',11,'Main',false,true,true);
 insert into private.sanctuary_character_owners_v412 values(12,null,11,'GUEST','CHARACTER_MASTER',now());
 insert into private.sanctuary_management_slots_v412 values(12,1,11,'ALT',0);`);
 const state=async id=>(await db.query('select private.kinojo_roster_family_state_v477($1) value',[id])).rows[0].value;
 const oldState=await state(11);assert.equal(oldState.items.length,4,'baseline reproduces archived nodes');
 await db.exec(read('supabase/migrations/20260909095156_roster_family_editable_unlink.sql'));
 const expected=async(...ids)=>Promise.all(ids.map(async id=>{const s=await state(id);return {rootId:s.rootId,revision:s.revision};}));
 const save=async(key,main,alts,groups,detached=[])=>(await db.query('select private.kinojo_roster_family_save_v487(1,$1,$2,$3,$4,$5) result',[key,main,alts,JSON.stringify(groups),detached])).rows[0].result;
 assert.deepEqual((await state(11)).items.map(x=>x.characterId),['11','12']);assert.equal(await state(13),null);
 let groups=await expected(11);
 assert.equal((await save('fixture-omission-487',11,[],groups)).code,'FAMILY_INCOMPLETE');
 assert.equal((await save('fixture-injection-487',11,[],groups,[14])).code,'FAMILY_INCOMPLETE');
 assert.equal((await save('fixture-duplicate-487',11,[12],groups,[12])).code,'FAMILY_DUPLICATE');
 assert.equal((await save('fixture-archived-487',11,[12],groups,[13])).code,'FAMILY_UNAVAILABLE');
 assert.equal((await save('fixture-oldtab-487',11,[12],[{rootId:oldState.rootId,revision:oldState.revision}])).code,'FAMILY_CONFLICT');
 let result=await save('fixture-detach-487',11,[],groups,[12]);assert.equal(result.ok,true);assert.deepEqual(result.detachedCharacterIds,[12]);
 assert.equal((await state(11)).items.length,1);assert.equal((await state(12)).rootId,'12');
 let owner=(await db.query('select * from private.sanctuary_character_owners_v412 where character_id=12')).rows[0];assert.equal(owner.relation,'GUEST');assert.equal(owner.root_character_id,12);
 assert.equal((await db.query('select owner_root_character_id from private.sanctuary_management_slots_v412')).rows[0].owner_root_character_id,12);
 assert.equal((await save('fixture-detach-487',11,[],groups,[12])).replayed,true);
 assert.equal((await save('fixture-detach-487',11,[12],groups)).code,'REQUEST_REUSED');
 assert.equal((await save('fixture-stale-487',11,[],groups,[12])).code,'FAMILY_CONFLICT');
 await db.exec("update public.character_master set main_character_id=11,is_main=false,main_character_name='Main' where id=12");assert.equal((await state(12)).rootId,'12','worker cannot reconnect detached character');
 const archived=(await db.query('select is_active,visibility_excluded,main_character_id from public.character_master where id=13')).rows[0];assert.deepEqual(archived,{is_active:false,visibility_excluded:true,main_character_id:11});
 groups=await expected(11,12,14);assert.equal((await save('fixture-multi-487',14,[],groups,[11,12])).ok,true,'multiple detach with main replacement');
 groups=await expected(14);await db.exec("update public.character_master set is_active=true,visibility_excluded=false,main_character_id=14 where id=13");assert.equal((await save('fixture-restored-487',14,[],groups)).code,'FAMILY_CONFLICT','restoration changes revision');
 await db.exec(read('tests/roster-family-v477.sql'));
 const acl=(await db.query("select has_function_privilege('anon','public.kinojo_roster_family_save_v487(text,text,bigint,bigint[],jsonb,bigint[])','execute') allowed")).rows[0];assert.equal(acl.allowed,false);
 await db.exec(read('supabase/rollbacks/20260909095156_roster_family_editable_unlink_rollback.sql'));
 assert.equal((await state(11)).items.some(x=>x.characterId==='15'),true,'rollback restores old reader without deleting data');
 console.log('roster family DB: archive exclusion, atomic detach, guards, replay, override, GUEST, legacy and rollback PASS');
 }finally{await db.close();}})().catch(e=>{console.error(e);process.exitCode=1;});
