const fs=require('node:fs'),assert=require('node:assert/strict');
const {PGlite}=require(process.env.PGLITE_MODULE||'../.codex-test-runtime/node_modules/@electric-sql/pglite');
const read=p=>fs.readFileSync(p,'utf8');
(async()=>{
 const db=new PGlite();
 try{
  await db.exec(read('tests/fixtures/sanctuary-registration-visibility.sql'));
  const candidate=async(name,legion='external',server=2002)=> (await db.query(`insert into private.sanctuary_management_official_candidates_v432
   (actor_member_id,team_id,requested_character_name,character_name,server_id,server_name,race_id,class_name,char_key,official_character_id,detail_url,official_payload,legion_name)
   values(1,1,$1,$1,$3,'synthetic-server',2,'synthetic-class','synthetic-key','synthetic-official-id','https://example.invalid/character','{"pveCombatPower":1200,"pveItemLevel":500}',$2) returning candidate_id`,[name,legion,server])).rows[0].candidate_id;
  const register=async(id,key,relation='GUEST',main=null,list=false,mainCandidate=null,credential='synthetic-authorized')=> (await db.query(`select public.kinojo_sanctuary_management_official_materialize_v480($1,1,$2,$3,$4,$5,$6,$7) result`,[credential,id,relation,main,mainCandidate,list,key])).rows[0].result;
  const count=async(table)=>Number((await db.query('select count(*) n from '+table)).rows[0].n);
  const first=await candidate('new-guest');
  await assert.rejects(register(first,'before-empty'),/null value in column "character_id"/);
  assert.equal(await count('character_master'),0);
  await db.exec("insert into character_master(character_name) values('unrelated-existing')");
  await assert.rejects(register(first,'before-populated'),/null value in column "character_id"/);
  assert.equal(await count('character_master'),1);
  assert.equal(await count('private.sanctuary_character_registration_events_v480'),0);
  assert.equal((await db.query('select state from private.sanctuary_management_official_candidates_v432 where candidate_id=$1',[first])).rows[0].state,'VERIFIED');
  await db.exec(read('supabase/migrations/20261007005939_sanctuary_guest_registration_visibility.sql'));
  const result=await register(first,'after-guest');
  assert.equal(result.membershipRelation,'GUEST');
  assert.equal(result.character.characterName,'new-guest');
  assert.equal(result.character.power,1200);
  assert.equal(result.listSync.status,'NOT_REQUESTED');
  assert.equal(await count('character_master'),2);
  assert.equal(await count('private.sanctuary_character_registration_events_v480'),1);
  const guestId=result.character.characterId;
  const owner=(await db.query('select * from private.sanctuary_character_owners_v412 where character_id=$1',[guestId])).rows[0];
  assert.equal(owner.owner_member_id,null);
  assert.equal(Number(owner.root_character_id),guestId);
  assert.equal(owner.relation,'GUEST');
  assert.equal((await register(first,'after-guest')).idempotent,true);
  assert.equal(await count('character_master'),2);
  const existing=await candidate('new-guest');
  const refresh=await register(existing,'existing-guest','GUEST',null,true);
  assert.equal(refresh.character.characterId,guestId);
  assert.equal(refresh.listSync.queueCount,1);
  assert.equal(await count('google_list_sheet_sync_queue'),1);
  const mainCandidate=await candidate('new-main','synthetic-legion');
  await db.exec("insert into member_codes values(44,'new-main',true)");
  const main=await register(mainCandidate,'new-main-key','MAIN');
  assert.equal(main.membershipRelation,'MAIN');
  const altCandidate=await candidate('new-alt');
  const alt=await register(altCandidate,'new-alt-key','ALT',main.character.characterId,true);
  assert.equal(alt.familyRelation,'ALT');
  assert.equal(alt.membershipRelation,'ALT');
  assert.equal(alt.listSync.queueCount,2);
  const externalMain=await candidate('external-main'),externalAlt=await candidate('external-alt');
  const family=await register(externalAlt,'external-family','ALT',null,false,externalMain);
  assert.equal(family.familyRelation,'ALT');
  assert.equal(family.membershipRelation,'GUEST');
  const otherServer=await candidate('new-guest','external',2003);
  assert.notEqual((await register(otherServer,'other-server')).character.characterId,guestId);
  const rollbackCandidate=await candidate('must-rollback');
  const beforeMaster=await count('character_master'),beforeEvents=await count('private.sanctuary_character_registration_events_v480'),beforeQueue=await count('google_list_sheet_sync_queue');
  await db.exec("set test.fail_audit='yes'");
  await assert.rejects(register(rollbackCandidate,'rollback-guest','GUEST',null,true),/FIXTURE_LATE_FAILURE/);
  await db.exec("set test.fail_audit='no'");
  assert.equal(await count('character_master'),beforeMaster);
  assert.equal(await count('private.sanctuary_character_registration_events_v480'),beforeEvents);
  assert.equal(await count('google_list_sheet_sync_queue'),beforeQueue);
  await assert.rejects(register(rollbackCandidate,'denied-key','GUEST',null,false,null,'denied'),/FIXTURE_DENIED/);
  await db.query("update private.sanctuary_management_official_candidates_v432 set expires_at=now()-interval '1 minute' where candidate_id=$1",[rollbackCandidate]);
  await assert.rejects(register(rollbackCandidate,'expired-key'),/만료/);
  assert.equal(await count('character_master'),beforeMaster);
  await db.exec(read('supabase/rollbacks/20261007005939_sanctuary_guest_registration_visibility.sql'));
  assert.equal(await count('character_master'),beforeMaster);
  assert.equal(await count('private.sanctuary_character_registration_events_v480'),beforeEvents);
  console.log('PASS SQL525: reproduced production 23502 before fix on empty/populated master; new/existing guest, MAIN/ALT and external family, server identity, List Y/N queue, idempotency, denied/expired input, late failure atomicity, data-preserving code rollback.');
 }finally{await db.close();}
})().catch(e=>{console.error(e);process.exitCode=1;});
