const fs = require('node:fs');
const assert = require('node:assert/strict');
const { PGlite } = require(process.env.PGLITE_MODULE || '../.codex-test-runtime/node_modules/@electric-sql/pglite');

(async () => {
  const db = new PGlite();
  try {
    await db.exec(`
      create schema private; create schema cron;
      create role anon; create role authenticated; create role service_role;
      create function cron.schedule(text,text,text) returns integer language sql as 'select 1';
      create function cron.unschedule(text) returns boolean language sql as 'select true';
      create function private.kinojo_json_find_text_v321(p_doc jsonb,p_keys text[],p_depth integer default 0)
        returns text language sql immutable as $$
          select coalesce(
            (select p_doc->>k from unnest(p_keys) k where p_doc ? k limit 1),
            (select p_doc#>>array['officialRaw','info','profile',k]
               from unnest(p_keys) k where p_doc#>array['officialRaw','info','profile'] ? k limit 1))$$;
      create table public.lookup_snapshots(id bigint primary key,session_id text,server_id integer,
        character_name text,status text,created_at timestamptz,snapshot_uid text,raw_payload jsonb,
        retained_parser_stats_v504 jsonb);
      create table public.updater_sessions(session_id text primary key,status text,finished_at timestamptz);
      create table public.updater_runtime_jobs(session_id text,status text);
      create table public.lookup_batches(session_id text,status text);
      create table public.character_master(latest_snapshot_uid text,legion_source_snapshot_id bigint,
        latest_payload_id bigint,latest_pve_payload_id bigint,latest_pvp_payload_id bigint);
      create table public.character_skill_current_state(snapshot_id bigint);
      create table public.character_stat_sources(snapshot_id bigint,payload_id bigint);
      create table private.character_snapshot_requests(snapshot_id bigint);
      create table public.lookup_session_targets(snapshot_id bigint);
      create table public.extension_character_payloads(id bigint generated by default as identity primary key,
        source_snapshot_id bigint,session_id text,master_sync_status text,server_id integer,
        character_name text,received_at timestamptz,gear_type text,
        pve_item_level int,pve_combat_power int,pvp_item_level int,pvp_combat_power int);
      create table public.ranking_entries(latest_payload_id bigint);
      create table public.google_list_sheet_sync_queue(session_id text,sync_status text);
      create function public.kinojo_payload_gear_diagnosis(bigint) returns jsonb
        language sql stable as $$select jsonb_build_object('ok',true,'payloadId',$1)$$;
      create function private.kinojo_payload_evidence_v509(jsonb) returns jsonb
        language sql immutable as 'select $1';
      create function public.kinojo_normalize_character_name(text) returns text
        language sql immutable as 'select lower($1)';
      insert into public.updater_sessions values
        ('a-old','completed',now()-interval '8 days'),('a-new','completed',now()),
        ('b-old','completed',now()-interval '8 days'),
        ('c-old','completed',now()-interval '8 days'),('c-new','completed',now()),
        ('d-old','completed',now()-interval '8 days'),('d-new','completed',now()),
        ('e-old','completed',now()-interval '8 days'),('e-new','completed',now());
      insert into public.lookup_snapshots values
        (1,'a-old',2002,'A','OK',now()-interval '8 days','a-old',
          '{"officialRaw":{"info":{"profile":{"characterName":"A","serverId":2002}}},"combatPower":123,"itemLevel":99,"extra":{"large":"discard"}}',null),
        (2,'a-new',2002,'A','OK',now(),'a-new','{"officialRaw":{"info":{}}}',null),
        (3,'b-old',2002,'B','OK',now()-interval '8 days','b-old','{"extra":1}',null),
        (4,'c-old',2002,'C','OK',now()-interval '8 days','c-old','{"extra":1}',null),
        (5,'c-new',2002,'C','OK',now(),'c-new','{}',null),
        (6,'d-old',2002,'D','OK',now()-interval '8 days','d-old','{"extra":1}',null),
        (7,'d-new',2002,'D','OK',now(),'d-new','{}',null),
        (8,'e-old',2002,'E','OK',now()-interval '8 days','e-old','{"extra":1}',null),
        (9,'e-new',2002,'E','OK',now(),'e-new','{}',null);
      insert into public.lookup_session_targets values(1);
      insert into public.character_master(latest_snapshot_uid) values('c-old');
      insert into public.character_skill_current_state values(8);
      insert into public.extension_character_payloads(source_snapshot_id,session_id,master_sync_status,server_id,character_name)
        values(1,'a-old','synced',2002,'A'),(6,'d-old','pending',2002,'D');
    `);
    await db.exec(fs.readFileSync('supabase/migrations/20260924093500_superseded_snapshot_retention.sql','utf8'));
    await db.exec(fs.readFileSync('supabase/migrations/20260924100500_superseded_snapshot_backup_waiver.sql','utf8'));
    await db.exec(`create or replace function public.kinojo_payload_gear_diagnosis(p_payload_id bigint)
      returns jsonb language sql stable as $$select jsonb_build_object('ok',true,
      'payloadId',p_payload_id,'gearEvidence',jsonb_build_object('gearReasonCode','PROVEN'))$$`);
    await db.exec(fs.readFileSync('supabase/migrations/20260924104300_snapshot_seven_day_raw_summary.sql','utf8'));
    const run = dry => db.query('select private.kinojo_snapshot_raw_cleanup_v514($1,50) result',[dry]);
    assert.equal((await run(true)).rows[0].result.candidates,1);
    assert.equal((await run(false)).rows[0].result.code,'RETENTION_NOT_ENABLED');
    await db.exec('update private.kinojo_snapshot_retention_control_v512 set enabled=true');
    const result=(await run(false)).rows[0].result;
    assert.equal(result.compacted,1);assert.equal(result.cachedPayloads,1);
    const source=(await db.query('select raw_payload from public.lookup_snapshots where id=1')).rows[0].raw_payload;
    assert.equal(source.retainedSummaryVersion,514);
    assert.equal(source.characterName,'A');assert.equal(source.combatPower,'123');
    assert.equal(source.itemLevel,'99');assert.equal(source.officialRaw,undefined);
    assert.equal((await db.query('select count(*)::int n from public.lookup_session_targets where snapshot_id=1')).rows[0].n,1);
    const payload=(await db.query('select retained_diagnosis_v512 from public.extension_character_payloads where id=1')).rows[0].retained_diagnosis_v512;
    assert.equal(payload.gearEvidence.gearReasonCode,'PROVEN');
    for(const id of [2,3,4,6,8]) assert.equal((await db.query('select raw_payload->>\'retainedSummaryVersion\' v from public.lookup_snapshots where id=$1',[id])).rows[0].v,null);
    assert.equal((await run(true)).rows[0].result.candidates,0);
    await db.exec(fs.readFileSync('supabase/rollbacks/20260924104300_snapshot_seven_day_raw_summary.sql','utf8'));
    console.log('seven-day snapshot raw summary: PASS');
  } finally { await db.close(); }
})().catch(error => { console.error(error); process.exitCode=1; });
