const fs=require('node:fs');
const assert=require('node:assert/strict');
const {PGlite}=require(process.env.PGLITE_MODULE || '../.codex-test-runtime/node_modules/@electric-sql/pglite');

(async()=>{
 const db=new PGlite();
 try{
  await db.exec(`
   create schema private; create schema cron;
   create role anon; create role authenticated; create role service_role;
   create function cron.schedule(text,text,text) returns integer language sql as 'select 1';
   create function cron.unschedule(text) returns boolean language sql as 'select true';
   create table public.lookup_snapshots(id bigint primary key,session_id text,server_id integer,
     character_name text,status text,created_at timestamptz,snapshot_uid text,raw_payload jsonb);
   create table public.updater_sessions(session_id text primary key,status text,finished_at timestamptz);
   create table public.updater_runtime_jobs(session_id text,status text);
   create table public.lookup_batches(session_id text,status text);
   create table public.character_master(id bigint generated by default as identity primary key,
     latest_snapshot_uid text,legion_source_snapshot_id bigint,server_id integer,
     character_name text,char_key text,is_active boolean default true,updated_at timestamptz default now(),
     latest_payload_id bigint,latest_pve_payload_id bigint,latest_pvp_payload_id bigint);
   create function public.kinojo_character_identity_key_v298(text) returns text
     language sql immutable as 'select lower($1)';
   create table public.character_skill_current_state(snapshot_id bigint);
   create table public.character_stat_sources(snapshot_id bigint,payload_id bigint);
   create table private.character_snapshot_requests(snapshot_id bigint);
   create table public.lookup_session_targets(snapshot_id bigint);
   create table public.extension_character_payloads(id bigint generated by default as identity primary key,
     source_snapshot_id bigint,session_id text,master_sync_status text,server_id integer,
     character_name text,received_at timestamptz,gear_type text,
     pve_item_level int,pve_combat_power int,pvp_item_level int,pvp_combat_power int);
   create table public.ranking_entries(latest_payload_id bigint);
   create table public.google_list_sheet_sync_queue(session_id text,sync_status text);
   create function public.kinojo_payload_gear_diagnosis(bigint) returns jsonb
     language sql stable as $$select jsonb_build_object('ok',true,'payloadId',$1)$$;
   create function private.kinojo_payload_evidence_v509(jsonb) returns jsonb
     language sql immutable as 'select $1';
   create function public.kinojo_normalize_character_name(text) returns text
     language sql immutable as 'select lower($1)';
   insert into public.updater_sessions values('old','completed',now()-interval '1 day'),
     ('new','completed',now()),('running','running',null);
   insert into public.lookup_snapshots values
     (1,'old',2002,'A','OK',now()-interval '1 day','a1','{"officialRaw":{"info":{"profile":{"profileImage":"/p?charKey=123"},"title":{"titleList":[{"name":"old"}]}}}}'),
     (2,'new',2002,'A','OK',now(),'a2','{"officialRaw":{"info":{"profile":{"profileImage":"/p?charKey=123"}}}}'),
     (3,'old',2002,'B','OK',now()-interval '1 day','b1','{}'),
     (4,'new',2002,'B','OK',now(),'b2','{"officialRaw":{"info":{"profile":{"profileImage":"/p?charKey=123"},"title":{"titleList":[{"name":"new"}]}}}}'),
     (5,'old',2002,'C','OK',now()-interval '1 day','c1','{}'),
     (6,'new',2002,'C','OK',now(),'c2','{"officialRaw":{"info":{"profile":{"profileImage":"/p?charKey=999"}}}}'),
     (7,'old',2002,'D','OK',now()-interval '1 day','d1','{"officialRaw":{"info":{"profile":{"profileImage":"/p?charKey=123"},"title":{"titleList":[{"name":"old"}]}}}}'),
     (8,'new',2002,'D','STAT_PARSE_FAILED',now(),'d2','{}'),
     (9,'old',2002,'E','OK',now()-interval '1 day','e1','{}'),
     (10,'new',2002,'E','OK',now(),'e2','{}'),
     (11,'old',2002,'G','OK',now()-interval '1 day','g1','{}'),
     (12,'new',2002,'G','OK',now(),'g2','{}');
   insert into public.extension_character_payloads(source_snapshot_id,session_id,master_sync_status)
     values(3,'old','synced'),(11,'old','synced');
   insert into public.character_master(latest_snapshot_uid,legion_source_snapshot_id,server_id,character_name,char_key,latest_payload_id)
     values(null,null,2002,'A','123',null),(null,null,2002,'B','123',1),
       (null,null,2002,'C','123',null),(null,null,2002,'D','123',null);
   insert into public.lookup_session_targets values(9);
  `);
  await db.exec(fs.readFileSync('supabase/migrations/20260924093500_superseded_snapshot_retention.sql','utf8'));
  // The production diagnosis has a broad parser dependency; this fixture exercises
  // the cleanup's cache-and-unlink transaction with a deterministic diagnosis.
  await db.exec(`create or replace function public.kinojo_payload_gear_diagnosis(p_payload_id bigint)
    returns jsonb language sql stable as $$select jsonb_build_object('ok',true,'payloadId',p_payload_id,
      'gearEvidence',jsonb_build_object('gearReasonCode','PROVEN'))$$`);
  const call=dry=>db.query('select private.kinojo_superseded_snapshot_cleanup_v512($1,50) result',[dry]);
  const dry=(await call(true)).rows[0].result;
  assert.equal(dry.candidates,3); assert.equal(dry.deleted,0);
  assert.equal((await call(false)).rows[0].result.code,'BACKUP_NOT_VERIFIED');
  await db.exec(fs.readFileSync('supabase/migrations/20260924100500_superseded_snapshot_backup_waiver.sql','utf8'));
  assert.equal((await call(false)).rows[0].result.code,'RETENTION_NOT_ENABLED');
  await db.exec("update private.kinojo_snapshot_retention_control_v512 set enabled=true");
  const applied=(await call(false)).rows[0].result;
  assert.equal(applied.deleted,3);assert.equal(applied.cachedPayloads,1);
  const cached=(await db.query('select source_snapshot_id,retained_diagnosis_v512 from public.extension_character_payloads where id=2')).rows[0];
  assert.equal(cached.source_snapshot_id,null);
  assert.equal(cached.retained_diagnosis_v512.payloadId,2);
  assert.deepEqual((await db.query('select id from public.lookup_snapshots order by id')).rows.map(x=>Number(x.id)),
   [2,3,4,6,7,8,9,10,12]);
  for(const role of ['anon','authenticated','service_role'])
   assert.equal((await db.query("select has_function_privilege($1,'private.kinojo_superseded_snapshot_cleanup_v512(boolean,integer)','execute') v",[role])).rows[0].v,false);
  await db.exec(fs.readFileSync('supabase/rollbacks/20260924100500_superseded_snapshot_backup_waiver.sql','utf8'));
  assert.equal((await call(false)).rows[0].result.code,'RETENTION_NOT_ENABLED');
  await db.exec(fs.readFileSync('supabase/rollbacks/20260924093500_superseded_snapshot_retention.sql','utf8'));
  console.log('superseded snapshot retention: PASS');
 }finally{await db.close();}
})().catch(e=>{console.error(e);process.exitCode=1;});
