/* KINOJO Admin image management v2026082404 */
(function(A){'use strict';if(!A)throw Error('KINOJO Admin shared module is required.');
const EDGE='kinojo-banner-media',BUCKET='kinojo-site-banners',FORMAT='MAIN_16_9',MAX=5242880,MIMES=['image/jpeg','image/png','image/webp'];
const S={assets:[],campaigns:[],manifest:{},url:'',cid:0,selected:new Map(),loaded:false,busy:false};
const $=(q,r=document)=>r.querySelector(q),$$=(q,r=document)=>Array.from(r.querySelectorAll(q)),master=()=>A.isMaster?.()===true;
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function session(){const t=String(window.KinojoAuth?.getSession?.()?.token||'').trim();return /^kws_[A-Za-z0-9_-]{40,80}$/.test(t)?t:''}
function id(){return crypto.randomUUID()}
function imageRoute(){return String(location.hash||'').replace(/^#/,'').split('/')[0]==='images'}
function guard(){if(master()||!imageRoute())return false;history.replaceState(null,'',location.pathname+location.search+'#dashboard');A.switchTab?.('dashboard',{updateRoute:true});return true}
function label(){const e=$('#adminCurrentLocation'),p=$('[data-admin-pane="images"]'),text='[이미지 관리]';if(e&&p?.classList.contains('active')&&e.textContent!==text)e.textContent=text}
function msg(q,text,type=''){const e=$(q);if(e){e.textContent=text||'';e.className='admin-statusline '+type}}
const sectionHead=(title,description)=>`<div class="banner-section-head"><div><h3>${title}</h3><p>${description}</p></div></div>`;
function shell(){
  const nav=$('.admin-nav');
  if(nav&&!$('[data-admin-tab="images"]',nav)){const b=document.createElement('button');b.type='button';b.dataset.adminTab='images';b.setAttribute('data-admin-master-only','');b.textContent='🖼 이미지 관리';nav.insertBefore(b,$('[data-admin-tab="meter"]',nav)||$('[data-admin-tab="system"]',nav))}
  const main=$('.admin-main');
  if(main&&!$('[data-admin-pane="images"]',main)){const p=document.createElement('section');p.className='admin-pane';p.dataset.adminPane='images';p.setAttribute('data-admin-master-only','');main.insertBefore(p,$('[data-admin-pane="meter"]',main)||$('[data-admin-pane="system"]',main))}
  const p=$('[data-admin-pane="images"]');
  if(!p||$('[data-main-banner-admin]',p))return;
  p.innerHTML=`<div data-main-banner-admin>
    <section class="admin-card banner-admin-hero">
      <div class="admin-card-head"><div><h2>메인 배너 관리</h2><p>PC와 모바일 홈에 공통으로 노출되는 16:9 메인 배너를 관리합니다.</p></div><button class="admin-btn" data-b-refresh type="button">새로고침</button></div>
      <div class="banner-spec-list"><span>권장 1536×864 또는 1920×1080</span><span>JPEG · PNG · WebP</span><span>최대 5MB</span><span>일정 기준 Asia/Seoul</span></div>
      <div id="bStatus" class="admin-statusline"></div>
    </section>
    <div class="banner-admin-grid">
      <section class="admin-card banner-card">${sectionHead('현재 게시 중','홈 화면에 실제로 노출 중인 메인 배너를 확인합니다.')}<div id="bLive"></div></section>
      <section class="admin-card banner-card">${sectionHead('PC·모바일 미리보기','선택한 첫 번째 이미지가 각 화면에서 보이는 비율을 확인합니다.')}<div class="b-preview"><div><small>PC · 16:9</small><div id="bannerMainPreviewPc" class="b-frame">이미지를 선택하세요.</div></div><div><small>모바일 · 16:9</small><div id="bannerMainPreviewMobile" class="b-frame">이미지를 선택하세요.</div></div></div></section>
      <section class="admin-card banner-card">${sectionHead('이미지 업로드','새 16:9 이미지를 메인 배너 라이브러리에 등록합니다.')}<div class="banner-fields"><label class="banner-field banner-field-wide"><span>파일</span><input class="admin-input" id="bFile" type="file" accept="image/jpeg,image/png,image/webp"></label><label class="banner-field"><span>관리 이름</span><input class="admin-input" id="bUploadName" maxlength="120" placeholder="관리자에게 표시할 이름"></label><label class="banner-field"><span>기본 대체 텍스트</span><input class="admin-input" id="bUploadAlt" maxlength="300" placeholder="이미지를 설명하는 한 문장"></label></div><div class="banner-upload-actions"><button class="admin-btn primary" id="bUpload" type="button">이미지 업로드</button></div><div id="bUploadStatus" class="admin-statusline"></div></section>
      <section class="admin-card banner-card banner-settings-card"><div class="banner-section-head banner-section-head-action"><div><h3>캠페인 설정</h3><p>선택한 이미지를 언제, 어떤 속도로 노출할지 설정합니다.</p></div><button class="admin-btn" data-b-new type="button">새 캠페인</button></div><div class="banner-fields"><label class="banner-field"><span>캠페인 이름</span><input class="admin-input" id="bName" maxlength="120" placeholder="예: 여름 메인 배너"></label><label class="banner-field"><span>우선순위</span><input class="admin-input" id="bPriority" type="number" min="0" max="10000" value="100"></label><label class="banner-field banner-field-wide"><span>노출 방식</span><select class="admin-select" id="bMode"><option value="ALWAYS">항상 노출</option><option value="SCHEDULED">기간·요일 지정</option></select></label><label class="banner-field"><span>슬라이드 간격</span><input class="admin-input" id="bSlide" type="number" min="3000" max="60000" value="8000"><small>다음 이미지까지의 시간 · ms</small></label><label class="banner-field"><span>전환 속도</span><input class="admin-input" id="bTransition" type="number" min="0" max="5000" value="600"><small>이미지가 바뀌는 시간 · ms</small></label></div><div id="bSchedule" class="banner-schedule-panel" hidden><strong>기간·요일 설정</strong><p>지정한 기간과 요일에만 캠페인을 노출합니다.</p><div class="banner-fields"><label class="banner-field"><span>시작 KST</span><input class="admin-input" id="bStart" type="datetime-local"></label><label class="banner-field"><span>종료 KST</span><input class="admin-input" id="bEnd" type="datetime-local"></label></div><div id="bDays" class="b-days">${[['1','월'],['2','화'],['3','수'],['4','목'],['5','금'],['6','토'],['7','일']].map(x=>`<label><input type="checkbox" value="${x[0]}">${x[1]}</label>`).join('')}</div><input class="admin-input" id="bDates" placeholder="특정 날짜: 2026-09-01, 2026-09-15"></div><div class="banner-actions"><div class="banner-actions-primary"><button class="admin-btn primary" data-b-save type="button">저장</button><button class="admin-btn primary" data-b-publish type="button">게시</button></div><div class="banner-actions-secondary"><button class="admin-btn" data-b-pause type="button">일시정지</button><button class="admin-btn" data-b-archive type="button">보관</button><button class="admin-btn" data-b-restore type="button">복원</button></div></div><div id="bCampaignStatus" class="admin-statusline"></div></section>
      <section class="admin-card banner-card">${sectionHead('이미지 라이브러리','등록된 이미지 중 이번 캠페인에 사용할 항목을 선택합니다.')}<div id="bLibrary" class="b-list"></div></section>
      <section class="admin-card banner-card">${sectionHead('선택 이미지','선택한 이미지의 대체 텍스트와 연결 주소를 확인합니다.')}<div id="bSelected"></div></section>
      <section class="admin-card banner-card banner-span-all">${sectionHead('메인 캠페인 목록','저장된 캠페인의 상태를 확인하고 편집할 항목을 선택합니다.')}<div id="bCampaigns"></div></section>
    </div>
  </div>`;
  ensureBannerAdminLayoutStyle();style();
}
function ensureBannerAdminLayoutStyle(){if($('#bannerAdminLayoutStyle'))return;const s=document.createElement('style');s.id='bannerAdminLayoutStyle';s.textContent=`
  [data-main-banner-admin],[data-side-banner-admin]{color:#14213a}
  .banner-admin-hero{padding:21px 22px}.banner-admin-hero .admin-card-head{align-items:flex-start}.banner-admin-hero h2{margin:0 0 6px;font-size:21px;letter-spacing:-.025em}.banner-admin-hero p{margin:0;color:#64748b;font-size:12px;line-height:1.55}
  .banner-spec-list{display:flex;flex-wrap:wrap;gap:7px;margin-top:15px}.banner-spec-list span{display:inline-flex;align-items:center;min-height:27px;padding:0 9px;border:1px solid #dbeafe;border-radius:999px;background:#f8fbff;color:#45617f;font-size:9px;font-weight:800}
  .banner-admin-grid{display:grid;grid-template-columns:minmax(0,1fr) minmax(0,1fr);gap:16px;margin-top:16px;align-items:stretch}.banner-card{min-width:0;padding:19px}.banner-span-all{grid-column:1/-1}
  .banner-section-head{display:flex;align-items:flex-start;justify-content:space-between;gap:12px;margin-bottom:14px}.banner-section-head h3{margin:0;color:#17233b;font-size:15px;letter-spacing:-.02em}.banner-section-head p{margin:5px 0 0;color:#718096;font-size:10px;line-height:1.5}.banner-section-head-action{min-height:43px}.banner-section-head-action .admin-btn{flex:0 0 auto}
  .banner-fields{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:14px 16px}.banner-field{display:grid;grid-template-rows:auto 42px auto;align-content:start;gap:6px;min-width:0}.banner-field>span{color:#24324a;font-size:10px;font-weight:850}.banner-field>small{min-height:14px;color:#8a98ab;font-size:9px;line-height:1.45}.banner-field-wide{grid-column:1/-1}.banner-field>.admin-input,.banner-field>.admin-select{width:100%;height:42px;box-sizing:border-box}
  .banner-upload-actions{display:flex;justify-content:flex-end;margin-top:14px}.banner-upload-actions .admin-btn{min-width:118px}.banner-schedule-panel{margin-top:16px;padding:14px;border:1px solid #dbeafe;border-radius:13px;background:#f8fbff}.banner-schedule-panel>strong{display:block;font-size:11px}.banner-schedule-panel>p{margin:4px 0 12px;color:#718096;font-size:9px}
  .banner-actions{display:flex;align-items:center;justify-content:space-between;gap:10px;margin-top:17px;padding-top:15px;border-top:1px solid #e8edf4}.banner-actions-primary,.banner-actions-secondary{display:flex;align-items:center;gap:7px}.banner-actions .admin-btn{min-width:72px}
  .banner-card>.admin-statusline:last-child{margin-top:10px}.banner-inline-note{margin:10px 0 0;color:#718096;font-size:9px;line-height:1.55}
  @media(max-width:980px){.banner-admin-grid{grid-template-columns:1fr}.banner-span-all{grid-column:auto}}
  @media(max-width:620px){.banner-admin-hero{padding:17px}.banner-card{padding:15px}.banner-fields{grid-template-columns:1fr;gap:12px}.banner-field-wide{grid-column:auto}.banner-actions{align-items:stretch;flex-direction:column}.banner-actions-primary,.banner-actions-secondary{display:grid;grid-template-columns:repeat(2,minmax(0,1fr))}.banner-actions-secondary{grid-template-columns:repeat(3,minmax(0,1fr))}.banner-actions .admin-btn,.banner-upload-actions .admin-btn{width:100%}}
`;document.head.appendChild(s)}
function style(){if($('#bAdminStyle'))return;const s=document.createElement('style');s.id='bAdminStyle';s.textContent=`
  .b-list{display:grid;grid-template-columns:1fr 1fr;gap:9px;max-height:380px;overflow:auto}.b-asset,.b-campaign,.b-item{display:grid;gap:8px;padding:9px;border:1px solid #e2e8f0;border-radius:11px;background:#fff}.b-asset{grid-template-columns:82px 1fr}.b-asset.on,.b-campaign.on{border-color:#60a5fa;background:#eff6ff}.b-asset img,.b-item img,.b-live img{width:100%;aspect-ratio:16/9;object-fit:cover;border-radius:7px}.b-item{grid-template-columns:78px 1fr;margin-bottom:8px}.b-item>div{display:grid;grid-template-columns:1fr 1fr;gap:7px}.b-preview{display:grid;grid-template-columns:1fr 1fr;gap:12px}.b-preview>div>small{display:block;margin-bottom:7px;color:#64748b;font-size:9px;font-weight:800}.b-frame{position:relative;display:grid;place-items:center;aspect-ratio:16/9;overflow:hidden;border:1px dashed #94a3b8;border-radius:11px;background:#f8fafc;color:#94a3b8;font-size:10px}.b-frame img{position:absolute;inset:0;width:100%;height:100%;object-fit:cover}.b-days{display:flex;flex-wrap:wrap;gap:7px;margin:11px 0}.b-days label{font-size:10px}.b-campaign{grid-template-columns:1fr auto;align-items:center;margin-bottom:7px}.b-live{display:grid;grid-template-columns:1fr 1fr;gap:9px}
  @media(max-width:620px){.b-list,.b-preview,.b-item>div,.b-live{grid-template-columns:1fr}}
`;document.head.appendChild(s)}
async function client(){const c=window.KinojoSupabaseClientCore;if(!c?.invokeEdgeFunction)throw Error('배너 Server 연결 모듈이 없습니다.');const cfg=await c.ensureConfig();S.url=String(cfg.url||'').replace(/\/$/,'');return c}
async function api(action,body={},mutation=false){const c=await client(),p={action,...body};if(action!=='manifest'){const t=session();if(!t)throw Error('MASTER 세션이 만료되었습니다.');p.sessionToken=t}if(mutation)p.idempotencyKey=id();return c.invokeEdgeFunction(EDGE,p)}
function url(a){if(a?.sourceType==='STATIC'){const p=String(a.staticPath||'');return /^\/assets\/images\/[A-Za-z0-9._/-]+$/.test(p)&&!p.includes('..')?location.origin+p:''}const p=String(a?.objectPath||'');return S.url&&/^\d{4}\/\d{2}\/[0-9a-f-]{36}\.(jpg|jpeg|png|webp)$/i.test(p)?`${S.url}/storage/v1/object/public/${BUCKET}/${p.split('/').map(encodeURIComponent).join('/')}`:''}
const assets=()=>S.assets.filter(a=>a.status==='READY'&&a.formatCode===FORMAT&&url(a));
const campaigns=()=>S.campaigns.filter(c=>c.type==='MAIN'&&c.pageCode==='HOME'&&c.slotCodes?.length===1&&c.slotCodes[0]==='MAIN');
const current=()=>campaigns().find(c=>Number(c.campaignId)===Number(S.cid))||null;
function render(){renderLive();renderAssets();renderSelected();renderCampaigns();renderButtons()}
function renderLive(){const r=$('#bLive'),m=S.manifest||{};if(!r)return;if(!m.active){r.innerHTML=`<div class="admin-empty">현재 노출 대상 없음${m.reason?' · '+esc(m.reason):''}</div>`;return}const seen=new Set(),xs=(m.playlist||[]).filter(x=>x?.imageUrl&&!seen.has(x.imageUrl)&&seen.add(x.imageUrl));r.innerHTML=`<small>Manifest ${esc(m.manifestVersion||'-')} · validUntil ${esc(m.validUntil||'-')}</small><div class="b-live">${xs.map(x=>`<div><img src="${esc(x.imageUrl)}" alt="${esc(x.alt||'')}"><small>${esc(x.alt||'대체 텍스트 없음')}</small></div>`).join('')}</div>`}
function renderAssets(){const r=$('#bLibrary'),xs=assets();if(!r)return;r.innerHTML=xs.length?xs.map(a=>`<label class="b-asset${S.selected.has(Number(a.assetId))?' on':''}"><img src="${esc(url(a))}" alt=""><span><b><input data-b-check="${a.assetId}" type="checkbox" ${S.selected.has(Number(a.assetId))?'checked':''}>${esc(a.displayName||a.originalFileName||'Asset '+a.assetId)}</b><br><small>${a.width}×${a.height}</small></span></label>`).join(''):'<div class="admin-empty">등록된 메인 이미지가 없습니다.</div>'}
function renderSelected(){const r=$('#bSelected'),map=new Map(assets().map(a=>[Number(a.assetId),a])),xs=[...S.selected].map(([id,v])=>({id,v,a:map.get(id)})).filter(x=>x.a);if(!r)return;r.innerHTML=xs.length?xs.map(x=>`<div class="b-item"><img src="${esc(url(x.a))}" alt=""><div><input class="admin-input" data-b-alt="${x.id}" value="${esc(x.v.alt||x.a.defaultAlt||'')}" maxlength="300" placeholder="대체 텍스트"><input class="admin-input" data-b-link="${x.id}" value="${esc(x.v.link||'')}" maxlength="2048" placeholder="https://... 또는 /경로"></div></div>`).join(''):'<div class="admin-empty">이미지를 선택하세요.</div>';const a=xs[0]?.a,u=url(a),alt=xs[0]?.v.alt||a?.defaultAlt||'';['#bannerMainPreviewPc','#bannerMainPreviewMobile'].forEach(q=>{const e=$(q);if(e)e.innerHTML=u?`<img src="${esc(u)}" alt="${esc(alt)}">`:'이미지를 선택하세요.'})}
function renderCampaigns(){const r=$('#bCampaigns'),xs=campaigns();if(!r)return;r.innerHTML=xs.length?xs.map(c=>`<div class="b-campaign${Number(c.campaignId)===Number(S.cid)?' on':''}"><span><b>${esc(c.name||'Campaign '+c.campaignId)}</b><br><small>${esc(c.status)} · 이미지 ${c.items?.length||0} · 우선순위 ${c.priority}</small></span><button class="admin-btn" data-b-edit="${c.campaignId}">편집</button></div>`).join(''):'<div class="admin-empty">저장된 메인 캠페인이 없습니다.</div>'}
function renderButtons(){const c=current(),s=c?.status||'DRAFT';$('[data-b-save]').disabled=s==='PUBLISHED'||s==='ARCHIVED';$('[data-b-publish]').disabled=s==='PUBLISHED'||s==='ARCHIVED';$('[data-b-pause]').disabled=!c||s!=='PUBLISHED';$('[data-b-archive]').disabled=!c||s==='ARCHIVED';$('[data-b-restore]').disabled=!c||s!=='ARCHIVED';msg('#bCampaignStatus',c?`#${c.campaignId} · ${s}${s==='PUBLISHED'?' · 수정 전 일시정지 필요':''}`:'새 캠페인 작성 중')}
function mode(){const e=$('#bSchedule');if(e)e.hidden=$('#bMode')?.value!=='SCHEDULED'}
function fill(c={}){$('#bName').value=c.name||'';$('#bPriority').value=c.priority??100;$('#bMode').value=c.scheduleMode||'ALWAYS';$('#bStart').value=String(c.startsAtKst||'').slice(0,16);$('#bEnd').value=String(c.endsAtKst||'').slice(0,16);const days=new Set((c.weekdays||[]).map(Number));$$('#bDays input').forEach(x=>x.checked=days.has(Number(x.value)));$('#bDates').value=(c.specificDates||[]).join(', ');$('#bSlide').value=c.slideIntervalMs??8000;$('#bTransition').value=c.transitionDurationMs??600;S.selected.clear();(c.items||[]).sort((a,b)=>(a.sortOrder||0)-(b.sortOrder||0)).forEach(x=>S.selected.set(Number(x.assetId),{alt:x.alt||'',link:x.clickUrl||''}));mode();render()}
function edit(id){const c=campaigns().find(x=>Number(x.campaignId)===Number(id));if(c){S.cid=Number(id);fill(c)}}
function fresh(){S.cid=0;S.selected.clear();fill({})}
function payload(){const m=$('#bMode').value,days=$$('#bDays input:checked').map(x=>Number(x.value)),dates=String($('#bDates').value||'').split(',').map(x=>x.trim()).filter(Boolean);let i=0;return{name:String($('#bName').value||'').trim(),type:'MAIN',pageCode:'HOME',slotCodes:['MAIN'],priority:Number($('#bPriority').value||100),scheduleMode:m,startsAtKst:m==='SCHEDULED'?$('#bStart').value||null:null,endsAtKst:m==='SCHEDULED'?$('#bEnd').value||null:null,weekdays:m==='SCHEDULED'?days:[],specificDates:m==='SCHEDULED'?dates:[],slideIntervalMs:Number($('#bSlide').value||8000),transitionDurationMs:Number($('#bTransition').value||600),items:[...S.selected].map(([assetId,v])=>({assetId,weight:100,enabled:true,alt:String(v.alt||'').trim(),clickUrl:String(v.link||'').trim()||null,sortOrder:i++,scheduleMode:'INHERIT'}))}}
async function load(force=false){if(!master()||S.busy||(!force&&S.loaded))return;S.busy=true;msg('#bStatus','불러오는 중...');try{await client();const [a,c,m]=await Promise.all([api('asset-list',{includeArchived:false}),api('campaign-list',{includeArchived:true}),api('manifest',{pageCode:'HOME',slotCode:'MAIN'})]);S.assets=a.assets||[];S.campaigns=c.campaigns||[];S.manifest=m||{};S.loaded=true;if(S.cid&&!campaigns().some(x=>Number(x.campaignId)===S.cid))S.cid=0;if(S.cid)fill(current());else render();msg('#bStatus',`메인 이미지 ${assets().length} · 캠페인 ${campaigns().length} · Server Manifest ${m.active?'활성':'비활성'}`,'ok')}catch(e){msg('#bStatus',e.message||String(e),'error')}finally{S.busy=false}}
async function inspect(f){if(!f||!MIMES.includes(String(f.type).toLowerCase()))throw Error('JPEG, PNG, WebP만 가능합니다.');if(f.size<1||f.size>MAX)throw Error('5MB 이하만 가능합니다.');const u=URL.createObjectURL(f);try{const im=await new Promise((ok,no)=>{const x=new Image();x.onload=()=>ok(x);x.onerror=()=>no(Error('이미지를 읽지 못했습니다.'));x.src=u});if(im.naturalWidth*9!==im.naturalHeight*16)throw Error(`정확한 16:9가 필요합니다. 현재 ${im.naturalWidth}×${im.naturalHeight}`)}finally{URL.revokeObjectURL(u)}}
async function upload(){const b=$('#bUpload'),f=$('#bFile')?.files?.[0];b.disabled=true;try{await inspect(f);const name=String($('#bUploadName').value||'').trim()||String(f.name||'메인 배너').slice(0,120),alt=String($('#bUploadAlt').value||'').trim();msg('#bUploadStatus','업로드 준비 중...');const p=await api('upload-prepare',{mimeType:f.type,sizeBytes:f.size,formatCode:FORMAT},true),u=p.upload||{};if(u.bucket!==BUCKET||u.upsert!==false)throw Error('업로드 계약 오류');const cfg=await window.KinojoSupabaseClientCore.ensureConfig(),to=new URL(u.uploadUrl),origin=new URL(cfg.url);if(to.origin!==origin.origin||!to.pathname.startsWith(`/storage/v1/object/upload/sign/${BUCKET}/`))throw Error('Signed URL 오류');const put=await fetch(to,{method:'PUT',headers:{'content-type':f.type,'x-upsert':'false'},body:f});if(!put.ok)throw Error('Storage 업로드 실패 HTTP '+put.status);const done=await api('upload-complete',{objectPath:u.objectPath,mimeType:f.type,sizeBytes:f.size,formatCode:FORMAT,displayName:name,originalFileName:String(f.name||'').slice(0,255),defaultAlt:alt},true);if(done?.image?.activation!=='ASSET_READY'||done?.image?.aspectValid!==true)throw Error('Asset READY 검증 실패');$('#bFile').value='';$('#bUploadName').value='';$('#bUploadAlt').value='';msg('#bUploadStatus','등록 완료','ok');S.loaded=false;await load(true)}catch(e){msg('#bUploadStatus',e.message||String(e),'error')}finally{b.disabled=false}}
async function save(){const c=current(),d=await api(c?'campaign-update':'campaign-create',c?{campaignId:Number(c.campaignId),campaign:payload()}:{campaign:payload()},true),cid=Number(d?.campaign?.campaignId||d?.campaignId||c?.campaignId||0);S.loaded=false;await load(true);if(cid)edit(cid);msg('#bCampaignStatus','저장 완료','ok');return cid}
async function change(action){let c=current(),saved=false;try{if(action==='campaign-publish'&&!c){await save();c=current();saved=true}if(!c)throw Error('캠페인을 먼저 저장하세요.');if(action==='campaign-publish'&&!saved&&c.status!=='PUBLISHED'&&c.status!=='ARCHIVED'){await save();c=current()}await api(action,{campaignId:Number(c.campaignId)},true);S.loaded=false;await load(true);edit(c.campaignId);msg('#bCampaignStatus',{'campaign-publish':'게시 완료','campaign-pause':'일시정지 완료','campaign-archive':'보관 완료','campaign-restore':'복원 완료'}[action],'ok')}catch(e){msg('#bCampaignStatus',e.message||String(e),'error')}}
function check(x){const aid=Number(x.dataset.bCheck),a=assets().find(v=>Number(v.assetId)===aid);if(!a)return;if(x.checked)S.selected.set(aid,{alt:a.defaultAlt||'',link:''});else S.selected.delete(aid);renderAssets();renderSelected()}
shell();guard();const pane=$('[data-admin-pane="images"]');if(pane)new MutationObserver(()=>{if(pane.classList.contains('active')){label();load()}}).observe(pane,{attributes:true,attributeFilter:['class']});const loc=$('#adminCurrentLocation');if(loc)new MutationObserver(label).observe(loc,{childList:true,subtree:true,characterData:true});
document.addEventListener('click',e=>{const t=e.target.closest?.('button');if(!t)return;if(t.matches('[data-admin-tab="images"]')){queueMicrotask(()=>{label();load()});return}if(!t.closest?.('[data-main-banner-admin]'))return;if(t.matches('[data-b-refresh]')){S.loaded=false;load(true)}else if(t.matches('[data-b-new]'))fresh();else if(t.matches('[data-b-edit]'))edit(t.dataset.bEdit);else if(t.matches('[data-b-save]'))save().catch(e=>msg('#bCampaignStatus',e.message,'error'));else if(t.matches('[data-b-publish]'))change('campaign-publish');else if(t.matches('[data-b-pause]'))change('campaign-pause');else if(t.matches('[data-b-archive]'))change('campaign-archive');else if(t.matches('[data-b-restore]'))change('campaign-restore');else if(t.id==='bUpload')upload()});
document.addEventListener('change',e=>{const t=e.target;if(!t?.closest?.('[data-main-banner-admin]'))return;if(t.matches('[data-b-check]'))check(t);if(t.id==='bMode')mode()});document.addEventListener('input',e=>{const t=e.target;if(!t?.closest?.('[data-main-banner-admin]'))return;const a=Number(t.dataset?.bAlt),l=Number(t.dataset?.bLink);if(a&&S.selected.has(a))S.selected.get(a).alt=t.value;if(l&&S.selected.has(l))S.selected.get(l).link=t.value});window.addEventListener('hashchange',()=>{if(!guard()&&imageRoute())queueMicrotask(()=>load())});if(imageRoute()&&master())queueMicrotask(()=>load());Object.assign(A,{ensureImageManagementShell:shell,ensureBannerAdminLayoutStyle,loadMainBannerManagement:load});
})(window.KinojoAdmin);
