/* KINOJO Admin image management v2026082405 */
(function(A){'use strict';if(!A)throw Error('KINOJO Admin shared module is required.');
const EDGE='kinojo-banner-media',BUCKET='kinojo-site-banners',FORMAT='MAIN_16_9',MAX=5242880,MIMES=['image/jpeg','image/png','image/webp'];
const MAIN_OUTPUT={width:1536,height:864,label:'1536×864'};
const S={assets:[],campaigns:[],manifest:{},url:'',cid:0,selected:new Map(),assetTag:'ALL',loaded:false,busy:false};
const QUEUE_URLS={b:[],s:[]};
const $=(q,r=document)=>r.querySelector(q),$$=(q,r=document)=>Array.from(r.querySelectorAll(q)),master=()=>A.isMaster?.()===true;
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function session(){const t=String(window.KinojoAuth?.getSession?.()?.token||'').trim();return /^kws_[A-Za-z0-9_-]{40,80}$/.test(t)?t:''}
function id(){return crypto.randomUUID()}
function imageRoute(){return String(location.hash||'').replace(/^#/,'').split('/')[0]==='images'}
function guard(){if(master()||!imageRoute())return false;history.replaceState(null,'',location.pathname+location.search+'#dashboard');A.switchTab?.('dashboard',{updateRoute:true});return true}
function label(){const e=$('#adminCurrentLocation'),p=$('[data-admin-pane="images"]'),text='[이미지 관리]';if(e&&p?.classList.contains('active')&&e.textContent!==text)e.textContent=text}
function msg(q,text,type=''){const e=$(q);if(e){e.textContent=text||'';e.className='admin-statusline '+type}}
const bytes=value=>{const size=Number(value)||0;return size>=1048576?(size/1048576).toFixed(1)+'MB':Math.max(1,Math.round(size/1024))+'KB'};
const fileStem=name=>String(name||'').replace(/\.[^.]+$/,'').trim()||'배너 이미지';
function canvasBlob(canvas,quality=.9){return new Promise((resolve,reject)=>{try{const dataUrl=canvas.toDataURL('image/webp',quality);if(!dataUrl.startsWith('data:image/webp;base64,'))throw Error('이 브라우저에서는 WebP 이미지 변환을 지원하지 않습니다.');const raw=atob(dataUrl.slice(dataUrl.indexOf(',')+1)),bytes=new Uint8Array(raw.length);for(let index=0;index<raw.length;index++)bytes[index]=raw.charCodeAt(index);resolve(new Blob([bytes],{type:'image/webp'}))}catch(error){reject(error)}})}
async function prepareBannerUploadImage(file,{width,height,fit='COVER',background='#111827'}={}){if(!file||!MIMES.includes(String(file.type).toLowerCase()))throw Error('JPEG, PNG, WebP만 가능합니다.');if(file.size<1||file.size>MAX)throw Error('원본 이미지는 5MB 이하만 가능합니다.');let decoded=null,objectUrl='';try{if(typeof createImageBitmap==='function')decoded=await createImageBitmap(file);else{objectUrl=URL.createObjectURL(file);decoded=await new Promise((resolve,reject)=>{const image=new Image();image.onload=()=>resolve(image);image.onerror=()=>reject(Error('이미지를 읽지 못했습니다.'));image.src=objectUrl})}const sourceWidth=decoded.naturalWidth||decoded.width,sourceHeight=decoded.naturalHeight||decoded.height;if(!sourceWidth||!sourceHeight)throw Error('이미지 크기를 확인하지 못했습니다.');const canvas=document.createElement('canvas');canvas.width=Number(width);canvas.height=Number(height);const context=canvas.getContext('2d',{alpha:true});if(!context)throw Error('이미지 변환 기능을 사용할 수 없습니다.');context.imageSmoothingEnabled=true;context.imageSmoothingQuality='high';const contain=fit==='CONTAIN',scale=(contain?Math.min:Math.max)(canvas.width/sourceWidth,canvas.height/sourceHeight),drawWidth=sourceWidth*scale,drawHeight=sourceHeight*scale;if(contain){context.fillStyle=/^#[0-9a-f]{6}$/i.test(background)?background:'#111827';context.fillRect(0,0,canvas.width,canvas.height)}context.drawImage(decoded,(canvas.width-drawWidth)/2,(canvas.height-drawHeight)/2,drawWidth,drawHeight);let quality=.9,blob=await canvasBlob(canvas,quality);while(blob.size>MAX&&quality>.6){quality-=.08;blob=await canvasBlob(canvas,quality)}if(blob.size>MAX)throw Error('변환된 이미지가 5MB를 초과합니다. 더 작은 원본을 사용해 주세요.');return{blob,mimeType:'image/webp',sizeBytes:blob.size,width:canvas.width,height:canvas.height,sourceWidth,sourceHeight,fit:contain?'CONTAIN':'COVER'}}finally{decoded?.close?.();if(objectUrl)URL.revokeObjectURL(objectUrl)}}
function normalizeTags(value){const seen=new Set();return String(value||'').split(/[\s,]+/).map(tag=>tag.replace(/^#+/,'').replace(/[^0-9A-Za-z가-힣_-]/g,'').slice(0,20)).filter(tag=>tag&&!seen.has(tag)&&seen.add(tag)).slice(0,5)}
function assetTags(asset){return Array.from(String(asset?.displayName||'').matchAll(/#([^\s#·]+)/g),match=>match[1])}
function uploadDisplayName(base,file,total,tags=[]){const stem=fileStem(file?.name),prefix=String(base||'').trim(),name=prefix?(total>1?`${prefix} · ${stem}`:prefix):stem,tagText=normalizeTags(tags).map(tag=>'#'+tag).join(' ');return String(tagText?`${tagText} · ${name}`:name).slice(0,120)}
function releaseQueueUrls(prefix){for(const value of QUEUE_URLS[prefix]||[])URL.revokeObjectURL(value);QUEUE_URLS[prefix]=[]}
function queueWarning(sourceWidth,sourceHeight,output,fit){const ratioDiff=Math.abs(sourceWidth/sourceHeight-output.width/output.height)>.003,small=sourceWidth<output.width||sourceHeight<output.height;if(fit==='CONTAIN')return{kind:small?'':'safe',text:`원본 ${sourceWidth}×${sourceHeight} · 전체 이미지를 유지하고 ${output.label} 여백을 추가합니다.`};if(ratioDiff)return{kind:'',text:`원본 ${sourceWidth}×${sourceHeight} · 배너 비율과 달라 중앙 기준으로 일부가 잘릴 수 있습니다.`};if(small)return{kind:'',text:`원본 ${sourceWidth}×${sourceHeight} · 배너보다 작아 확대되며 선명도가 낮아질 수 있습니다.`};return{kind:'safe',text:`원본 ${sourceWidth}×${sourceHeight} · 잘림 없이 ${output.label}로 자동 축소됩니다.`}}
async function renderFileQueue(prefix,output){const input=$(`#${prefix}File`),root=$(`#${prefix}FileQueue`),button=$(`#${prefix}Upload`),fit=$(`#${prefix}Fit`)?.value||'COVER',files=Array.from(input?.files||[]);releaseQueueUrls(prefix);if(root)root.innerHTML=files.length?files.map((file,index)=>{const preview=URL.createObjectURL(file);QUEUE_URLS[prefix].push(preview);return `<div class="banner-upload-file" data-${prefix.toLowerCase()}-queue="${index}"><div class="banner-upload-thumb"><img src="${esc(preview)}" alt=""></div><span class="banner-upload-copy"><b>${esc(file.name)}</b><small>${bytes(file.size)} · ${output.label} WebP 자동 변환</small><strong class="banner-upload-warning" data-${prefix.toLowerCase()}-warning="${index}">이미지 크기 확인 중...</strong></span><em>대기</em></div>`}).join(''):'<div class="admin-empty">＋ 추가하기를 눌러 업로드할 이미지를 선택하세요.</div>';if(button)button.textContent=files.length>1?`${files.length}개 이미지 업로드`:'선택 이미지 업로드';await Promise.all(files.map((file,index)=>new Promise(resolve=>{const image=new Image(),warning=$(`[data-${prefix.toLowerCase()}-warning="${index}"]`);image.onload=()=>{const report=queueWarning(image.naturalWidth,image.naturalHeight,output,fit);if(warning){warning.textContent=report.text;warning.className='banner-upload-warning '+report.kind}resolve()};image.onerror=()=>{if(warning)warning.textContent='이미지를 읽지 못했습니다.';resolve()};image.src=QUEUE_URLS[prefix][index]})));return files}
function updateQueue(prefix,index,textValue,kind=''){const row=$(`[data-${prefix.toLowerCase()}-queue="${index}"]`);if(!row)return;row.className='banner-upload-file '+kind;const state=$('em',row);if(state)state.textContent=textValue}
const sectionHead=(title,description)=>`<div class="banner-section-head"><div><h3>${title}</h3><p>${description}</p></div></div>`;
function shell(){
  const nav=$('.admin-nav');
  if(nav&&!$('[data-admin-tab="images"]',nav)){const b=document.createElement('button');b.type='button';b.dataset.adminTab='images';b.setAttribute('data-admin-master-only','');b.textContent='🖼 이미지 관리';nav.insertBefore(b,$('[data-admin-tab="meter"]',nav)||$('[data-admin-tab="system"]',nav))}
  const main=$('.admin-main');
  if(main&&!$('[data-admin-pane="images"]',main)){const p=document.createElement('section');p.className='admin-pane';p.dataset.adminPane='images';p.setAttribute('data-admin-master-only','');main.insertBefore(p,$('[data-admin-pane="meter"]',main)||$('[data-admin-pane="system"]',main))}
  const p=$('[data-admin-pane="images"]');
  if(!p||$('[data-main-banner-admin]',p))return;
  p.innerHTML=`<div data-main-banner-admin>
    <section class="admin-card banner-admin-hero"><div class="admin-card-head"><div><h2>메인 배너 관리</h2><p>이미지 추가부터 노출 묶음 구성, 조건 설정, 게시까지 위에서 아래로 진행합니다.</p></div><button class="admin-btn" data-b-refresh type="button">새로고침</button></div><div class="banner-spec-list"><span>자동 출력 1536×864</span><span>JPEG · PNG · WebP 원본</span><span>원본 최대 5MB</span><span>다중 업로드 지원</span><span>일정 기준 Asia/Seoul</span></div><div id="bStatus" class="admin-statusline"></div></section>
    <div class="banner-flow" aria-label="메인 배너 게시 절차">
      <div class="banner-flow-step"><div class="banner-flow-rail"><span>1</span></div><section class="admin-card banner-step-card"><div class="banner-section-head"><div><h3>이미지 추가</h3><p>크기와 비율이 다른 원본을 여러 장 고르고, 잘림·확대 가능성을 확인한 뒤 라이브러리에 올립니다. 이 단계만으로는 노출되지 않습니다.</p></div><label class="admin-btn primary banner-file-add" for="bFile">＋ 추가하기</label></div><input class="banner-file-input" id="bFile" type="file" accept="image/jpeg,image/png,image/webp" multiple><div id="bFileQueue" class="banner-upload-queue"><div class="admin-empty">＋ 추가하기를 눌러 업로드할 이미지를 선택하세요.</div></div><div class="banner-compact-fields banner-upload-options"><label class="banner-field"><span>분류 태그 · 선택</span><input class="admin-input" id="bUploadTags" maxlength="100" placeholder="#여름 #이벤트"></label><label class="banner-field"><span>묶음/관리 이름 · 선택</span><input class="admin-input" id="bUploadName" maxlength="120" placeholder="여러 장이면 파일명과 함께 구분"></label><label class="banner-field"><span>공통 대체 텍스트 · 선택</span><input class="admin-input" id="bUploadAlt" maxlength="300" placeholder="비우면 각 파일명 사용"></label><label class="banner-field"><span>맞춤 방식</span><select class="admin-select" id="bFit"><option value="COVER">영역 채우기 · 중앙 자르기</option><option value="CONTAIN">전체 보기 · 여백 추가</option></select><small>${MAIN_OUTPUT.label} WebP 자동 변환</small></label><label class="banner-field banner-color-field"><span>여백 색상</span><input class="admin-input banner-color-input" id="bBackground" type="color" value="#111827" disabled><small>전체 보기에서만 사용</small></label></div><div class="banner-upload-actions"><button class="admin-btn primary" id="bUpload" type="button">선택 이미지 업로드</button></div><div id="bUploadStatus" class="admin-statusline"></div></section></div>
      <div class="banner-flow-step"><div class="banner-flow-rail"><span>2</span></div><section class="admin-card banner-step-card"><div class="banner-section-head"><div><h3>노출 묶음 구성</h3><p>라이브러리에서 여러 이미지를 체크하면 한 슬라이드 노출 묶음으로 구성됩니다.</p></div><div class="banner-state-legend"><span class="banner-asset-state live">현재 노출 중</span><span class="banner-asset-state published">게시 설정됨</span><span class="banner-asset-state linked">묶음 연결</span><span class="banner-asset-state uploaded">업로드만</span></div></div><div id="bAssetFilters" class="banner-tag-filters"></div><div class="banner-inner-grid"><div class="banner-subsection"><h4>이미지 라이브러리</h4><p>태그·업로드 상태를 확인하고 사용할 이미지를 선택합니다.</p><div id="bLibrary" class="b-list"></div></div><div class="banner-subsection"><h4>이번 묶음에 선택한 이미지</h4><p>이미지별 대체 텍스트와 클릭 연결 주소를 설정합니다.</p><div id="bSelected"></div></div></div></section></div>
      <div class="banner-flow-step"><div class="banner-flow-rail"><span>3</span></div><section class="admin-card banner-step-card banner-settings-card"><div class="banner-section-head banner-section-head-action"><div><h3>노출 조건 설정</h3><p>묶음 이름, 일정, 우선순위와 이미지 전환 속도를 지정합니다.</p></div><button class="admin-btn" data-b-new type="button">새 노출 묶음</button></div><div class="banner-compact-fields banner-campaign-fields"><label class="banner-field banner-name-field"><span>노출 묶음 이름</span><input class="admin-input" id="bName" maxlength="120" placeholder="예: 여름 메인 배너"></label><label class="banner-field banner-priority-field"><span>우선순위</span><input class="admin-input" id="bPriority" type="number" min="0" max="10000" value="100"></label><label class="banner-field"><span>노출 방식</span><select class="admin-select" id="bMode"><option value="ALWAYS">항상 노출</option><option value="SCHEDULED">기간·요일 지정</option></select></label><label class="banner-field"><span>슬라이드 간격</span><input class="admin-input" id="bSlide" type="number" min="3000" max="60000" value="8000"><small>다음 이미지까지 · ms</small></label><label class="banner-field"><span>전환 속도</span><input class="admin-input" id="bTransition" type="number" min="0" max="5000" value="600"><small>바뀌는 시간 · ms</small></label></div><div id="bSchedule" class="banner-schedule-panel" hidden><strong>기간·요일 설정</strong><p>지정한 기간과 요일에만 노출합니다.</p><div class="banner-fields"><label class="banner-field"><span>시작 KST</span><input class="admin-input" id="bStart" type="datetime-local"></label><label class="banner-field"><span>종료 KST</span><input class="admin-input" id="bEnd" type="datetime-local"></label></div><div id="bDays" class="b-days">${[['1','월'],['2','화'],['3','수'],['4','목'],['5','금'],['6','토'],['7','일']].map(x=>`<label><input type="checkbox" value="${x[0]}">${x[1]}</label>`).join('')}</div><input class="admin-input" id="bDates" placeholder="특정 날짜: 2026-09-01, 2026-09-15"></div></section></div>
      <div class="banner-flow-step last"><div class="banner-flow-rail"><span>4</span></div><section class="admin-card banner-step-card"><div class="banner-section-head"><div><h3>검토하고 게시</h3><p>현재 노출과 미리보기를 확인하고, 초안 저장 또는 게시로 노출을 시작합니다.</p></div></div><div class="banner-review-grid"><div class="banner-subsection"><h4>현재 게시 중</h4><p>홈 화면에 실제로 노출 중인 이미지입니다.</p><div id="bLive"></div></div><div class="banner-subsection"><h4>PC·모바일 미리보기</h4><p>이번 묶음의 첫 번째 이미지를 기준으로 확인합니다.</p><div class="b-preview"><div><small>PC · 16:9</small><div id="bannerMainPreviewPc" class="b-frame">이미지를 선택하세요.</div></div><div><small>모바일 · 16:9</small><div id="bannerMainPreviewMobile" class="b-frame">이미지를 선택하세요.</div></div></div></div></div><div class="banner-actions"><button class="admin-btn primary" data-b-save type="button">초안 저장</button><button class="admin-btn primary" data-b-publish type="button">게시 · 노출 시작</button><button class="admin-btn" data-b-pause type="button">일시정지</button><button class="admin-btn" data-b-archive type="button" title="목록에서 숨기며 나중에 복원할 수 있습니다.">보관</button><button class="admin-btn" data-b-restore type="button">복원</button><button class="admin-btn danger" data-b-delete type="button" title="캠페인 설정과 연결 항목을 복구할 수 없게 삭제합니다.">영구 삭제</button></div><div id="bCampaignStatus" class="admin-statusline"></div><p class="banner-inline-note"><strong>보관</strong>은 복원할 수 있고, <strong>영구 삭제</strong>는 캠페인 설정과 연결 항목을 서버에서 제거해 되돌릴 수 없습니다. 업로드 이미지 원본은 라이브러리에 남습니다.</p><div class="banner-subsection banner-campaign-list"><h4>메인 노출 묶음 목록</h4><p>초안·게시·일시정지 상태와 포함 이미지 수를 확인합니다.</p><div id="bCampaigns"></div></div></section></div>
    </div>
  </div>`;
  ensureBannerAdminLayoutStyle();style();
}
function ensureBannerAdminLayoutStyle(){if($('#bannerAdminLayoutStyle'))return;const s=document.createElement('style');s.id='bannerAdminLayoutStyle';s.textContent=`
  [data-main-banner-admin],[data-side-banner-admin]{color:#14213a}
  .banner-admin-hero{padding:21px 22px}.banner-admin-hero .admin-card-head{align-items:flex-start}.banner-admin-hero h2{margin:0 0 6px;font-size:21px;letter-spacing:-.025em}.banner-admin-hero p{margin:0;color:#64748b;font-size:12px;line-height:1.55}
  .banner-spec-list{display:flex;flex-wrap:wrap;gap:7px;margin-top:15px}.banner-spec-list span{display:inline-flex;align-items:center;min-height:27px;padding:0 9px;border:1px solid #dbeafe;border-radius:999px;background:#f8fbff;color:#45617f;font-size:9px;font-weight:800}
  .banner-flow{display:grid;gap:16px;margin-top:16px}.banner-flow-step{display:grid;grid-template-columns:46px minmax(0,1fr);align-items:stretch}.banner-flow-rail{position:relative;display:flex;justify-content:center}.banner-flow-rail::after{content:"";position:absolute;top:37px;bottom:-18px;width:3px;border-radius:3px;background:#bfd3f6}.banner-flow-step.last .banner-flow-rail::after{display:none}.banner-flow-rail>span{position:relative;z-index:1;display:grid;place-items:center;width:34px;height:34px;border:4px solid #e8f0ff;border-radius:50%;background:#2563eb;color:#fff;font-size:13px;font-weight:950;box-shadow:0 0 0 1px #93b5ec}.banner-step-card{min-width:0;padding:19px 20px}.banner-step-card>.banner-section-head{margin-bottom:15px}
  .banner-admin-grid{display:grid;grid-template-columns:minmax(0,1fr) minmax(0,1fr);gap:16px;margin-top:16px;align-items:stretch}.banner-card{min-width:0;padding:19px}.banner-span-all{grid-column:1/-1}
  .banner-section-head{display:flex;align-items:flex-start;justify-content:space-between;gap:12px;margin-bottom:14px}.banner-section-head h3{margin:0;color:#17233b;font-size:15px;letter-spacing:-.02em}.banner-section-head p{margin:5px 0 0;color:#718096;font-size:10px;line-height:1.5}.banner-section-head-action{min-height:43px}.banner-section-head-action .admin-btn{flex:0 0 auto}
  .banner-fields{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:14px 16px}.banner-compact-fields{display:grid;grid-template-columns:repeat(auto-fit,minmax(145px,1fr));gap:11px}.banner-campaign-fields{grid-template-columns:minmax(210px,2fr) 90px minmax(140px,1.15fr) 125px 125px}.banner-upload-options{grid-template-columns:minmax(130px,.8fr) minmax(170px,1.2fr) minmax(190px,1.4fr) minmax(190px,1.25fr) 88px;margin-top:14px}.banner-field{display:grid;grid-template-rows:auto 42px auto;align-content:start;gap:6px;min-width:0}.banner-field>span{color:#24324a;font-size:10px;font-weight:850}.banner-field>small{min-height:14px;color:#8a98ab;font-size:9px;line-height:1.45}.banner-field-wide{grid-column:1/-1}.banner-field>.admin-input,.banner-field>.admin-select{width:100%;height:42px;box-sizing:border-box}.banner-file-input{position:absolute;width:1px;height:1px;overflow:hidden;clip:rect(0 0 0 0);clip-path:inset(50%);white-space:nowrap}.banner-file-add{cursor:pointer;flex:0 0 auto}
  .banner-color-input{padding:5px 8px}.banner-upload-queue{display:grid;grid-template-columns:repeat(auto-fill,minmax(270px,1fr));gap:8px}.banner-upload-file{display:grid;grid-template-columns:74px minmax(0,1fr) auto;align-items:center;gap:10px;min-height:74px;padding:8px 10px;border:1px solid #e2e8f0;border-radius:10px;background:#fbfdff}.banner-upload-thumb{width:74px;height:58px;overflow:hidden;border-radius:7px;background:#e8edf4}.banner-upload-thumb img{width:100%;height:100%;object-fit:cover}.banner-upload-copy{min-width:0}.banner-upload-file b{display:block;overflow:hidden;color:#334155;font-size:10px;text-overflow:ellipsis;white-space:nowrap}.banner-upload-file small{display:block;margin-top:3px;color:#8290a3;font-size:8px}.banner-upload-warning{display:block;margin-top:5px;color:#b45309;font-size:9px;font-weight:850;line-height:1.4}.banner-upload-warning.safe{color:#15803d}.banner-upload-file em{color:#64748b;font-size:9px;font-style:normal;font-weight:800}.banner-upload-file.processing{border-color:#93c5fd;background:#eff6ff}.banner-upload-file.ok{border-color:#86efac;background:#f0fdf4}.banner-upload-file.error{border-color:#fca5a5;background:#fff1f2}.banner-upload-file.error em{color:#dc2626}
  .banner-upload-actions{display:flex;justify-content:flex-end;margin-top:14px}.banner-upload-actions .admin-btn{min-width:118px}.banner-schedule-panel{margin-top:16px;padding:14px;border:1px solid #dbeafe;border-radius:13px;background:#f8fbff}.banner-schedule-panel>strong{display:block;font-size:11px}.banner-schedule-panel>p{margin:4px 0 12px;color:#718096;font-size:9px}
  .banner-actions{display:flex;align-items:center;justify-content:flex-start;flex-wrap:wrap;gap:7px;margin-top:17px;padding-top:15px;border-top:1px solid #e8edf4}.banner-actions-primary,.banner-actions-secondary{display:contents}.banner-actions .admin-btn{flex:0 0 auto;width:auto;min-width:0;padding-left:13px;padding-right:13px}
  .banner-card>.admin-statusline:last-child,.banner-step-card>.admin-statusline{margin-top:10px}.banner-inline-note{margin:10px 0 0;color:#718096;font-size:9px;line-height:1.55}.banner-inner-grid,.banner-review-grid{display:grid;grid-template-columns:minmax(0,1fr) minmax(0,1fr);gap:14px}.banner-subsection{min-width:0;padding:13px;border:1px solid #e6ecf4;border-radius:11px;background:#fbfdff}.banner-subsection h4{margin:0;color:#25324a;font-size:11px}.banner-subsection>p{margin:4px 0 11px;color:#7a889b;font-size:9px;line-height:1.45}.banner-campaign-list{margin-top:14px}.banner-state-legend{display:flex;flex-wrap:wrap;justify-content:flex-end;gap:6px;margin:0}.banner-asset-state{display:inline-flex;align-items:center;width:max-content;min-height:21px;padding:0 7px;border-radius:999px;background:#edf2f7;color:#526174;font-size:8px;font-weight:900;letter-spacing:-.01em}.banner-asset-state.live{background:#dcfce7;color:#15803d}.banner-asset-state.published{background:#dbeafe;color:#1d4ed8}.banner-asset-state.linked{background:#fef3c7;color:#a16207}.banner-asset-state.uploaded{background:#eef2f7;color:#64748b}.banner-asset-detail{display:block;margin-top:5px;color:#718096;font-size:8px;line-height:1.45}.banner-campaign-status{display:inline-flex;margin-right:5px;padding:2px 6px;border-radius:999px;background:#eef2f7;color:#526174;font-size:8px;font-weight:900}.banner-campaign-status.published{background:#dcfce7;color:#15803d}.banner-campaign-status.draft{background:#fef3c7;color:#a16207}.banner-campaign-status.paused{background:#fee2e2;color:#b91c1c}.banner-tag-filters{display:flex;flex-wrap:wrap;gap:6px;margin:-3px 0 12px}.banner-tag-filter{padding:5px 9px;border:1px solid #d9e3f0;border-radius:999px;background:#fff;color:#526174;font-size:9px;font-weight:850;cursor:pointer}.banner-tag-filter.active{border-color:#60a5fa;background:#eaf2ff;color:#1d4ed8}
  .admin-btn.danger{border-color:#fecaca;background:#fff7f7;color:#b91c1c}.admin-btn.danger:hover:not(:disabled){border-color:#ef4444;background:#fef2f2}.banner-delete-modal{position:fixed;inset:0;z-index:10080;display:grid;place-items:center;padding:18px;background:rgba(15,23,42,.62)}.banner-delete-dialog{width:min(480px,100%);padding:22px;border:1px solid #fecaca;border-radius:16px;background:#fff;box-shadow:0 24px 70px rgba(15,23,42,.28)}.banner-delete-dialog h2{margin:0;color:#991b1b;font-size:19px}.banner-delete-dialog p{margin:10px 0;color:#55657a;font-size:11px;line-height:1.65}.banner-delete-name{display:block;margin:12px 0 6px;color:#17233b;font-size:12px;font-weight:900;word-break:break-all}.banner-delete-dialog label{display:grid;gap:6px;color:#334155;font-size:10px;font-weight:850}.banner-delete-dialog .banner-actions{margin-top:16px;justify-content:flex-end}
  @media(max-width:1100px){.banner-campaign-fields,.banner-upload-options{grid-template-columns:repeat(auto-fit,minmax(145px,1fr))}}
  @media(max-width:980px){.banner-admin-grid,.banner-inner-grid,.banner-review-grid{grid-template-columns:1fr}.banner-span-all{grid-column:auto}}
  @media(max-width:620px){.banner-admin-hero{padding:17px}.banner-card,.banner-step-card{padding:15px}.banner-flow-step{grid-template-columns:37px minmax(0,1fr)}.banner-flow-rail>span{width:29px;height:29px;border-width:3px}.banner-flow-rail::after{top:32px}.banner-section-head{align-items:stretch;flex-direction:column}.banner-file-add{width:max-content}.banner-fields,.banner-compact-fields{grid-template-columns:1fr;gap:12px}.banner-field-wide{grid-column:auto}.banner-upload-file{grid-template-columns:60px minmax(0,1fr)}.banner-upload-thumb{width:60px;height:48px}.banner-upload-file em{grid-column:2}.banner-actions{align-items:center;flex-direction:row}.banner-actions .admin-btn{width:auto}.banner-upload-actions .admin-btn{width:100%}.banner-state-legend{justify-content:flex-start}}
`;document.head.appendChild(s)}
function style(){if($('#bAdminStyle'))return;const s=document.createElement('style');s.id='bAdminStyle';s.textContent=`
  .b-list{display:grid;grid-template-columns:1fr 1fr;gap:9px;max-height:380px;overflow:auto}.b-asset,.b-campaign,.b-item{display:grid;gap:8px;padding:9px;border:1px solid #e2e8f0;border-radius:11px;background:#fff}.b-asset{grid-template-columns:82px 1fr}.b-asset.on,.b-campaign.on{border-color:#60a5fa;background:#eff6ff}.b-asset img,.b-item img,.b-live img{width:100%;aspect-ratio:16/9;object-fit:cover;border-radius:7px}.b-item{grid-template-columns:78px 1fr;margin-bottom:8px}.b-item>div{display:grid;grid-template-columns:1fr 1fr;gap:7px}.b-preview{display:grid;grid-template-columns:1fr 1fr;gap:12px}.b-preview>div>small{display:block;margin-bottom:7px;color:#64748b;font-size:9px;font-weight:800}.b-frame{position:relative;display:grid;place-items:center;aspect-ratio:16/9;overflow:hidden;border:1px dashed #94a3b8;border-radius:11px;background:#f8fafc;color:#94a3b8;font-size:10px}.b-frame img{position:absolute;inset:0;width:100%;height:100%;object-fit:cover}.b-days{display:flex;flex-wrap:wrap;gap:7px;margin:11px 0}.b-days label{font-size:10px}.b-campaign{grid-template-columns:1fr auto;align-items:center;margin-bottom:7px}.b-live{display:grid;grid-template-columns:1fr 1fr;gap:9px}
  @media(max-width:620px){.b-list,.b-preview,.b-item>div,.b-live{grid-template-columns:1fr}}
`;document.head.appendChild(s)}
async function client(){const c=window.KinojoSupabaseClientCore;if(!c?.invokeEdgeFunction)throw Error('배너 Server 연결 모듈이 없습니다.');const cfg=await c.ensureConfig();S.url=String(cfg.url||'').replace(/\/$/,'');return c}
async function api(action,body={},mutation=false){const c=await client(),p={action,...body};if(action!=='manifest'){const t=session();if(!t)throw Error('MASTER 세션이 만료되었습니다.');p.sessionToken=t}if(mutation)p.idempotencyKey=id();return c.invokeEdgeFunction(EDGE,p)}
function url(a){if(a?.sourceType==='STATIC'){const p=String(a.staticPath||'');return /^\/assets\/images\/[A-Za-z0-9._/-]+$/.test(p)&&!p.includes('..')?location.origin+p:''}const p=String(a?.objectPath||'');return S.url&&/^\d{4}\/\d{2}\/[0-9a-f-]{36}\.(jpg|jpeg|png|webp)$/i.test(p)?`${S.url}/storage/v1/object/public/${BUCKET}/${p.split('/').map(encodeURIComponent).join('/')}`:''}
const assets=()=>S.assets.filter(a=>a.status==='READY'&&a.formatCode===FORMAT&&url(a));
const campaigns=()=>S.campaigns.filter(c=>c.type==='MAIN'&&c.pageCode==='HOME'&&c.slotCodes?.length===1&&c.slotCodes[0]==='MAIN');
const current=()=>campaigns().find(c=>Number(c.campaignId)===Number(S.cid))||null;
function campaignMeta(value){const status=String(value||'DRAFT').toUpperCase();return{status,className:status.toLowerCase(),label:{DRAFT:'초안 · 노출 안 함',PUBLISHED:'게시됨',PAUSED:'일시정지 · 노출 안 함',ARCHIVED:'보관 · 노출 안 함'}[status]||status}}
function mainAssetExposure(asset){const assetId=Number(asset.assetId),refs=campaigns().filter(c=>(c.items||[]).some(item=>Number(item.assetId)===assetId)),image=url(asset),live=Boolean(image&&(S.manifest?.playlist||[]).some(item=>item?.imageUrl===image)),published=refs.filter(c=>c.status==='PUBLISHED');if(live)return{kind:'live',label:'현재 노출 중',detail:published.map(c=>c.name).filter(Boolean).join(' · ')||'게시된 메인 노출 묶음'};if(published.length)return{kind:'published',label:'게시 설정됨',detail:'일정·우선순위 조건에 따라 노출 대기'};if(refs.length)return{kind:'linked',label:'묶음 연결 · 노출 안 함',detail:refs.slice(0,2).map(c=>`${c.name||'#'+c.campaignId} (${campaignMeta(c.status).label})`).join(' · ')};return{kind:'uploaded',label:'업로드만 · 노출 안 함',detail:'노출 묶음에 선택한 뒤 게시해야 표시됩니다.'}}
function renderMainTagFilters(){const root=$('#bAssetFilters'),tags=[...new Set(assets().flatMap(assetTags))].sort((a,b)=>a.localeCompare(b,'ko'));if(!root)return;if(S.assetTag!=='ALL'&&!tags.includes(S.assetTag))S.assetTag='ALL';root.innerHTML=[`<button type="button" class="banner-tag-filter${S.assetTag==='ALL'?' active':''}" data-b-tag="ALL">전체 ${assets().length}</button>`,...tags.map(tag=>`<button type="button" class="banner-tag-filter${S.assetTag===tag?' active':''}" data-b-tag="${esc(tag)}">#${esc(tag)}</button>`)].join('')}
function render(){renderLive();renderMainTagFilters();renderAssets();renderSelected();renderCampaigns();renderButtons()}
function renderLive(){const r=$('#bLive'),m=S.manifest||{};if(!r)return;if(!m.active){r.innerHTML=`<div class="admin-empty">현재 노출 대상 없음${m.reason?' · '+esc(m.reason):''}</div>`;return}const seen=new Set(),xs=(m.playlist||[]).filter(x=>x?.imageUrl&&!seen.has(x.imageUrl)&&seen.add(x.imageUrl));r.innerHTML=`<small>Manifest ${esc(m.manifestVersion||'-')} · validUntil ${esc(m.validUntil||'-')}</small><div class="b-live">${xs.map(x=>`<div><img src="${esc(x.imageUrl)}" alt="${esc(x.alt||'')}"><small>${esc(x.alt||'대체 텍스트 없음')}</small></div>`).join('')}</div>`}
function renderAssets(){const r=$('#bLibrary'),all=assets(),xs=S.assetTag==='ALL'?all:all.filter(asset=>assetTags(asset).includes(S.assetTag));if(!r)return;r.innerHTML=xs.length?xs.map(a=>{const exposure=mainAssetExposure(a);return `<label class="b-asset${S.selected.has(Number(a.assetId))?' on':''}"><img src="${esc(url(a))}" alt=""><span><b><input data-b-check="${a.assetId}" type="checkbox" ${S.selected.has(Number(a.assetId))?'checked':''}>${esc(a.displayName||a.originalFileName||'Asset '+a.assetId)}</b><br><small>${a.width}×${a.height}</small><br><span class="banner-asset-state ${exposure.kind}">${exposure.label}</span><small class="banner-asset-detail">${esc(exposure.detail)}</small></span></label>`}).join(''):`<div class="admin-empty">${S.assetTag==='ALL'?'등록된 메인 이미지가 없습니다.':`#${esc(S.assetTag)} 분류 이미지가 없습니다.`}</div>`}
function renderSelected(){const r=$('#bSelected'),map=new Map(assets().map(a=>[Number(a.assetId),a])),xs=[...S.selected].map(([id,v])=>({id,v,a:map.get(id)})).filter(x=>x.a);if(!r)return;r.innerHTML=xs.length?xs.map(x=>`<div class="b-item"><img src="${esc(url(x.a))}" alt=""><div><input class="admin-input" data-b-alt="${x.id}" value="${esc(x.v.alt||x.a.defaultAlt||'')}" maxlength="300" placeholder="대체 텍스트"><input class="admin-input" data-b-link="${x.id}" value="${esc(x.v.link||'')}" maxlength="2048" placeholder="https://... 또는 /경로"></div></div>`).join(''):'<div class="admin-empty">이미지를 선택하세요.</div>';const a=xs[0]?.a,u=url(a),alt=xs[0]?.v.alt||a?.defaultAlt||'';['#bannerMainPreviewPc','#bannerMainPreviewMobile'].forEach(q=>{const e=$(q);if(e)e.innerHTML=u?`<img src="${esc(u)}" alt="${esc(alt)}">`:'이미지를 선택하세요.'})}
function renderCampaigns(){const r=$('#bCampaigns'),xs=campaigns();if(!r)return;r.innerHTML=xs.length?xs.map(c=>{const meta=campaignMeta(c.status);return `<div class="b-campaign${Number(c.campaignId)===Number(S.cid)?' on':''}"><span><b>${esc(c.name||'Campaign '+c.campaignId)}</b><br><small><span class="banner-campaign-status ${meta.className}">${meta.label}</span>이미지 ${c.items?.length||0} · 우선순위 ${c.priority}</small></span><button class="admin-btn" data-b-edit="${c.campaignId}">편집</button></div>`}).join(''):'<div class="admin-empty">저장된 메인 노출 묶음이 없습니다.</div>'}
function renderButtons(){const c=current(),s=c?.status||'DRAFT';$('[data-b-save]').disabled=s==='PUBLISHED'||s==='ARCHIVED';$('[data-b-publish]').disabled=s==='PUBLISHED'||s==='ARCHIVED';$('[data-b-pause]').disabled=!c||s!=='PUBLISHED';$('[data-b-archive]').disabled=!c||s==='ARCHIVED';$('[data-b-restore]').disabled=!c||s!=='ARCHIVED';$('[data-b-delete]').disabled=!c||s==='PUBLISHED';msg('#bCampaignStatus',c?`#${c.campaignId} · ${campaignMeta(s).label}${s==='PUBLISHED'?' · 수정 또는 영구 삭제 전에 먼저 일시정지하세요.':''}`:'새 노출 묶음 작성 중 · 저장 전에는 노출되지 않습니다.')}
function mode(){const e=$('#bSchedule');if(e)e.hidden=$('#bMode')?.value!=='SCHEDULED'}
function fill(c={}){$('#bName').value=c.name||'';$('#bPriority').value=c.priority??100;$('#bMode').value=c.scheduleMode||'ALWAYS';$('#bStart').value=String(c.startsAtKst||'').slice(0,16);$('#bEnd').value=String(c.endsAtKst||'').slice(0,16);const days=new Set((c.weekdays||[]).map(Number));$$('#bDays input').forEach(x=>x.checked=days.has(Number(x.value)));$('#bDates').value=(c.specificDates||[]).join(', ');$('#bSlide').value=c.slideIntervalMs??8000;$('#bTransition').value=c.transitionDurationMs??600;S.selected.clear();(c.items||[]).sort((a,b)=>(a.sortOrder||0)-(b.sortOrder||0)).forEach(x=>S.selected.set(Number(x.assetId),{alt:x.alt||'',link:x.clickUrl||''}));mode();render()}
function edit(id){const c=campaigns().find(x=>Number(x.campaignId)===Number(id));if(c){S.cid=Number(id);fill(c)}}
function fresh(){S.cid=0;S.selected.clear();fill({})}
function payload(){const m=$('#bMode').value,days=$$('#bDays input:checked').map(x=>Number(x.value)),dates=String($('#bDates').value||'').split(',').map(x=>x.trim()).filter(Boolean);let i=0;return{name:String($('#bName').value||'').trim(),type:'MAIN',pageCode:'HOME',slotCodes:['MAIN'],priority:Number($('#bPriority').value||100),scheduleMode:m,startsAtKst:m==='SCHEDULED'?$('#bStart').value||null:null,endsAtKst:m==='SCHEDULED'?$('#bEnd').value||null:null,weekdays:m==='SCHEDULED'?days:[],specificDates:m==='SCHEDULED'?dates:[],slideIntervalMs:Number($('#bSlide').value||8000),transitionDurationMs:Number($('#bTransition').value||600),items:[...S.selected].map(([assetId,v])=>({assetId,weight:100,enabled:true,alt:String(v.alt||'').trim(),clickUrl:String(v.link||'').trim()||null,sortOrder:i++,scheduleMode:'INHERIT'}))}}
async function load(force=false){if(!master()||S.busy||(!force&&S.loaded))return;S.busy=true;msg('#bStatus','불러오는 중...');try{await client();const [a,c,m]=await Promise.all([api('asset-list',{includeArchived:false}),api('campaign-list',{includeArchived:true}),api('manifest',{pageCode:'HOME',slotCode:'MAIN'})]);S.assets=a.assets||[];S.campaigns=c.campaigns||[];S.manifest=m||{};S.loaded=true;if(S.cid&&!campaigns().some(x=>Number(x.campaignId)===S.cid))S.cid=0;if(S.cid)fill(current());else render();msg('#bStatus',`메인 이미지 ${assets().length} · 캠페인 ${campaigns().length} · Server Manifest ${m.active?'활성':'비활성'}`,'ok')}catch(e){msg('#bStatus',e.message||String(e),'error')}finally{S.busy=false}}
async function upload(){const button=$('#bUpload'),files=Array.from($('#bFile')?.files||[]),fit=$('#bFit')?.value||'COVER',background=$('#bBackground')?.value||'#111827',base=$('#bUploadName')?.value||'',commonAlt=String($('#bUploadAlt')?.value||'').trim(),tags=normalizeTags($('#bUploadTags')?.value||''),created=[],failures=[];if(!files.length){msg('#bUploadStatus','＋ 추가하기로 이미지를 한 장 이상 선택하세요.','error');return}button.disabled=true;try{for(let index=0;index<files.length;index++){const file=files[index];try{updateQueue('b',index,'변환 중','processing');msg('#bUploadStatus',`${index+1}/${files.length} · ${file.name} 자동 맞춤 중...`);const prepared=await prepareBannerUploadImage(file,{...MAIN_OUTPUT,fit,background});updateQueue('b',index,'업로드 중','processing');const response=await api('upload-prepare',{mimeType:prepared.mimeType,sizeBytes:prepared.sizeBytes,formatCode:FORMAT},true),uploadInfo=response.upload||{};if(uploadInfo.bucket!==BUCKET||uploadInfo.upsert!==false)throw Error('업로드 계약 오류');const cfg=await window.KinojoSupabaseClientCore.ensureConfig(),target=new URL(uploadInfo.uploadUrl),origin=new URL(cfg.url);if(target.origin!==origin.origin||!target.pathname.startsWith(`/storage/v1/object/upload/sign/${BUCKET}/`))throw Error('Signed URL 오류');const put=await fetch(target,{method:'PUT',headers:{'content-type':prepared.mimeType,'x-upsert':'false'},body:prepared.blob});if(!put.ok)throw Error('Storage 업로드 실패 HTTP '+put.status);const done=await api('upload-complete',{objectPath:uploadInfo.objectPath,mimeType:prepared.mimeType,sizeBytes:prepared.sizeBytes,formatCode:FORMAT,displayName:uploadDisplayName(base,file,files.length,tags),originalFileName:String(file.name||'').slice(0,255),defaultAlt:commonAlt||fileStem(file.name)},true);if(done?.image?.activation!=='ASSET_READY'||done?.image?.aspectValid!==true)throw Error('Asset READY 검증 실패');created.push({assetId:Number(done?.asset?.assetId||0),objectPath:uploadInfo.objectPath});updateQueue('b',index,'등록 완료','ok')}catch(error){failures.push(`${file.name}: ${error.message||String(error)}`);updateQueue('b',index,'실패','error')}}S.loaded=false;await load(true);for(const item of created){const asset=S.assets.find(value=>Number(value.assetId)===item.assetId||value.objectPath===item.objectPath);if(asset)S.selected.set(Number(asset.assetId),{alt:asset.defaultAlt||'',link:''})}render();if(created.length){$('#bFile').value='';$('#bUploadName').value='';$('#bUploadAlt').value='';releaseQueueUrls('b');$('#bFileQueue').innerHTML='<div class="admin-empty">업로드한 이미지가 아래 라이브러리와 이번 묶음에 선택되었습니다.</div>'}const summary=`${created.length}개 등록 완료${failures.length?` · ${failures.length}개 실패`:''}`;msg('#bUploadStatus',failures.length?`${summary} · ${failures[0]}`:summary,failures.length?'error':'ok')}catch(error){msg('#bUploadStatus',error.message||String(error),'error')}finally{button.disabled=false}}
async function save(){const c=current(),d=await api(c?'campaign-update':'campaign-create',c?{campaignId:Number(c.campaignId),campaign:payload()}:{campaign:payload()},true),cid=Number(d?.campaign?.campaignId||d?.campaignId||c?.campaignId||0);S.loaded=false;await load(true);if(cid)edit(cid);msg('#bCampaignStatus','저장 완료','ok');return cid}
async function change(action){let c=current(),saved=false;try{if(action==='campaign-publish'&&!c){await save();c=current();saved=true}if(!c)throw Error('캠페인을 먼저 저장하세요.');if(action==='campaign-publish'&&!saved&&c.status!=='PUBLISHED'&&c.status!=='ARCHIVED'){await save();c=current()}await api(action,{campaignId:Number(c.campaignId)},true);S.loaded=false;await load(true);edit(c.campaignId);msg('#bCampaignStatus',{'campaign-publish':'게시 완료','campaign-pause':'일시정지 완료','campaign-archive':'보관 완료','campaign-restore':'복원 완료'}[action],'ok')}catch(e){msg('#bCampaignStatus',e.message||String(e),'error')}}
function confirmPermanentCampaignDelete(c){return new Promise(resolve=>{const old=$('#bannerCampaignDeleteDialog');if(old)old.remove();const modal=document.createElement('div');modal.id='bannerCampaignDeleteDialog';modal.className='banner-delete-modal';modal.setAttribute('role','presentation');modal.innerHTML=`<section class="banner-delete-dialog" role="dialog" aria-modal="true" aria-labelledby="bannerDeleteTitle"><h2 id="bannerDeleteTitle">캠페인을 영구 삭제할까요?</h2><p>캠페인 설정과 연결 항목이 서버에서 즉시 삭제되며 복구할 수 없습니다. 업로드 이미지 원본은 이미지 라이브러리에 남습니다.</p><span class="banner-delete-name">${esc(c.name||'Campaign '+c.campaignId)}</span><label>확인을 위해 위 캠페인 이름을 정확히 입력하세요.<input class="admin-input" data-banner-delete-name autocomplete="off"></label><div class="banner-actions"><button class="admin-btn" data-banner-delete-cancel type="button">취소</button><button class="admin-btn danger" data-banner-delete-confirm type="button" disabled>영구 삭제</button></div></section>`;document.body.appendChild(modal);const input=$('[data-banner-delete-name]',modal),confirmButton=$('[data-banner-delete-confirm]',modal),finish=value=>{document.removeEventListener('keydown',onKey);modal.remove();resolve(value)},onKey=event=>{if(event.key==='Escape')finish(false)};input.addEventListener('input',()=>confirmButton.disabled=input.value!==String(c.name||''));modal.addEventListener('click',event=>{if(event.target===modal||event.target.closest('[data-banner-delete-cancel]'))finish(false);else if(event.target.closest('[data-banner-delete-confirm]')&&!confirmButton.disabled)finish(true)});document.addEventListener('keydown',onKey);input.focus()})}
async function deleteCampaign(){const c=current();if(!c)return;if(c.status==='PUBLISHED'){msg('#bCampaignStatus','게시 중인 캠페인은 먼저 일시정지하세요.','error');return}if(!await confirmPermanentCampaignDelete(c))return;try{msg('#bCampaignStatus','캠페인을 영구 삭제하는 중...');await api('campaign-delete',{campaignId:Number(c.campaignId),expectedName:String(c.name||'')},true);S.cid=0;S.selected.clear();S.loaded=false;await load(true);fresh();msg('#bCampaignStatus',`#${c.campaignId} 캠페인을 영구 삭제했습니다. 이 작업은 복구할 수 없습니다.`,'ok')}catch(error){msg('#bCampaignStatus',error.message||String(error),'error')}}
function check(x){const aid=Number(x.dataset.bCheck),a=assets().find(v=>Number(v.assetId)===aid);if(!a)return;if(x.checked)S.selected.set(aid,{alt:a.defaultAlt||'',link:''});else S.selected.delete(aid);renderAssets();renderSelected()}
shell();guard();const pane=$('[data-admin-pane="images"]');if(pane)new MutationObserver(()=>{if(pane.classList.contains('active')){label();load()}}).observe(pane,{attributes:true,attributeFilter:['class']});const loc=$('#adminCurrentLocation');if(loc)new MutationObserver(label).observe(loc,{childList:true,subtree:true,characterData:true});
document.addEventListener('click',e=>{const t=e.target.closest?.('button');if(!t)return;if(t.matches('[data-admin-tab="images"]')){queueMicrotask(()=>{label();load()});return}if(!t.closest?.('[data-main-banner-admin]'))return;if(t.matches('[data-b-refresh]')){S.loaded=false;load(true)}else if(t.matches('[data-b-new]'))fresh();else if(t.matches('[data-b-edit]'))edit(t.dataset.bEdit);else if(t.matches('[data-b-tag]')){S.assetTag=t.dataset.bTag||'ALL';renderMainTagFilters();renderAssets()}else if(t.matches('[data-b-save]'))save().catch(e=>msg('#bCampaignStatus',e.message,'error'));else if(t.matches('[data-b-publish]'))change('campaign-publish');else if(t.matches('[data-b-pause]'))change('campaign-pause');else if(t.matches('[data-b-archive]'))change('campaign-archive');else if(t.matches('[data-b-restore]'))change('campaign-restore');else if(t.matches('[data-b-delete]'))deleteCampaign();else if(t.id==='bUpload')upload()});
document.addEventListener('change',e=>{const t=e.target;if(!t?.closest?.('[data-main-banner-admin]'))return;if(t.matches('[data-b-check]'))check(t);if(t.id==='bMode')mode();if(t.id==='bFile')renderFileQueue('b',MAIN_OUTPUT);if(t.id==='bFit'){const color=$('#bBackground');if(color)color.disabled=t.value!=='CONTAIN';renderFileQueue('b',MAIN_OUTPUT)}});document.addEventListener('input',e=>{const t=e.target;if(!t?.closest?.('[data-main-banner-admin]'))return;const a=Number(t.dataset?.bAlt),l=Number(t.dataset?.bLink);if(a&&S.selected.has(a))S.selected.get(a).alt=t.value;if(l&&S.selected.has(l))S.selected.get(l).link=t.value});window.addEventListener('hashchange',()=>{if(!guard()&&imageRoute())queueMicrotask(()=>load())});if(imageRoute()&&master())queueMicrotask(()=>load());Object.assign(A,{ensureImageManagementShell:shell,ensureBannerAdminLayoutStyle,loadMainBannerManagement:load,prepareBannerUploadImage,renderBannerFileQueue:renderFileQueue,updateBannerUploadQueue:updateQueue,bannerUploadDisplayName:uploadDisplayName,bannerNormalizeTags:normalizeTags,bannerAssetTags:assetTags,bannerFileStem:fileStem,bannerReleaseQueueUrls:releaseQueueUrls,confirmPermanentCampaignDelete});
})(window.KinojoAdmin);
