const DEFAULT_WEB_APP_URL="https://script.google.com/macros/s/AKfycbztXbGEbiId1yOfa3CVmErivNVi5IUi64qxIQRf8Sm_KduCPieeAKlNRMGyYkKL5iPaYg/exec";
const API_URL=new URLSearchParams(location.search).get("api")||DEFAULT_WEB_APP_URL;
const params=new URLSearchParams(location.search);
const currentId=params.get("id")||"rudra";
const FALLBACK={
  rudra:{info:{sanctuaryId:"rudra",sanctuaryNo:1,sanctuaryName:"심연의 재련: 루드라",shortName:"루드라팟",bossName:"루드라"}},
  bagot:{info:{sanctuaryId:"bagot",sanctuaryNo:2,sanctuaryName:"침식의 정화소",shortName:"바고트팟",bossName:"바고트"}},
  kaldrix:{info:{sanctuaryId:"kaldrix",sanctuaryNo:3,sanctuaryName:"무스펠의 성배",shortName:"칼드릭스팟",bossName:"칼드릭스"}}
};
const CLASS_ICON={"검성":"../hall-of-fame/assets/class_icon_gladiator.png","수호성":"../hall-of-fame/assets/class_icon_templar.png","살성":"../hall-of-fame/assets/class_icon_assassin.png","궁성":"../hall-of-fame/assets/class_icon_ranger.png","정령성":"../hall-of-fame/assets/class_icon_elementalist.png","마도성":"../hall-of-fame/assets/class_icon_sorcerer.png","치유성":"../hall-of-fame/assets/class_icon_cleric.png","호법성":"../hall-of-fame/assets/class_icon_chanter.png"};
let sanctuaryData=null;
function esc(v){return String(v??"").replaceAll("&","&amp;").replaceAll("<","&lt;").replaceAll(">","&gt;").replaceAll('"',"&quot;").replaceAll("'","&#39;")}
function fmt(n){return Number(n||0).toLocaleString("ko-KR")}
function currentFallback(){return FALLBACK[currentId]||FALLBACK.rudra}
function setActiveLinks(){document.querySelectorAll('[data-sanctuary-link]').forEach(a=>{a.classList.toggle('active',a.dataset.sanctuaryLink===currentId)})}
function setupDrawer(){const d=document.getElementById('sideDrawer'),btn=document.getElementById('drawerToggleBtn'),close=document.getElementById('drawerCloseBtn');function open(){document.body.classList.add('drawer-open');d.classList.add('open');d.setAttribute('aria-hidden','false');btn?.classList.add('is-pressed');btn?.setAttribute('aria-expanded','true')}function shut(){document.body.classList.remove('drawer-open');d.classList.remove('open');d.setAttribute('aria-hidden','true');btn?.classList.remove('is-pressed');btn?.setAttribute('aria-expanded','false')}btn?.addEventListener('click',open);close?.addEventListener('click',shut);d?.addEventListener('click',e=>{if(e.target===d)shut()});document.addEventListener('keydown',e=>{if(e.key==='Escape'){shut();closeTip();closeAdmin()}})}
async function loadData(){setActiveLinks();renderSkeleton();try{const url=API_URL+(API_URL.includes('?')?'&':'?')+'action=sanctuary&id='+encodeURIComponent(currentId)+'&t='+Date.now();const res=await fetch(url,{cache:'no-store'});const data=await res.json();if(!data||!data.ok)throw new Error(data?.message||'성역 데이터 로드 실패');sanctuaryData=data;render(data);document.getElementById('syncChip').textContent='업데이트 '+(data.generatedAt||'완료')}catch(err){const f=currentFallback();sanctuaryData={ok:true,info:f.info,summary:{totalCharacters:0,teamCount:0,partyCount:0,averagePower:0},teams:[],waiting:[],tips:['성역 시트 또는 Apps Script 연결 후 실제 데이터가 표시됩니다.'],generatedAt:'대기중'};render(sanctuaryData);document.getElementById('syncChip').textContent='샘플 프레임 표시 중'}}
function renderSkeleton(){document.getElementById('teamList').innerHTML='<div class="loading"><span>성역 파티 데이터를 불러오는 중...</span></div>'}
function render(data){const info=data.info||currentFallback().info;const hero=document.getElementById('sanctuaryHero');hero.className='sanctuary-hero '+esc(info.sanctuaryId||currentId);document.getElementById('heroKicker').textContent='성역 '+(info.sanctuaryNo||'');document.getElementById('heroTitle').textContent=info.sanctuaryName||info.shortName||'성역';document.getElementById('heroSub').textContent='Boss. '+(info.bossName||'-')+' · '+(info.shortName||'');renderSummary(data);renderTeams(data.teams||[]);renderWaiting(data.waiting||[]);document.getElementById('tipTitle').textContent=(info.shortName||'성역')+' 공략 팁';document.getElementById('tipBody').innerHTML=(data.tips||[]).map(t=>'<div class="tip-line">'+esc(t)+'</div>').join('')||'<div class="tip-line">공략 팁이 준비 중입니다.</div>';setupSliders()}
function renderSummary(data){const s=data.summary||{};document.getElementById('summaryGrid').innerHTML=[
  summaryCard(fmt(s.totalCharacters),'총 등록 캐릭터'),summaryCard(fmt(s.teamCount),'운영 팀'),summaryCard(fmt(s.partyCount),'운영 파티'),summaryCard(fmt(s.averagePower),'평균 전투력'),'<button class="summary-card summary-tip" id="tipOpenBtn" type="button"><div class="summary-num">💡</div><div class="summary-label">공략 팁 보기</div></button>'
].join('');document.getElementById('tipOpenBtn')?.addEventListener('click',openTip)}
function summaryCard(num,label){return '<div class="summary-card"><div class="summary-num">'+esc(num)+'</div><div class="summary-label">'+esc(label)+'</div></div>'}
function renderTeams(teams){const root=document.getElementById('teamList');if(!teams.length){root.innerHTML='<div class="empty-main">아직 표시할 팀 데이터가 없습니다.<br>성역 시트에 1-1, 1-2 같은 파티 마커를 넣으면 자동 인식됩니다.</div>';return}root.innerHTML=teams.map(teamHtml).join('')}
function teamHtml(t){const custom=t.nameMode==='manual';const style=custom&&t.customColor?' style="--custom-color:'+esc(t.customColor)+'"':'';return '<article class="team-card" data-team="'+esc(t.teamId)+'"><header class="team-head"><div class="team-title-wrap"><div class="team-name '+(custom?'custom':'')+'"'+style+'><span>'+esc(t.teamName||('TEAM '+t.teamNo))+'</span><span class="team-badge">'+(custom?'CUSTOM':'AUTO')+'</span></div><div class="team-meta">'+fmt(t.characterCount)+'캐릭터 · '+fmt(t.partyCount)+'파티 · 평균 '+fmt(t.averagePower)+'</div></div><div class="leader">👑 '+esc(t.leaderCharacter||'대표 미설정')+'</div></header><div class="party-slider-shell"><button class="slide-btn left" type="button" aria-label="왼쪽으로 이동">‹</button><div class="party-track">'+(t.parties||[]).map(partyHtml).join('')+'</div><button class="slide-btn right" type="button" aria-label="오른쪽으로 이동">›</button></div></article>'}
function partyHtml(p){return '<section class="party-card"><div class="party-head"><div class="party-title">'+esc(p.partyNo)+'파티</div><div class="party-count">'+fmt(p.filled)+' / '+fmt(p.capacity)+'</div></div><div class="slot-grid">'+(p.slots||[]).map(slotHtml).join('')+'</div></section>'}
function slotHtml(s){if(!s.name)return '<div class="empty-slot"><strong>+ '+esc(s.vacancyText||'파티 인원 모집중')+'</strong><span>대기자 명단에서 추가 가능</span></div>';const icon=CLASS_ICON[s.className]?'<img src="'+CLASS_ICON[s.className]+'" alt="" width="15" height="15"> ':'';return '<div class="char-card" draggable="false"><div class="char-name">'+esc(s.name)+'</div><div class="char-meta">'+icon+esc(s.className||'직업 미확인')+' · '+fmt(s.power)+'</div></div>'}
function renderWaiting(waiting){const root=document.getElementById('waitingSection');if(!waiting||!waiting.length){root.innerHTML='<h2 class="waiting-title">대기자 명단</h2><div class="waiting-list"><span class="waiting-chip">미배치 캐릭터 없음</span></div>';return}root.innerHTML='<h2 class="waiting-title">대기자 명단</h2><div class="waiting-list">'+waiting.slice(0,80).map(x=>'<span class="waiting-chip">'+esc(x.name)+'</span>').join('')+(waiting.length>80?'<span class="waiting-chip">+'+(waiting.length-80)+'명</span>':'')+'</div>'}
function setupSliders(){document.querySelectorAll('.party-slider-shell').forEach(shell=>{const track=shell.querySelector('.party-track'),left=shell.querySelector('.slide-btn.left'),right=shell.querySelector('.slide-btn.right');function update(){const max=track.scrollWidth-track.clientWidth;left.classList.toggle('show',track.scrollLeft>8);right.classList.toggle('show',max>8&&track.scrollLeft<max-8)}left.onclick=()=>track.scrollBy({left:-Math.min(330,track.clientWidth*.82),behavior:'smooth'});right.onclick=()=>track.scrollBy({left:Math.min(330,track.clientWidth*.82),behavior:'smooth'});track.addEventListener('scroll',update,{passive:true});window.addEventListener('resize',update);setTimeout(update,50)})}
function openTip(){document.getElementById('tipPanel')?.classList.add('open');document.getElementById('tipPanel')?.setAttribute('aria-hidden','false')}function closeTip(){document.getElementById('tipPanel')?.classList.remove('open');document.getElementById('tipPanel')?.setAttribute('aria-hidden','true')}function openAdmin(){document.getElementById('adminCodeModal')?.classList.add('open');document.getElementById('adminCodeModal')?.setAttribute('aria-hidden','false')}function closeAdmin(){document.getElementById('adminCodeModal')?.classList.remove('open');document.getElementById('adminCodeModal')?.setAttribute('aria-hidden','true')}
document.getElementById('tipCloseBtn')?.addEventListener('click',closeTip);document.getElementById('tipPanel')?.addEventListener('click',e=>{if(e.target.id==='tipPanel')closeTip()});document.getElementById('editModeBtn')?.addEventListener('click',openAdmin);document.getElementById('adminCodeCloseBtn')?.addEventListener('click',closeAdmin);document.getElementById('adminCodeModal')?.addEventListener('click',e=>{if(e.target.id==='adminCodeModal')closeAdmin()});setupDrawer();loadData();
