-- Exact command layers v449-v453 from read-only catalog, 2026-09-09. No operational data.
create table private.sanctuary_management_balance_proposals_v451 (
 proposal_id bigint generated by default as identity,
 team_id bigint,
 actor_member_id bigint,
 team_revision bigint,
 token_hash text,
 stable_seed text,
 candidate_hash text,
 composition_hash text,
 lock_overrides jsonb default '[]'::jsonb,
 assignments jsonb default '[]'::jsonb,
 excluded jsonb default '[]'::jsonb,
 before_averages jsonb default '[]'::jsonb,
 after_averages jsonb default '[]'::jsonb,
 expires_at timestamp with time zone,
 consumed_at timestamp with time zone,
 consumed_request_key text,
 created_at timestamp with time zone default clock_timestamp()
);
CREATE OR REPLACE FUNCTION public.kinojo_sanctuary_management_command_v449(p_credential text, p_request_key text, p_action text, p_payload jsonb, p_expected_revision bigint DEFAULT NULL::bigint)
 RETURNS jsonb
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO ''
AS $function$
declare
  v_action text := upper(btrim(coalesce(p_action, '')));
  v_rules_version integer := coalesce(nullif(p_payload->>'compositionRulesVersion', '')::integer, 0);
  v_response jsonb;
  v_actor jsonb;
  v_actor_id bigint;
  v_team_id bigint;
  v_force_id bigint;
  v_party_id bigint;
  v_force_item jsonb;
  v_rule_item jsonb;
  v_force_no integer;
  v_scope_type text;
  v_rule_type text;
  v_party_no integer;
  v_minimum_count integer;
  v_power_threshold integer;
begin
  if v_action <> 'SAVE_COMPOSITION' then
    return public.kinojo_sanctuary_management_command_v446(p_credential, p_request_key, p_action, p_payload, p_expected_revision)
      || jsonb_build_object('apiVersion', 1.9, 'schemaVersion', 449, 'databaseContract', 449);
  end if;

  if v_rules_version not in (0, 1) then
    raise exception '포스 구성 조건 형식을 다시 확인해 주세요.' using errcode = 'P0001';
  end if;
  if v_rules_version = 1 and exists (
    select 1
    from jsonb_array_elements(coalesce(p_payload->'composition', '[]'::jsonb)) force_source(force_item)
    where jsonb_typeof(coalesce(force_item->'requirements', '[]'::jsonb)) <> 'array'
      or jsonb_array_length(coalesce(force_item->'requirements', '[]'::jsonb)) > 6
      or exists (
        select 1
        from jsonb_array_elements(coalesce(force_item->'requirements', '[]'::jsonb)) rule_source(rule_item)
        where upper(coalesce(rule_item->>'scopeType', '')) not in ('FORCE', 'PARTY')
          or upper(coalesce(rule_item->>'ruleType', '')) not in ('MAIN_MIN', 'POWER_MIN')
          or nullif(rule_item->>'minimumCount', '')::integer not between 1 and case when upper(rule_item->>'scopeType') = 'PARTY' then 5 else 10 end
          or (upper(rule_item->>'scopeType') = 'FORCE' and rule_item->>'partyNo' is not null)
          or (upper(rule_item->>'scopeType') = 'PARTY' and nullif(rule_item->>'partyNo', '')::integer not in (1, 2))
          or (upper(rule_item->>'ruleType') = 'MAIN_MIN' and rule_item->>'powerThreshold' is not null)
          or (upper(rule_item->>'ruleType') = 'POWER_MIN' and nullif(rule_item->>'powerThreshold', '')::integer not between 1000 and 1000000000)
      )
      or (
        select count(*) <> count(distinct upper(rule_item->>'scopeType') || ':' || coalesce(rule_item->>'partyNo', '0') || ':' || upper(rule_item->>'ruleType'))
        from jsonb_array_elements(coalesce(force_item->'requirements', '[]'::jsonb)) rule_source(rule_item)
      )
  ) then
    raise exception '본캐·전투력 배치 조건을 다시 확인해 주세요.' using errcode = 'P0001';
  end if;

  v_response := public.kinojo_sanctuary_management_command_v446(
    p_credential, p_request_key, p_action, p_payload, p_expected_revision
  );
  v_team_id := nullif(v_response->>'teamId', '')::bigint;
  if v_rules_version = 1 and coalesce((v_response->>'replayed')::boolean, false) is not true then
    v_actor := private.kinojo_sm_actor_v412(p_credential);
    v_actor_id := nullif(v_actor->>'memberId', '')::bigint;
    delete from private.sanctuary_management_composition_rules_v449 where team_id = v_team_id;

    for v_force_item, v_force_no in
      select force_item, ordinality::integer
      from jsonb_array_elements(coalesce(p_payload->'composition', '[]'::jsonb))
        with ordinality force_source(force_item, ordinality)
    loop
      select force.force_id into strict v_force_id
      from private.sanctuary_management_forces_v412 force
      where force.team_id = v_team_id and force.force_no = v_force_no;

      for v_rule_item in
        select rule_item from jsonb_array_elements(coalesce(v_force_item->'requirements', '[]'::jsonb)) rule_source(rule_item)
      loop
        v_scope_type := upper(v_rule_item->>'scopeType');
        v_rule_type := upper(v_rule_item->>'ruleType');
        v_party_no := nullif(v_rule_item->>'partyNo', '')::integer;
        v_minimum_count := nullif(v_rule_item->>'minimumCount', '')::integer;
        v_power_threshold := nullif(v_rule_item->>'powerThreshold', '')::integer;
        v_party_id := null;
        if v_scope_type = 'PARTY' then
          select party.party_id into strict v_party_id
          from private.sanctuary_management_parties_v412 party
          where party.force_id = v_force_id and party.party_no = v_party_no;
        end if;
        insert into private.sanctuary_management_composition_rules_v449(
          team_id, force_id, party_id, scope_type, rule_type, minimum_count,
          power_threshold, created_by_member_id, updated_by_member_id
        ) values (
          v_team_id, v_force_id, v_party_id, v_scope_type, v_rule_type, v_minimum_count,
          case when v_rule_type = 'POWER_MIN' then v_power_threshold else null end,
          v_actor_id, v_actor_id
        );
      end loop;
    end loop;
  end if;
  return v_response || jsonb_build_object(
    'apiVersion', 1.9,
    'schemaVersion', 449,
    'databaseContract', 449,
    'compositionRulesVersion', v_rules_version
  );
end
$function$;
CREATE OR REPLACE FUNCTION public.kinojo_sanctuary_management_command_v451(p_credential text, p_request_key text, p_action text, p_payload jsonb, p_expected_revision bigint DEFAULT NULL::bigint)
 RETURNS jsonb
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO ''
AS $function$
declare
  v_action text := upper(btrim(coalesce(p_action, '')));
  v_actor jsonb;
  v_actor_id bigint;
  v_hash text;
  v_existing private.sanctuary_management_commands_v412%rowtype;
  v_team private.sanctuary_management_teams_v412%rowtype;
  v_team_id bigint := nullif(p_payload->>'teamId', '')::bigint;
  v_proposal private.sanctuary_management_balance_proposals_v451%rowtype;
  v_proposal_token text := btrim(coalesce(p_payload->>'balanceProposalToken', ''));
  v_response jsonb;
  v_before_locks jsonb;
  v_after_locks jsonb;
  v_force_item jsonb;
  v_slot_item jsonb;
  v_assignment jsonb;
  v_force_id bigint;
  v_slot_id bigint;
  v_force_no integer;
  v_locked boolean;
  v_batch_id bigint;
  v_pending integer;
  v_applied integer;
  v_rejected integer;
  v_cancelled integer;
begin
  if v_action <> 'SAVE_COMPOSITION' then
    if v_action = 'SET_SLOT' and exists (
      select 1 from private.sanctuary_management_slots_v412 slot
      join private.sanctuary_management_parties_v412 party on party.party_id = slot.party_id
      where slot.team_id = v_team_id and slot.force_id = nullif(p_payload->>'forceId', '')::bigint
        and party.party_no = nullif(p_payload->>'partyNo', '')::integer
        and slot.slot_no = nullif(p_payload->>'slotNo', '')::integer and slot.placement_locked
    ) then raise exception '배치 잠금된 슬롯입니다. 잠금을 해제한 뒤 변경해 주세요.' using errcode = 'P0001'; end if;
    if v_action = 'MOVE_SLOT' and exists (
      select 1 from private.sanctuary_management_slots_v412
      where slot_id in (nullif(p_payload->>'fromSlotId', '')::bigint, nullif(p_payload->>'toSlotId', '')::bigint)
        and placement_locked
    ) then raise exception '배치 잠금된 카드는 이동하거나 교환할 수 없습니다.' using errcode = 'P0001'; end if;
    v_response := public.kinojo_sanctuary_management_command_v450(
      p_credential, p_request_key, v_action, p_payload, p_expected_revision
    );
    return v_response || jsonb_build_object('apiVersion', 2.1, 'schemaVersion', 451, 'databaseContract', 451);
  end if;

  if exists (
    select 1 from jsonb_array_elements(coalesce(p_payload->'composition', '[]'::jsonb)) force_source(force_item)
    cross join lateral jsonb_array_elements(coalesce(force_item->'slots', '[]'::jsonb)) slot_source(slot_item)
    where lower(coalesce(slot_item->>'placementLocked', 'false')) not in ('true', 'false')
  ) then raise exception '배치 잠금 상태를 다시 확인해 주세요.' using errcode = 'P0001'; end if;

  v_actor := private.kinojo_sm_actor_v412(p_credential);
  v_actor_id := nullif(v_actor->>'memberId', '')::bigint;
  if v_actor_id is null then raise exception '로그인 후 팀을 저장해 주세요.' using errcode = 'P0001'; end if;
  v_hash := encode(sha256(convert_to(v_action || ':' || coalesce(p_payload, '{}'::jsonb)::text, 'UTF8')), 'hex');
  perform pg_advisory_xact_lock(hashtextextended('sanctuary-management:' || v_actor_id || ':' || btrim(coalesce(p_request_key, '')), 451));
  select * into v_existing from private.sanctuary_management_commands_v412
  where actor_member_id = v_actor_id and request_key = btrim(coalesce(p_request_key, ''));
  if v_existing.command_id is not null then
    if v_existing.action <> v_action or v_existing.request_hash <> v_hash then
      raise exception '같은 요청 키가 다른 작업에 사용되었습니다.' using errcode = 'P0001';
    end if;
    v_response := public.kinojo_sanctuary_management_command_v450(
      p_credential, p_request_key, v_action, p_payload, p_expected_revision
    );
    return v_response || jsonb_build_object('replayed', true, 'apiVersion', 2.1, 'schemaVersion', 451, 'databaseContract', 451);
  end if;

  if v_team_id is not null then
    select * into v_team from private.sanctuary_management_teams_v412 where team_id = v_team_id for update;
    if v_team.team_id is null or not private.kinojo_sm_can_manage_team_v412(v_actor, v_team_id) then
      raise exception '이 팀을 편집할 권한이 없습니다.' using errcode = 'P0001';
    end if;
    if p_expected_revision is null or v_team.revision <> p_expected_revision then
      raise exception '다른 사용자가 먼저 팀을 수정했습니다. 새로고침 후 다시 시도해 주세요.' using errcode = '40001';
    end if;
    perform private.kinojo_sm_assert_lease_v433(v_actor_id, v_team_id, p_payload->>'leaseToken');
    if exists (
      select 1
      from private.sanctuary_management_slots_v412 slot
      join private.sanctuary_management_parties_v412 party on party.party_id = slot.party_id
      where slot.team_id = v_team_id and slot.placement_locked
        and not exists (
          select 1
          from jsonb_array_elements(coalesce(p_payload->'composition', '[]'::jsonb)) force_source(force_item)
          cross join lateral jsonb_array_elements(coalesce(force_item->'slots', '[]'::jsonb)) slot_source(slot_item)
          where nullif(force_item->>'sourceForceId', '')::bigint = slot.force_id
            and nullif(slot_item->>'partyNo', '')::integer = party.party_no
            and nullif(slot_item->>'slotNo', '')::integer = slot.slot_no
            and upper(coalesce(slot_item->>'assignmentKind', 'ACTUAL_CHARACTER')) = slot.assignment_kind
            and (
              slot.assignment_kind = 'RANDOM_ALT' and nullif(slot_item->>'mainCharacterId', '')::bigint = slot.owner_root_character_id
              or slot.assignment_kind = 'ACTUAL_CHARACTER' and nullif(slot_item->>'characterId', '')::bigint = slot.character_id
            )
        )
    ) then raise exception '배치 잠금된 카드는 잠금을 해제하기 전까지 위치와 캐릭터를 유지해야 합니다.' using errcode = 'P0001'; end if;
  end if;

  if v_proposal_token <> '' then
    if v_team_id is null then raise exception '새 팀에는 균형 배치 제안 토큰을 사용할 수 없습니다.' using errcode = 'P0001'; end if;
    select * into v_proposal
    from private.sanctuary_management_balance_proposals_v451
    where token_hash = encode(sha256(convert_to(v_proposal_token, 'UTF8')), 'hex') for update;
    if v_proposal.proposal_id is null or v_proposal.team_id <> v_team_id or v_proposal.actor_member_id <> v_actor_id then
      raise exception '균형 배치 제안을 다시 만들어 주세요.' using errcode = 'P0001';
    end if;
    if v_proposal.consumed_at is not null then raise exception '이미 저장에 사용한 균형 배치 제안입니다.' using errcode = 'P0001'; end if;
    if v_proposal.expires_at <= clock_timestamp() then raise exception '균형 배치 제안이 만료되었습니다. 다시 계산해 주세요.' using errcode = '40001'; end if;
    if v_proposal.team_revision <> p_expected_revision
       or v_proposal.candidate_hash <> private.kinojo_sm_balance_candidate_hash_v451(v_team_id, v_proposal.lock_overrides) then
      raise exception '지원자 또는 편성 상태가 바뀌었습니다. 새로고침 후 균형 배치를 다시 계산해 주세요.' using errcode = '40001';
    end if;
    if v_proposal.composition_hash <> private.kinojo_sm_composition_hash_v451(p_payload->'composition') then
      raise exception '균형 배치 제안 이후 편성안이 바뀌었습니다. 제안을 다시 적용해 주세요.' using errcode = '40001';
    end if;
  end if;

  if v_team_id is not null then
    select coalesce(jsonb_agg(jsonb_build_object('slotId', slot_id, 'locked', placement_locked) order by slot_id), '[]'::jsonb)
    into v_before_locks from private.sanctuary_management_slots_v412 where team_id = v_team_id;
    update private.sanctuary_management_slots_v412 set placement_locked = false where team_id = v_team_id and placement_locked;
  end if;

  v_response := public.kinojo_sanctuary_management_command_v450(
    p_credential, p_request_key, v_action, p_payload, p_expected_revision
  );
  v_team_id := nullif(v_response->>'teamId', '')::bigint;
  if coalesce((v_response->>'replayed')::boolean, false) then
    return v_response || jsonb_build_object('apiVersion', 2.1, 'schemaVersion', 451, 'databaseContract', 451);
  end if;

  for v_force_item, v_force_no in
    select force_item, ordinality::integer
    from jsonb_array_elements(coalesce(p_payload->'composition', '[]'::jsonb)) with ordinality source(force_item, ordinality)
  loop
    select force_id into strict v_force_id from private.sanctuary_management_forces_v412
    where team_id = v_team_id and force_no = v_force_no;
    for v_slot_item in select slot_item from jsonb_array_elements(coalesce(v_force_item->'slots', '[]'::jsonb)) source(slot_item) loop
      v_locked := coalesce((v_slot_item->>'placementLocked')::boolean, false);
      select slot.slot_id into strict v_slot_id
      from private.sanctuary_management_slots_v412 slot
      join private.sanctuary_management_parties_v412 party on party.party_id = slot.party_id
      where slot.force_id = v_force_id
        and party.party_no = nullif(v_slot_item->>'partyNo', '')::integer
        and slot.slot_no = nullif(v_slot_item->>'slotNo', '')::integer;
      if v_locked and not exists (
        select 1 from private.sanctuary_management_slots_v412
        where slot_id = v_slot_id and (character_id is not null or assignment_kind = 'RANDOM_ALT')
      ) then raise exception '빈 슬롯은 배치 잠금할 수 없습니다.' using errcode = 'P0001'; end if;
      update private.sanctuary_management_slots_v412
      set placement_locked = v_locked, revision = revision + case when placement_locked is distinct from v_locked then 1 else 0 end,
          updated_at = case when placement_locked is distinct from v_locked then clock_timestamp() else updated_at end
      where slot_id = v_slot_id;
    end loop;
  end loop;

  if v_proposal.proposal_id is not null then
    for v_assignment in select item from jsonb_array_elements(v_proposal.assignments) source(item) loop
      v_slot_id := nullif(v_assignment->>'slotId', '')::bigint;
      if not exists (
        select 1 from private.sanctuary_management_slots_v412 slot
        where slot.slot_id = v_slot_id and slot.team_id = v_team_id
          and slot.force_id = nullif(v_assignment->>'forceId', '')::bigint
          and slot.character_id = nullif(v_assignment->>'characterId', '')::bigint
      ) then raise exception '균형 배치 저장 결과가 제안과 일치하지 않습니다.' using errcode = '40001'; end if;
      update private.sanctuary_management_support_items_v412 set
        status = 'APPLIED', applied_slot_id = v_slot_id, result_code = 'BALANCE_APPLIED',
        result_message = '전투력 균형 배치 제안으로 클래스 조건에 맞는 슬롯에 배치했습니다.', updated_at = clock_timestamp()
      where support_item_id = nullif(v_assignment->>'supportItemId', '')::bigint
        and status = 'PENDING' and force_id = nullif(v_assignment->>'forceId', '')::bigint;
      if not found then raise exception '지원 후보 상태가 바뀌었습니다. 균형 배치를 다시 계산해 주세요.' using errcode = '40001'; end if;
    end loop;
    for v_batch_id in select distinct nullif(item->>'supportBatchId', '')::bigint from jsonb_array_elements(v_proposal.assignments) source(item) loop
      select count(*) filter(where status = 'PENDING')::integer,
             count(*) filter(where status = 'APPLIED')::integer,
             count(*) filter(where status = 'REJECTED')::integer,
             count(*) filter(where status = 'CANCELLED')::integer
      into v_pending, v_applied, v_rejected, v_cancelled
      from private.sanctuary_management_support_items_v412 where support_batch_id = v_batch_id;
      update private.sanctuary_management_support_batches_v412 set
        status = case when v_pending > 0 then 'PARTIAL'
          when v_applied > 0 and (v_rejected > 0 or v_cancelled > 0) then 'PARTIAL'
          when v_applied > 0 then 'APPLIED' else 'REJECTED' end,
        decision_member_id = v_actor_id, decision_note = '균형 배치 저장',
        decided_at = coalesce(decided_at, clock_timestamp()), updated_at = clock_timestamp()
      where support_batch_id = v_batch_id;
    end loop;
    update private.sanctuary_management_balance_proposals_v451 set
      consumed_at = clock_timestamp(), consumed_request_key = btrim(p_request_key)
    where proposal_id = v_proposal.proposal_id;
    perform private.kinojo_sm_audit_v412(v_actor_id, v_team_id, 'TEAM', v_team_id, 'BALANCE_APPLY',
      jsonb_build_object('proposalId', v_proposal.proposal_id, 'beforeAverages', v_proposal.before_averages),
      jsonb_build_object('assignmentCount', jsonb_array_length(v_proposal.assignments), 'afterAverages', v_proposal.after_averages), p_request_key);
  end if;

  select coalesce(jsonb_agg(jsonb_build_object('slotId', slot_id, 'locked', placement_locked) order by slot_id), '[]'::jsonb)
  into v_after_locks from private.sanctuary_management_slots_v412 where team_id = v_team_id;
  if v_before_locks is distinct from v_after_locks then
    perform private.kinojo_sm_audit_v412(v_actor_id, v_team_id, 'TEAM', v_team_id, 'PLACEMENT_LOCK_SAVE', v_before_locks, v_after_locks, p_request_key);
  end if;
  perform private.kinojo_sm_recompute_status_v450(v_team_id);
  return v_response || jsonb_build_object(
    'placementLockedCount', (select count(*) from private.sanctuary_management_slots_v412 where team_id = v_team_id and placement_locked),
    'balanceApplied', v_proposal.proposal_id is not null,
    'balanceAssignmentCount', case when v_proposal.proposal_id is null then 0 else jsonb_array_length(v_proposal.assignments) end,
    'apiVersion', 2.1, 'schemaVersion', 451, 'databaseContract', 451, 'slotContractVersion', 2
  );
end
$function$;
CREATE OR REPLACE FUNCTION public.kinojo_sanctuary_management_command_v453(p_credential text, p_request_key text, p_action text, p_payload jsonb, p_expected_revision bigint DEFAULT NULL::bigint)
 RETURNS jsonb
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO ''
AS $function$
declare
  v_action text := upper(btrim(coalesce(p_action, '')));
  v_payload jsonb := coalesce(p_payload, '{}'::jsonb);
  v_delegate jsonb;
  v_composition jsonb;
  v_response jsonb;
  v_team_id bigint;
  v_force_item jsonb;
  v_slot_item jsonb;
  v_force_no integer;
  v_force_id bigint;
  v_slot_id bigint;
  v_required_class text;
  v_main_character_id bigint;
  v_owner record;
  v_occupied_count integer;
begin
  if v_action <> 'SAVE_COMPOSITION' then
    v_response := public.kinojo_sanctuary_management_command_v452(
      p_credential, p_request_key, p_action, v_payload, p_expected_revision
    );
    return v_response || jsonb_build_object(
      'apiVersion', 2.2, 'schemaVersion', 453, 'databaseContract', 453
    );
  end if;

  if exists (
    select 1
    from jsonb_array_elements(coalesce(v_payload->'composition', '[]'::jsonb)) force_source(force_item)
    cross join lateral jsonb_array_elements(coalesce(force_item->'slots', '[]'::jsonb)) slot_source(slot_item)
    where upper(coalesce(slot_item->>'assignmentKind', 'ACTUAL_CHARACTER')) = 'RANDOM_ALT'
      and (
        slot_item->>'characterId' is not null
        or nullif(slot_item->>'mainCharacterId', '')::bigint is null
        or upper(coalesce(slot_item->>'requiredClassCode', 'ALL')) not in (
          'ALL', 'TEMPLAR', 'GLADIATOR', 'ASSASSIN', 'RANGER', 'SORCERER',
          'ELEMENTALIST', 'CLERIC', 'CHANTER', 'FIGHTER'
        )
      )
  ) then
    raise exception '랜덤 부캐의 본캐와 클래스를 다시 확인해 주세요.' using errcode = 'P0001';
  end if;

  -- v452 remains the atomic composer authority. Random reservations are sent
  -- through it as typed empty slots, then restored in this same transaction.
  -- This avoids fabricating a character identity while preserving revision,
  -- lease, idempotency and all existing composition-rule validation.
  select jsonb_agg(
    (force_item - 'slots') || jsonb_build_object('slots', coalesce((
      select jsonb_agg(
        case
          when upper(coalesce(slot_item->>'assignmentKind', 'ACTUAL_CHARACTER')) = 'RANDOM_ALT'
            then (slot_item - 'mainCharacterId') || jsonb_build_object(
              'assignmentKind', 'ACTUAL_CHARACTER', 'characterId', null
            )
          else slot_item
        end
        order by slot_ordinality
      )
      from jsonb_array_elements(coalesce(force_item->'slots', '[]'::jsonb))
        with ordinality slots(slot_item, slot_ordinality)
    ), '[]'::jsonb))
    order by force_ordinality
  ) into v_composition
  from jsonb_array_elements(coalesce(v_payload->'composition', '[]'::jsonb))
    with ordinality forces(force_item, force_ordinality);

  v_delegate := (v_payload - 'composition') || jsonb_build_object(
    'composition', coalesce(v_composition, '[]'::jsonb)
  );
  v_response := public.kinojo_sanctuary_management_command_v452(
    p_credential, p_request_key, v_action, v_delegate, p_expected_revision
  );
  v_team_id := nullif(v_response->>'teamId', '')::bigint;

  for v_force_item, v_force_no in
    select force_item, ordinality::integer
    from jsonb_array_elements(coalesce(v_payload->'composition', '[]'::jsonb))
      with ordinality source(force_item, ordinality)
  loop
    select force_id into strict v_force_id
    from private.sanctuary_management_forces_v412
    where team_id = v_team_id and force_no = v_force_no;

    for v_slot_item in
      select slot_item
      from jsonb_array_elements(coalesce(v_force_item->'slots', '[]'::jsonb)) source(slot_item)
      where upper(coalesce(slot_item->>'assignmentKind', 'ACTUAL_CHARACTER')) = 'RANDOM_ALT'
    loop
      v_required_class := upper(coalesce(v_slot_item->>'requiredClassCode', 'ALL'));
      v_main_character_id := nullif(v_slot_item->>'mainCharacterId', '')::bigint;
      select * into v_owner from private.kinojo_sm_resolve_character_owner_v412(v_main_character_id);
      if v_owner.character_id is null
         or v_owner.root_character_id is distinct from v_main_character_id
         or v_owner.owner_member_id is null then
        raise exception '랜덤 부캐의 본캐 소유 관계를 확인할 수 없습니다.' using errcode = 'P0001';
      end if;

      select slot.slot_id into strict v_slot_id
      from private.sanctuary_management_slots_v412 slot
      join private.sanctuary_management_parties_v412 party on party.party_id = slot.party_id
      where slot.force_id = v_force_id
        and party.party_no = nullif(v_slot_item->>'partyNo', '')::integer
        and slot.slot_no = nullif(v_slot_item->>'slotNo', '')::integer;

      update private.sanctuary_management_slots_v412 set
        required_class_code = v_required_class,
        assignment_kind = 'RANDOM_ALT',
        character_id = null,
        owner_member_id = v_owner.owner_member_id,
        owner_root_character_id = v_owner.root_character_id,
        character_relation = 'ALT'
      where slot_id = v_slot_id;
    end loop;
  end loop;

  perform private.kinojo_sm_recompute_status_v450(v_team_id);
  select count(*)::integer into v_occupied_count
  from private.sanctuary_management_slots_v412
  where team_id = v_team_id and (character_id is not null or assignment_kind = 'RANDOM_ALT');

  return v_response || jsonb_build_object(
    'occupiedCount', v_occupied_count,
    'apiVersion', 2.2, 'schemaVersion', 453, 'databaseContract', 453,
    'randomAltClassReservation', true
  );
end
$function$;
CREATE OR REPLACE FUNCTION public.kinojo_sanctuary_management_command_v450(p_credential text, p_request_key text, p_action text, p_payload jsonb, p_expected_revision bigint DEFAULT NULL::bigint)
 RETURNS jsonb
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO ''
AS $function$
declare
  v_action text := upper(btrim(coalesce(p_action, '')));
  v_actor jsonb;
  v_actor_id bigint;
  v_hash text;
  v_existing private.sanctuary_management_commands_v412%rowtype;
  v_response jsonb;
  v_team_id bigint;
  v_force_id bigint;
  v_slot_id bigint;
  v_force_item jsonb;
  v_slot_item jsonb;
  v_force_no integer;
  v_required_class text;
  v_assignment_kind text;
  v_character_id bigint;
  v_main_character_id bigint;
  v_owner record;
  v_occupied_count integer;
begin
  if v_action in ('SUBMIT_SUPPORT', 'DECIDE_SUPPORT') then
    return private.kinojo_sm_support_command_v450(p_credential, p_request_key, v_action, p_payload);
  end if;
  if v_action <> 'SAVE_COMPOSITION' then
    v_response := public.kinojo_sanctuary_management_command_v449(
      p_credential, p_request_key, v_action, p_payload, p_expected_revision
    );
    v_team_id := nullif(v_response->>'teamId', '')::bigint;
    if v_team_id is not null and v_action in ('SET_SLOT', 'MOVE_SLOT') and coalesce((v_response->>'replayed')::boolean, false) is not true then
      perform private.kinojo_sm_recompute_status_v450(v_team_id);
    end if;
    return v_response || jsonb_build_object('apiVersion', 2.0, 'schemaVersion', 450, 'databaseContract', 450);
  end if;

  if exists (
    select 1
    from jsonb_array_elements(coalesce(p_payload->'composition', '[]'::jsonb)) force_source(force_item)
    cross join lateral jsonb_array_elements(coalesce(force_item->'slots', '[]'::jsonb)) slot_source(slot_item)
    where upper(coalesce(slot_item->>'requiredClassCode', 'ALL')) not in (
      'ALL', 'TEMPLAR', 'GLADIATOR', 'ASSASSIN', 'RANGER', 'SORCERER',
      'ELEMENTALIST', 'CLERIC', 'CHANTER', 'FIGHTER'
    )
      or upper(coalesce(slot_item->>'assignmentKind', 'ACTUAL_CHARACTER')) not in ('ACTUAL_CHARACTER', 'RANDOM_ALT')
      or (
        upper(coalesce(slot_item->>'assignmentKind', 'ACTUAL_CHARACTER')) = 'RANDOM_ALT'
        and (
          slot_item->>'characterId' is not null
          or nullif(slot_item->>'mainCharacterId', '')::bigint is null
          or upper(coalesce(slot_item->>'requiredClassCode', 'ALL')) <> 'ALL'
        )
      )
  ) then
    raise exception '슬롯 클래스 제한 또는 랜덤 부캐 편성 형식을 다시 확인해 주세요.' using errcode = 'P0001';
  end if;

  v_actor := private.kinojo_sm_actor_v412(p_credential);
  v_actor_id := nullif(v_actor->>'memberId', '')::bigint;
  if v_actor_id is null then raise exception '로그인 후 팀을 저장해 주세요.' using errcode = 'P0001'; end if;
  v_hash := encode(sha256(convert_to(v_action || ':' || coalesce(p_payload, '{}'::jsonb)::text, 'UTF8')), 'hex');
  select * into v_existing
    from private.sanctuary_management_commands_v412
   where actor_member_id = v_actor_id and request_key = btrim(coalesce(p_request_key, ''));
  if v_existing.command_id is not null then
    if v_existing.action <> v_action or v_existing.request_hash <> v_hash then
      raise exception '같은 요청 키가 다른 작업에 사용되었습니다.' using errcode = 'P0001';
    end if;
    v_response := public.kinojo_sanctuary_management_command_v449(
      p_credential, p_request_key, p_action, p_payload, p_expected_revision
    );
    v_team_id := nullif(v_response->>'teamId', '')::bigint;
    select count(*)::integer into v_occupied_count
      from private.sanctuary_management_slots_v412
     where team_id = v_team_id and (character_id is not null or assignment_kind = 'RANDOM_ALT');
    return v_response || jsonb_build_object(
      'replayed', true, 'occupiedCount', v_occupied_count,
      'apiVersion', 2.0, 'schemaVersion', 450, 'databaseContract', 450, 'slotContractVersion', 1
    );
  end if;

  v_team_id := nullif(p_payload->>'teamId', '')::bigint;
  if v_team_id is not null then
    update private.sanctuary_management_slots_v412
       set assignment_kind = 'ACTUAL_CHARACTER', character_id = null, owner_member_id = null,
           owner_root_character_id = null, character_relation = null, added_by_member_id = v_actor_id
     where team_id = v_team_id and assignment_kind = 'RANDOM_ALT';
  end if;

  v_response := public.kinojo_sanctuary_management_command_v449(
    p_credential, p_request_key, p_action, p_payload, p_expected_revision
  );
  v_team_id := nullif(v_response->>'teamId', '')::bigint;

  for v_force_item, v_force_no in
    select force_item, ordinality::integer
    from jsonb_array_elements(coalesce(p_payload->'composition', '[]'::jsonb))
      with ordinality force_source(force_item, ordinality)
  loop
    select force_id into strict v_force_id
      from private.sanctuary_management_forces_v412
     where team_id = v_team_id and force_no = v_force_no;
    for v_slot_item in
      select slot_item from jsonb_array_elements(coalesce(v_force_item->'slots', '[]'::jsonb)) slot_source(slot_item)
    loop
      v_required_class := upper(coalesce(v_slot_item->>'requiredClassCode', 'ALL'));
      v_assignment_kind := upper(coalesce(v_slot_item->>'assignmentKind', 'ACTUAL_CHARACTER'));
      v_character_id := nullif(v_slot_item->>'characterId', '')::bigint;
      v_main_character_id := nullif(v_slot_item->>'mainCharacterId', '')::bigint;
      select slot.slot_id into strict v_slot_id
        from private.sanctuary_management_slots_v412 slot
        join private.sanctuary_management_parties_v412 party on party.party_id = slot.party_id
       where slot.force_id = v_force_id
         and party.party_no = nullif(v_slot_item->>'partyNo', '')::integer
         and slot.slot_no = nullif(v_slot_item->>'slotNo', '')::integer;
      if v_assignment_kind = 'RANDOM_ALT' then
        select * into v_owner from private.kinojo_sm_resolve_character_owner_v412(v_main_character_id);
        if v_owner.character_id is null or v_owner.root_character_id is distinct from v_main_character_id then
          raise exception '랜덤 부캐의 본캐 소유 관계를 확인할 수 없습니다.' using errcode = 'P0001';
        end if;
        update private.sanctuary_management_slots_v412 set
          required_class_code = 'ALL', assignment_kind = 'RANDOM_ALT', character_id = null,
          owner_member_id = v_owner.owner_member_id, owner_root_character_id = v_owner.root_character_id,
          character_relation = 'ALT', added_by_member_id = v_actor_id
        where slot_id = v_slot_id;
      else
        update private.sanctuary_management_slots_v412 set
          required_class_code = v_required_class, assignment_kind = 'ACTUAL_CHARACTER'
        where slot_id = v_slot_id;
      end if;
    end loop;
  end loop;

  perform private.kinojo_sm_recompute_status_v450(v_team_id);
  select count(*)::integer into v_occupied_count
    from private.sanctuary_management_slots_v412
   where team_id = v_team_id and (character_id is not null or assignment_kind = 'RANDOM_ALT');
  return v_response || jsonb_build_object(
    'occupiedCount', v_occupied_count,
    'apiVersion', 2.0, 'schemaVersion', 450, 'databaseContract', 450, 'slotContractVersion', 1
  );
end
$function$;
CREATE OR REPLACE FUNCTION public.kinojo_sanctuary_management_command_v452(p_credential text, p_request_key text, p_action text, p_payload jsonb, p_expected_revision bigint DEFAULT NULL::bigint)
 RETURNS jsonb
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO ''
AS $function$
declare
  v_action text := upper(btrim(coalesce(p_action, ''))); v_payload jsonb := coalesce(p_payload, '{}'::jsonb);
  v_delegate jsonb; v_response jsonb; v_team_id bigint; v_team private.sanctuary_management_teams_v412%rowtype;
  v_sanctuary public.sanctuary_master%rowtype; v_difficulty text; v_minimum integer;
  v_force jsonb; v_rule jsonb; v_force_no integer; v_force_id bigint; v_party_id bigint;
  v_scope text; v_type text; v_party_no integer; v_count integer; v_item_threshold integer;
begin
  if v_action = 'SUBMIT_SUPPORT' then
    v_delegate := private.kinojo_sm_support_payload_v452(p_credential, p_request_key, v_payload);
    v_response := public.kinojo_sanctuary_management_command_v451(p_credential, p_request_key, v_action, v_delegate, p_expected_revision);
    return v_response || jsonb_build_object('apiVersion', 2.2, 'schemaVersion', 452, 'databaseContract', 452);
  end if;
  if v_action = 'DECIDE_SUPPORT' and upper(coalesce(v_payload->>'decision', '')) = 'APPROVE' and exists (
    select 1
    from private.sanctuary_management_support_batches_v412 batch
    join private.sanctuary_management_support_items_v412 item on item.support_batch_id = batch.support_batch_id and item.status = 'PENDING'
    where batch.support_batch_id = nullif(v_payload->>'supportBatchId', '')::bigint
      and not private.kinojo_sm_character_eligible_v452(item.character_id, private.kinojo_sm_team_min_item_level_v452(batch.team_id))
  ) then raise exception '현재 성역 아이템레벨을 충족하지 않는 지원 캐릭터가 있습니다.' using errcode = 'P0001'; end if;

  if v_action <> 'SAVE_COMPOSITION' then
    if v_action = 'SET_SLOT' then
      v_team_id := nullif(v_payload->>'teamId', '')::bigint;
      if v_payload->>'characterId' is not null and not private.kinojo_sm_character_eligible_v452(
        nullif(v_payload->>'characterId', '')::bigint, private.kinojo_sm_team_min_item_level_v452(v_team_id)
      ) then raise exception '해당 성역 아이템레벨을 충족하는 캐릭터만 배치할 수 있습니다.' using errcode = 'P0001'; end if;
    end if;
    v_response := public.kinojo_sanctuary_management_command_v451(p_credential, p_request_key, v_action, v_payload, p_expected_revision);
    return v_response || jsonb_build_object('apiVersion', 2.2, 'schemaVersion', 452, 'databaseContract', 452);
  end if;

  v_team_id := nullif(v_payload->>'teamId', '')::bigint;
  if v_team_id is not null then
    select * into v_team from private.sanctuary_management_teams_v412 where team_id = v_team_id;
    select * into v_sanctuary from public.sanctuary_master where id = v_team.sanctuary_id;
  else
    select * into v_sanctuary from public.sanctuary_master where code = btrim(v_payload->>'sanctuaryCode') and management_visible;
  end if;
  if v_sanctuary.id is null then raise exception '선택한 성역을 찾을 수 없습니다.' using errcode = 'P0001'; end if;
  v_difficulty := upper(coalesce(nullif(v_payload->>'difficulty', ''), case when v_sanctuary.code = 'kaldrix' then 'NORMAL' else 'NORMAL' end));
  if (v_sanctuary.code = 'kaldrix' and v_difficulty not in ('NORMAL', 'HARD'))
     or (v_sanctuary.code <> 'kaldrix' and v_difficulty <> 'NORMAL') then
    raise exception '선택한 성역 난이도를 다시 확인해 주세요.' using errcode = 'P0001';
  end if;
  v_minimum := private.kinojo_sm_min_item_level_v452(v_sanctuary.id, v_difficulty);
  if exists (
    select 1 from jsonb_array_elements(coalesce(v_payload->'composition', '[]'::jsonb)) force_source(force_item)
    cross join lateral jsonb_array_elements(coalesce(force_item->'slots', '[]'::jsonb)) slot_source(slot_item)
    where nullif(slot_item->>'characterId', '')::bigint is not null
      and not private.kinojo_sm_character_eligible_v452(nullif(slot_item->>'characterId', '')::bigint, v_minimum)
  ) then raise exception '해당 성역 아이템레벨을 충족하는 캐릭터만 배치할 수 있습니다.' using errcode = 'P0001'; end if;
  if exists (
    select 1 from jsonb_array_elements(coalesce(v_payload->'composition', '[]'::jsonb)) force_source(force_item)
    cross join lateral jsonb_array_elements(coalesce(force_item->'slots', '[]'::jsonb)) slot_source(slot_item)
    where upper(coalesce(slot_item->>'assignmentKind', 'ACTUAL_CHARACTER')) = 'RANDOM_ALT'
      and not exists (
        select 1 from public.character_master character
        where character.main_character_id = nullif(slot_item->>'mainCharacterId', '')::bigint
          and character.id <> nullif(slot_item->>'mainCharacterId', '')::bigint
          and coalesce(character.is_active, true) and not coalesce(character.lookup_excluded, false)
          and (v_minimum is null or character.latest_pve_item_level >= v_minimum)
      )
  ) then raise exception '해당 성역 아이템레벨을 충족하는 부캐가 없어 랜덤 부캐를 배치할 수 없습니다.' using errcode = 'P0001'; end if;

  if coalesce(nullif(v_payload->>'compositionRulesVersion', '')::integer, 0) not in (0, 1, 2) then
    raise exception '포스 구성 조건 형식을 다시 확인해 주세요.' using errcode = 'P0001';
  end if;
  if exists (
    select 1 from jsonb_array_elements(coalesce(v_payload->'composition', '[]'::jsonb)) force_source(force_item)
    where jsonb_typeof(coalesce(force_item->'requirements', '[]'::jsonb)) <> 'array'
      or jsonb_array_length(coalesce(force_item->'requirements', '[]'::jsonb)) > 6
      or exists (
        select 1 from jsonb_array_elements(coalesce(force_item->'requirements', '[]'::jsonb)) rule_source(rule_item)
        where upper(coalesce(rule_item->>'ruleType', '')) not in ('MAIN_MIN', 'POWER_MIN', 'ITEM_LEVEL_MIN')
          or upper(coalesce(rule_item->>'scopeType', '')) not in ('FORCE', 'PARTY')
          or nullif(rule_item->>'minimumCount', '')::integer is null
          or nullif(rule_item->>'minimumCount', '')::integer not between 1 and
            case when upper(coalesce(rule_item->>'scopeType', '')) = 'PARTY' then 5 else 10 end
          or (upper(coalesce(rule_item->>'scopeType', '')) = 'FORCE' and rule_item->>'partyNo' is not null)
          or (upper(coalesce(rule_item->>'scopeType', '')) = 'PARTY' and
            coalesce(nullif(rule_item->>'partyNo', '')::integer, 0) not in (1, 2))
          or (upper(coalesce(rule_item->>'ruleType', '')) = 'MAIN_MIN' and (
            rule_item->>'powerThreshold' is not null or rule_item->>'itemLevelThreshold' is not null
          ))
          or (upper(coalesce(rule_item->>'ruleType', '')) = 'POWER_MIN' and (
            nullif(rule_item->>'powerThreshold', '')::integer is null
            or nullif(rule_item->>'powerThreshold', '')::integer not between 1000 and 1000000000
            or rule_item->>'itemLevelThreshold' is not null
          ))
          or (upper(rule_item->>'ruleType') = 'ITEM_LEVEL_MIN' and (
            nullif(rule_item->>'itemLevelThreshold', '')::integer is null
            or nullif(rule_item->>'itemLevelThreshold', '')::integer not between 1 and 100000
            or (v_minimum is not null and nullif(rule_item->>'itemLevelThreshold', '')::integer < v_minimum)
            or rule_item->>'powerThreshold' is not null
          ))
      )
      or exists (
        select 1
        from jsonb_array_elements(coalesce(force_item->'requirements', '[]'::jsonb)) rule_source(rule_item)
        group by upper(coalesce(rule_item->>'scopeType', '')),
          coalesce(rule_item->>'partyNo', '0'), upper(coalesce(rule_item->>'ruleType', ''))
        having count(*) > 1
      )
      or exists (
        select 1 from jsonb_array_elements(coalesce(force_item->'requirements', '[]'::jsonb)) rule_source(rule_item)
        where upper(rule_item->>'ruleType') in ('POWER_MIN', 'ITEM_LEVEL_MIN')
        group by upper(rule_item->>'scopeType'), coalesce(rule_item->>'partyNo', '0') having count(*) > 1
      )
  ) then raise exception '본캐·전투력·아이템레벨 배치 조건을 다시 확인해 주세요.' using errcode = 'P0001'; end if;

  select jsonb_agg((force_item - 'requirements') || jsonb_build_object('requirements', coalesce((
    select jsonb_agg(rule_item order by rule_ordinality)
    from jsonb_array_elements(coalesce(force_item->'requirements', '[]'::jsonb)) with ordinality rules(rule_item, rule_ordinality)
    where upper(coalesce(rule_item->>'ruleType', '')) <> 'ITEM_LEVEL_MIN'
  ), '[]'::jsonb)) order by force_ordinality) into v_delegate
  from jsonb_array_elements(coalesce(v_payload->'composition', '[]'::jsonb)) with ordinality forces(force_item, force_ordinality);
  v_delegate := (v_payload - 'composition' - 'compositionRulesVersion') || jsonb_build_object(
    'composition', coalesce(v_delegate, '[]'::jsonb), 'compositionRulesVersion', 1
  );
  v_response := public.kinojo_sanctuary_management_command_v451(p_credential, p_request_key, v_action, v_delegate, p_expected_revision);
  v_team_id := nullif(v_response->>'teamId', '')::bigint;
  if coalesce((v_response->>'replayed')::boolean, false) is not true then
    update private.sanctuary_management_teams_v412 set difficulty = v_difficulty, updated_at = clock_timestamp() where team_id = v_team_id;
    for v_force, v_force_no in
      select force_item, ordinality::integer from jsonb_array_elements(coalesce(v_payload->'composition', '[]'::jsonb)) with ordinality source(force_item, ordinality)
    loop
      select force_id into strict v_force_id from private.sanctuary_management_forces_v412 where team_id = v_team_id and force_no = v_force_no;
      for v_rule in select rule_item from jsonb_array_elements(coalesce(v_force->'requirements', '[]'::jsonb)) source(rule_item)
      loop
        v_type := upper(v_rule->>'ruleType');
        if v_type = 'ITEM_LEVEL_MIN' then
          v_scope := upper(v_rule->>'scopeType'); v_party_no := nullif(v_rule->>'partyNo', '')::integer;
          v_count := nullif(v_rule->>'minimumCount', '')::integer; v_item_threshold := nullif(v_rule->>'itemLevelThreshold', '')::integer;
          v_party_id := null;
          if v_scope = 'PARTY' then select party_id into strict v_party_id from private.sanctuary_management_parties_v412 where force_id = v_force_id and party_no = v_party_no; end if;
          insert into private.sanctuary_management_composition_rules_v449(
            team_id, force_id, party_id, scope_type, rule_type, minimum_count,
            power_threshold, item_level_threshold, created_by_member_id, updated_by_member_id
          ) values (
            v_team_id, v_force_id, v_party_id, v_scope, v_type, v_count,
            null, v_item_threshold, nullif(private.kinojo_sm_actor_v412(p_credential)->>'memberId', '')::bigint,
            nullif(private.kinojo_sm_actor_v412(p_credential)->>'memberId', '')::bigint
          );
        end if;
      end loop;
    end loop;
  end if;
  return v_response || jsonb_build_object(
    'difficulty', v_difficulty, 'minimumItemLevel', v_minimum, 'compositionRulesVersion', 2,
    'apiVersion', 2.2, 'schemaVersion', 452, 'databaseContract', 452
  );
end
$function$;
