-- Read-only catalog snapshot 2026-09-09; no operational row data or credentials.
-- Exact v446/v454 bodies; test harness supplies explicit synthetic surrounding services.
create table private.sanctuary_management_commands_v412 (
 command_id bigint generated by default as identity,
 actor_member_id bigint,
 request_key text,
 action text,
 request_hash text,
 response_payload jsonb default '{}'::jsonb,
 created_at timestamp with time zone default clock_timestamp()
);
create table private.sanctuary_management_composition_rules_v449 (
 composition_rule_id bigint generated by default as identity,
 team_id bigint,
 force_id bigint,
 party_id bigint,
 scope_type text,
 rule_type text,
 minimum_count smallint,
 power_threshold integer,
 revision bigint default 1,
 created_by_member_id bigint,
 updated_by_member_id bigint,
 created_at timestamp with time zone default clock_timestamp(),
 updated_at timestamp with time zone default clock_timestamp(),
 item_level_threshold integer
);
create table private.sanctuary_management_forces_v412 (
 force_id bigint generated by default as identity,
 team_id bigint,
 force_no smallint,
 capacity smallint default 10,
 status text default 'OPEN'::text,
 revision bigint default 1,
 created_at timestamp with time zone default clock_timestamp(),
 updated_at timestamp with time zone default clock_timestamp(),
 difficulty text default 'NORMAL'::text
);
create table private.sanctuary_management_parties_v412 (
 party_id bigint generated by default as identity,
 team_id bigint,
 force_id bigint,
 party_no smallint,
 capacity smallint default 5,
 created_at timestamp with time zone default clock_timestamp()
);
create table private.sanctuary_management_schedule_exceptions_v412 (
 exception_id bigint generated by default as identity,
 schedule_id bigint,
 occurrence_date date,
 exception_type text,
 moved_to_date date,
 moved_to_time time without time zone,
 created_by_member_id bigint,
 created_at timestamp with time zone default clock_timestamp(),
 moved_duration_minutes integer
);
create table private.sanctuary_management_schedule_rules_v412 (
 schedule_id bigint generated by default as identity,
 team_id bigint,
 schedule_kind text,
 starts_on date,
 weekdays smallint[] default '{}'::smallint[],
 starts_at time without time zone,
 duration_minutes integer default 30,
 timezone_name text default 'Asia/Seoul'::text,
 status text default 'ACTIVE'::text,
 revision bigint default 1,
 created_at timestamp with time zone default clock_timestamp(),
 updated_at timestamp with time zone default clock_timestamp()
);
create table private.sanctuary_management_schedule_versions_v437 (
 schedule_version_id bigint generated by default as identity,
 schedule_id bigint,
 team_id bigint,
 effective_from date,
 effective_to date,
 schedule_kind text,
 starts_on date,
 weekdays smallint[] default '{}'::smallint[],
 starts_at time without time zone,
 duration_minutes integer default 30,
 timezone_name text default 'Asia/Seoul'::text,
 status text default 'ACTIVE'::text,
 revision bigint default 1,
 created_by_member_id bigint,
 created_at timestamp with time zone default clock_timestamp()
);
create table private.sanctuary_management_slots_v412 (
 slot_id bigint generated by default as identity,
 team_id bigint,
 force_id bigint,
 party_id bigint,
 slot_no smallint,
 character_id bigint,
 owner_member_id bigint,
 owner_root_character_id bigint,
 character_relation text,
 added_by_member_id bigint,
 revision bigint default 1,
 created_at timestamp with time zone default clock_timestamp(),
 updated_at timestamp with time zone default clock_timestamp(),
 required_class_code text default 'ALL'::text,
 assignment_kind text default 'ACTUAL_CHARACTER'::text,
 placement_locked boolean default false
);
create table private.sanctuary_management_support_batches_v412 (
 support_batch_id bigint generated by default as identity,
 team_id bigint,
 requester_member_id bigint,
 request_key text,
 status text default 'PENDING'::text,
 decision_member_id bigint,
 decision_note text,
 decided_at timestamp with time zone,
 created_at timestamp with time zone default clock_timestamp(),
 updated_at timestamp with time zone default clock_timestamp()
);
create table private.sanctuary_management_support_items_v412 (
 support_item_id bigint generated by default as identity,
 support_batch_id bigint,
 force_id bigint,
 character_id bigint,
 owner_member_id bigint,
 owner_root_character_id bigint,
 status text default 'PENDING'::text,
 applied_slot_id bigint,
 created_at timestamp with time zone default clock_timestamp(),
 updated_at timestamp with time zone default clock_timestamp(),
 result_code text,
 result_message text
);
create table private.sanctuary_management_teams_v412 (
 team_id bigint generated by default as identity,
 sanctuary_id bigint,
 title text,
 activity text,
 team_mode text,
 join_policy text default 'INSTANT'::text,
 status text default 'DRAFT'::text,
 creator_member_id bigint,
 revision bigint default 1,
 published_at timestamp with time zone,
 archived_at timestamp with time zone,
 archived_by_member_id bigint,
 archive_reason text,
 created_at timestamp with time zone default clock_timestamp(),
 updated_at timestamp with time zone default clock_timestamp(),
 difficulty text default 'NORMAL'::text
);
create table public.character_master (
 id bigint generated by default as identity,
 server_id integer default 2002,
 server_name text,
 character_name text,
 char_key text,
 profile_image_url text,
 detail_url text,
 image_updated_at timestamp with time zone,
 status text default 'OK'::text,
 error_message text,
 main_character_name text,
 is_main boolean default false,
 class_name text,
 list_row integer,
 first_seen_at timestamp with time zone,
 last_seen_at timestamp with time zone,
 created_at timestamp with time zone default now(),
 updated_at timestamp with time zone default now(),
 latest_pve_item_level integer,
 latest_pve_combat_power integer,
 latest_pvp_item_level integer,
 latest_pvp_combat_power integer,
 latest_item_level_total integer,
 latest_power_total integer,
 latest_session_id text,
 latest_payload_id bigint,
 latest_snapshot_uid text,
 latest_payload_hash text,
 last_synced_at timestamp with time zone,
 sync_status text default 'idle'::text,
 bootstrap_source text,
 bootstrap_imported_at timestamp with time zone,
 is_active boolean default true,
 inactive_reason text,
 inactive_memo text,
 inactivated_at timestamp with time zone,
 restored_at timestamp with time zone,
 previous_name text,
 renamed_to text,
 status_updated_at timestamp with time zone,
 lookup_excluded boolean default false,
 visibility_excluded boolean default false,
 exclusion_reason text,
 exclusion_memo text,
 lookup_excluded_at timestamp with time zone,
 visibility_excluded_at timestamp with time zone,
 lookup_failure_streak integer default 0,
 lookup_failure_total integer default 0,
 last_lookup_failure_code text,
 last_lookup_failure_session_id text,
 last_lookup_failed_at timestamp with time zone,
 last_lookup_success_at timestamp with time zone,
 latest_pve_payload_id bigint,
 latest_pvp_payload_id bigint,
 main_character_id bigint,
 previous_character_name text,
 previous_server_id integer,
 previous_server_name text,
 previous_char_key text,
 previous_profile_url text,
 identity_change_type text,
 identity_status text default 'CURRENT'::text,
 identity_changed_at timestamp with time zone,
 identity_verified_at timestamp with time zone,
 legion_name text,
 legion_updated_at timestamp with time zone,
 legion_source_snapshot_id bigint,
 lookup_policy text default 'INHERIT'::text,
 lookup_group_policy text default 'AUTO'::text,
 lookup_policy_reason text,
 lookup_policy_actor_id bigint,
 lookup_policy_updated_at timestamp with time zone,
 relation_review_attempted_at timestamp with time zone,
 relation_review_session_id text
);
create table public.member_codes (
 id bigint generated by default as identity,
 main_character_name text,
 pass_code text,
 level integer default 1,
 role text default 'MEMBER'::text,
 can_like boolean default true,
 can_suggest boolean default true,
 can_manage boolean default false,
 is_active boolean default true,
 created_at timestamp with time zone default now(),
 updated_at timestamp with time zone default now(),
 role_label text,
 permissions text[] default '{}'::text[],
 memo text,
 issued_by text,
 last_login_at timestamp with time zone,
 list_absent_access_override boolean default false,
 list_absent_access_override_at timestamp with time zone,
 list_absent_auto_disabled_at timestamp with time zone,
 is_automation_account boolean default false
);
create table public.sanctuary_master (
 id bigint generated by default as identity,
 code text,
 name text,
 short_name text,
 boss_name text,
 sheet_name text,
 display_order integer default 100,
 enabled boolean default true,
 banner_image text,
 card_class text,
 mobile_card_class text,
 card_background text,
 card_symbol text,
 card_layout text default 'symbol'::text,
 card_layers jsonb default '[]'::jsonb,
 accent_color text,
 metadata jsonb default '{}'::jsonb,
 created_at timestamp with time zone default now(),
 updated_at timestamp with time zone default now(),
 management_visible boolean default true,
 available_from date
);
create table public.sanctuary_role_permissions (
 role_key text,
 permission_key text,
 enabled boolean default false,
 updated_by_member_id bigint,
 updated_by_character text,
 created_at timestamp with time zone default now(),
 updated_at timestamp with time zone default now()
);
alter table public.member_codes add primary key(id);
alter table private.sanctuary_management_teams_v412 add primary key(team_id);
alter table public.sanctuary_role_permissions add primary key(role_key,permission_key);
CREATE OR REPLACE FUNCTION public.kinojo_sanctuary_management_command_v446(p_credential text, p_request_key text, p_action text, p_payload jsonb, p_expected_revision bigint DEFAULT NULL::bigint)
 RETURNS jsonb
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'pg_catalog', 'public', 'private'
AS $function$
declare
  v_action text := upper(btrim(coalesce(p_action, '')));
  v_request_key text := btrim(coalesce(p_request_key, ''));
  v_actor jsonb;
  v_actor_id bigint;
  v_hash text;
  v_existing private.sanctuary_management_commands_v412%rowtype;
  v_team private.sanctuary_management_teams_v412%rowtype;
  v_sanctuary public.sanctuary_master%rowtype;
  v_owner record;
  v_team_id bigint;
  v_force_id bigint;
  v_party_id bigint;
  v_character_id bigint;
  v_desired_count integer;
  v_current_count integer;
  v_force_no integer;
  v_party_no integer;
  v_slot_no integer;
  v_mode text;
  v_policy text;
  v_kind text;
  v_starts_on date;
  v_weekdays smallint[];
  v_starts_at time;
  v_duration integer;
  v_composition jsonb;
  v_force_json jsonb;
  v_slot_json jsonb;
  v_before jsonb;
  v_after jsonb;
  v_conflicts jsonb;
  v_response jsonb;
  v_created boolean := false;
  v_sub_key text;
begin
  if v_action <> 'SAVE_COMPOSITION' then
    return public.kinojo_sanctuary_management_command_v445(p_credential,p_request_key,p_action,p_payload,p_expected_revision)
      || jsonb_build_object('apiVersion',1.8,'schemaVersion',446,'databaseContract',446);
  end if;

  perform private.kinojo_sm_assert_pilot_write_v439(p_credential, v_action);
  v_actor := private.kinojo_sm_actor_v412(p_credential);
  v_actor_id := nullif(v_actor->>'memberId', '')::bigint;
  if v_actor_id is null then raise exception '로그인 후 팀을 저장해 주세요.' using errcode='P0001'; end if;
  if char_length(v_request_key) not between 8 and 120 then raise exception '요청 키가 올바르지 않습니다.' using errcode='P0001'; end if;
  if jsonb_typeof(coalesce(p_payload, '{}'::jsonb)) <> 'object' then raise exception '팀 저장 형식이 올바르지 않습니다.' using errcode='P0001'; end if;

  v_hash := encode(sha256(convert_to(v_action||':'||coalesce(p_payload,'{}'::jsonb)::text, 'UTF8')), 'hex');
  perform pg_advisory_xact_lock(hashtextextended('sanctuary-management:'||v_actor_id||':'||v_request_key,446));
  select * into v_existing from private.sanctuary_management_commands_v412 where actor_member_id=v_actor_id and request_key=v_request_key;
  if v_existing.command_id is not null then
    if v_existing.action<>v_action or v_existing.request_hash<>v_hash then raise exception '같은 요청 키가 다른 작업에 사용되었습니다.' using errcode='P0001'; end if;
    return v_existing.response_payload||jsonb_build_object('replayed',true,'apiVersion',1.8,'schemaVersion',446,'databaseContract',446);
  end if;

  v_mode := upper(btrim(coalesce(p_payload->>'mode','')));
  v_policy := upper(btrim(coalesce(p_payload->>'joinPolicy','INSTANT')));
  if v_mode not in ('FIXED','PARTICIPATION') or v_policy not in ('INSTANT','APPROVAL') then raise exception '고정·참여 팀과 참가 방식을 다시 선택해 주세요.' using errcode='P0001'; end if;
  if v_mode='FIXED' then v_policy:='INSTANT'; end if;
  if char_length(btrim(coalesce(p_payload->>'title',''))) not between 1 and 80 then raise exception '팀 이름을 1자 이상 80자 이하로 입력해 주세요.' using errcode='P0001'; end if;
  if char_length(btrim(coalesce(p_payload->>'activity',''))) not between 1 and 24 then raise exception '팀 이름을 다시 확인해 주세요.' using errcode='P0001'; end if;

  select * into v_sanctuary from public.sanctuary_master where code=btrim(p_payload->>'sanctuaryCode') and management_visible;
  if v_sanctuary.id is null then raise exception '선택한 성역을 찾을 수 없습니다.' using errcode='P0001'; end if;
  v_kind := upper(coalesce(p_payload->'schedule'->>'kind',''));
  v_starts_on := nullif(p_payload->'schedule'->>'startsOn','')::date;
  v_weekdays := coalesce(array(select distinct weekday::smallint from jsonb_array_elements_text(coalesce(p_payload->'schedule'->'weekdays','[]'::jsonb)) weekday order by weekday::smallint),'{}'::smallint[]);
  v_starts_at := nullif(p_payload->'schedule'->>'startsAt','')::time;
  v_duration := coalesce(nullif(p_payload->'schedule'->>'durationMinutes','')::integer,30);
  if v_starts_on is null or v_starts_at is null or v_kind not in ('ONCE','WEEKLY')
     or (v_kind='ONCE' and cardinality(v_weekdays)<>0)
     or (v_kind='WEEKLY' and cardinality(v_weekdays) not between 1 and 7)
     or exists(select 1 from unnest(v_weekdays) weekday where weekday not between 1 and 7)
     or v_duration not in (30,60,120,720) then raise exception '일정과 진행 시간을 다시 확인해 주세요.' using errcode='P0001'; end if;
  if v_sanctuary.available_from is not null and v_starts_on<v_sanctuary.available_from then raise exception '% 일정은 %부터 등록할 수 있습니다.',v_sanctuary.short_name,v_sanctuary.available_from using errcode='P0001'; end if;

  v_composition := coalesce(p_payload->'composition','[]'::jsonb);
  if jsonb_typeof(v_composition)<>'array' or jsonb_array_length(v_composition) not between 1 and 9 then raise exception '포스를 하나 이상, 최대 9개까지 구성해 주세요.' using errcode='P0001'; end if;
  if exists(
    select 1 from jsonb_array_elements(v_composition) force_item
     where coalesce(jsonb_typeof(force_item->'slots'),'')<>'array'
        or jsonb_array_length(force_item->'slots')<>10
        or exists(select 1 from jsonb_array_elements(force_item->'slots') slot_item
                   where nullif(slot_item->>'partyNo','')::integer not in (1,2)
                      or nullif(slot_item->>'slotNo','')::integer not between 1 and 5
                      or (slot_item->>'characterId' is not null and nullif(slot_item->>'characterId','')::bigint<1))
        or (select count(distinct ((slot_item->>'partyNo')||':'||(slot_item->>'slotNo'))) from jsonb_array_elements(force_item->'slots') slot_item)<>10
  ) then raise exception '각 포스는 1·2파티의 10개 슬롯을 정확히 포함해야 합니다.' using errcode='P0001'; end if;
  if (select count(*)<>count(distinct nullif(slot_item->>'characterId','')::bigint)
        from jsonb_array_elements(v_composition) force_item
        cross join lateral jsonb_array_elements(force_item->'slots') slot_item
       where slot_item->>'characterId' is not null) then raise exception '같은 캐릭터는 한 팀에 중복 배치할 수 없습니다.' using errcode='P0001'; end if;
  if (select count(*)<>count(distinct nullif(force_item->>'sourceForceId','')::bigint)
        from jsonb_array_elements(v_composition) force_item
       where force_item->>'sourceForceId' is not null) then raise exception '같은 포스가 편성안에 중복되었습니다.' using errcode='P0001'; end if;

  v_team_id := nullif(p_payload->>'teamId','')::bigint;
  if v_team_id is null then
    v_sub_key := left(v_request_key||':create',120);
    v_response := public.kinojo_sanctuary_management_command_v436(
      p_credential,v_sub_key,'CREATE_TEAM',coalesce(p_payload,'{}'::jsonb)||jsonb_build_object('mode',v_mode,'joinPolicy',v_policy),null
    );
    v_team_id := nullif(v_response->>'teamId','')::bigint;
    v_created := true;
    select * into v_team from private.sanctuary_management_teams_v412 where team_id=v_team_id for update;
  else
    select * into v_team from private.sanctuary_management_teams_v412 where team_id=v_team_id for update;
    if v_team.team_id is null or not private.kinojo_sm_can_manage_team_v412(v_actor,v_team_id) then raise exception '이 팀을 편집할 권한이 없습니다.' using errcode='P0001'; end if;
    if v_team.status='ARCHIVED' then raise exception '현재 편집할 수 없는 팀입니다.' using errcode='P0001'; end if;
    if p_expected_revision is null or v_team.revision<>p_expected_revision then raise exception '다른 사용자가 먼저 팀을 수정했습니다. 새로고침 후 다시 시도해 주세요.' using errcode='40001'; end if;
    perform private.kinojo_sm_assert_lease_v433(v_actor_id,v_team_id,p_payload->>'leaseToken');
  end if;

  select jsonb_build_object(
    'team',to_jsonb(v_team),
    'forceCount',(select count(*) from private.sanctuary_management_forces_v412 where team_id=v_team_id),
    'occupiedCount',(select count(*) from private.sanctuary_management_slots_v412 where team_id=v_team_id and character_id is not null)
  ) into v_before;

  if not v_created then
    if v_team.team_mode<>v_mode and v_mode='FIXED' then
      update private.sanctuary_management_support_items_v412 support_item
         set status='CANCELLED'
        from private.sanctuary_management_support_batches_v412 support_batch
       where support_batch.team_id=v_team_id
         and support_batch.support_batch_id=support_item.support_batch_id
         and support_item.status='PENDING';
      update private.sanctuary_management_support_batches_v412
         set status='CANCELLED',decision_member_id=v_actor_id,decided_at=clock_timestamp()
       where team_id=v_team_id and status='PENDING';
    end if;
    update private.sanctuary_management_teams_v412 set sanctuary_id=v_sanctuary.id,title=btrim(p_payload->>'title'),activity=btrim(p_payload->>'activity'),team_mode=v_mode,join_policy=v_policy,updated_at=clock_timestamp() where team_id=v_team_id returning * into v_team;
    update private.sanctuary_management_schedule_rules_v412 set schedule_kind=v_kind,starts_on=v_starts_on,weekdays=v_weekdays,starts_at=v_starts_at,duration_minutes=v_duration,status='ACTIVE',updated_at=clock_timestamp() where team_id=v_team_id;
    if not found then raise exception '팀 일정을 찾을 수 없습니다.' using errcode='P0001'; end if;

    if exists(
      select 1 from private.sanctuary_management_forces_v412 force_row
       where force_row.team_id=v_team_id
         and not exists(select 1 from jsonb_array_elements(v_composition) force_item where nullif(force_item->>'sourceForceId','')::bigint=force_row.force_id)
         and exists(select 1 from private.sanctuary_management_support_items_v412 support_item where support_item.force_id=force_row.force_id)
    ) then raise exception '지원 이력이 있는 포스는 바로 제거할 수 없습니다.' using errcode='P0001'; end if;
    delete from private.sanctuary_management_forces_v412 force_row
     where force_row.team_id=v_team_id
       and not exists(select 1 from jsonb_array_elements(v_composition) force_item where nullif(force_item->>'sourceForceId','')::bigint=force_row.force_id);

    for v_force_json,v_force_no in select force_item,ordinality::integer from jsonb_array_elements(v_composition) with ordinality as desired(force_item,ordinality) loop
      v_force_id:=nullif(v_force_json->>'sourceForceId','')::bigint;
      if v_force_id is not null then
        if not exists(select 1 from private.sanctuary_management_forces_v412 where team_id=v_team_id and force_id=v_force_id) then raise exception '편집할 포스를 다시 불러와 주세요.' using errcode='40001'; end if;
        update private.sanctuary_management_forces_v412 set force_no=v_force_no where team_id=v_team_id and force_id=v_force_id and force_no<>v_force_no;
      end if;
    end loop;
  end if;

  v_desired_count := jsonb_array_length(v_composition);
  select count(*)::integer into v_current_count from private.sanctuary_management_forces_v412 where team_id=v_team_id;
  while v_current_count<v_desired_count loop
    v_force_no := v_current_count+1;
    insert into private.sanctuary_management_forces_v412(team_id,force_no) values(v_team_id,v_force_no) returning force_id into v_force_id;
    for v_party_no in 1..2 loop
      insert into private.sanctuary_management_parties_v412(team_id,force_id,party_no) values(v_team_id,v_force_id,v_party_no) returning party_id into v_party_id;
      insert into private.sanctuary_management_slots_v412(team_id,force_id,party_id,slot_no) select v_team_id,v_force_id,v_party_id,slot_number from generate_series(1,5) slot_number;
    end loop;
    v_current_count := v_current_count+1;
  end loop;
  while v_current_count>v_desired_count loop
    select force_id into v_force_id from private.sanctuary_management_forces_v412 where team_id=v_team_id order by force_no desc limit 1;
    if exists(select 1 from private.sanctuary_management_support_items_v412 where force_id=v_force_id) then raise exception '지원 이력이 있는 포스는 바로 제거할 수 없습니다.' using errcode='P0001'; end if;
    delete from private.sanctuary_management_forces_v412 where force_id=v_force_id;
    v_current_count := v_current_count-1;
  end loop;

  update private.sanctuary_management_slots_v412 set character_id=null,owner_member_id=null,owner_root_character_id=null,character_relation=null,added_by_member_id=v_actor_id where team_id=v_team_id and character_id is not null;
  for v_force_json,v_force_no in select force_item,ordinality::integer from jsonb_array_elements(v_composition) with ordinality as desired(force_item,ordinality) loop
    select force_id into strict v_force_id from private.sanctuary_management_forces_v412 where team_id=v_team_id and force_no=v_force_no;
    for v_slot_json in select slot_item from jsonb_array_elements(v_force_json->'slots') slot_item loop
      v_character_id := nullif(v_slot_json->>'characterId','')::bigint;
      if v_character_id is not null then
        select * into v_owner from private.kinojo_sm_resolve_character_owner_v412(v_character_id);
        if v_owner.character_id is null then raise exception '캐릭터 %의 소유 관계를 확인할 수 없습니다.',v_character_id using errcode='P0001'; end if;
        update private.sanctuary_management_slots_v412 slot_row
           set character_id=v_owner.character_id,owner_member_id=v_owner.owner_member_id,owner_root_character_id=v_owner.root_character_id,
               character_relation=v_owner.relation,added_by_member_id=v_actor_id
          from private.sanctuary_management_parties_v412 party_row
         where slot_row.team_id=v_team_id and slot_row.force_id=v_force_id and slot_row.party_id=party_row.party_id
           and party_row.party_no=(v_slot_json->>'partyNo')::integer and slot_row.slot_no=(v_slot_json->>'slotNo')::integer;
        if not found then raise exception '캐릭터를 배치할 슬롯을 찾을 수 없습니다.' using errcode='P0001'; end if;
      end if;
    end loop;
  end loop;

  if exists(select 1 from private.sanctuary_management_slots_v412 where team_id=v_team_id and owner_member_id is not null group by force_id,owner_member_id having count(*)>1) then raise exception '모든 이용자는 각 포스에 본캐·부캐를 합쳐 캐릭터 1개만 배치할 수 있습니다.' using errcode='P0001'; end if;
  select * into v_team from private.sanctuary_management_teams_v412 where team_id=v_team_id for update;

  perform private.kinojo_sm_recompute_status_v412(v_team_id);
  select * into v_team from private.sanctuary_management_teams_v412 where team_id=v_team_id for update;
  if v_team.status='DRAFT' then
    v_sub_key := left(v_request_key||':publish',120);
    v_response := to_jsonb(v_team);
    update private.sanctuary_management_teams_v412
       set published_at=coalesce(published_at,clock_timestamp()),status='ACTIVE',updated_at=clock_timestamp()
     where team_id=v_team_id returning * into v_team;
    perform private.kinojo_sm_recompute_status_v412(v_team_id);
    select * into v_team from private.sanctuary_management_teams_v412 where team_id=v_team_id for update;
    perform private.kinojo_sm_audit_v412(v_actor_id,v_team_id,'TEAM',v_team_id,'PUBLISH_TEAM',v_response,to_jsonb(v_team),v_sub_key);
  end if;
  v_conflicts := private.kinojo_sm_team_conflicts_v437(v_team_id,current_date,current_date+366);
  if jsonb_array_length(v_conflicts)>0 then raise exception '%',v_conflicts->0->>'message' using errcode='P0001',detail=v_conflicts::text; end if;

  select jsonb_build_object(
    'team',to_jsonb(v_team),
    'forceCount',(select count(*) from private.sanctuary_management_forces_v412 where team_id=v_team_id),
    'occupiedCount',(select count(*) from private.sanctuary_management_slots_v412 where team_id=v_team_id and character_id is not null)
  ) into v_after;
  v_response := jsonb_build_object('ok',true,'action',v_action,'teamId',v_team_id,'revision',v_team.revision,'forceCount',v_desired_count,'occupiedCount',v_after->'occupiedCount','created',v_created,'replayed',false);
  perform private.kinojo_sm_audit_v412(v_actor_id,v_team_id,'TEAM',v_team_id,v_action,v_before,v_after,v_request_key);
  insert into private.sanctuary_management_commands_v412(actor_member_id,request_key,action,request_hash,response_payload) values(v_actor_id,v_request_key,v_action,v_hash,v_response);
  return v_response||jsonb_build_object('apiVersion',1.8,'schemaVersion',446,'databaseContract',446);
end;
$function$;

CREATE OR REPLACE FUNCTION public.kinojo_sanctuary_management_command_v454(p_credential text, p_request_key text, p_action text, p_payload jsonb, p_expected_revision bigint DEFAULT NULL::bigint)
 RETURNS jsonb
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO ''
AS $function$
declare
  v_action text := upper(btrim(coalesce(p_action, '')));
  v_payload jsonb := coalesce(p_payload, '{}'::jsonb);
  v_delegate jsonb;
  v_response jsonb;
  v_team_id bigint;
  v_force_id bigint;
  v_force_no integer;
  v_force jsonb;
  v_slot jsonb;
  v_rule jsonb;
  v_difficulty text;
  v_minimum integer;
  v_sanctuary public.sanctuary_master%rowtype;
  v_team private.sanctuary_management_teams_v412%rowtype;
  v_all_hard boolean := true;
begin
  if v_action = 'SUBMIT_SUPPORT' then
    v_delegate := private.kinojo_sm_support_payload_v454(p_credential, p_request_key, v_payload);
    v_response := public.kinojo_sanctuary_management_command_v451(
      p_credential, p_request_key, v_action, v_delegate, p_expected_revision
    );
    return v_response || jsonb_build_object('apiVersion', 2.2, 'schemaVersion', 454, 'databaseContract', 454);
  end if;

  if v_action = 'DECIDE_SUPPORT' and upper(coalesce(v_payload->>'decision', '')) = 'APPROVE' then
    if exists (
      select 1
      from private.sanctuary_management_support_batches_v412 batch
      join private.sanctuary_management_support_items_v412 item
        on item.support_batch_id = batch.support_batch_id and item.status = 'PENDING'
      where batch.support_batch_id = nullif(v_payload->>'supportBatchId', '')::bigint
        and not private.kinojo_sm_character_eligible_v452(
          item.character_id,
          private.kinojo_sm_force_min_item_level_v454(item.force_id)
        )
    ) then
      raise exception '현재 포스 아이템레벨을 충족하지 않는 지원 캐릭터가 있습니다.' using errcode = 'P0001';
    end if;
    v_response := public.kinojo_sanctuary_management_command_v451(
      p_credential, p_request_key, v_action, v_payload, p_expected_revision
    );
    return v_response || jsonb_build_object('apiVersion', 2.2, 'schemaVersion', 454, 'databaseContract', 454);
  end if;

  if v_action = 'SET_SLOT' then
    v_force_id := nullif(v_payload->>'forceId', '')::bigint;
    if v_payload->>'characterId' is not null and not private.kinojo_sm_character_eligible_v452(
      nullif(v_payload->>'characterId', '')::bigint,
      private.kinojo_sm_force_min_item_level_v454(v_force_id)
    ) then
      raise exception '해당 포스 아이템레벨을 충족하는 캐릭터만 배치할 수 있습니다.' using errcode = 'P0001';
    end if;
    v_response := public.kinojo_sanctuary_management_command_v451(
      p_credential, p_request_key, v_action, v_payload, p_expected_revision
    );
    return v_response || jsonb_build_object('apiVersion', 2.2, 'schemaVersion', 454, 'databaseContract', 454);
  end if;

  if v_action = 'ADD_FORCE' then
    -- v453 only understands the legacy team-level NORMAL/HARD contract.
    -- Insert with NORMAL and persist the force-owned value after validation.
    v_delegate := (v_payload - 'difficulty') || jsonb_build_object('difficulty', 'NORMAL');
    v_response := public.kinojo_sanctuary_management_command_v453(
      p_credential, p_request_key, v_action, v_delegate, p_expected_revision
    );
    v_force_id := nullif(v_response->>'forceId', '')::bigint;
    v_difficulty := upper(coalesce(nullif(v_payload->>'difficulty', ''), 'NORMAL'));
    select * into v_team
      from private.sanctuary_management_teams_v412
     where team_id = nullif(v_response->>'teamId', '')::bigint;
    select * into v_sanctuary
      from public.sanctuary_master
     where id = v_team.sanctuary_id;
    if not private.kinojo_sm_difficulty_allowed_v464(v_sanctuary.id, v_difficulty) then
      raise exception '선택한 포스 난이도를 다시 확인해 주세요.' using errcode = 'P0001';
    end if;
    update private.sanctuary_management_forces_v412
       set difficulty = v_difficulty, updated_at = clock_timestamp()
     where force_id = v_force_id;
    return v_response || jsonb_build_object(
      'difficulty', v_difficulty, 'apiVersion', 2.2, 'schemaVersion', 454, 'databaseContract', 454
    );
  end if;

  if v_action <> 'SAVE_COMPOSITION' then
    v_response := public.kinojo_sanctuary_management_command_v453(
      p_credential, p_request_key, v_action, v_payload, p_expected_revision
    );
    return v_response || jsonb_build_object('apiVersion', 2.2, 'schemaVersion', 454, 'databaseContract', 454);
  end if;

  v_team_id := nullif(v_payload->>'teamId', '')::bigint;
  if v_team_id is not null then
    select * into v_team from private.sanctuary_management_teams_v412 where team_id = v_team_id;
    select * into v_sanctuary from public.sanctuary_master where id = v_team.sanctuary_id;
  else
    select * into v_sanctuary
      from public.sanctuary_master
     where code = btrim(v_payload->>'sanctuaryCode') and management_visible;
  end if;
  if v_sanctuary.id is null then
    raise exception '선택한 성역을 찾을 수 없습니다.' using errcode = 'P0001';
  end if;

  for v_force, v_force_no in
    select force_item, ordinality::integer
    from jsonb_array_elements(coalesce(v_payload->'composition', '[]'::jsonb))
      with ordinality source(force_item, ordinality)
  loop
    v_difficulty := upper(coalesce(nullif(v_force->>'difficulty', ''), nullif(v_payload->>'difficulty', ''), 'NORMAL'));
    if not private.kinojo_sm_difficulty_allowed_v464(v_sanctuary.id, v_difficulty) then
      raise exception '선택한 포스 난이도를 다시 확인해 주세요.' using errcode = 'P0001';
    end if;
    if v_difficulty <> 'HARD' then v_all_hard := false; end if;
    v_minimum := private.kinojo_sm_min_item_level_v452(v_sanctuary.id, v_difficulty);

    for v_slot in
      select slot_item from jsonb_array_elements(coalesce(v_force->'slots', '[]'::jsonb)) source(slot_item)
    loop
      if nullif(v_slot->>'characterId', '')::bigint is not null
         and not private.kinojo_sm_character_eligible_v452(nullif(v_slot->>'characterId', '')::bigint, v_minimum) then
        raise exception '해당 포스 아이템레벨을 충족하는 캐릭터만 배치할 수 있습니다.' using errcode = 'P0001';
      end if;
      if upper(coalesce(v_slot->>'assignmentKind', 'ACTUAL_CHARACTER')) = 'RANDOM_ALT'
         and not exists (
           select 1 from public.character_master character
           where character.main_character_id = nullif(v_slot->>'mainCharacterId', '')::bigint
             and character.id <> nullif(v_slot->>'mainCharacterId', '')::bigint
             and coalesce(character.is_active, true) and not coalesce(character.lookup_excluded, false)
             and private.kinojo_sm_character_eligible_v452(character.id, v_minimum)
         ) then
        raise exception '해당 포스 아이템레벨을 충족하는 부캐가 없어 랜덤 부캐를 배치할 수 없습니다.' using errcode = 'P0001';
      end if;
    end loop;

    for v_rule in
      select rule_item from jsonb_array_elements(coalesce(v_force->'requirements', '[]'::jsonb)) source(rule_item)
    loop
      if upper(coalesce(v_rule->>'ruleType', '')) = 'ITEM_LEVEL_MIN'
         and v_minimum is not null
         and coalesce(nullif(v_rule->>'itemLevelThreshold', '')::integer, 0) < v_minimum then
        raise exception '포스 아이템레벨 배치 조건은 성역 최소치보다 낮을 수 없습니다.' using errcode = 'P0001';
      end if;
    end loop;
  end loop;

  v_delegate := (v_payload - 'difficulty') || jsonb_build_object('difficulty', 'NORMAL');
  v_response := public.kinojo_sanctuary_management_command_v453(
    p_credential, p_request_key, v_action, v_delegate, p_expected_revision
  );
  v_team_id := nullif(v_response->>'teamId', '')::bigint;

  for v_force, v_force_no in
    select force_item, ordinality::integer
    from jsonb_array_elements(coalesce(v_payload->'composition', '[]'::jsonb))
      with ordinality source(force_item, ordinality)
  loop
    v_difficulty := upper(coalesce(nullif(v_force->>'difficulty', ''), nullif(v_payload->>'difficulty', ''), 'NORMAL'));
    update private.sanctuary_management_forces_v412
       set difficulty = v_difficulty, updated_at = clock_timestamp()
     where team_id = v_team_id and force_no = v_force_no;
  end loop;
  update private.sanctuary_management_teams_v412
     set difficulty = case when v_all_hard then 'HARD' else 'NORMAL' end,
         updated_at = clock_timestamp()
   where team_id = v_team_id;

  return v_response || jsonb_build_object(
    'difficultyScope', 'FORCE',
    'apiVersion', 2.2,
    'schemaVersion', 454,
    'databaseContract', 454
  );
end
$function$;
