from pathlib import Path

path = Path('tools/stage5_3_patch.py')
text = path.read_text(encoding='utf-8')
admin_old = '''for page in ["admin/index.html", "m/admin/index.html"]:\n    insert_before(page, '        <section class="admin-card admin-meter-release-card">\\n', stats_card)\n    rep(page, '../core/kinojo-supabase-features.js?cache=2026080205', '../core/kinojo-supabase-features.js?cache=2026080701')\n    rep(page, './js/admin.js?cache=2026080601', './js/admin.js?cache=2026080701')\n'''
admin_new = '''for page in ["admin/index.html", "m/admin/index.html"]:\n    insert_before(page, '        <section class="admin-card admin-meter-release-card">\\n', stats_card)\nrep('admin/index.html', '../core/kinojo-supabase-features.js?cache=2026080205', '../core/kinojo-supabase-features.js?cache=2026080701')\nrep('admin/index.html', './js/admin.js?cache=2026080601', './js/admin.js?cache=2026080701')\nrep('m/admin/index.html', '../../core/kinojo-supabase-features.js?cache=2026080205', '../../core/kinojo-supabase-features.js?cache=2026080701')\nrep('m/admin/index.html', '../../admin/js/admin.js?cache=2026080601', '../../admin/js/admin.js?cache=2026080701')\n'''
meter_old = '''for page in ["meter/index.html", "m/meter/index.html"]:\n    rep(page, 'RECENT CAPTURES · OWNER ONLY', 'RECENT COMBAT · OWNER ONLY')\n    rep(page, '최근 수집 기록', '최근 전투 기록')\n    rep(page, '<div class="meter-observed-policy"><strong>검증 전 실제 수집 데이터</strong><span>현재 Decoder가 읽은 범위만 표시하며 공개 통계·랭킹에는 포함하지 않습니다.</span></div>', '<div class="meter-observed-policy"><strong>Server 저장·검증 상태</strong><span>모든 실제 전투를 보존하고 검증 상태를 표시합니다. 공개 통계는 Server 적격 판정과 관리자 공개 설정을 모두 충족한 기록만 사용합니다.</span></div>')\n    rep(page, 'PASS KEY 로그인 후 이 계정에서 업로드한 기록을 확인할 수 있습니다.', 'PASS KEY 로그인 후 이 계정에서 업로드한 최근 전투와 Server 검증 상태를 확인할 수 있습니다.')\n    rep(page, './js/meter-app.js?cache=2026080601', './js/meter-app.js?cache=2026080701')\n'''
meter_new = '''for page in ["meter/index.html", "m/meter/index.html"]:\n    rep(page, 'RECENT CAPTURES · OWNER ONLY', 'RECENT COMBAT · OWNER ONLY')\n    rep(page, '최근 수집 기록', '최근 전투 기록')\n    rep(page, '<div class="meter-observed-policy"><strong>검증 전 실제 수집 데이터</strong><span>현재 Decoder가 읽은 범위만 표시하며 공개 통계·랭킹에는 포함하지 않습니다.</span></div>', '<div class="meter-observed-policy"><strong>Server 저장·검증 상태</strong><span>모든 실제 전투를 보존하고 검증 상태를 표시합니다. 공개 통계는 Server 적격 판정과 관리자 공개 설정을 모두 충족한 기록만 사용합니다.</span></div>')\n    rep(page, 'PASS KEY 로그인 후 이 계정에서 업로드한 기록을 확인할 수 있습니다.', 'PASS KEY 로그인 후 이 계정에서 업로드한 최근 전투와 Server 검증 상태를 확인할 수 있습니다.')\nrep('meter/index.html', './js/meter-app.js?cache=2026080601', './js/meter-app.js?cache=2026080701')\nrep('m/meter/index.html', '../../meter/js/meter-app.js?cache=2026080601', '../../meter/js/meter-app.js?cache=2026080701')\n'''
if text.count(admin_old) != 1:
    raise SystemExit('mobile admin path patch marker mismatch')
text = text.replace(admin_old, admin_new)
if text.count(meter_old) != 1:
    raise SystemExit('mobile meter path patch marker mismatch')
text = text.replace(meter_old, meter_new)
path.write_text(text, encoding='utf-8')
