-- KINOJO banner Phase 2 Stage 7: 99-item bundles, character links,
-- per-format representatives, and eventless automatic library pools.
-- All public tables remain closed to direct clients. MASTER-only RPCs are
-- called through kinojo-banner-media with the service role.

do $migration$
declare
  v_definition text;
begin
  select pg_catalog.pg_get_functiondef(
    'public.kinojo_banner_event_save_v391(text,uuid,jsonb)'::pg_catalog.regprocedure
  ) into v_definition;
  if pg_catalog.strpos(v_definition,'jsonb_array_length(v_items)>3')=0 then
    raise exception 'BANNER_EVENT_SAVE_V391_LIMIT_SIGNATURE_CHANGED';
  end if;
  execute pg_catalog.replace(
    v_definition,
    'jsonb_array_length(v_items)>3',
    'jsonb_array_length(v_items)>99'
  );

  select pg_catalog.pg_get_functiondef(
    'private.kinojo_banner_campaign_validate_items_v386(bigint,text,jsonb,boolean)'::pg_catalog.regprocedure
  ) into v_definition;
  if pg_catalog.strpos(v_definition,'jsonb_array_length(p_items) > 100')=0 then
    raise exception 'BANNER_CAMPAIGN_VALIDATE_V386_LIMIT_SIGNATURE_CHANGED';
  end if;
  execute pg_catalog.replace(
    v_definition,
    'jsonb_array_length(p_items) > 100',
    'jsonb_array_length(p_items) > 99'
  );
end
$migration$;

create table if not exists public.kinojo_banner_asset_characters_v407 (
  asset_id bigint primary key references public.kinojo_banner_assets(asset_id) on delete cascade,
  character_id bigint not null references public.character_master(id) on delete restrict,
  linked_name_snapshot text not null,
  linked_server_id_snapshot integer not null,
  created_by_member_id bigint,
  updated_by_member_id bigint,
  created_at timestamptz not null default clock_timestamp(),
  updated_at timestamptz not null default clock_timestamp(),
  constraint kinojo_banner_asset_character_name_v407_chk
    check (char_length(btrim(linked_name_snapshot)) between 1 and 60)
);

create index if not exists kinojo_banner_asset_characters_character_v407_idx
  on public.kinojo_banner_asset_characters_v407(character_id,asset_id);

create table if not exists public.kinojo_banner_asset_representatives_v407 (
  character_id bigint not null references public.character_master(id) on delete restrict,
  format_code text not null,
  asset_id bigint not null references public.kinojo_banner_assets(asset_id) on delete cascade,
  created_by_member_id bigint,
  updated_by_member_id bigint,
  created_at timestamptz not null default clock_timestamp(),
  updated_at timestamptz not null default clock_timestamp(),
  primary key(character_id,format_code),
  constraint kinojo_banner_asset_representative_format_v407_chk
    check (format_code in ('MAIN_16_9','SIDE_300_715'))
);

create unique index if not exists kinojo_banner_asset_representatives_asset_v407_uidx
  on public.kinojo_banner_asset_representatives_v407(asset_id,format_code);

create table if not exists public.kinojo_banner_auto_pools_v407 (
  pool_id bigint generated by default as identity primary key,
  pool_name text not null,
  format_code text not null,
  target_pages text[] not null default '{}'::text[],
  slot_codes text[] not null default '{}'::text[],
  tags text[] not null default '{}'::text[],
  character_ids bigint[] not null default '{}'::bigint[],
  representative_only boolean not null default false,
  max_per_character integer not null default 99,
  show_character_name boolean not null default false,
  strip_background_color text not null default '#111827',
  strip_text_color text not null default '#FFFFFF',
  strip_opacity integer not null default 78,
  strip_height_percent integer not null default 14,
  slide_interval_ms integer not null default 8000,
  transition_duration_ms integer not null default 600,
  transition_effect text not null default 'CROSSFADE',
  transition_direction text not null default 'NONE',
  priority integer not null default 100,
  starts_at timestamptz,
  ends_at timestamptz,
  is_enabled boolean not null default false,
  created_by_member_id bigint,
  updated_by_member_id bigint,
  created_at timestamptz not null default clock_timestamp(),
  updated_at timestamptz not null default clock_timestamp(),
  constraint kinojo_banner_auto_pool_name_v407_chk
    check (char_length(btrim(pool_name)) between 1 and 120),
  constraint kinojo_banner_auto_pool_format_v407_chk
    check (format_code in ('MAIN_16_9','SIDE_300_715')),
  constraint kinojo_banner_auto_pool_target_pages_v407_chk
    check (cardinality(target_pages) between 1 and 7),
  constraint kinojo_banner_auto_pool_slots_v407_chk
    check (cardinality(slot_codes) between 1 and 2),
  constraint kinojo_banner_auto_pool_tags_v407_chk check (cardinality(tags)<=5),
  constraint kinojo_banner_auto_pool_characters_v407_chk check (cardinality(character_ids)<=99),
  constraint kinojo_banner_auto_pool_max_character_v407_chk check (max_per_character between 1 and 99),
  constraint kinojo_banner_auto_pool_strip_bg_v407_chk check (strip_background_color ~ '^#[0-9A-F]{6}$'),
  constraint kinojo_banner_auto_pool_strip_text_v407_chk check (strip_text_color ~ '^#[0-9A-F]{6}$'),
  constraint kinojo_banner_auto_pool_strip_opacity_v407_chk check (strip_opacity between 0 and 100),
  constraint kinojo_banner_auto_pool_strip_height_v407_chk check (strip_height_percent between 6 and 30),
  constraint kinojo_banner_auto_pool_slide_v407_chk check (slide_interval_ms between 3000 and 60000),
  constraint kinojo_banner_auto_pool_transition_v407_chk check (transition_duration_ms between 0 and 5000),
  constraint kinojo_banner_auto_pool_effect_v407_chk
    check (transition_effect in ('NONE','CROSSFADE','SLIDE','SLIDE_FADE','ZOOM')),
  constraint kinojo_banner_auto_pool_direction_v407_chk
    check (transition_direction in ('NONE','LEFT_TO_RIGHT','RIGHT_TO_LEFT','TOP_TO_BOTTOM','BOTTOM_TO_TOP')),
  constraint kinojo_banner_auto_pool_priority_v407_chk check (priority between 0 and 10000),
  constraint kinojo_banner_auto_pool_range_v407_chk check (ends_at is null or starts_at is null or ends_at>starts_at)
);

create unique index if not exists kinojo_banner_auto_pool_name_v407_uidx
  on public.kinojo_banner_auto_pools_v407(lower(btrim(pool_name)));
create index if not exists kinojo_banner_auto_pool_active_v407_idx
  on public.kinojo_banner_auto_pools_v407(is_enabled,format_code,priority desc,updated_at desc);

create table if not exists public.kinojo_banner_auto_pool_assets_v407 (
  pool_id bigint not null references public.kinojo_banner_auto_pools_v407(pool_id) on delete cascade,
  asset_id bigint not null references public.kinojo_banner_assets(asset_id) on delete cascade,
  sort_order integer not null default 0,
  created_at timestamptz not null default clock_timestamp(),
  primary key(pool_id,asset_id),
  constraint kinojo_banner_auto_pool_asset_sort_v407_chk check (sort_order between 0 and 98)
);

create index if not exists kinojo_banner_auto_pool_assets_order_v407_idx
  on public.kinojo_banner_auto_pool_assets_v407(pool_id,sort_order,asset_id);

create table if not exists public.kinojo_banner_auto_pool_composites_v407 (
  pool_id bigint not null references public.kinojo_banner_auto_pools_v407(pool_id) on delete cascade,
  asset_id bigint not null references public.kinojo_banner_assets(asset_id) on delete cascade,
  object_path text not null,
  mime_type text not null,
  size_bytes bigint not null,
  width integer not null,
  height integer not null,
  source_hash text not null,
  created_by_member_id bigint,
  created_at timestamptz not null default clock_timestamp(),
  updated_at timestamptz not null default clock_timestamp(),
  primary key(pool_id,asset_id),
  constraint kinojo_banner_auto_pool_composite_path_v407_chk
    check (object_path ~ '^[0-9]{4}/[0-9]{2}/[0-9a-f-]{36}\\.(jpg|jpeg|png|webp)$'),
  constraint kinojo_banner_auto_pool_composite_mime_v407_chk
    check (mime_type in ('image/jpeg','image/png','image/webp')),
  constraint kinojo_banner_auto_pool_composite_size_v407_chk check (size_bytes between 1 and 5242880),
  constraint kinojo_banner_auto_pool_composite_hash_v407_chk check (source_hash ~ '^[0-9a-f]{64}$')
);

alter table public.kinojo_banner_asset_characters_v407 enable row level security;
alter table public.kinojo_banner_asset_representatives_v407 enable row level security;
alter table public.kinojo_banner_auto_pools_v407 enable row level security;
alter table public.kinojo_banner_auto_pool_assets_v407 enable row level security;
alter table public.kinojo_banner_auto_pool_composites_v407 enable row level security;

revoke all on table public.kinojo_banner_asset_characters_v407 from public,anon,authenticated;
revoke all on table public.kinojo_banner_asset_representatives_v407 from public,anon,authenticated;
revoke all on table public.kinojo_banner_auto_pools_v407 from public,anon,authenticated;
revoke all on table public.kinojo_banner_auto_pool_assets_v407 from public,anon,authenticated;
revoke all on table public.kinojo_banner_auto_pool_composites_v407 from public,anon,authenticated;

create or replace function private.kinojo_banner_character_json_v407(
  p_character_id bigint
) returns jsonb
language sql
stable
security definer
set search_path=pg_catalog,public,private
as $function$
  select case when c.id is null then null else pg_catalog.jsonb_build_object(
    'characterId',c.id,
    'characterName',c.character_name,
    'serverId',c.server_id,
    'serverName',coalesce(nullif(c.server_name,''),s.server_name),
    'raceId',s.race_id,
    'className',c.class_name,
    'isActive',c.is_active,
    'identityStatus',c.identity_status,
    'lookupExcluded',c.lookup_excluded,
    'duplicateNameCount',(
      select pg_catalog.count(*)::integer
      from public.character_master d
      where pg_catalog.lower(pg_catalog.btrim(d.character_name))=pg_catalog.lower(pg_catalog.btrim(c.character_name))
        and d.is_active and d.identity_status='CURRENT' and not d.lookup_excluded
    )
  ) end
  from public.character_master c
  left join public.server_master s on s.server_id=c.server_id
  where c.id=p_character_id
$function$;

create or replace function private.kinojo_banner_asset_character_json_v407(
  p_asset_id bigint
) returns jsonb
language sql
stable
security definer
set search_path=pg_catalog,public,private
as $function$
  select case when l.asset_id is null then null else
    private.kinojo_banner_character_json_v407(l.character_id)
    || pg_catalog.jsonb_build_object(
      'linkedNameSnapshot',l.linked_name_snapshot,
      'linkedServerIdSnapshot',l.linked_server_id_snapshot,
      'linkState',case
        when c.id is null then 'MISSING'
        when not c.is_active or c.identity_status<>'CURRENT' or c.lookup_excluded then 'INACTIVE'
        when c.character_name is distinct from l.linked_name_snapshot or c.server_id is distinct from l.linked_server_id_snapshot then 'CHANGED'
        else 'CURRENT'
      end
    ) end
  from public.kinojo_banner_asset_characters_v407 l
  left join public.character_master c on c.id=l.character_id
  where l.asset_id=p_asset_id
$function$;

create or replace function private.kinojo_banner_asset_json_v407(
  a public.kinojo_banner_assets
) returns jsonb
language sql
stable
security definer
set search_path=pg_catalog,public,private
as $function$
  select private.kinojo_banner_asset_json_v406(a)
    || pg_catalog.jsonb_build_object(
      'character',private.kinojo_banner_asset_character_json_v407(a.asset_id),
      'representativeFormats',coalesce((
        select pg_catalog.jsonb_agg(r.format_code order by r.format_code)
        from public.kinojo_banner_asset_representatives_v407 r
        where r.asset_id=a.asset_id
      ),'[]'::jsonb),
      'autoPoolCount',(
        select pg_catalog.count(distinct pa.pool_id)::integer
        from public.kinojo_banner_auto_pool_assets_v407 pa
        where pa.asset_id=a.asset_id
      )
    )
$function$;

create or replace function private.kinojo_banner_auto_pool_source_hash_v407(
  p_pool_id bigint,
  p_asset_id bigint
) returns text
language sql
stable
security definer
set search_path=pg_catalog,public,private
as $function$
  select pg_catalog.encode(extensions.digest(
    pg_catalog.concat_ws('|',p.pool_id,a.asset_id,a.updated_at::text,c.id,c.character_name,c.server_id,
      p.strip_background_color,p.strip_text_color,p.strip_opacity,p.strip_height_percent),
    'sha256'),'hex')
  from public.kinojo_banner_auto_pools_v407 p
  join public.kinojo_banner_auto_pool_assets_v407 pa on pa.pool_id=p.pool_id and pa.asset_id=p_asset_id
  join public.kinojo_banner_assets a on a.asset_id=pa.asset_id
  join public.kinojo_banner_asset_characters_v407 l on l.asset_id=a.asset_id
  join public.character_master c on c.id=l.character_id
  where p.pool_id=p_pool_id
$function$;

create or replace function private.kinojo_banner_auto_color_v407(
  p_asset_id bigint,
  p_character_id bigint
) returns jsonb
language sql
immutable
security definer
set search_path=pg_catalog,public,private
as $function$
  with h as (
    select pg_catalog.md5(coalesce(p_asset_id,0)::text||'|'||coalesce(p_character_id,0)::text) value
  ), c as (
    select ('#'||pg_catalog.upper(pg_catalog.substr(value,1,6))) background,
      (('x'||pg_catalog.substr(value,1,2))::bit(8)::integer
       +('x'||pg_catalog.substr(value,3,2))::bit(8)::integer
       +('x'||pg_catalog.substr(value,5,2))::bit(8)::integer) brightness
    from h
  )
  select pg_catalog.jsonb_build_object(
    'backgroundColor',background,
    'textColor',case when brightness>382 then '#111827' else '#FFFFFF' end
  ) from c
$function$;

create or replace function private.kinojo_banner_bigint_array_v407(
  p_value jsonb,
  p_max integer default 99
) returns bigint[]
language plpgsql
immutable
security definer
set search_path=pg_catalog,public,private
as $function$
declare
  v_result bigint[]:='{}'::bigint[];
  v_raw text;
  v_id bigint;
begin
  if p_value is null then return v_result; end if;
  if pg_catalog.jsonb_typeof(p_value)<>'array' or pg_catalog.jsonb_array_length(p_value)>p_max then
    raise exception using errcode='P0001',message='BANNER_ARRAY_INVALID';
  end if;
  for v_raw in select value from pg_catalog.jsonb_array_elements_text(p_value)
  loop
    begin v_id:=v_raw::bigint; exception when others then
      raise exception using errcode='P0001',message='BANNER_ARRAY_INVALID';
    end;
    if v_id<=0 or v_id=any(v_result) then
      raise exception using errcode='P0001',message='BANNER_ARRAY_INVALID';
    end if;
    v_result:=pg_catalog.array_append(v_result,v_id);
  end loop;
  return v_result;
end
$function$;

create or replace function private.kinojo_banner_auto_pool_candidates_v407(
  p_pool_id bigint
) returns table(asset_id bigint,character_id bigint,character_name text,sort_order integer)
language sql
stable
security definer
set search_path=pg_catalog,public,private
as $function$
  with eligible as (
    select
      a.asset_id,l.character_id,c.character_name,pa.sort_order,
      pg_catalog.row_number() over(
        partition by coalesce(l.character_id,-a.asset_id)
        order by pa.sort_order,a.asset_id
      ) per_character_rank
    from public.kinojo_banner_auto_pools_v407 p
    join public.kinojo_banner_auto_pool_assets_v407 pa on pa.pool_id=p.pool_id
    join public.kinojo_banner_assets a on a.asset_id=pa.asset_id
    left join public.kinojo_banner_asset_characters_v407 l on l.asset_id=a.asset_id
    left join public.character_master c on c.id=l.character_id
    where p.pool_id=p_pool_id
      and a.status='READY' and a.delete_token is null and a.format_code=p.format_code
      and (cardinality(p.tags)=0 or a.tags && p.tags)
      and (cardinality(p.character_ids)=0 or l.character_id=any(p.character_ids))
      and (not p.representative_only or exists(
        select 1 from public.kinojo_banner_asset_representatives_v407 r
        where r.character_id=l.character_id and r.format_code=p.format_code and r.asset_id=a.asset_id
      ))
      and (not p.show_character_name or (
        c.id is not null and c.is_active and c.identity_status='CURRENT' and not c.lookup_excluded
      ))
  )
  select e.asset_id,e.character_id,e.character_name,e.sort_order
  from eligible e
  join public.kinojo_banner_auto_pools_v407 p on p.pool_id=p_pool_id
  where e.per_character_rank<=p.max_per_character
$function$;

create or replace function private.kinojo_banner_auto_pool_json_v407(
  p_pool_id bigint
) returns jsonb
language sql
stable
security definer
set search_path=pg_catalog,public,private
as $function$
  select pg_catalog.jsonb_build_object(
    'poolId',p.pool_id,'name',p.pool_name,'formatCode',p.format_code,
    'targetPages',pg_catalog.to_jsonb(p.target_pages),'slotCodes',pg_catalog.to_jsonb(p.slot_codes),
    'tags',pg_catalog.to_jsonb(p.tags),'characterIds',pg_catalog.to_jsonb(p.character_ids),
    'representativeOnly',p.representative_only,'maxPerCharacter',p.max_per_character,
    'showCharacterName',p.show_character_name,
    'strip',pg_catalog.jsonb_build_object(
      'backgroundColor',p.strip_background_color,'textColor',p.strip_text_color,
      'opacity',p.strip_opacity,'heightPercent',p.strip_height_percent
    ),
    'slideIntervalMs',p.slide_interval_ms,'transitionDurationMs',p.transition_duration_ms,
    'transitionEffect',p.transition_effect,'transitionDirection',p.transition_direction,
    'priority',p.priority,'startsAt',p.starts_at,'endsAt',p.ends_at,'isEnabled',p.is_enabled,
    'priorityMode','AFTER_FORMAL_EVENTS',
    'assets',coalesce((
      select pg_catalog.jsonb_agg(
        private.kinojo_banner_asset_json_v407(a)
        || pg_catalog.jsonb_build_object(
          'poolSortOrder',pa.sort_order,
          'poolEligible',exists(select 1 from private.kinojo_banner_auto_pool_candidates_v407(p.pool_id) e where e.asset_id=a.asset_id),
          'poolCompositeReady',coalesce(pc.source_hash=private.kinojo_banner_auto_pool_source_hash_v407(p.pool_id,a.asset_id),false),
          'recommendedStrip',private.kinojo_banner_auto_color_v407(a.asset_id,l.character_id)
        ) order by pa.sort_order,a.asset_id
      )
      from public.kinojo_banner_auto_pool_assets_v407 pa
      join public.kinojo_banner_assets a on a.asset_id=pa.asset_id
      left join public.kinojo_banner_asset_characters_v407 l on l.asset_id=a.asset_id
      left join public.kinojo_banner_auto_pool_composites_v407 pc
        on pc.pool_id=pa.pool_id and pc.asset_id=pa.asset_id
      where pa.pool_id=p.pool_id
    ),'[]'::jsonb),
    'eligibleCount',(select pg_catalog.count(*)::integer from private.kinojo_banner_auto_pool_candidates_v407(p.pool_id)),
    'compositeReadyCount',(
      select pg_catalog.count(*)::integer
      from private.kinojo_banner_auto_pool_candidates_v407(p.pool_id) e
      join public.kinojo_banner_auto_pool_composites_v407 pc on pc.pool_id=p.pool_id and pc.asset_id=e.asset_id
      where pc.source_hash=private.kinojo_banner_auto_pool_source_hash_v407(p.pool_id,e.asset_id)
    )
  )
  from public.kinojo_banner_auto_pools_v407 p
  where p.pool_id=p_pool_id
$function$;

create or replace function public.kinojo_banner_auto_pool_list_v407(
  p_session_token text
) returns jsonb
language plpgsql
stable
security definer
set search_path=pg_catalog,public,private
as $function$
declare
  v_gate jsonb;
  v_pools jsonb;
begin
  v_gate:=private.kinojo_banner_require_master_v384(p_session_token);
  if coalesce((v_gate->>'ok')::boolean,false) is not true then return v_gate; end if;
  select coalesce(pg_catalog.jsonb_agg(private.kinojo_banner_auto_pool_json_v407(p.pool_id)
    order by p.is_enabled desc,p.priority desc,p.updated_at desc,p.pool_id desc),'[]'::jsonb)
  into v_pools from public.kinojo_banner_auto_pools_v407 p;
  return pg_catalog.jsonb_build_object(
    'ok',true,'apiVersion','407','contract','banner-auto-pool-list-v407',
    'priorityMode','AFTER_FORMAL_EVENTS','maxAssets',99,'pools',v_pools
  );
end
$function$;

create or replace function public.kinojo_banner_auto_pool_save_v407(
  p_session_token text,
  p_pool_id bigint,
  p_payload jsonb
) returns jsonb
language plpgsql
security definer
set search_path=pg_catalog,public,private
as $function$
declare
  v_gate jsonb;
  v_member bigint;
  v_pool public.kinojo_banner_auto_pools_v407;
  v_name text;
  v_format text;
  v_pages text[];
  v_slots text[];
  v_tags text[];
  v_character_ids bigint[];
  v_asset_ids bigint[];
  v_asset_id bigint;
  v_index integer:=0;
  v_representative_only boolean;
  v_max_per_character integer;
  v_show_name boolean;
  v_bg text;
  v_text text;
  v_opacity integer;
  v_height integer;
  v_slide integer;
  v_transition integer;
  v_effect text;
  v_direction text;
  v_priority integer;
  v_starts timestamptz;
  v_ends timestamptz;
begin
  v_gate:=private.kinojo_banner_require_master_v384(p_session_token);
  if coalesce((v_gate->>'ok')::boolean,false) is not true then return v_gate; end if;
  v_member:=(v_gate->>'memberId')::bigint;
  if p_payload is null or pg_catalog.jsonb_typeof(p_payload)<>'object' then
    return pg_catalog.jsonb_build_object('ok',false,'code','BANNER_AUTO_POOL_PAYLOAD_INVALID');
  end if;
  if p_pool_id is not null then
    select * into v_pool from public.kinojo_banner_auto_pools_v407 where pool_id=p_pool_id for update;
    if not found then return pg_catalog.jsonb_build_object('ok',false,'code','BANNER_AUTO_POOL_NOT_FOUND'); end if;
  end if;
  v_name:=pg_catalog.btrim(coalesce(p_payload->>'name',v_pool.pool_name,''));
  v_format:=pg_catalog.upper(pg_catalog.btrim(coalesce(p_payload->>'formatCode',v_pool.format_code,'')));
  begin
    v_pages:=private.kinojo_banner_text_array_v386(coalesce(p_payload->'targetPages',pg_catalog.to_jsonb(v_pool.target_pages)));
    v_slots:=private.kinojo_banner_text_array_v386(coalesce(p_payload->'slotCodes',pg_catalog.to_jsonb(v_pool.slot_codes)));
    v_tags:=private.kinojo_banner_tags_normalize_v391(coalesce(p_payload->'tags',pg_catalog.to_jsonb(v_pool.tags)));
    v_character_ids:=private.kinojo_banner_bigint_array_v407(coalesce(p_payload->'characterIds',pg_catalog.to_jsonb(v_pool.character_ids)),99);
    v_asset_ids:=private.kinojo_banner_bigint_array_v407(coalesce(p_payload->'assetIds',(
      select coalesce(pg_catalog.jsonb_agg(pa.asset_id order by pa.sort_order,pa.asset_id),'[]'::jsonb)
      from public.kinojo_banner_auto_pool_assets_v407 pa where pa.pool_id=p_pool_id
    )),99);
  exception when sqlstate 'P0001' then
    return pg_catalog.jsonb_build_object('ok',false,'code','BANNER_AUTO_POOL_ARRAY_INVALID');
  end;
  if char_length(v_name) not between 1 and 120 then return pg_catalog.jsonb_build_object('ok',false,'code','BANNER_AUTO_POOL_NAME_INVALID'); end if;
  if v_format not in ('MAIN_16_9','SIDE_300_715') then return pg_catalog.jsonb_build_object('ok',false,'code','BANNER_AUTO_POOL_FORMAT_INVALID'); end if;
  if cardinality(v_asset_ids)>99 then return pg_catalog.jsonb_build_object('ok',false,'code','BANNER_AUTO_POOL_ASSETS_MAX_99'); end if;
  if cardinality(v_pages)<1 or cardinality(v_slots)<1 then return pg_catalog.jsonb_build_object('ok',false,'code','BANNER_AUTO_POOL_TARGET_REQUIRED'); end if;
  if exists(select 1 from pg_catalog.unnest(v_pages) p(page_code) where p.page_code<>all(private.kinojo_banner_supported_page_codes_v404())) then
    return pg_catalog.jsonb_build_object('ok',false,'code','BANNER_AUTO_POOL_TARGET_INVALID');
  end if;
  if (v_format='MAIN_16_9' and (v_pages<>array['HOME']::text[] or v_slots<>array['MAIN']::text[]))
     or (v_format='SIDE_300_715' and (exists(select 1 from pg_catalog.unnest(v_slots) s(slot_code) where s.slot_code not in ('LEFT','RIGHT'))
       or ('HOF'=any(v_pages) and 'RIGHT'=any(v_slots)))) then
    return pg_catalog.jsonb_build_object('ok',false,'code','BANNER_AUTO_POOL_TARGET_FORMAT_MISMATCH');
  end if;
  if exists(
    select 1 from pg_catalog.unnest(v_asset_ids) x(asset_id)
    left join public.kinojo_banner_assets a on a.asset_id=x.asset_id
    where a.asset_id is null or a.status<>'READY' or a.delete_token is not null or a.format_code<>v_format
  ) then return pg_catalog.jsonb_build_object('ok',false,'code','BANNER_AUTO_POOL_ASSET_INVALID'); end if;
  if exists(
    select 1 from pg_catalog.unnest(v_character_ids) x(character_id)
    left join public.character_master c on c.id=x.character_id
    where c.id is null or not c.is_active or c.identity_status<>'CURRENT' or c.lookup_excluded
  ) then return pg_catalog.jsonb_build_object('ok',false,'code','BANNER_AUTO_POOL_CHARACTER_INVALID'); end if;

  begin
    v_representative_only:=coalesce((p_payload->>'representativeOnly')::boolean,v_pool.representative_only,false);
    v_max_per_character:=coalesce(nullif(p_payload->>'maxPerCharacter','')::integer,v_pool.max_per_character,99);
    v_show_name:=coalesce((p_payload->>'showCharacterName')::boolean,v_pool.show_character_name,false);
    v_bg:=pg_catalog.upper(coalesce(p_payload#>>'{strip,backgroundColor}',v_pool.strip_background_color,'#111827'));
    v_text:=pg_catalog.upper(coalesce(p_payload#>>'{strip,textColor}',v_pool.strip_text_color,'#FFFFFF'));
    v_opacity:=coalesce(nullif(p_payload#>>'{strip,opacity}','')::integer,v_pool.strip_opacity,78);
    v_height:=coalesce(nullif(p_payload#>>'{strip,heightPercent}','')::integer,v_pool.strip_height_percent,14);
    v_slide:=coalesce(nullif(p_payload->>'slideIntervalMs','')::integer,v_pool.slide_interval_ms,8000);
    v_transition:=coalesce(nullif(p_payload->>'transitionDurationMs','')::integer,v_pool.transition_duration_ms,600);
    v_effect:=pg_catalog.upper(coalesce(p_payload->>'transitionEffect',v_pool.transition_effect,'CROSSFADE'));
    v_direction:=pg_catalog.upper(coalesce(p_payload->>'transitionDirection',v_pool.transition_direction,'NONE'));
    v_priority:=coalesce(nullif(p_payload->>'priority','')::integer,v_pool.priority,100);
    v_starts:=case when p_payload ? 'startsAtKst' then private.kinojo_banner_parse_kst_v386(p_payload->>'startsAtKst') else v_pool.starts_at end;
    v_ends:=case when p_payload ? 'endsAtKst' then private.kinojo_banner_parse_kst_v386(p_payload->>'endsAtKst') else v_pool.ends_at end;
  exception when others then return pg_catalog.jsonb_build_object('ok',false,'code','BANNER_AUTO_POOL_SETTING_INVALID'); end;
  if v_max_per_character not between 1 and 99 or v_opacity not between 0 and 100 or v_height not between 6 and 30
     or v_slide not between 3000 and 60000 or v_transition not between 0 and 5000 or v_priority not between 0 and 10000
     or v_bg !~ '^#[0-9A-F]{6}$' or v_text !~ '^#[0-9A-F]{6}$'
     or v_effect not in ('NONE','CROSSFADE','SLIDE','SLIDE_FADE','ZOOM')
     or v_direction not in ('NONE','LEFT_TO_RIGHT','RIGHT_TO_LEFT','TOP_TO_BOTTOM','BOTTOM_TO_TOP')
     or (v_effect in ('SLIDE','SLIDE_FADE') and v_direction='NONE')
     or (v_effect in ('NONE','CROSSFADE','ZOOM') and v_direction<>'NONE')
     or (v_starts is not null and v_ends is not null and v_ends<=v_starts) then
    return pg_catalog.jsonb_build_object('ok',false,'code','BANNER_AUTO_POOL_SETTING_INVALID');
  end if;

  if p_pool_id is null then
    insert into public.kinojo_banner_auto_pools_v407(
      pool_name,format_code,target_pages,slot_codes,tags,character_ids,representative_only,max_per_character,
      show_character_name,strip_background_color,strip_text_color,strip_opacity,strip_height_percent,
      slide_interval_ms,transition_duration_ms,transition_effect,transition_direction,priority,starts_at,ends_at,
      is_enabled,created_by_member_id,updated_by_member_id
    ) values(
      v_name,v_format,v_pages,v_slots,v_tags,v_character_ids,v_representative_only,v_max_per_character,
      v_show_name,v_bg,v_text,v_opacity,v_height,v_slide,v_transition,v_effect,v_direction,v_priority,v_starts,v_ends,
      false,v_member,v_member
    ) returning * into v_pool;
  else
    update public.kinojo_banner_auto_pools_v407 set
      pool_name=v_name,format_code=v_format,target_pages=v_pages,slot_codes=v_slots,tags=v_tags,
      character_ids=v_character_ids,representative_only=v_representative_only,max_per_character=v_max_per_character,
      show_character_name=v_show_name,strip_background_color=v_bg,strip_text_color=v_text,
      strip_opacity=v_opacity,strip_height_percent=v_height,slide_interval_ms=v_slide,
      transition_duration_ms=v_transition,transition_effect=v_effect,transition_direction=v_direction,
      priority=v_priority,starts_at=v_starts,ends_at=v_ends,is_enabled=false,
      updated_by_member_id=v_member,updated_at=clock_timestamp()
    where pool_id=p_pool_id returning * into v_pool;
  end if;
  delete from public.kinojo_banner_auto_pool_assets_v407 where pool_id=v_pool.pool_id;
  foreach v_asset_id in array v_asset_ids loop
    insert into public.kinojo_banner_auto_pool_assets_v407(pool_id,asset_id,sort_order)
    values(v_pool.pool_id,v_asset_id,v_index);
    v_index:=v_index+1;
  end loop;
  delete from public.kinojo_banner_auto_pool_composites_v407 pc
  where pc.pool_id=v_pool.pool_id
    and pc.source_hash is distinct from private.kinojo_banner_auto_pool_source_hash_v407(pc.pool_id,pc.asset_id);
  return pg_catalog.jsonb_build_object(
    'ok',true,'apiVersion','407','contract','banner-auto-pool-save-v407',
    'pool',private.kinojo_banner_auto_pool_json_v407(v_pool.pool_id),
    'activation','SAVED_DISABLED','requiresExplicitEnable',true
  );
exception
  when unique_violation then return pg_catalog.jsonb_build_object('ok',false,'code','BANNER_AUTO_POOL_NAME_DUPLICATE');
  when check_violation then return pg_catalog.jsonb_build_object('ok',false,'code','BANNER_AUTO_POOL_VALIDATION_FAILED');
end
$function$;

create or replace function public.kinojo_banner_asset_library_v407(
  p_session_token text,
  p_include_archived boolean default false
) returns jsonb
language plpgsql
stable
security definer
set search_path=pg_catalog,public,private
as $function$
declare
  v_gate jsonb;
  v_assets jsonb;
  v_total integer;
  v_ready integer;
  v_archived integer;
  v_in_use integer;
  v_linked integer;
  v_representatives integer;
begin
  v_gate:=private.kinojo_banner_require_master_v384(p_session_token);
  if coalesce((v_gate->>'ok')::boolean,false) is not true then return v_gate; end if;
  select
    coalesce(pg_catalog.jsonb_agg(private.kinojo_banner_asset_json_v407(a) order by a.created_at desc,a.asset_id desc),'[]'::jsonb),
    pg_catalog.count(*)::integer,
    pg_catalog.count(*) filter(where a.status='READY')::integer,
    pg_catalog.count(*) filter(where a.status='ARCHIVED')::integer,
    pg_catalog.count(*) filter(where private.kinojo_banner_asset_ref_count_v384(a.asset_id)>0)::integer,
    pg_catalog.count(*) filter(where exists(select 1 from public.kinojo_banner_asset_characters_v407 l where l.asset_id=a.asset_id))::integer,
    pg_catalog.count(*) filter(where exists(select 1 from public.kinojo_banner_asset_representatives_v407 r where r.asset_id=a.asset_id))::integer
  into v_assets,v_total,v_ready,v_archived,v_in_use,v_linked,v_representatives
  from public.kinojo_banner_assets a
  where coalesce(p_include_archived,false) or a.status='READY';
  return pg_catalog.jsonb_build_object(
    'ok',true,'apiVersion','407','contract','banner-asset-library-v407',
    'memberId',(v_gate->>'memberId')::bigint,
    'assets',v_assets,
    'tagGroups',private.kinojo_banner_asset_tag_groups_v406(p_include_archived),
    'summary',pg_catalog.jsonb_build_object(
      'total',coalesce(v_total,0),'ready',coalesce(v_ready,0),'archived',coalesce(v_archived,0),
      'inUse',coalesce(v_in_use,0),'linked',coalesce(v_linked,0),'representatives',coalesce(v_representatives,0)
    )
  );
end
$function$;

create or replace function public.kinojo_banner_asset_character_set_v407(
  p_session_token text,
  p_asset_id bigint,
  p_character_id bigint,
  p_unlinked_confirmed boolean default false
) returns jsonb
language plpgsql
security definer
set search_path=pg_catalog,public,private
as $function$
declare
  v_gate jsonb;
  v_member bigint;
  v_asset public.kinojo_banner_assets;
  v_character public.character_master;
  v_previous bigint;
begin
  v_gate:=private.kinojo_banner_require_master_v384(p_session_token);
  if coalesce((v_gate->>'ok')::boolean,false) is not true then return v_gate; end if;
  v_member:=(v_gate->>'memberId')::bigint;
  select * into v_asset from public.kinojo_banner_assets where asset_id=p_asset_id for update;
  if not found then return pg_catalog.jsonb_build_object('ok',false,'code','BANNER_ASSET_NOT_FOUND'); end if;
  if v_asset.delete_token is not null then return pg_catalog.jsonb_build_object('ok',false,'code','BANNER_ASSET_NOT_READY'); end if;
  select character_id into v_previous from public.kinojo_banner_asset_characters_v407 where asset_id=p_asset_id;
  if p_character_id is null then
    if coalesce(p_unlinked_confirmed,false) is not true then
      return pg_catalog.jsonb_build_object('ok',false,'code','BANNER_CHARACTER_UNLINK_CONFIRMATION_REQUIRED');
    end if;
    delete from public.kinojo_banner_asset_representatives_v407 where asset_id=p_asset_id;
    delete from public.kinojo_banner_asset_characters_v407 where asset_id=p_asset_id;
  else
    select * into v_character
    from public.character_master
    where id=p_character_id and is_active and identity_status='CURRENT' and not lookup_excluded
    for share;
    if not found then return pg_catalog.jsonb_build_object('ok',false,'code','BANNER_CHARACTER_NOT_ACTIVE'); end if;
    if v_previous is distinct from p_character_id then
      delete from public.kinojo_banner_asset_representatives_v407 where asset_id=p_asset_id;
    end if;
    insert into public.kinojo_banner_asset_characters_v407(
      asset_id,character_id,linked_name_snapshot,linked_server_id_snapshot,
      created_by_member_id,updated_by_member_id
    ) values(
      p_asset_id,p_character_id,v_character.character_name,v_character.server_id,v_member,v_member
    ) on conflict(asset_id) do update set
      character_id=excluded.character_id,
      linked_name_snapshot=excluded.linked_name_snapshot,
      linked_server_id_snapshot=excluded.linked_server_id_snapshot,
      updated_by_member_id=v_member,
      updated_at=clock_timestamp();
  end if;
  select * into v_asset from public.kinojo_banner_assets where asset_id=p_asset_id;
  return pg_catalog.jsonb_build_object(
    'ok',true,'apiVersion','407','contract','banner-asset-character-set-v407',
    'asset',private.kinojo_banner_asset_json_v407(v_asset)
  );
end
$function$;

create or replace function public.kinojo_banner_asset_representative_set_v407(
  p_session_token text,
  p_asset_id bigint,
  p_enabled boolean,
  p_expected_asset_id bigint default null
) returns jsonb
language plpgsql
security definer
set search_path=pg_catalog,public,private
as $function$
declare
  v_gate jsonb;
  v_member bigint;
  v_asset public.kinojo_banner_assets;
  v_character_id bigint;
  v_current bigint;
begin
  v_gate:=private.kinojo_banner_require_master_v384(p_session_token);
  if coalesce((v_gate->>'ok')::boolean,false) is not true then return v_gate; end if;
  v_member:=(v_gate->>'memberId')::bigint;
  select a.* into v_asset
  from public.kinojo_banner_assets a
  join public.kinojo_banner_asset_characters_v407 l on l.asset_id=a.asset_id
  where a.asset_id=p_asset_id and a.status='READY' and a.delete_token is null
  for update of a;
  if not found then return pg_catalog.jsonb_build_object('ok',false,'code','BANNER_REPRESENTATIVE_LINKED_READY_ASSET_REQUIRED'); end if;
  select l.character_id into v_character_id
  from public.kinojo_banner_asset_characters_v407 l
  where l.asset_id=p_asset_id;
  perform 1 from public.character_master c
  where c.id=v_character_id and c.is_active and c.identity_status='CURRENT' and not c.lookup_excluded
  for share;
  if not found then return pg_catalog.jsonb_build_object('ok',false,'code','BANNER_CHARACTER_NOT_ACTIVE'); end if;
  select asset_id into v_current
  from public.kinojo_banner_asset_representatives_v407
  where character_id=v_character_id and format_code=v_asset.format_code
  for update;
  if coalesce(p_enabled,false) then
    if v_current is not null and v_current<>p_asset_id
       and p_expected_asset_id is distinct from v_current then
      return pg_catalog.jsonb_build_object(
        'ok',false,'code','BANNER_REPRESENTATIVE_REPLACE_CONFIRMATION_REQUIRED',
        'currentAssetId',v_current,'requestedAssetId',p_asset_id
      );
    end if;
    insert into public.kinojo_banner_asset_representatives_v407(
      character_id,format_code,asset_id,created_by_member_id,updated_by_member_id
    ) values(v_character_id,v_asset.format_code,p_asset_id,v_member,v_member)
    on conflict(character_id,format_code) do update set
      asset_id=excluded.asset_id,updated_by_member_id=v_member,updated_at=clock_timestamp();
  else
    delete from public.kinojo_banner_asset_representatives_v407
    where character_id=v_character_id and format_code=v_asset.format_code and asset_id=p_asset_id;
  end if;
  return pg_catalog.jsonb_build_object(
    'ok',true,'apiVersion','407','contract','banner-asset-representative-set-v407',
    'characterId',v_character_id,'formatCode',v_asset.format_code,
    'assetId',case when coalesce(p_enabled,false) then p_asset_id else null end,
    'replacedAssetId',case when coalesce(p_enabled,false) and v_current is distinct from p_asset_id then v_current else null end
  );
end
$function$;

create or replace function private.kinojo_banner_auto_pool_source_hash_v407(
  p_pool_id bigint,
  p_asset_id bigint
) returns text
language sql
stable
security definer
set search_path=pg_catalog,public,private
as $function$
  select pg_catalog.encode(extensions.digest(
    pg_catalog.concat_ws('|',p.pool_id,a.asset_id,a.updated_at::text,c.id,c.character_name,c.server_id,
      p.strip_background_color,p.strip_text_color,p.strip_opacity,p.strip_height_percent),
    'sha256'),'hex')
  from public.kinojo_banner_auto_pools_v407 p
  join public.kinojo_banner_auto_pool_assets_v407 pa on pa.pool_id=p.pool_id and pa.asset_id=p_asset_id
  join public.kinojo_banner_assets a on a.asset_id=pa.asset_id
  join public.kinojo_banner_asset_characters_v407 l on l.asset_id=a.asset_id
  join public.character_master c on c.id=l.character_id
  where p.pool_id=p_pool_id
$function$;

create or replace function private.kinojo_banner_auto_color_v407(
  p_asset_id bigint,
  p_character_id bigint
) returns jsonb
language sql
immutable
security definer
set search_path=pg_catalog,public,private
as $function$
  with h as (
    select pg_catalog.md5(coalesce(p_asset_id,0)::text||'|'||coalesce(p_character_id,0)::text) value
  ), c as (
    select ('#'||pg_catalog.upper(pg_catalog.substr(value,1,6))) background,
      (('x'||pg_catalog.substr(value,1,2))::bit(8)::integer
       +('x'||pg_catalog.substr(value,3,2))::bit(8)::integer
       +('x'||pg_catalog.substr(value,5,2))::bit(8)::integer) brightness
    from h
  )
  select pg_catalog.jsonb_build_object(
    'backgroundColor',background,
    'textColor',case when brightness>382 then '#111827' else '#FFFFFF' end
  ) from c
$function$;

create or replace function private.kinojo_banner_asset_character_json_v407(
  p_asset_id bigint
) returns jsonb
language sql
stable
security definer
set search_path=pg_catalog,public,private
as $function$
  select case when l.asset_id is null then null else
    private.kinojo_banner_character_json_v407(l.character_id)
    || pg_catalog.jsonb_build_object(
      'linkedNameSnapshot',l.linked_name_snapshot,
      'linkedServerIdSnapshot',l.linked_server_id_snapshot,
      'linkState',case
        when c.id is null then 'MISSING'
        when not c.is_active or c.identity_status<>'CURRENT' or c.lookup_excluded then 'INACTIVE'
        when c.character_name is distinct from l.linked_name_snapshot or c.server_id is distinct from l.linked_server_id_snapshot then 'CHANGED'
        else 'CURRENT'
      end
    ) end
  from public.kinojo_banner_asset_characters_v407 l
  left join public.character_master c on c.id=l.character_id
  where l.asset_id=p_asset_id
$function$;

create or replace function private.kinojo_banner_asset_json_v407(
  a public.kinojo_banner_assets
) returns jsonb
language sql
stable
security definer
set search_path=pg_catalog,public,private
as $function$
  select private.kinojo_banner_asset_json_v406(a)
    || pg_catalog.jsonb_build_object(
      'character',private.kinojo_banner_asset_character_json_v407(a.asset_id),
      'representativeFormats',coalesce((
        select pg_catalog.jsonb_agg(r.format_code order by r.format_code)
        from public.kinojo_banner_asset_representatives_v407 r
        where r.asset_id=a.asset_id
      ),'[]'::jsonb),
      'autoPoolCount',(
        select pg_catalog.count(distinct pa.pool_id)::integer
        from public.kinojo_banner_auto_pool_assets_v407 pa
        where pa.asset_id=a.asset_id
      )
    )
$function$;

create or replace function public.kinojo_banner_character_search_v407(
  p_session_token text,
  p_query text,
  p_limit integer default 20
) returns jsonb
language plpgsql
stable
security definer
set search_path=pg_catalog,public,private
as $function$
declare
  v_gate jsonb;
  v_query text:=pg_catalog.lower(pg_catalog.btrim(coalesce(p_query,'')));
  v_limit integer:=greatest(1,least(coalesce(p_limit,20),30));
  v_rows jsonb;
begin
  v_gate:=private.kinojo_banner_require_master_v384(p_session_token);
  if coalesce((v_gate->>'ok')::boolean,false) is not true then return v_gate; end if;
  if char_length(v_query)<1 or char_length(v_query)>60 then
    return pg_catalog.jsonb_build_object('ok',false,'code','BANNER_CHARACTER_QUERY_INVALID');
  end if;
  select coalesce(pg_catalog.jsonb_agg(private.kinojo_banner_character_json_v407(q.id)
    order by q.exact_match desc,q.character_name,q.server_id,q.id),'[]'::jsonb)
  into v_rows
  from (
    select c.id,c.character_name,c.server_id,
      (pg_catalog.lower(pg_catalog.btrim(c.character_name))=v_query) exact_match
    from public.character_master c
    where c.is_active and c.identity_status='CURRENT' and not c.lookup_excluded
      and pg_catalog.strpos(pg_catalog.lower(c.character_name),v_query)>0
    order by exact_match desc,c.character_name,c.server_id,c.id
    limit v_limit
  ) q;
  return pg_catalog.jsonb_build_object(
    'ok',true,'apiVersion','407','contract','banner-character-search-v407',
    'query',pg_catalog.btrim(p_query),'characters',v_rows
  );
end
$function$;

create or replace function public.kinojo_banner_character_resolve_v407(
  p_session_token text,
  p_character_id bigint
) returns jsonb
language plpgsql
stable
security definer
set search_path=pg_catalog,public,private
as $function$
declare
  v_gate jsonb;
  v_character jsonb;
begin
  v_gate:=private.kinojo_banner_require_master_v384(p_session_token);
  if coalesce((v_gate->>'ok')::boolean,false) is not true then return v_gate; end if;
  select private.kinojo_banner_character_json_v407(c.id) into v_character
  from public.character_master c
  where c.id=p_character_id and c.is_active and c.identity_status='CURRENT' and not c.lookup_excluded;
  if v_character is null then return pg_catalog.jsonb_build_object('ok',false,'code','BANNER_CHARACTER_NOT_ACTIVE'); end if;
  return pg_catalog.jsonb_build_object(
    'ok',true,'apiVersion','407','contract','banner-character-resolve-v407','character',v_character
  );
end
$function$;

create or replace function public.kinojo_banner_auto_pool_state_v407(
  p_session_token text,
  p_pool_id bigint,
  p_enabled boolean
) returns jsonb
language plpgsql
security definer
set search_path=pg_catalog,public,private
as $function$
declare
  v_gate jsonb;
  v_member bigint;
  v_pool public.kinojo_banner_auto_pools_v407;
  v_eligible integer;
  v_ready integer;
begin
  v_gate:=private.kinojo_banner_require_master_v384(p_session_token);
  if coalesce((v_gate->>'ok')::boolean,false) is not true then return v_gate; end if;
  v_member:=(v_gate->>'memberId')::bigint;
  select * into v_pool from public.kinojo_banner_auto_pools_v407 where pool_id=p_pool_id for update;
  if not found then return pg_catalog.jsonb_build_object('ok',false,'code','BANNER_AUTO_POOL_NOT_FOUND'); end if;
  if coalesce(p_enabled,false) then
    select pg_catalog.count(*)::integer into v_eligible
    from private.kinojo_banner_auto_pool_candidates_v407(p_pool_id);
    if v_eligible<1 then return pg_catalog.jsonb_build_object('ok',false,'code','BANNER_AUTO_POOL_ELIGIBLE_ASSET_REQUIRED'); end if;
    if v_pool.show_character_name then
      select pg_catalog.count(*)::integer into v_ready
      from private.kinojo_banner_auto_pool_candidates_v407(p_pool_id) e
      join public.kinojo_banner_auto_pool_composites_v407 pc on pc.pool_id=p_pool_id and pc.asset_id=e.asset_id
      where pc.source_hash=private.kinojo_banner_auto_pool_source_hash_v407(p_pool_id,e.asset_id);
      if v_ready<>v_eligible then
        return pg_catalog.jsonb_build_object(
          'ok',false,'code','BANNER_AUTO_POOL_COMPOSITES_REQUIRED',
          'eligibleCount',v_eligible,'compositeReadyCount',v_ready
        );
      end if;
    end if;
  end if;
  update public.kinojo_banner_auto_pools_v407 set
    is_enabled=coalesce(p_enabled,false),updated_by_member_id=v_member,updated_at=clock_timestamp()
  where pool_id=p_pool_id;
  return pg_catalog.jsonb_build_object(
    'ok',true,'apiVersion','407','contract','banner-auto-pool-state-v407',
    'pool',private.kinojo_banner_auto_pool_json_v407(p_pool_id)
  );
end
$function$;

create or replace function public.kinojo_banner_auto_pool_delete_v407(
  p_session_token text,
  p_pool_id bigint,
  p_expected_name text
) returns jsonb
language plpgsql
security definer
set search_path=pg_catalog,public,private
as $function$
declare
  v_gate jsonb;
  v_pool public.kinojo_banner_auto_pools_v407;
  v_paths jsonb;
begin
  v_gate:=private.kinojo_banner_require_master_v384(p_session_token);
  if coalesce((v_gate->>'ok')::boolean,false) is not true then return v_gate; end if;
  select * into v_pool from public.kinojo_banner_auto_pools_v407 where pool_id=p_pool_id for update;
  if not found then return pg_catalog.jsonb_build_object('ok',false,'code','BANNER_AUTO_POOL_NOT_FOUND'); end if;
  if v_pool.is_enabled then return pg_catalog.jsonb_build_object('ok',false,'code','BANNER_AUTO_POOL_DISABLE_REQUIRED'); end if;
  if pg_catalog.btrim(coalesce(p_expected_name,''))<>v_pool.pool_name then
    return pg_catalog.jsonb_build_object('ok',false,'code','BANNER_AUTO_POOL_DELETE_CONFIRMATION_MISMATCH');
  end if;
  select coalesce(pg_catalog.jsonb_agg(pc.object_path order by pc.object_path),'[]'::jsonb)
  into v_paths from public.kinojo_banner_auto_pool_composites_v407 pc where pc.pool_id=p_pool_id;
  delete from public.kinojo_banner_auto_pools_v407 where pool_id=p_pool_id;
  return pg_catalog.jsonb_build_object(
    'ok',true,'apiVersion','407','contract','banner-auto-pool-delete-v407',
    'poolId',p_pool_id,'compositeObjectPaths',v_paths
  );
end
$function$;

create or replace function public.kinojo_banner_auto_pool_composite_register_v407(
  p_session_token text,
  p_pool_id bigint,
  p_asset_id bigint,
  p_object_path text,
  p_mime_type text,
  p_size_bytes bigint,
  p_width integer,
  p_height integer
) returns jsonb
language plpgsql
security definer
set search_path=pg_catalog,public,private
as $function$
declare
  v_gate jsonb;
  v_member bigint;
  v_pool public.kinojo_banner_auto_pools_v407;
  v_asset public.kinojo_banner_assets;
  v_hash text;
begin
  v_gate:=private.kinojo_banner_require_master_v384(p_session_token);
  if coalesce((v_gate->>'ok')::boolean,false) is not true then return v_gate; end if;
  v_member:=(v_gate->>'memberId')::bigint;
  select * into v_pool from public.kinojo_banner_auto_pools_v407 where pool_id=p_pool_id for update;
  if not found or not v_pool.show_character_name then
    return pg_catalog.jsonb_build_object('ok',false,'code','BANNER_AUTO_POOL_NAME_COMPOSITE_NOT_CONFIGURED');
  end if;
  select a.* into v_asset
  from public.kinojo_banner_auto_pool_assets_v407 pa
  join public.kinojo_banner_assets a on a.asset_id=pa.asset_id
  where pa.pool_id=p_pool_id and pa.asset_id=p_asset_id and a.status='READY' and a.delete_token is null
  for update of a;
  if not found then return pg_catalog.jsonb_build_object('ok',false,'code','BANNER_AUTO_POOL_ASSET_INVALID'); end if;
  if (v_pool.format_code='MAIN_16_9' and (p_width<>1536 or p_height<>864))
     or (v_pool.format_code='SIDE_300_715' and (p_width<>300 or p_height<>715)) then
    return pg_catalog.jsonb_build_object('ok',false,'code','BANNER_AUTO_POOL_COMPOSITE_DIMENSIONS_INVALID');
  end if;
  if p_mime_type not in ('image/jpeg','image/png','image/webp') or p_size_bytes not between 1 and 5242880
     or coalesce(p_object_path,'') !~ '^[0-9]{4}/[0-9]{2}/[0-9a-f-]{36}\\.(jpg|jpeg|png|webp)$' then
    return pg_catalog.jsonb_build_object('ok',false,'code','BANNER_AUTO_POOL_COMPOSITE_INVALID');
  end if;
  v_hash:=private.kinojo_banner_auto_pool_source_hash_v407(p_pool_id,p_asset_id);
  if v_hash is null then return pg_catalog.jsonb_build_object('ok',false,'code','BANNER_AUTO_POOL_CHARACTER_REQUIRED'); end if;
  insert into public.kinojo_banner_auto_pool_composites_v407(
    pool_id,asset_id,object_path,mime_type,size_bytes,width,height,source_hash,created_by_member_id
  ) values(p_pool_id,p_asset_id,p_object_path,p_mime_type,p_size_bytes,p_width,p_height,v_hash,v_member)
  on conflict(pool_id,asset_id) do update set
    object_path=excluded.object_path,mime_type=excluded.mime_type,size_bytes=excluded.size_bytes,
    width=excluded.width,height=excluded.height,source_hash=excluded.source_hash,
    created_by_member_id=v_member,updated_at=clock_timestamp();
  return pg_catalog.jsonb_build_object(
    'ok',true,'apiVersion','407','contract','banner-auto-pool-composite-register-v407',
    'poolId',p_pool_id,'assetId',p_asset_id,'sourceHash',v_hash,'activation','AUTO_POOL_COMPOSITE_READY'
  );
end
$function$;

create or replace function public.kinojo_banner_event_save_v407(
  p_session_token text,
  p_event_group_id uuid,
  p_payload jsonb
) returns jsonb
language plpgsql
security definer
set search_path=pg_catalog,public,private
as $function$
declare
  v_variant jsonb;
  v_items jsonb;
  v_result jsonb;
begin
  if pg_catalog.jsonb_typeof(p_payload->'variants')='array' then
    for v_variant in select value from pg_catalog.jsonb_array_elements(p_payload->'variants') loop
      v_items:=coalesce(v_variant->'items','[]'::jsonb);
      if pg_catalog.jsonb_typeof(v_items)<>'array' or pg_catalog.jsonb_array_length(v_items)>99 then
        return pg_catalog.jsonb_build_object('ok',false,'code','BANNER_EVENT_ITEMS_MAX_99');
      end if;
    end loop;
  end if;
  v_result:=public.kinojo_banner_event_save_v404(p_session_token,p_event_group_id,p_payload);
  if coalesce((v_result->>'ok')::boolean,false) is not true then return v_result; end if;
  return v_result||pg_catalog.jsonb_build_object(
    'apiVersion','407','contract','banner-event-save-v407','maxItemsPerVariant',99
  );
end
$function$;

create or replace function private.kinojo_banner_auto_playlist_v407(
  p_page_code text,
  p_slot_code text,
  p_now timestamptz
) returns jsonb
language sql
stable
security definer
set search_path=pg_catalog,public,private
as $function$
  with pools as (
    select p.*,
      pg_catalog.floor(extract(epoch from p_now)/300.0)::bigint bucket
    from public.kinojo_banner_auto_pools_v407 p
    where p.is_enabled
      and pg_catalog.upper(pg_catalog.btrim(p_page_code))=any(p.target_pages)
      and pg_catalog.upper(pg_catalog.btrim(p_slot_code))=any(p.slot_codes)
      and (p.starts_at is null or p.starts_at<=p_now)
      and (p.ends_at is null or p.ends_at>p_now)
  ), scored as (
    select p.pool_id,p.priority,p.updated_at,p.bucket,p.show_character_name,
      p.slide_interval_ms,p.transition_duration_ms,p.transition_effect,p.transition_direction,
      e.asset_id,e.character_id,e.character_name,e.sort_order,
      a.source_type,a.static_path,a.object_path,a.default_alt,
      pc.object_path composite_object_path,
      pg_catalog.row_number() over(partition by p.pool_id order by
        pg_catalog.md5(p.bucket::text||'|'||p.pool_id::text||'|'||p_page_code||'|'||p_slot_code||'|'||e.asset_id::text),e.asset_id) current_rank,
      pg_catalog.row_number() over(partition by p.pool_id order by
        pg_catalog.md5((p.bucket-1)::text||'|'||p.pool_id::text||'|'||p_page_code||'|'||p_slot_code||'|'||e.asset_id::text) desc,e.asset_id desc) previous_reverse_rank,
      pg_catalog.count(*) over(partition by p.pool_id) pool_count
    from pools p
    join private.kinojo_banner_auto_pool_candidates_v407(p.pool_id) e on true
    join public.kinojo_banner_assets a on a.asset_id=e.asset_id
    left join public.kinojo_banner_auto_pool_composites_v407 pc
      on pc.pool_id=p.pool_id and pc.asset_id=e.asset_id
      and pc.source_hash=private.kinojo_banner_auto_pool_source_hash_v407(p.pool_id,e.asset_id)
    where not p.show_character_name or pc.object_path is not null
  ), flags as (
    select s.*,
      pg_catalog.max(asset_id) filter(where current_rank=1) over(partition by pool_id)
        =pg_catalog.max(asset_id) filter(where previous_reverse_rank=1) over(partition by pool_id) repeat_boundary
    from scored s
  ), ordered as (
    select f.*,
      case when repeat_boundary and pool_count>1 and current_rank=1 then 2
           when repeat_boundary and pool_count>1 and current_rank=2 then 1
           else current_rank end playback_rank
    from flags f
  )
  select coalesce(pg_catalog.jsonb_agg(pg_catalog.jsonb_build_object(
    'sourceType',case when o.show_character_name then 'STORAGE' else o.source_type end,
    'staticPath',case when o.show_character_name then null else o.static_path end,
    'objectPath',case when o.show_character_name then o.composite_object_path else o.object_path end,
    'alt',coalesce(nullif(o.default_alt,''),o.character_name,''),
    'clickUrl',null,'fitMode','COVER',
    'slideIntervalMs',o.slide_interval_ms,
    'transitionDurationMs',o.transition_duration_ms,
    'transitionEffect',o.transition_effect,'transitionDirection',o.transition_direction,
    'textOverlay',pg_catalog.jsonb_build_object('enabled',false),
    'sourceMode','AUTO_LIBRARY_POOL','characterName',o.character_name
  ) order by o.priority desc,o.updated_at,o.pool_id,o.playback_rank),'[]'::jsonb)
  from ordered o
$function$;

create or replace function private.kinojo_banner_manifest_internal_v407(
  p_page_code text,
  p_slot_code text,
  p_now timestamptz
) returns jsonb
language plpgsql
stable
security definer
set search_path=pg_catalog,public,private
as $function$
declare
  v_base jsonb;
  v_auto jsonb;
  v_playlist jsonb;
  v_next_boundary timestamptz;
  v_valid_until timestamptz;
begin
  v_base:=private.kinojo_banner_manifest_internal_v402(p_page_code,p_slot_code,p_now);
  if coalesce((v_base->>'ok')::boolean,false) is not true then return v_base; end if;
  v_auto:=private.kinojo_banner_auto_playlist_v407(p_page_code,p_slot_code,p_now);
  if pg_catalog.jsonb_array_length(v_auto)=0 then return v_base; end if;
  v_playlist:=coalesce(v_base->'playlist','[]'::jsonb)||v_auto;
  select pg_catalog.min(boundary_at) into v_next_boundary from (
    select p.starts_at boundary_at from public.kinojo_banner_auto_pools_v407 p
    where p.is_enabled and p.starts_at>p_now
      and pg_catalog.upper(pg_catalog.btrim(p_page_code))=any(p.target_pages)
      and pg_catalog.upper(pg_catalog.btrim(p_slot_code))=any(p.slot_codes)
    union all
    select p.ends_at from public.kinojo_banner_auto_pools_v407 p
    where p.is_enabled and p.ends_at>p_now
      and pg_catalog.upper(pg_catalog.btrim(p_page_code))=any(p.target_pages)
      and pg_catalog.upper(pg_catalog.btrim(p_slot_code))=any(p.slot_codes)
  ) b where boundary_at is not null;
  v_valid_until:=least(
    coalesce((v_base->>'validUntil')::timestamptz,p_now+interval '5 minutes'),
    coalesce(v_next_boundary,'infinity'::timestamptz)
  );
  return v_base||pg_catalog.jsonb_build_object(
    'apiVersion','407','contract','banner-manifest-internal-v407',
    'manifestVersion','bm407-'||pg_catalog.substr(pg_catalog.md5(coalesce(v_base->>'manifestVersion','')||'|'||v_playlist::text),1,24),
    'validUntil',pg_catalog.to_char(v_valid_until at time zone 'Asia/Seoul','YYYY-MM-DD"T"HH24:MI:SS')||'+09:00',
    'active',true,'reason',null,'playlist',v_playlist,
    'eventlessAutoPoolMode','AFTER_FORMAL_EVENTS','activeAutoPoolItemCount',pg_catalog.jsonb_array_length(v_auto)
  );
end
$function$;

create or replace function public.kinojo_banner_manifest_v407(
  p_page_code text,
  p_slot_code text
) returns jsonb
language sql
stable
security definer
set search_path=pg_catalog,public,private
as $function$
  select private.kinojo_banner_manifest_internal_v407(p_page_code,p_slot_code,statement_timestamp())
$function$;

alter table private.kinojo_banner_idempotency_v388
  drop constraint if exists kinojo_banner_idempotency_action_v388_chk;
alter table private.kinojo_banner_idempotency_v388
  add constraint kinojo_banner_idempotency_action_v388_chk check(action in (
    'upload-prepare','upload-complete','asset-update','asset-character-set','asset-representative-set',
    'asset-archive','asset-restore','asset-delete','orphan-cleanup',
    'campaign-create','campaign-update','campaign-publish','campaign-pause','campaign-archive','campaign-restore','campaign-delete',
    'event-save','event-publish','event-move','event-playback','event-rotation','event-pause','event-delete',
    'overlay-upload-prepare','overlay-upload-complete','composite-upload-prepare','composite-upload-complete',
    'auto-pool-save','auto-pool-state','auto-pool-delete','pool-composite-upload-prepare','pool-composite-upload-complete'
  ));

revoke all on function private.kinojo_banner_character_json_v407(bigint) from public,anon,authenticated,service_role;
revoke all on function private.kinojo_banner_asset_character_json_v407(bigint) from public,anon,authenticated,service_role;
revoke all on function private.kinojo_banner_asset_json_v407(public.kinojo_banner_assets) from public,anon,authenticated,service_role;
revoke all on function private.kinojo_banner_bigint_array_v407(jsonb,integer) from public,anon,authenticated,service_role;
revoke all on function private.kinojo_banner_auto_pool_source_hash_v407(bigint,bigint) from public,anon,authenticated,service_role;
revoke all on function private.kinojo_banner_auto_color_v407(bigint,bigint) from public,anon,authenticated,service_role;
revoke all on function private.kinojo_banner_auto_pool_candidates_v407(bigint) from public,anon,authenticated,service_role;
revoke all on function private.kinojo_banner_auto_pool_json_v407(bigint) from public,anon,authenticated,service_role;
revoke all on function private.kinojo_banner_auto_playlist_v407(text,text,timestamptz) from public,anon,authenticated,service_role;
revoke all on function private.kinojo_banner_manifest_internal_v407(text,text,timestamptz) from public,anon,authenticated,service_role;

revoke all on function public.kinojo_banner_character_search_v407(text,text,integer) from public,anon,authenticated;
revoke all on function public.kinojo_banner_character_resolve_v407(text,bigint) from public,anon,authenticated;
revoke all on function public.kinojo_banner_asset_library_v407(text,boolean) from public,anon,authenticated;
revoke all on function public.kinojo_banner_asset_character_set_v407(text,bigint,bigint,boolean) from public,anon,authenticated;
revoke all on function public.kinojo_banner_asset_representative_set_v407(text,bigint,boolean,bigint) from public,anon,authenticated;
revoke all on function public.kinojo_banner_auto_pool_list_v407(text) from public,anon,authenticated;
revoke all on function public.kinojo_banner_auto_pool_save_v407(text,bigint,jsonb) from public,anon,authenticated;
revoke all on function public.kinojo_banner_auto_pool_state_v407(text,bigint,boolean) from public,anon,authenticated;
revoke all on function public.kinojo_banner_auto_pool_delete_v407(text,bigint,text) from public,anon,authenticated;
revoke all on function public.kinojo_banner_auto_pool_composite_register_v407(text,bigint,bigint,text,text,bigint,integer,integer) from public,anon,authenticated;
revoke all on function public.kinojo_banner_event_save_v407(text,uuid,jsonb) from public,anon,authenticated;
revoke all on function public.kinojo_banner_manifest_v407(text,text) from public,anon,authenticated;

grant execute on function public.kinojo_banner_character_search_v407(text,text,integer) to service_role;
grant execute on function public.kinojo_banner_character_resolve_v407(text,bigint) to service_role;
grant execute on function public.kinojo_banner_asset_library_v407(text,boolean) to service_role;
grant execute on function public.kinojo_banner_asset_character_set_v407(text,bigint,bigint,boolean) to service_role;
grant execute on function public.kinojo_banner_asset_representative_set_v407(text,bigint,boolean,bigint) to service_role;
grant execute on function public.kinojo_banner_auto_pool_list_v407(text) to service_role;
grant execute on function public.kinojo_banner_auto_pool_save_v407(text,bigint,jsonb) to service_role;
grant execute on function public.kinojo_banner_auto_pool_state_v407(text,bigint,boolean) to service_role;
grant execute on function public.kinojo_banner_auto_pool_delete_v407(text,bigint,text) to service_role;
grant execute on function public.kinojo_banner_auto_pool_composite_register_v407(text,bigint,bigint,text,text,bigint,integer,integer) to service_role;
grant execute on function public.kinojo_banner_event_save_v407(text,uuid,jsonb) to service_role;
grant execute on function public.kinojo_banner_manifest_v407(text,text) to anon,authenticated,service_role;

comment on function public.kinojo_banner_asset_character_set_v407(text,bigint,bigint,boolean) is
  'MASTER-only permanent character-master ID link or explicit unlink. Name collisions are never guessed.';
comment on function public.kinojo_banner_asset_representative_set_v407(text,bigint,boolean,bigint) is
  'MASTER-only atomic per-character, per-banner-format representative replacement contract.';
comment on function public.kinojo_banner_auto_pool_save_v407(text,bigint,jsonb) is
  'MASTER-only eventless library pool draft save. Every save disables the pool until explicit validated activation.';
comment on function public.kinojo_banner_manifest_v407(text,text) is
  'Anonymous banner manifest. Existing formal event playlist stays first; eligible enabled automatic pool items append by a deterministic shuffle bag.';
