-- Banner redesign stage 5: reusable overlay library, general content layers,
-- draft save/publish round-trip, and public manifest delivery. Text layers
-- remain limited to three; reusable emoji/image decoration layers are limited
-- to three more per banner image.

create table if not exists public.kinojo_banner_overlay_assets (
  overlay_asset_id bigint generated by default as identity primary key,
  asset_kind text not null,
  display_name text not null,
  object_path text not null unique,
  mime_type text not null,
  size_bytes bigint not null,
  width integer not null,
  height integer not null,
  status text not null default 'READY',
  created_by_member_id bigint not null,
  created_at timestamptz not null default clock_timestamp(),
  updated_at timestamptz not null default clock_timestamp(),
  constraint kinojo_banner_overlay_asset_kind_v396_chk
    check (asset_kind in ('EMOTICON','STICKER','BADGE')),
  constraint kinojo_banner_overlay_asset_name_v396_chk
    check (char_length(btrim(display_name)) between 1 and 80),
  constraint kinojo_banner_overlay_asset_path_v396_chk
    check (object_path ~ '^[0-9]{4}/[0-9]{2}/[0-9a-f-]{36}\.(jpg|jpeg|png|webp)$'),
  constraint kinojo_banner_overlay_asset_mime_v396_chk
    check (mime_type in ('image/jpeg','image/png','image/webp')),
  constraint kinojo_banner_overlay_asset_size_v396_chk
    check (size_bytes between 1 and 5242880),
  constraint kinojo_banner_overlay_asset_dimensions_v396_chk
    check (width between 1 and 4096 and height between 1 and 4096),
  constraint kinojo_banner_overlay_asset_status_v396_chk
    check (status in ('READY','ARCHIVED'))
);

alter table public.kinojo_banner_overlay_assets enable row level security;
revoke all on table public.kinojo_banner_overlay_assets from public, anon, authenticated;
revoke all on sequence public.kinojo_banner_overlay_assets_overlay_asset_id_seq
  from public, anon, authenticated;

create index if not exists kinojo_banner_overlay_assets_status_kind_v396_idx
  on public.kinojo_banner_overlay_assets(status,asset_kind,updated_at desc);

create or replace function private.kinojo_banner_content_layer_normalize_v396(
  p_value jsonb
) returns jsonb
language plpgsql
immutable
set search_path = pg_catalog, private
as $function$
declare
  v_value jsonb := coalesce(p_value,'{}'::jsonb);
  v_type text := 'TEXT';
  v_enabled boolean := true;
  v_layer_position text := 'FRONT';
  v_vertical text := 'BOTTOM';
  v_horizontal text := 'CENTER';
  v_opacity integer := 100;
  v_size integer := 24;
  v_rotation integer := 0;
  v_asset_id bigint;
  v_emoji text := '';
  v_text_input jsonb;
  v_text jsonb;
begin
  if jsonb_typeof(v_value)<>'object' then
    raise exception using errcode='P0001',message='BANNER_CONTENT_LAYER_INVALID';
  end if;
  if exists (
    select 1 from jsonb_object_keys(v_value) key_name
    where key_name not in (
      'type','enabled','layerPosition','verticalPosition','horizontalPosition',
      'opacity','sizePercent','rotationDeg','overlayAssetId','emoji',
      'text','fontFamily','fontSizePx','textColor','backgroundColor',
      'backgroundOpacity','heightPercent','widthMode'
    )
  ) then
    raise exception using errcode='P0001',message='BANNER_CONTENT_LAYER_FIELD_INVALID';
  end if;

  v_type := upper(btrim(coalesce(nullif(v_value->>'type',''),'TEXT')));
  if v_type not in ('TEXT','EMOJI','EMOTICON','STICKER','BADGE') then
    raise exception using errcode='P0001',message='BANNER_CONTENT_LAYER_TYPE_INVALID';
  end if;
  if v_value ? 'enabled' then
    if jsonb_typeof(v_value->'enabled')<>'boolean' then
      raise exception using errcode='P0001',message='BANNER_CONTENT_LAYER_ENABLED_INVALID';
    end if;
    v_enabled := (v_value->>'enabled')::boolean;
  end if;
  v_layer_position := upper(btrim(coalesce(nullif(v_value->>'layerPosition',''),'FRONT')));
  if v_layer_position not in ('FRONT','BACK') then
    raise exception using errcode='P0001',message='BANNER_CONTENT_LAYER_POSITION_INVALID';
  end if;
  v_vertical := upper(btrim(coalesce(nullif(v_value->>'verticalPosition',''),'BOTTOM')));
  if v_vertical not in ('TOP','MIDDLE','BOTTOM') then
    raise exception using errcode='P0001',message='BANNER_CONTENT_LAYER_VERTICAL_INVALID';
  end if;
  v_horizontal := upper(btrim(coalesce(nullif(v_value->>'horizontalPosition',''),'CENTER')));
  if v_horizontal not in ('LEFT','CENTER','RIGHT') then
    raise exception using errcode='P0001',message='BANNER_CONTENT_LAYER_HORIZONTAL_INVALID';
  end if;

  begin
    v_opacity := coalesce((v_value->>'opacity')::integer,100);
    v_size := coalesce((v_value->>'sizePercent')::integer,24);
    v_rotation := coalesce((v_value->>'rotationDeg')::integer,0);
  exception when others then
    raise exception using errcode='P0001',message='BANNER_CONTENT_LAYER_GEOMETRY_INVALID';
  end;
  if v_opacity not between 0 and 100 or v_size not between 5 and 60
     or v_rotation not between -180 and 180 then
    raise exception using errcode='P0001',message='BANNER_CONTENT_LAYER_GEOMETRY_INVALID';
  end if;

  if v_type='TEXT' then
    v_text_input := v_value - 'type' - 'layerPosition' - 'horizontalPosition'
      - 'opacity' - 'sizePercent' - 'rotationDeg' - 'overlayAssetId' - 'emoji';
    -- Drafts may preserve an unfinished enabled text layer. The legacy mirror
    -- remains disabled until the text is complete, while v396 keeps intent.
    if v_enabled and char_length(btrim(coalesce(v_value->>'text','')))=0 then
      v_text_input := v_text_input || jsonb_build_object('enabled',false);
    end if;
    v_text := private.kinojo_banner_text_overlay_normalize_v394(v_text_input);
    return v_text || jsonb_build_object(
      'type','TEXT','enabled',v_enabled,'layerPosition',v_layer_position,
      'horizontalPosition','CENTER','opacity',v_opacity,
      'sizePercent',v_size,'rotationDeg',v_rotation
    );
  end if;

  if v_type='EMOJI' then
    v_emoji := coalesce(v_value->>'emoji','');
    if char_length(v_emoji)>12 then
      raise exception using errcode='P0001',message='BANNER_CONTENT_EMOJI_INVALID';
    end if;
    return jsonb_build_object(
      'type','EMOJI','enabled',v_enabled,'emoji',v_emoji,
      'layerPosition',v_layer_position,'verticalPosition',v_vertical,
      'horizontalPosition',v_horizontal,'opacity',v_opacity,
      'sizePercent',v_size,'rotationDeg',v_rotation
    );
  end if;

  if v_value ? 'overlayAssetId' and v_value->'overlayAssetId'<>'null'::jsonb then
    begin
      v_asset_id := (v_value->>'overlayAssetId')::bigint;
    exception when others then
      raise exception using errcode='P0001',message='BANNER_CONTENT_ASSET_ID_INVALID';
    end;
    if v_asset_id<1 then
      raise exception using errcode='P0001',message='BANNER_CONTENT_ASSET_ID_INVALID';
    end if;
  end if;
  return jsonb_build_object(
    'type',v_type,'enabled',v_enabled,'overlayAssetId',v_asset_id,
    'layerPosition',v_layer_position,'verticalPosition',v_vertical,
    'horizontalPosition',v_horizontal,'opacity',v_opacity,
    'sizePercent',v_size,'rotationDeg',v_rotation
  );
end;
$function$;

create or replace function private.kinojo_banner_content_overlays_normalize_v396(
  p_value jsonb
) returns jsonb
language plpgsql
immutable
set search_path = pg_catalog, private
as $function$
declare
  v_value jsonb := case when p_value is null or p_value='null'::jsonb
    then '[]'::jsonb else p_value end;
  v_result jsonb := '[]'::jsonb;
  v_item jsonb;
  v_normalized jsonb;
  v_text_count integer := 0;
  v_decor_count integer := 0;
begin
  if jsonb_typeof(v_value)<>'array' or jsonb_array_length(v_value)>6 then
    raise exception using errcode='P0001',message='BANNER_CONTENT_LAYERS_INVALID';
  end if;
  for v_item in select value from jsonb_array_elements(v_value)
  loop
    v_normalized := private.kinojo_banner_content_layer_normalize_v396(v_item);
    if v_normalized->>'type'='TEXT' then
      v_text_count := v_text_count+1;
    else
      v_decor_count := v_decor_count+1;
    end if;
    if v_text_count>3 or v_decor_count>3 then
      raise exception using errcode='P0001',message='BANNER_CONTENT_LAYER_LIMIT';
    end if;
    v_result := v_result || jsonb_build_array(v_normalized);
  end loop;
  return v_result;
end;
$function$;

create or replace function private.kinojo_banner_content_overlays_valid_v396(
  p_value jsonb
) returns boolean
language plpgsql
immutable
set search_path = pg_catalog, private
as $function$
begin
  perform private.kinojo_banner_content_overlays_normalize_v396(p_value);
  return true;
exception when others then
  return false;
end;
$function$;

create or replace function private.kinojo_banner_content_from_item_v396(
  p_item jsonb,
  p_previous jsonb default '[]'::jsonb
) returns jsonb
language plpgsql
immutable
set search_path = pg_catalog, private
as $function$
declare
  v_layers jsonb;
begin
  if p_item ? 'contentOverlays' then
    return private.kinojo_banner_content_overlays_normalize_v396(p_item->'contentOverlays');
  end if;
  if p_item ? 'textOverlays' then
    if jsonb_typeof(p_item->'textOverlays')<>'array' then
      raise exception using errcode='P0001',message='BANNER_CONTENT_LAYERS_INVALID';
    end if;
    select coalesce(jsonb_agg(value || jsonb_build_object('type','TEXT')),'[]'::jsonb)
      into v_layers from jsonb_array_elements(p_item->'textOverlays');
    return private.kinojo_banner_content_overlays_normalize_v396(v_layers);
  end if;
  if p_item ? 'textOverlay' then
    return private.kinojo_banner_content_overlays_normalize_v396(
      jsonb_build_array(p_item->'textOverlay' || jsonb_build_object('type','TEXT','layerPosition','FRONT'))
    );
  end if;
  return private.kinojo_banner_content_overlays_normalize_v396(p_previous);
end;
$function$;

create or replace function private.kinojo_banner_content_legacy_overlay_v396(
  p_value jsonb
) returns jsonb
language plpgsql
immutable
set search_path = pg_catalog, private
as $function$
declare
  v_layer jsonb;
begin
  for v_layer in
    select value from jsonb_array_elements(
      private.kinojo_banner_content_overlays_normalize_v396(p_value)
    )
  loop
    if v_layer->>'type'='TEXT' and v_layer->>'layerPosition'='FRONT'
       and coalesce((v_layer->>'enabled')::boolean,false)
       and char_length(btrim(coalesce(v_layer->>'text','')))>0 then
      return private.kinojo_banner_text_overlay_normalize_v394(
        v_layer - 'type' - 'layerPosition' - 'horizontalPosition'
          - 'opacity' - 'sizePercent' - 'rotationDeg'
      );
    end if;
  end loop;
  return private.kinojo_banner_text_overlay_normalize_v394(null);
end;
$function$;

revoke all on function private.kinojo_banner_content_layer_normalize_v396(jsonb) from public, anon, authenticated, service_role;
revoke all on function private.kinojo_banner_content_overlays_normalize_v396(jsonb) from public, anon, authenticated, service_role;
revoke all on function private.kinojo_banner_content_overlays_valid_v396(jsonb) from public, anon, authenticated, service_role;
revoke all on function private.kinojo_banner_content_from_item_v396(jsonb,jsonb) from public, anon, authenticated, service_role;
revoke all on function private.kinojo_banner_content_legacy_overlay_v396(jsonb) from public, anon, authenticated, service_role;

alter table public.kinojo_banner_campaign_items
  add column if not exists content_overlays jsonb not null default '[]'::jsonb,
  add column if not exists composite_object_path text,
  add column if not exists composite_mime_type text,
  add column if not exists composite_size_bytes bigint,
  add column if not exists composite_width integer,
  add column if not exists composite_height integer,
  add column if not exists composite_source_hash text;

update public.kinojo_banner_campaign_items
set content_overlays=case
  when coalesce((text_overlay->>'enabled')::boolean,false) then
    private.kinojo_banner_content_overlays_normalize_v396(
      jsonb_build_array(text_overlay || jsonb_build_object('type','TEXT','layerPosition','FRONT'))
    )
  else '[]'::jsonb
end
where content_overlays='[]'::jsonb;

alter table public.kinojo_banner_campaign_items
  drop constraint if exists kinojo_banner_item_content_overlays_v396_chk;
alter table public.kinojo_banner_campaign_items
  add constraint kinojo_banner_item_content_overlays_v396_chk
  check (private.kinojo_banner_content_overlays_valid_v396(content_overlays));

alter table public.kinojo_banner_campaign_items
  drop constraint if exists kinojo_banner_item_composite_v396_chk;
alter table public.kinojo_banner_campaign_items
  add constraint kinojo_banner_item_composite_v396_chk check (
    (composite_object_path is null and composite_mime_type is null
      and composite_size_bytes is null and composite_width is null
      and composite_height is null and composite_source_hash is null)
    or
    (composite_object_path ~ '^[0-9]{4}/[0-9]{2}/[0-9a-f-]{36}\.(jpg|jpeg|png|webp)$'
      and composite_mime_type in ('image/jpeg','image/png','image/webp')
      and composite_size_bytes between 1 and 5242880
      and composite_width between 1 and 4096
      and composite_height between 1 and 4096
      and composite_source_hash ~ '^[0-9a-f]{32}$')
  );

create or replace function private.kinojo_banner_content_enabled_v396(
  p_value jsonb
) returns boolean
language sql
immutable
set search_path = pg_catalog, private
as $function$
  select exists (
    select 1
    from jsonb_array_elements(
      private.kinojo_banner_content_overlays_normalize_v396(p_value)
    ) layer
    where coalesce((layer->>'enabled')::boolean,false)
  );
$function$;

revoke all on function private.kinojo_banner_content_enabled_v396(jsonb)
  from public, anon, authenticated, service_role;

create or replace function private.kinojo_banner_overlay_asset_json_v396(
  p_asset public.kinojo_banner_overlay_assets
) returns jsonb
language sql
stable
security definer
set search_path = pg_catalog, public, private
as $function$
  select jsonb_build_object(
    'overlayAssetId',p_asset.overlay_asset_id,
    'assetKind',p_asset.asset_kind,
    'displayName',p_asset.display_name,
    'objectPath',p_asset.object_path,
    'mimeType',p_asset.mime_type,
    'sizeBytes',p_asset.size_bytes,
    'width',p_asset.width,
    'height',p_asset.height,
    'status',p_asset.status,
    'createdAt',to_char(p_asset.created_at at time zone 'Asia/Seoul','YYYY-MM-DD"T"HH24:MI:SS')
  );
$function$;

create or replace function public.kinojo_banner_overlay_asset_register_v396(
  p_session_token text,
  p_object_path text,
  p_mime_type text,
  p_size_bytes bigint,
  p_width integer,
  p_height integer,
  p_asset_kind text,
  p_display_name text
) returns jsonb
language plpgsql
security definer
set search_path = pg_catalog, public, private
as $function$
declare
  v_gate jsonb;
  v_kind text := upper(btrim(coalesce(p_asset_kind,'')));
  v_name text := btrim(coalesce(p_display_name,''));
  v_asset public.kinojo_banner_overlay_assets;
begin
  v_gate := private.kinojo_banner_require_master_v384(p_session_token);
  if coalesce((v_gate->>'ok')::boolean,false) is not true then return v_gate; end if;
  if v_kind not in ('EMOTICON','STICKER','BADGE') then
    return jsonb_build_object('ok',false,'code','BANNER_OVERLAY_KIND_INVALID');
  end if;
  if char_length(v_name) not between 1 and 80 then
    return jsonb_build_object('ok',false,'code','BANNER_OVERLAY_NAME_INVALID');
  end if;
  insert into public.kinojo_banner_overlay_assets(
    asset_kind,display_name,object_path,mime_type,size_bytes,width,height,
    created_by_member_id
  ) values (
    v_kind,v_name,p_object_path,lower(p_mime_type),p_size_bytes,p_width,p_height,
    (v_gate->>'memberId')::bigint
  ) returning * into v_asset;
  return jsonb_build_object(
    'ok',true,'apiVersion','396','contract','banner-overlay-asset-register-v396',
    'asset',private.kinojo_banner_overlay_asset_json_v396(v_asset)
  );
exception
  when unique_violation then return jsonb_build_object('ok',false,'code','BANNER_OVERLAY_OBJECT_CONFLICT');
  when check_violation then return jsonb_build_object('ok',false,'code','BANNER_OVERLAY_ASSET_INVALID');
end;
$function$;

create or replace function public.kinojo_banner_overlay_asset_list_v396(
  p_session_token text,
  p_include_archived boolean default false
) returns jsonb
language plpgsql
stable
security definer
set search_path = pg_catalog, public, private
as $function$
declare
  v_gate jsonb;
  v_assets jsonb;
begin
  v_gate := private.kinojo_banner_require_master_v384(p_session_token);
  if coalesce((v_gate->>'ok')::boolean,false) is not true then return v_gate; end if;
  select coalesce(jsonb_agg(private.kinojo_banner_overlay_asset_json_v396(a)
    order by a.updated_at desc,a.overlay_asset_id desc),'[]'::jsonb)
    into v_assets
  from public.kinojo_banner_overlay_assets a
  where coalesce(p_include_archived,false) or a.status<>'ARCHIVED';
  return jsonb_build_object(
    'ok',true,'apiVersion','396','contract','banner-overlay-asset-list-v396',
    'assets',v_assets
  );
end;
$function$;

create or replace function public.kinojo_banner_composite_register_v396(
  p_session_token text,
  p_event_group_id uuid,
  p_asset_id bigint,
  p_object_path text,
  p_mime_type text,
  p_size_bytes bigint,
  p_width integer,
  p_height integer
) returns jsonb
language plpgsql
security definer
set search_path = pg_catalog, public, private
as $function$
declare
  v_gate jsonb;
  v_kind text;
  v_hash text;
  v_hash_count integer;
  v_updated integer;
begin
  v_gate := private.kinojo_banner_require_master_v384(p_session_token);
  if coalesce((v_gate->>'ok')::boolean,false) is not true then return v_gate; end if;
  if p_event_group_id is null or coalesce(p_asset_id,0)<1 then
    return jsonb_build_object('ok',false,'code','BANNER_COMPOSITE_TARGET_INVALID');
  end if;

  select min(c.campaign_type),count(distinct md5(
    private.kinojo_banner_content_overlays_normalize_v396(i.content_overlays)::text
  )),min(md5(
    private.kinojo_banner_content_overlays_normalize_v396(i.content_overlays)::text
  )) into v_kind,v_hash_count,v_hash
  from public.kinojo_banner_campaign_items i
  join public.kinojo_banner_campaigns c on c.campaign_id=i.campaign_id
  where c.event_group_id=p_event_group_id and i.asset_id=p_asset_id;

  if v_kind is null then
    return jsonb_build_object('ok',false,'code','BANNER_COMPOSITE_TARGET_NOT_FOUND');
  end if;
  if v_hash_count<>1 then
    return jsonb_build_object('ok',false,'code','BANNER_COMPOSITE_LAYER_MISMATCH');
  end if;
  if (v_kind='MAIN' and (p_width<>1536 or p_height<>864))
     or (v_kind='SIDE' and (p_width<>300 or p_height<>715)) then
    return jsonb_build_object('ok',false,'code','BANNER_COMPOSITE_DIMENSIONS_INVALID');
  end if;

  update public.kinojo_banner_campaign_items i
     set composite_object_path=p_object_path,
         composite_mime_type=lower(p_mime_type),
         composite_size_bytes=p_size_bytes,
         composite_width=p_width,
         composite_height=p_height,
         composite_source_hash=v_hash,
         updated_at=clock_timestamp()
    from public.kinojo_banner_campaigns c
   where c.campaign_id=i.campaign_id
     and c.event_group_id=p_event_group_id
     and i.asset_id=p_asset_id;
  get diagnostics v_updated=row_count;

  return jsonb_build_object(
    'ok',true,'apiVersion','396','contract','banner-composite-register-v396',
    'eventGroupId',p_event_group_id,'assetId',p_asset_id,
    'attachedItemCount',v_updated,'sourceHash',v_hash
  );
exception
  when check_violation then
    return jsonb_build_object('ok',false,'code','BANNER_COMPOSITE_INVALID');
end;
$function$;

revoke all on function private.kinojo_banner_overlay_asset_json_v396(public.kinojo_banner_overlay_assets) from public, anon, authenticated, service_role;
revoke all on function public.kinojo_banner_overlay_asset_register_v396(text,text,text,bigint,integer,integer,text,text) from public, anon, authenticated;
revoke all on function public.kinojo_banner_overlay_asset_list_v396(text,boolean) from public, anon, authenticated;
revoke all on function public.kinojo_banner_composite_register_v396(text,uuid,bigint,text,text,bigint,integer,integer) from public, anon, authenticated;
grant execute on function public.kinojo_banner_overlay_asset_register_v396(text,text,text,bigint,integer,integer,text,text) to service_role;
grant execute on function public.kinojo_banner_overlay_asset_list_v396(text,boolean) to service_role;
grant execute on function public.kinojo_banner_composite_register_v396(text,uuid,bigint,text,text,bigint,integer,integer) to service_role;

create or replace function private.kinojo_banner_campaign_json_v396(
  p_campaign public.kinojo_banner_campaigns
) returns jsonb
language plpgsql
stable
security definer
set search_path = pg_catalog, public, private
as $function$
declare
  v_items jsonb;
begin
  select coalesce(jsonb_agg(jsonb_build_object(
      'itemId',i.item_id,
      'assetId',i.asset_id,
      'weight',i.weight,
      'enabled',i.is_enabled,
      'alt',i.alt_text,
      'clickUrl',nullif(i.click_url,''),
      'sortOrder',i.sort_order,
      'scheduleMode',i.schedule_mode,
      'startsAtKst',case when i.starts_at is null then null else to_char(i.starts_at at time zone 'Asia/Seoul','YYYY-MM-DD"T"HH24:MI:SS') end,
      'endsAtKst',case when i.ends_at is null then null else to_char(i.ends_at at time zone 'Asia/Seoul','YYYY-MM-DD"T"HH24:MI:SS') end,
      'weekdays',to_jsonb(i.weekdays),
      'specificDates',to_jsonb(i.specific_dates),
      'textOverlay',private.kinojo_banner_text_overlay_normalize_v394(i.text_overlay),
      'contentOverlays',private.kinojo_banner_content_overlays_normalize_v396(i.content_overlays),
      'compositeReady',i.composite_object_path is not null
        and i.composite_source_hash=md5(
          private.kinojo_banner_content_overlays_normalize_v396(i.content_overlays)::text
        )
    ) order by i.sort_order,i.item_id),'[]'::jsonb)
    into v_items
  from public.kinojo_banner_campaign_items i
  where i.campaign_id=p_campaign.campaign_id;

  return private.kinojo_banner_campaign_json_v394(p_campaign)
    || jsonb_build_object('items',v_items);
end;
$function$;

create or replace function private.kinojo_banner_event_json_v396(
  p_event_group_id uuid
) returns jsonb
language plpgsql
stable
security definer
set search_path = pg_catalog, public, private
as $function$
declare
  v_base jsonb;
  v_campaigns jsonb;
begin
  v_base := private.kinojo_banner_event_json_v394(p_event_group_id);
  if v_base is null then return null; end if;
  select coalesce(
    jsonb_agg(private.kinojo_banner_campaign_json_v396(c)
      order by c.page_code,c.event_role,c.campaign_id),
    '[]'::jsonb
  ) into v_campaigns
  from public.kinojo_banner_campaigns c
  where c.event_group_id=p_event_group_id;
  return v_base || jsonb_build_object('campaigns',v_campaigns);
end;
$function$;

create or replace function public.kinojo_banner_event_list_v396(
  p_session_token text,
  p_include_archived boolean default true
) returns jsonb
language plpgsql
stable
security definer
set search_path = pg_catalog, public, private
as $function$
declare
  v_gate jsonb;
  v_events jsonb;
  v_legacy jsonb;
begin
  v_gate := private.kinojo_banner_require_master_v384(p_session_token);
  if coalesce((v_gate->>'ok')::boolean,false) is not true then return v_gate; end if;

  select coalesce(
    jsonb_agg(private.kinojo_banner_event_json_v396(g.event_group_id)
      order by g.updated_at desc,g.event_group_id),
    '[]'::jsonb
  ) into v_events
  from private.kinojo_banner_event_groups_v391 g
  where coalesce(p_include_archived,true)
     or exists (
       select 1 from public.kinojo_banner_campaigns c
       where c.event_group_id=g.event_group_id and c.status<>'ARCHIVED'
     );

  select coalesce(
    jsonb_agg(private.kinojo_banner_campaign_json_v396(c)
      order by c.updated_at desc,c.campaign_id desc),
    '[]'::jsonb
  ) into v_legacy
  from public.kinojo_banner_campaigns c
  where c.event_group_id is null
    and (coalesce(p_include_archived,true) or c.status<>'ARCHIVED');

  return jsonb_build_object(
    'ok',true,'apiVersion','396','contract','banner-event-list-v396',
    'events',v_events,'legacyCampaigns',v_legacy
  );
end;
$function$;

create or replace function public.kinojo_banner_event_save_v396(
  p_session_token text,
  p_event_group_id uuid,
  p_payload jsonb
) returns jsonb
language plpgsql
security definer
set search_path = pg_catalog, public, private
as $function$
declare
  v_gate jsonb;
  v_result jsonb;
  v_group_id uuid;
  v_variants jsonb := p_payload->'variants';
  v_variant jsonb;
  v_items jsonb;
  v_item jsonb;
  v_page text;
  v_role text;
  v_campaign_id bigint;
  v_asset_id bigint;
  v_content_key text;
  v_content jsonb;
  v_previous_content jsonb := '{}'::jsonb;
begin
  v_gate := private.kinojo_banner_require_master_v384(p_session_token);
  if coalesce((v_gate->>'ok')::boolean,false) is not true then return v_gate; end if;

  if p_event_group_id is not null then
    select coalesce(jsonb_object_agg(
      c.page_code||':'||c.event_role||':'||i.asset_id::text,
      i.content_overlays
    ),'{}'::jsonb) into v_previous_content
    from public.kinojo_banner_campaigns c
    join public.kinojo_banner_campaign_items i on i.campaign_id=c.campaign_id
    where c.event_group_id=p_event_group_id;
  end if;

  if jsonb_typeof(v_variants)='array' then
    for v_variant in select value from jsonb_array_elements(v_variants)
    loop
      v_items := v_variant->'items';
      if jsonb_typeof(v_variant)='object' and jsonb_typeof(v_items)='array' then
        for v_item in select value from jsonb_array_elements(v_items)
        loop
          perform private.kinojo_banner_content_from_item_v396(v_item,'[]'::jsonb);
        end loop;
      end if;
    end loop;
  end if;

  v_result := public.kinojo_banner_event_save_v394(
    p_session_token,p_event_group_id,p_payload
  );
  if coalesce((v_result->>'ok')::boolean,false) is not true then return v_result; end if;
  v_group_id := (v_result->>'eventGroupId')::uuid;

  if jsonb_typeof(v_variants)='array' then
    for v_variant in select value from jsonb_array_elements(v_variants)
    loop
      if jsonb_typeof(v_variant)='object' then
        v_page := upper(btrim(coalesce(v_variant->>'pageCode','')));
        v_role := upper(btrim(coalesce(v_variant->>'eventRole','')));
        select c.campaign_id into v_campaign_id
        from public.kinojo_banner_campaigns c
        where c.event_group_id=v_group_id
          and c.page_code=v_page
          and c.event_role=v_role;
        if not found then
          raise exception using errcode='P0001',message='BANNER_EVENT_CAMPAIGN_NOT_FOUND';
        end if;

        v_items := v_variant->'items';
        if jsonb_typeof(v_items)='array' then
          for v_item in select value from jsonb_array_elements(v_items)
          loop
            begin
              v_asset_id := (v_item->>'assetId')::bigint;
            exception when others then
              raise exception using errcode='P0001',message='BANNER_CAMPAIGN_ASSET_ID_INVALID';
            end;
            v_content_key := v_page||':'||v_role||':'||v_asset_id::text;
            v_content := private.kinojo_banner_content_from_item_v396(
              v_item,
              case when v_previous_content ? v_content_key
                then v_previous_content->v_content_key else '[]'::jsonb end
            );
            update public.kinojo_banner_campaign_items
               set composite_object_path=case when content_overlays is distinct from v_content then null else composite_object_path end,
                   composite_mime_type=case when content_overlays is distinct from v_content then null else composite_mime_type end,
                   composite_size_bytes=case when content_overlays is distinct from v_content then null else composite_size_bytes end,
                   composite_width=case when content_overlays is distinct from v_content then null else composite_width end,
                   composite_height=case when content_overlays is distinct from v_content then null else composite_height end,
                   composite_source_hash=case when content_overlays is distinct from v_content then null else composite_source_hash end,
                   content_overlays=v_content,
                   text_overlay=private.kinojo_banner_content_legacy_overlay_v396(v_content),
                   updated_at=clock_timestamp()
             where campaign_id=v_campaign_id and asset_id=v_asset_id;
            if not found then
              raise exception using errcode='P0001',message='BANNER_EVENT_ITEM_NOT_FOUND';
            end if;
          end loop;
        end if;
      end if;
    end loop;
  end if;

  update private.kinojo_banner_event_groups_v391
     set updated_by_member_id=(v_gate->>'memberId')::bigint,
         updated_at=clock_timestamp()
   where event_group_id=v_group_id;

  return jsonb_build_object(
    'ok',true,'apiVersion','396','contract','banner-event-save-v396',
    'eventGroupId',v_group_id,
    'savedCampaignIds',coalesce(v_result->'savedCampaignIds','[]'::jsonb),
    'event',private.kinojo_banner_event_json_v396(v_group_id)
  );
exception
  when sqlstate 'P0001' then
    return jsonb_build_object('ok',false,'code',coalesce(nullif(sqlerrm,''),'BANNER_EVENT_SAVE_FAILED'));
end;
$function$;

create or replace function public.kinojo_banner_event_publish_v396(
  p_session_token text,
  p_event_group_id uuid
) returns jsonb
language plpgsql
security definer
set search_path = pg_catalog, public, private
as $function$
declare
  v_gate jsonb;
  v_result jsonb;
  v_item record;
  v_layer jsonb;
  v_asset_id bigint;
  v_expected_hash text;
begin
  v_gate := private.kinojo_banner_require_master_v384(p_session_token);
  if coalesce((v_gate->>'ok')::boolean,false) is not true then return v_gate; end if;

  for v_item in
    select i.item_id,i.content_overlays
    from public.kinojo_banner_campaign_items i
    join public.kinojo_banner_campaigns c on c.campaign_id=i.campaign_id
    where c.event_group_id=p_event_group_id and i.is_enabled
  loop
    v_expected_hash := md5(
      private.kinojo_banner_content_overlays_normalize_v396(v_item.content_overlays)::text
    );
    for v_layer in
      select value from jsonb_array_elements(
        private.kinojo_banner_content_overlays_normalize_v396(v_item.content_overlays)
      )
    loop
      if coalesce((v_layer->>'enabled')::boolean,false) then
        if v_layer->>'type'='TEXT' and char_length(btrim(coalesce(v_layer->>'text','')))=0 then
          return jsonb_build_object('ok',false,'code','BANNER_CONTENT_TEXT_REQUIRED','itemId',v_item.item_id);
        elsif v_layer->>'type'='EMOJI' and char_length(btrim(coalesce(v_layer->>'emoji','')))=0 then
          return jsonb_build_object('ok',false,'code','BANNER_CONTENT_EMOJI_REQUIRED','itemId',v_item.item_id);
        elsif v_layer->>'type' in ('EMOTICON','STICKER','BADGE') then
          begin
            v_asset_id := (v_layer->>'overlayAssetId')::bigint;
          exception when others then
            return jsonb_build_object('ok',false,'code','BANNER_CONTENT_ASSET_REQUIRED','itemId',v_item.item_id);
          end;
          if not exists (
            select 1 from public.kinojo_banner_overlay_assets a
            where a.overlay_asset_id=v_asset_id
              and a.status='READY'
              and a.asset_kind=v_layer->>'type'
          ) then
            return jsonb_build_object('ok',false,'code','BANNER_CONTENT_ASSET_REQUIRED','itemId',v_item.item_id);
          end if;
        end if;
      end if;
    end loop;
    if private.kinojo_banner_content_enabled_v396(v_item.content_overlays) and not exists (
      select 1
      from public.kinojo_banner_campaign_items check_item
      where check_item.item_id=v_item.item_id
        and check_item.composite_object_path is not null
        and check_item.composite_source_hash=v_expected_hash
    ) then
      return jsonb_build_object(
        'ok',false,'code','BANNER_COMPOSITE_REQUIRED','itemId',v_item.item_id
      );
    end if;
  end loop;

  v_result := public.kinojo_banner_event_publish_v394(
    p_session_token,p_event_group_id
  );
  if coalesce((v_result->>'ok')::boolean,false) is not true then return v_result; end if;
  return jsonb_build_object(
    'ok',true,'apiVersion','396','contract','banner-event-publish-v396',
    'eventGroupId',p_event_group_id,
    'publishedCampaignCount',v_result->'publishedCampaignCount',
    'event',private.kinojo_banner_event_json_v396(p_event_group_id)
  );
exception
  when invalid_text_representation or numeric_value_out_of_range then
    return jsonb_build_object('ok',false,'code','BANNER_CONTENT_ASSET_REQUIRED');
end;
$function$;

create or replace function private.kinojo_banner_content_manifest_v396(
  p_value jsonb
) returns jsonb
language plpgsql
stable
security definer
set search_path = pg_catalog, public, private
as $function$
declare
  v_result jsonb := '[]'::jsonb;
  v_layer jsonb;
  v_asset public.kinojo_banner_overlay_assets;
begin
  for v_layer in
    select value from jsonb_array_elements(
      private.kinojo_banner_content_overlays_normalize_v396(p_value)
    )
  loop
    if not coalesce((v_layer->>'enabled')::boolean,false) then continue; end if;
    if v_layer->>'type'='TEXT' and char_length(btrim(coalesce(v_layer->>'text','')))=0 then continue; end if;
    if v_layer->>'type'='EMOJI' and char_length(btrim(coalesce(v_layer->>'emoji','')))=0 then continue; end if;
    if v_layer->>'type' in ('EMOTICON','STICKER','BADGE') then
      select a.* into v_asset
      from public.kinojo_banner_overlay_assets a
      where a.overlay_asset_id=(v_layer->>'overlayAssetId')::bigint
        and a.status='READY'
        and a.asset_kind=v_layer->>'type';
      if not found then continue; end if;
      v_layer := (v_layer - 'overlayAssetId') || jsonb_build_object(
        'sourceType','STORAGE','objectPath',v_asset.object_path,
        'mimeType',v_asset.mime_type,'width',v_asset.width,'height',v_asset.height,
        'assetKind',v_asset.asset_kind
      );
    end if;
    v_result := v_result || jsonb_build_array(v_layer);
  end loop;
  return v_result;
exception when invalid_text_representation or numeric_value_out_of_range then
  return v_result;
end;
$function$;

create or replace function private.kinojo_banner_manifest_internal_v396(
  p_page_code text,
  p_slot_code text,
  p_now timestamptz
) returns jsonb
language plpgsql
stable
security definer
set search_path = pg_catalog, public, private
as $function$
declare
  v_base jsonb;
  v_playlist jsonb := '[]'::jsonb;
  v_manifest_version text;
begin
  v_base := private.kinojo_banner_manifest_internal_v395(
    p_page_code,p_slot_code,p_now
  );
  if coalesce((v_base->>'ok')::boolean,false) is not true then return v_base; end if;

  select coalesce(jsonb_agg(
    p.item || case
      when private.kinojo_banner_content_enabled_v396(i.content_overlays)
       and i.composite_object_path is not null
       and i.composite_source_hash=md5(
         private.kinojo_banner_content_overlays_normalize_v396(i.content_overlays)::text
       ) then jsonb_build_object(
         'sourceType','STORAGE','staticPath',null,
         'objectPath',i.composite_object_path,
         'fitMode','COVER','composite',true,
         'textOverlay',private.kinojo_banner_text_overlay_normalize_v394(null),
         'contentOverlays','[]'::jsonb
       )
      else jsonb_build_object(
        'composite',false,
        'contentOverlays',private.kinojo_banner_content_manifest_v396(i.content_overlays)
      )
    end order by p.ordinality
  ),'[]'::jsonb) into v_playlist
  from jsonb_array_elements(coalesce(v_base->'playlist','[]'::jsonb))
    with ordinality p(item,ordinality)
  join public.kinojo_banner_campaign_items i
    on i.item_id=(p.item->>'itemId')::bigint;

  v_manifest_version := 'bm396-'||substr(md5(
    coalesce(v_base->>'manifestVersion','')||'|'||v_playlist::text
  ),1,24);
  return v_base || jsonb_build_object(
    'apiVersion','396','contract','banner-manifest-internal-v396',
    'manifestVersion',v_manifest_version,'playlist',v_playlist
  );
end;
$function$;

create or replace function public.kinojo_banner_manifest_v396(
  p_page_code text,
  p_slot_code text
) returns jsonb
language sql
stable
security definer
set search_path = pg_catalog, public, private
as $function$
  select private.kinojo_banner_manifest_internal_v396(
    p_page_code,p_slot_code,statement_timestamp()
  );
$function$;

revoke all on function private.kinojo_banner_campaign_json_v396(public.kinojo_banner_campaigns) from public, anon, authenticated, service_role;
revoke all on function private.kinojo_banner_event_json_v396(uuid) from public, anon, authenticated, service_role;
revoke all on function private.kinojo_banner_content_manifest_v396(jsonb) from public, anon, authenticated, service_role;
revoke all on function private.kinojo_banner_manifest_internal_v396(text,text,timestamptz) from public, anon, authenticated, service_role;
revoke all on function public.kinojo_banner_event_list_v396(text,boolean) from public, anon, authenticated;
revoke all on function public.kinojo_banner_event_save_v396(text,uuid,jsonb) from public, anon, authenticated;
revoke all on function public.kinojo_banner_event_publish_v396(text,uuid) from public, anon, authenticated;
revoke all on function public.kinojo_banner_manifest_v396(text,text) from public, anon, authenticated;
grant execute on function public.kinojo_banner_event_list_v396(text,boolean) to service_role;
grant execute on function public.kinojo_banner_event_save_v396(text,uuid,jsonb) to service_role;
grant execute on function public.kinojo_banner_event_publish_v396(text,uuid) to service_role;
grant execute on function public.kinojo_banner_manifest_v396(text,text) to service_role;

comment on table public.kinojo_banner_overlay_assets is
  'Reusable MASTER-only emoticon, sticker, and badge assets for banner content layers.';
comment on column public.kinojo_banner_campaign_items.content_overlays is
  'v396 ordered layers per banner image: up to three TEXT and three emoji/reusable image decorations.';
comment on function public.kinojo_banner_event_publish_v396(text,uuid) is
  'Validates all enabled content layers, then publishes every event campaign as one atomic workflow.';
comment on function public.kinojo_banner_manifest_v396(text,text) is
  'ALL_ACTIVE frequency-weighted banner manifest with public-ready reusable content overlay layers.';
