-- Sanctuary management Stage 5 / DB 437
-- Server-owned recruitment alerts, Wednesday-first calendar, scoped schedule
-- operations and archive impact preview. Historical roster/audit rows are kept.

create table if not exists private.sanctuary_management_schedule_versions_v437 (
  schedule_version_id bigint generated by default as identity primary key,
  schedule_id bigint not null references private.sanctuary_management_schedule_rules_v412(schedule_id) on delete cascade,
  team_id bigint not null references private.sanctuary_management_teams_v412(team_id) on delete cascade,
  effective_from date not null,
  effective_to date,
  schedule_kind text not null check (schedule_kind in ('ONCE','WEEKLY')),
  starts_on date not null,
  weekdays smallint[] not null default '{}',
  starts_at time not null,
  duration_minutes integer not null default 30 check (duration_minutes between 30 and 720 and duration_minutes % 30 = 0),
  timezone_name text not null default 'Asia/Seoul',
  status text not null default 'ACTIVE' check (status in ('ACTIVE','STOPPED')),
  revision bigint not null default 1,
  created_by_member_id bigint references public.member_codes(id) on delete restrict,
  created_at timestamptz not null default clock_timestamp(),
  check (effective_to is null or effective_to >= effective_from),
  check ((schedule_kind='ONCE' and cardinality(weekdays)=0) or (schedule_kind='WEEKLY' and cardinality(weekdays) between 1 and 7)),
  unique(schedule_id,effective_from)
);

create index if not exists sanctuary_management_schedule_versions_v437_team_range_idx
  on private.sanctuary_management_schedule_versions_v437(team_id,effective_from,effective_to);
alter table private.sanctuary_management_schedule_versions_v437 enable row level security;
revoke all on private.sanctuary_management_schedule_versions_v437 from public, anon, authenticated;

alter table private.sanctuary_management_schedule_exceptions_v412
  add column if not exists moved_duration_minutes integer;
update private.sanctuary_management_schedule_exceptions_v412 e
   set moved_duration_minutes=r.duration_minutes
  from private.sanctuary_management_schedule_rules_v412 r
 where e.schedule_id=r.schedule_id and e.exception_type='MOVE' and e.moved_duration_minutes is null;
alter table private.sanctuary_management_schedule_exceptions_v412
  drop constraint if exists sanctuary_management_schedule_exceptions_v412_check;
alter table private.sanctuary_management_schedule_exceptions_v412
  add constraint sanctuary_management_schedule_exceptions_v437_check check (
    (exception_type='CANCEL' and moved_to_date is null and moved_to_time is null and moved_duration_minutes is null)
    or
    (exception_type='MOVE' and moved_to_date is not null and moved_to_time is not null
      and moved_duration_minutes between 30 and 720 and moved_duration_minutes % 30 = 0)
  );

insert into private.sanctuary_management_schedule_versions_v437(
  schedule_id,team_id,effective_from,schedule_kind,starts_on,weekdays,starts_at,
  duration_minutes,timezone_name,status,revision,created_by_member_id
)
select r.schedule_id,r.team_id,r.starts_on,r.schedule_kind,r.starts_on,r.weekdays,r.starts_at,
       r.duration_minutes,r.timezone_name,r.status,r.revision,t.creator_member_id
  from private.sanctuary_management_schedule_rules_v412 r
  join private.sanctuary_management_teams_v412 t on t.team_id=r.team_id
 where not exists(
   select 1 from private.sanctuary_management_schedule_versions_v437 v where v.schedule_id=r.schedule_id
 );

create or replace function private.kinojo_sm_schedule_version_sync_v437()
returns trigger
language plpgsql
security definer
set search_path='pg_catalog','public','private'
as $$
declare v_actor_id bigint;
begin
  if coalesce(current_setting('kinojo.schedule_version_guard',true),'')='1' then return new; end if;
  select creator_member_id into v_actor_id from private.sanctuary_management_teams_v412 where team_id=new.team_id;
  if tg_op='UPDATE' then
    delete from private.sanctuary_management_schedule_versions_v437 where schedule_id=new.schedule_id;
  end if;
  insert into private.sanctuary_management_schedule_versions_v437(
    schedule_id,team_id,effective_from,schedule_kind,starts_on,weekdays,starts_at,
    duration_minutes,timezone_name,status,revision,created_by_member_id
  ) values(
    new.schedule_id,new.team_id,new.starts_on,new.schedule_kind,new.starts_on,new.weekdays,new.starts_at,
    new.duration_minutes,new.timezone_name,new.status,new.revision,v_actor_id
  );
  return new;
end;
$$;

drop trigger if exists sanctuary_management_schedule_version_sync_v437 on private.sanctuary_management_schedule_rules_v412;
create trigger sanctuary_management_schedule_version_sync_v437
after insert or update of schedule_kind,starts_on,weekdays,starts_at,duration_minutes,timezone_name,status
on private.sanctuary_management_schedule_rules_v412
for each row execute function private.kinojo_sm_schedule_version_sync_v437();

create or replace function private.kinojo_sm_rule_occurrences_v437(p_schedule_id bigint,p_from date,p_to date)
returns table(occurrence_date date,start_at timestamptz,end_at timestamptz,source_scope text)
language sql
stable security definer
set search_path='pg_catalog','private'
as $$
  with versions as (
    select * from private.sanctuary_management_schedule_versions_v437
     where schedule_id=p_schedule_id and status='ACTIVE'
       and effective_from<=p_to and coalesce(effective_to,'infinity'::date)>=p_from
  ), generated as (
    select d::date occurrence_date,v.*
      from versions v
      cross join lateral generate_series(
        greatest(p_from,v.effective_from,v.starts_on),
        least(p_to,coalesce(v.effective_to,p_to)),interval '1 day'
      ) d
     where (v.schedule_kind='ONCE' and d::date=v.starts_on)
        or (v.schedule_kind='WEEKLY' and extract(isodow from d)::smallint=any(v.weekdays))
  ), originals as (
    select g.occurrence_date,
           ((g.occurrence_date+g.starts_at) at time zone g.timezone_name) start_at,
           (((g.occurrence_date+g.starts_at)+make_interval(mins=>g.duration_minutes)) at time zone g.timezone_name) end_at,
           'RULE'::text source_scope
      from generated g
     where not exists(select 1 from private.sanctuary_management_schedule_exceptions_v412 e
       where e.schedule_id=g.schedule_id and e.occurrence_date=g.occurrence_date)
  ), moved as (
    select e.moved_to_date,
           ((e.moved_to_date+e.moved_to_time) at time zone v.timezone_name),
           (((e.moved_to_date+e.moved_to_time)+make_interval(mins=>e.moved_duration_minutes)) at time zone v.timezone_name),
           'OCCURRENCE'::text
      from private.sanctuary_management_schedule_exceptions_v412 e
      join versions v on v.schedule_id=e.schedule_id
       and e.occurrence_date between v.effective_from and coalesce(v.effective_to,'infinity'::date)
     where e.schedule_id=p_schedule_id and e.exception_type='MOVE'
       and e.moved_to_date between p_from and p_to
  )
  select * from originals union all select * from moved;
$$;

create or replace function private.kinojo_sm_team_conflicts_v437(p_team_id bigint,p_from date,p_to date)
returns jsonb
language sql
stable security definer
set search_path='pg_catalog','public','private'
as $$
  select coalesce(jsonb_agg(distinct jsonb_build_object(
    'teamId',other_team.team_id,'teamTitle',other_team.title,'characterName',cm.character_name,
    'message','['||case mine.character_relation when 'MAIN' then '본캐' when 'ALT' then '부캐' else '게스트' end||'] '
      ||cm.character_name||' 캐릭터가 참여하고 있는 '||other_team.title||' 일정과 충돌합니다.'
  )),'[]'::jsonb)
  from private.sanctuary_management_teams_v412 candidate_team
  join private.sanctuary_management_schedule_rules_v412 candidate_rule on candidate_rule.team_id=candidate_team.team_id
  join private.sanctuary_management_slots_v412 mine on mine.team_id=candidate_team.team_id and mine.character_id is not null
  join public.character_master cm on cm.id=mine.character_id
  join private.sanctuary_management_slots_v412 other_slot
    on other_slot.team_id<>candidate_team.team_id and other_slot.character_id is not null
   and ((mine.owner_member_id is not null and other_slot.owner_member_id=mine.owner_member_id)
     or (mine.owner_root_character_id is not null and other_slot.owner_root_character_id=mine.owner_root_character_id))
  join private.sanctuary_management_teams_v412 other_team on other_team.team_id=other_slot.team_id and other_team.status in ('ACTIVE','FULL')
  join private.sanctuary_management_schedule_rules_v412 other_rule on other_rule.team_id=other_team.team_id
  cross join lateral private.kinojo_sm_rule_occurrences_v437(candidate_rule.schedule_id,p_from,p_to) candidate_occurrence
  cross join lateral private.kinojo_sm_rule_occurrences_v437(other_rule.schedule_id,p_from,p_to) other_occurrence
  where candidate_team.team_id=p_team_id
    and candidate_team.status in ('ACTIVE','FULL')
    and tstzrange(candidate_occurrence.start_at,candidate_occurrence.end_at,'[)')
        && tstzrange(other_occurrence.start_at,other_occurrence.end_at,'[)');
$$;

create or replace function public.kinojo_sanctuary_management_bootstrap_v437(p_credential text)
returns jsonb
language plpgsql
stable security definer
set search_path='pg_catalog','public','private'
as $$
declare v_base jsonb; v_teams jsonb;
begin
  v_base:=public.kinojo_sanctuary_management_bootstrap_v436(p_credential);
  select coalesce(jsonb_agg(team_item || jsonb_build_object(
    'canArchive',coalesce((team_item->>'canEdit')::boolean,false) and team_item->>'status'<>'ARCHIVED',
    'scheduleEditScopes',case when team_item->'schedule'->>'kind'='WEEKLY'
      then jsonb_build_array('OCCURRENCE','FUTURE','ALL') else jsonb_build_array('OCCURRENCE','ALL') end
  )),'[]'::jsonb) into v_teams
  from jsonb_array_elements(coalesce(v_base->'teams','[]'::jsonb)) team_item;
  return (v_base-'teams') || jsonb_build_object(
    'apiVersion',1.5,'schemaVersion',437,'databaseContract',437,'teams',v_teams,
    'notificationPolicy',jsonb_build_object('dedupe','WEB_SESSION','groupBy','TEAM','navigation','TEAM_FORCE_SUPPORT')
  );
end;
$$;

create or replace function public.kinojo_sanctuary_management_month_v437(p_credential text,p_month date)
returns jsonb
language plpgsql
stable security definer
set search_path='pg_catalog','public','private'
as $$
declare v_actor jsonb; v_month_start date; v_month_end date; v_range_start date; v_range_end date;
begin
  v_actor:=private.kinojo_sm_actor_v412(p_credential);
  if p_month is null then raise exception '조회할 월을 선택해 주세요.' using errcode='P0001'; end if;
  v_month_start:=date_trunc('month',p_month)::date;
  if extract(year from v_month_start) not between 2025 and 2100 then raise exception '조회할 월 범위를 다시 확인해 주세요.' using errcode='P0001'; end if;
  v_month_end:=(v_month_start+interval '1 month - 1 day')::date;
  v_range_start:=v_month_start-((extract(isodow from v_month_start)::integer-3+7)%7);
  v_range_end:=v_month_end+((2-extract(isodow from v_month_end)::integer+7)%7);
  return jsonb_build_object(
    'ok',true,'apiVersion',1.5,'schemaVersion',437,'databaseContract',437,
    'month',to_char(v_month_start,'YYYY-MM'),'weekStartsOn','WEDNESDAY','rangeStart',v_range_start,'rangeEnd',v_range_end,
    'weekStarts',(select coalesce(jsonb_agg(day::date order by day),'[]'::jsonb) from generate_series(v_range_start,v_range_end,interval '7 days') day),
    'occurrences',(select coalesce(jsonb_agg(jsonb_build_object(
      'occurrenceKey','sm-'||t.team_id||'-'||to_char(o.occurrence_date,'YYYYMMDD')||'-'||to_char(o.start_at at time zone r.timezone_name,'HH24MI'),
      'scheduleId',r.schedule_id,'scheduleRevision',r.revision,'teamId',t.team_id,'teamTitle',t.title,
      'sanctuaryId',t.sanctuary_id,'teamMode',t.team_mode,'joinPolicy',t.join_policy,
      'occurrenceDate',o.occurrence_date,'weekStart',o.occurrence_date-((extract(isodow from o.occurrence_date)::integer-3+7)%7),
      'startAt',o.start_at,'endAt',o.end_at,
      'durationMinutes',round(extract(epoch from(o.end_at-o.start_at))/60)::integer,'sourceScope',o.source_scope,
      'canEdit',private.kinojo_sm_can_manage_team_v412(v_actor,t.team_id)
    ) order by o.start_at,t.team_id),'[]'::jsonb)
      from private.sanctuary_management_teams_v412 t
      join private.sanctuary_management_schedule_rules_v412 r on r.team_id=t.team_id
      cross join lateral private.kinojo_sm_rule_occurrences_v437(r.schedule_id,v_range_start,v_range_end) o
     where t.status in ('ACTIVE','FULL'))
  );
end;
$$;

create or replace function public.kinojo_sanctuary_management_notification_summary_v437(p_credential text)
returns jsonb
language plpgsql
stable security definer
set search_path='pg_catalog','public','private'
as $$
declare v_actor jsonb; v_actor_id bigint; v_team record; v_force record; v_characters jsonb; v_forces jsonb; v_groups jsonb:='[]'::jsonb;
begin
  v_actor:=private.kinojo_sm_actor_v412(p_credential);v_actor_id:=nullif(v_actor->>'memberId','')::bigint;
  for v_team in
    select t.*,r.starts_on,r.starts_at,r.duration_minutes,r.schedule_kind,r.weekdays,s.code sanctuary_code,s.name sanctuary_name
      from private.sanctuary_management_teams_v412 t
      join private.sanctuary_management_schedule_rules_v412 r on r.team_id=t.team_id and r.status='ACTIVE'
      join public.sanctuary_master s on s.id=t.sanctuary_id
     where t.team_mode='PARTICIPATION' and t.status in ('ACTIVE','FULL')
     order by t.created_at,t.team_id
  loop
    v_characters:=private.kinojo_sm_support_characters_v436(v_team.team_id,v_actor_id);
    v_forces:='[]'::jsonb;
    for v_force in
      select f.force_id,f.force_no,10-count(s.character_id)::integer open_slots
        from private.sanctuary_management_forces_v412 f
        join private.sanctuary_management_slots_v412 s on s.force_id=f.force_id
       where f.team_id=v_team.team_id and f.status='OPEN'
       group by f.force_id,f.force_no
      having count(s.character_id)<10
       order by f.force_no
    loop
      if exists(select 1 from jsonb_array_elements(coalesce(v_characters->'characters','[]'::jsonb)) c
        where coalesce(c->'availableForceIds','[]'::jsonb) @> jsonb_build_array(v_force.force_id)) then
        v_forces:=v_forces||jsonb_build_array(jsonb_build_object(
          'forceId',v_force.force_id,'forceNo',v_force.force_no,'openSlots',v_force.open_slots
        ));
      end if;
    end loop;
    if jsonb_array_length(v_forces)>0 then
      v_groups:=v_groups||jsonb_build_array(jsonb_build_object(
        'eventKey','sanctuary-recruitment-team-'||v_team.team_id,
        'teamId',v_team.team_id,'teamTitle',v_team.title,'sanctuaryId',v_team.sanctuary_id,
        'sanctuaryCode',v_team.sanctuary_code,'sanctuaryName',v_team.sanctuary_name,
        'joinPolicy',v_team.join_policy,'forces',v_forces,'eligibleCharacterCount',v_characters->'candidateCount',
        'schedule',jsonb_build_object('kind',v_team.schedule_kind,'startsOn',v_team.starts_on,'weekdays',v_team.weekdays,
          'startsAt',to_char(v_team.starts_at,'HH24:MI'),'durationMinutes',v_team.duration_minutes),
        'navigation',jsonb_build_object('path','/sanctuary-management/','teamId',v_team.team_id,'forceId',(v_forces->0->>'forceId')::bigint,'openSupport',true)
      ));
    end if;
  end loop;
  return jsonb_build_object('ok',true,'apiVersion',1.5,'schemaVersion',437,'databaseContract',437,
    'memberId',v_actor_id,'dedupePolicy','WEB_SESSION','recruitmentCount',jsonb_array_length(v_groups),'recruitmentGroups',v_groups);
end;
$$;

create or replace function public.kinojo_sanctuary_management_archive_preview_v437(p_credential text,p_team_id bigint)
returns jsonb
language plpgsql
stable security definer
set search_path='pg_catalog','public','private'
as $$
declare v_actor jsonb; v_team private.sanctuary_management_teams_v412%rowtype; v_schedule_id bigint; v_pending integer; v_future integer; v_recurring boolean;
begin
  v_actor:=private.kinojo_sm_actor_v412(p_credential);
  select * into v_team from private.sanctuary_management_teams_v412 where team_id=p_team_id;
  if v_team.team_id is null or not private.kinojo_sm_can_manage_team_v412(v_actor,p_team_id) then raise exception '팀 해산 영향을 확인할 권한이 없습니다.' using errcode='P0001'; end if;
  select schedule_id,(schedule_kind='WEEKLY') into v_schedule_id,v_recurring from private.sanctuary_management_schedule_rules_v412 where team_id=p_team_id;
  select count(*)::integer into v_pending from private.sanctuary_management_support_items_v412 i
    join private.sanctuary_management_support_batches_v412 b on b.support_batch_id=i.support_batch_id
    where b.team_id=p_team_id and i.status='PENDING';
  select count(*)::integer into v_future from private.kinojo_sm_rule_occurrences_v437(v_schedule_id,current_date,current_date+366) o;
  return jsonb_build_object('ok',true,'schemaVersion',437,'teamId',p_team_id,'teamTitle',v_team.title,'revision',v_team.revision,
    'canArchive',true,'futureOccurrenceCount',v_future,'futureWindowDays',366,'recurringSchedule',coalesce(v_recurring,false),
    'pendingSupportCount',v_pending,'historyPreserved',true,'message','팀 편성·감사 이력은 보존하고 이후 일정과 승인 대기 지원을 종료합니다.');
end;
$$;

create or replace function public.kinojo_sanctuary_management_command_v437(
  p_credential text,p_request_key text,p_action text,p_payload jsonb default '{}'::jsonb,p_expected_revision bigint default null
)
returns jsonb
language plpgsql
security definer
set search_path='pg_catalog','public','private'
as $$
declare
  v_actor jsonb;v_actor_id bigint;v_action text:=upper(btrim(coalesce(p_action,'')));v_team_id bigint;
  v_team private.sanctuary_management_teams_v412%rowtype;v_rule private.sanctuary_management_schedule_rules_v412%rowtype;
  v_existing private.sanctuary_management_commands_v412%rowtype;v_hash text;v_response jsonb;v_preview jsonb;v_before jsonb;v_after jsonb;
  v_scope text;v_operation text;v_occurrence date;v_kind text;v_starts_on date;v_weekdays smallint[];v_starts_at time;v_duration integer;v_conflicts jsonb;
begin
  if v_action not in ('EDIT_SCHEDULE','ARCHIVE_TEAM') then
    return public.kinojo_sanctuary_management_command_v436(p_credential,p_request_key,v_action,p_payload,p_expected_revision)
      || jsonb_build_object('schemaVersion',437,'databaseContract',437);
  end if;
  v_actor:=private.kinojo_sm_actor_v412(p_credential);v_actor_id:=nullif(v_actor->>'memberId','')::bigint;
  v_team_id:=nullif(p_payload->>'teamId','')::bigint;
  select * into v_team from private.sanctuary_management_teams_v412 where team_id=v_team_id for update;
  if v_team.team_id is null or not private.kinojo_sm_can_manage_team_v412(v_actor,v_team_id) then raise exception '이 팀을 운영할 권한이 없습니다.' using errcode='P0001'; end if;
  if p_expected_revision is null or v_team.revision<>p_expected_revision then raise exception '다른 사용자가 먼저 팀을 수정했습니다. 새로고침 후 다시 시도해 주세요.' using errcode='40001'; end if;
  v_hash:=md5(v_action||'|'||coalesce(p_payload,'{}'::jsonb)::text||'|'||coalesce(p_expected_revision::text,''));
  select * into v_existing from private.sanctuary_management_commands_v412 where actor_member_id=v_actor_id and request_key=p_request_key;
  if v_existing.command_id is not null then
    if v_existing.request_hash<>v_hash then raise exception '같은 요청 키에 다른 작업 내용이 사용되었습니다.' using errcode='P0001'; end if;
    return v_existing.response_payload||jsonb_build_object('replayed',true,'schemaVersion',437,'databaseContract',437);
  end if;
  if v_action='ARCHIVE_TEAM' then
    v_preview:=public.kinojo_sanctuary_management_archive_preview_v437(p_credential,v_team_id);
    v_response:=public.kinojo_sanctuary_management_command_v436(p_credential,p_request_key,v_action,p_payload,p_expected_revision);
    return v_response||jsonb_build_object('archiveImpact',v_preview,'historyPreserved',true,'schemaVersion',437,'databaseContract',437);
  end if;
  if v_team.status not in ('ACTIVE','FULL') then raise exception '공개된 운영 팀의 일정만 변경할 수 있습니다.' using errcode='P0001'; end if;
  select * into v_rule from private.sanctuary_management_schedule_rules_v412 where team_id=v_team_id for update;
  v_scope:=upper(coalesce(p_payload->>'scope','ALL'));v_operation:=upper(coalesce(p_payload->>'operation','UPDATE'));
  v_occurrence:=nullif(p_payload->>'occurrenceDate','')::date;
  v_kind:=upper(coalesce(p_payload->'schedule'->>'kind',v_rule.schedule_kind));
  v_starts_on:=coalesce(nullif(p_payload->'schedule'->>'startsOn','')::date,v_occurrence,v_rule.starts_on);
  v_weekdays:=coalesce(array(select distinct d::smallint from jsonb_array_elements_text(coalesce(p_payload->'schedule'->'weekdays',to_jsonb(v_rule.weekdays))) d order by d::smallint),'{}'::smallint[]);
  v_starts_at:=coalesce(nullif(p_payload->'schedule'->>'startsAt','')::time,v_rule.starts_at);
  v_duration:=coalesce(nullif(p_payload->'schedule'->>'durationMinutes','')::integer,v_rule.duration_minutes);
  if v_scope not in ('OCCURRENCE','FUTURE','ALL') or v_operation not in ('UPDATE','CANCEL','STOP') then raise exception '일정 변경 범위와 작업을 다시 선택해 주세요.' using errcode='P0001'; end if;
  if v_scope in ('OCCURRENCE','FUTURE') and v_occurrence is null then raise exception '변경 기준 날짜를 선택해 주세요.' using errcode='P0001'; end if;
  if v_operation='UPDATE' and (v_kind not in ('ONCE','WEEKLY') or v_starts_at is null or v_duration not between 30 and 720 or v_duration%30<>0
    or (v_kind='ONCE' and cardinality(v_weekdays)<>0) or (v_kind='WEEKLY' and cardinality(v_weekdays) not between 1 and 7))
  then raise exception '1회성 또는 반복 일정과 30분 단위 진행 시간을 다시 확인해 주세요.' using errcode='P0001'; end if;
  v_before:=to_jsonb(v_rule);perform set_config('kinojo.schedule_version_guard','1',true);
  if v_scope='OCCURRENCE' then
    insert into private.sanctuary_management_schedule_exceptions_v412(schedule_id,occurrence_date,exception_type,moved_to_date,moved_to_time,moved_duration_minutes,created_by_member_id)
    values(v_rule.schedule_id,v_occurrence,case when v_operation='UPDATE' then 'MOVE' else 'CANCEL' end,
      case when v_operation='UPDATE' then v_starts_on end,case when v_operation='UPDATE' then v_starts_at end,
      case when v_operation='UPDATE' then v_duration end,v_actor_id)
    on conflict(schedule_id,occurrence_date) do update set exception_type=excluded.exception_type,moved_to_date=excluded.moved_to_date,
      moved_to_time=excluded.moved_to_time,moved_duration_minutes=excluded.moved_duration_minutes,created_by_member_id=excluded.created_by_member_id,created_at=clock_timestamp();
  else
    if v_scope='FUTURE' then
      update private.sanctuary_management_schedule_versions_v437 set effective_to=v_occurrence-1,revision=revision+1
       where schedule_id=v_rule.schedule_id and effective_from<v_occurrence and coalesce(effective_to,'infinity'::date)>=v_occurrence;
      delete from private.sanctuary_management_schedule_versions_v437 where schedule_id=v_rule.schedule_id and effective_from>=v_occurrence;
    else
      delete from private.sanctuary_management_schedule_versions_v437 where schedule_id=v_rule.schedule_id;
      delete from private.sanctuary_management_schedule_exceptions_v412 where schedule_id=v_rule.schedule_id;
    end if;
    if v_operation='UPDATE' then
      insert into private.sanctuary_management_schedule_versions_v437(schedule_id,team_id,effective_from,schedule_kind,starts_on,weekdays,starts_at,duration_minutes,timezone_name,status,revision,created_by_member_id)
      values(v_rule.schedule_id,v_team_id,case when v_scope='FUTURE' then v_occurrence else v_starts_on end,v_kind,v_starts_on,v_weekdays,v_starts_at,v_duration,v_rule.timezone_name,'ACTIVE',v_rule.revision+1,v_actor_id);
      update private.sanctuary_management_schedule_rules_v412 set schedule_kind=v_kind,starts_on=v_starts_on,weekdays=v_weekdays,starts_at=v_starts_at,
        duration_minutes=v_duration,status='ACTIVE',revision=revision+1,updated_at=clock_timestamp() where schedule_id=v_rule.schedule_id;
    else
      update private.sanctuary_management_schedule_rules_v412 set status='STOPPED',revision=revision+1,updated_at=clock_timestamp() where schedule_id=v_rule.schedule_id;
    end if;
  end if;
  v_conflicts:=private.kinojo_sm_team_conflicts_v437(v_team_id,coalesce(v_occurrence,current_date),coalesce(v_occurrence,current_date)+366);
  if jsonb_array_length(v_conflicts)>0 then raise exception '%',v_conflicts->0->>'message' using errcode='P0001',detail=v_conflicts::text; end if;
  update private.sanctuary_management_teams_v412 set revision=revision+1,updated_at=clock_timestamp() where team_id=v_team_id returning * into v_team;
  select to_jsonb(r) into v_after from private.sanctuary_management_schedule_rules_v412 r where schedule_id=v_rule.schedule_id;
  v_response:=jsonb_build_object('ok',true,'action',v_action,'teamId',v_team_id,'revision',v_team.revision,'scope',v_scope,'operation',v_operation,
    'scheduleRevision',v_after->'revision','message',case when v_operation='UPDATE' then '일정 변경을 저장했습니다.' else '선택한 범위의 일정을 종료했습니다.' end);
  perform private.kinojo_sm_audit_v412(v_actor_id,v_team_id,'SCHEDULE',v_rule.schedule_id,'EDIT_SCHEDULE_'||v_scope||'_'||v_operation,v_before,v_after,p_request_key);
  insert into private.sanctuary_management_commands_v412(actor_member_id,request_key,action,request_hash,response_payload)
  values(v_actor_id,p_request_key,v_action,v_hash,v_response);
  return v_response||jsonb_build_object('replayed',false,'schemaVersion',437,'databaseContract',437);
end;
$$;

comment on function public.kinojo_sanctuary_management_command_v437(text,text,text,jsonb,bigint) is
  'Stage 5 Server command boundary. ADMIN is a dedicated Codex QA grade with MASTER-equivalent rights; authorization remains private.kinojo_sm_can_manage_team_v412 and no passkey is embedded here.';

revoke all on function public.kinojo_sanctuary_management_bootstrap_v437(text) from public,anon,authenticated;
revoke all on function public.kinojo_sanctuary_management_month_v437(text,date) from public,anon,authenticated;
revoke all on function public.kinojo_sanctuary_management_notification_summary_v437(text) from public,anon,authenticated;
revoke all on function public.kinojo_sanctuary_management_archive_preview_v437(text,bigint) from public,anon,authenticated;
revoke all on function public.kinojo_sanctuary_management_command_v437(text,text,text,jsonb,bigint) from public,anon,authenticated;
grant execute on function public.kinojo_sanctuary_management_bootstrap_v437(text) to service_role;
grant execute on function public.kinojo_sanctuary_management_month_v437(text,date) to service_role;
grant execute on function public.kinojo_sanctuary_management_notification_summary_v437(text) to service_role;
grant execute on function public.kinojo_sanctuary_management_archive_preview_v437(text,bigint) to service_role;
grant execute on function public.kinojo_sanctuary_management_command_v437(text,text,text,jsonb,bigint) to service_role;
